### ISSUE TITLE
Rocket Turret Glitch

### ISSUE THREAD

**Issue by Tjmcnee** [BEEmod/BEE2-items#2284] opened 2017-10-14 23:30 UTC
For some reason The rocket turrets laser torch doesn't show, it doesn't show the rocket move and explodes immediately except when player is in front if it.

**Comment by LautaroL20** [comment] 2017-10-17 07:54
This is a duplicate of: https://github.com/BEEmod/BEE2-items/issues/1984

**Closed by LautaroL20** 2017-10-17 07:54 UTC
Labels: Bug, Duplicate
