### ISSUE TITLE
Rexaura Pellet Deflector Upgrade

### ISSUE THREAD

**Issue by The-Queen55142** [BEEmod/BEE2-items#2581] opened 2018-03-19 18:24 UTC
Perhaps be able to place it on walls? That way we could have puzzles where you use the deflector to aim the pellet to the roof or ground. It would add many more puzzle possibilities

**Comment by xGARDYx** [comment] 2018-03-19 21:12
i like this idea :)

**Comment by SCIENTIST2004** [comment] 2018-03-22 10:38
Me too

**Comment by KaziPlays** [comment] 2021-12-15 02:07
Duplicate of #2206

**Comment by KaziPlays** [comment] 2021-12-15 02:08
I think is

**Comment by Luke18033** [comment] 2021-12-15 02:09
Yep

**Closed by Luke18033** 2021-12-15 02:09 UTC
Labels: Enhancement
