### ISSUE TITLE
Electric Floor

### ISSUE THREAD

**Issue by King0191** [BEEmod/BEE2-items#2749] opened 2018-07-13 23:45 UTC
The electric floor, also known as the Zapper, is a testing element that appears in Portal: Still Alive's challenge maps. 

The electric floor consists of two rectangular devices located opposite each other, with one on the floor and the other on the ceiling. It periodically turns on and off; while it's active, any Test Subject caught in the electric field generated between those two devices dies instantly. 

The electric floor originates from Portal: The Flash Version, remade by fans for Portal as Portal: The Flash Version MapPack. Levels from the map pack were the basis for the challenge maps included in Portal: Still Alive. 

Signage! 
![xbla_signage_electric_floor](https://user-images.githubusercontent.com/37309250/42718234-3fac7b5c-86d5-11e8-8463-4407c95b5c85.png)

Appearance! 
![image](https://user-images.githubusercontent.com/37309250/42718239-495973f8-86d5-11e8-9535-fdbf1716db65.png)

**Comment by HugoBDesigner** [comment] 2018-07-13 23:54
Duplicate of #2179

**Closed by HugoBDesigner** 2018-07-13 23:54 UTC
