### ISSUE TITLE
Toggleable Lifeform Sensor/ Radiative Flux rectangle

### ISSUE THREAD

**Issue by kdabest2** [BEEmod/BEE2-items#2923] opened 2019-03-04 03:15 UTC
Could you make it so they can be shut off by like a button or something? shutting it off will keep the input, but it won't activate when a Player/ HEP passes through it

**Comment by Luke18033** [comment] 2019-03-04 03:19
Duplicate of #1619

**Closed by Luke18033** 2019-03-04 03:19 UTC
