### ISSUE TITLE
Pellet Catcher does not activate output

### ISSUE THREAD

**Issue by flickygameshowOFC** [BEEmod/BEE2-items#4210] opened 2022-08-13 23:46 UTC
I connected an Energy Pellet Catcher to a cube dropper. When activated, the antline stayed blue, and the cube did not came for me. It played the animation and the pellet was inside it, but nothing else happened; what do I do?

NOTE: I was in 1960s Old Aperture Style, if this helps anyway.

![image](https://user-images.githubusercontent.com/111207001/184516946-c4815374-8fee-4131-9f08-2190a2c072ab.png)

**Comment by LautaroL20** [comment] 2022-08-14 02:09
This is a duplicate of: https://github.com/BEEmod/BEE2-items/issues/3858

**Closed by LautaroL20** 2022-08-14 02:09 UTC
Labels: Duplicate

**Comment by flickygameshowOFC** [comment] 2022-08-17 14:27
Hi, Lautaro! You deleted my thread because there was already another with
the same problem, but, in the original, I could not find the solution.
Could you please reply with a solution?

Em sáb, 13 de ago de 2022 23:09, Lautaro ***@***.***>
escreveu:

**Comment by LautaroL20** [comment] 2022-08-17 23:50
> flickygameshowOFC said: "Hi, Lautaro! You deleted my thread because there was already another with the same problem, but, in the original, I could not find the solution. Could you please reply with a solution?

What thread did i "deleted" according to you? On Github, we can not delete posted issues, all we can do is deleting comments or closing an issue which is something different. In regards to a solution for your issue, you will need to wait for it to get fixed by TeamSpen210 or a collaborator, because there is currently no temporary workaround fix for it.

**Comment by flickygameshowOFC** [comment] 2022-10-11 09:23
Sorry. By "deleting" I meant closing my issue (#4210, btw). And thanks for
the answer. The next update with this bug fix is expected to come when?

Em qua, 17 de ago de 2022 20:51, Lautaro ***@***.***>
escreveu:

**Comment by LautaroL20** [comment] 2022-10-11 12:38
> flickygameshowOFC said: "The next update with this bug fix is expected to come when?"

Well, the original issue (https://github.com/BEEmod/BEE2-items/issues/3858) does not have the "fixed" label. So, we would need to ask @TeamSpen210 if he considers that this particular issue needs to be fixed before the next BEE2.4 release?

**Comment by LautaroL20** [comment] 2022-10-15 15:19
@flickygameshowOFC - This is now fixed in the next BEE2.4 release.
