### ISSUE TITLE
Generate Giant Fan in bottomless pit style and item vars (long term)

### ISSUE THREAD

**Issue by EllingtonElectrician** [BEEmod/BEE2-items#3617] opened 2021-01-31 20:27 UTC
Since a future update is going to make bottomless pits generate around the map properly 

there should be a "Generate Giant Fan in bottomless pit" style var which would generate a giant fan into the pit like the one from portal stories mel etc.

![fan](https://user-images.githubusercontent.com/11165643/106396807-5d0ab280-63d8-11eb-8697-693523677f83.jpg)

![fan 3](https://user-images.githubusercontent.com/11165643/106397983-410a0f80-63de-11eb-8498-fcc4d4e38d3c.jpg)

Also under item properties there should be a drop down menu that says something like "Bottomless Pit giant fan orientation"

which would have options up, down, north, south, east, west. up would generate a fan in the ceiling, down would make one in the floor of the pit, with open walls north would make it on the opposite side of the entry door, south would behind the entry door, east would make it on the right side and west left side of the entry door of the test chamber.

There should be a item var to also set the fan speed based upon 3 speeds from high, medium, low, and off.

there should be different variants of the fan based upon the style used such as the darker looking one from underground during the original Coop story.

the clean one could look like the one from mel, the overgrown one could have plants around the frame and inside of it and maybe sparks coming from inside of it. the bts one should look similar to the clean one, the underground one should look like the one in the campaign with a dark unlit background and the p1 one should have a incinerator / orange light source coming from inside it.

![fan 2](https://user-images.githubusercontent.com/11165643/106397846-8b3ec100-63dd-11eb-9c87-f15f626cd6d5.jpg)

**Comment by seagemgames** [comment] 2021-01-31 21:06
I don't personally think this would really work in BEEmod. Though, I am working on a BTS UCP, and I may add that 👀

**Comment by Luke18033** [comment] 2021-01-31 21:14
Duplicate of #255 (your own issue).

**Comment by EllingtonElectrician** [comment] 2021-01-31 21:14
> I don't personally think this would really work in BEEmod. Though, I am working on a BTS UCP, and I may add that 👀

a future update is going to automatically generate bottomless pits with wires, vactubes, paint tubes, other test chambers, catwalks etc, and make them look like they would in the original game or mel.

**Closed by Luke18033** 2021-01-31 21:14 UTC
Labels: Enhancement
