### ISSUE TITLE
Wall emitters and piston emitters are bugged

### ISSUE THREAD

**Issue by BathWizard** [BEEmod/BEE2-items#3847] opened 2021-07-13 22:48 UTC
**BEE2 version:**
4.40.2

**Description of the bug:**
Both wall and piston emitters don't connect to scaffold slots, I don't even see that little beam of light, connecting two piston emitters or two scaffold slots works just fine.

**Expected behavior:**
the platforms would come out of the slot, turn when they get to the piston emitter, and exit though the other slot

**Steps to reproduce:**
make a new test, place a slot, connect it to a piston, then connect the piston to another slot

**Additional information:**
I did not change any of the default settings for the items
![part1](https://user-images.githubusercontent.com/80733484/125534868-66c14f04-c956-4df8-8b45-d067890c1028.PNG)
![part2](https://user-images.githubusercontent.com/80733484/125534888-ebf3ce22-8855-42b9-bde5-086f019b9e20.PNG)

**Comment by FrozenDragon0** [comment] 2021-07-14 01:11
Duplicate of https://github.com/BEEmod/BEE2-items/issues/3678

**Closed by FrozenDragon0** 2021-07-14 01:11 UTC
Labels: Bug, Duplicate
