### ISSUE TITLE
Physler missing texture in the in-game palette

### ISSUE THREAD

**Issue by snorepion** [BEEmod/BEE2-items#1953] opened 2017-05-11 16:35 UTC
![notexture](https://cloud.githubusercontent.com/assets/24462989/25960824/67eb2b32-3635-11e7-84f2-0b21101bb896.PNG)
You can see it right next to the FDF. 
Also, the custom fizzlers don't use their new icons in the palette, except for the Closed Solid Field.

**Comment by Luke18033** [comment] 2017-05-11 16:52
CSF is Compressed Smoke Field, the Closed Solid Field is CSFi.

**Comment by snorepion** [comment] 2017-05-11 16:55
My bad.

**Comment by Luke18033** [comment] 2017-05-11 16:56
The PRF I think had the wrong file path set, which has been fixed in the next release. The new icons for the other fizzlers aren't appearing because of a bug with copying resources.

**Comment by Luke18033** [comment] 2017-05-11 16:58
Duplicate of #1920.

**Comment by snorepion** [comment] 2017-05-11 16:58
I'm an idiot, I actually saw that before but forgot about it.

**Closed by Luke18033** 2017-05-11 16:58 UTC
