### ISSUE TITLE
Portal 1 heavy door/ square door.

### ISSUE THREAD

**Issue by GalexTEMYT** [BEEmod/BEE2-items#3127] opened 2019-10-11 22:27 UTC
this item has also been used in portal 2, it is used right before you enter the glados chamber in the first chapter of portal 2, it is also a very usefull testing element in portal 1.

**Comment by Luke18033** [comment] 2019-10-11 23:04
Duplicate of #95. Have you read the contributing guidelines?

**Closed by Luke18033** 2019-10-11 23:04 UTC
