### ISSUE TITLE
offset items with flat partial blocks on top of them to the front of the partial blocks (long term)

### ISSUE THREAD

**Issue by EllingtonElectrician** [BEEmod/BEE2-items#3872] opened 2021-08-09 18:50 UTC
since partial blocks are going to soon be able to move and offset antlines to the front of them.

i had the following suggestion to do this someday...

Move and offset any items with partial blocks placed on top them to the front of the flat partial blocks.

with this we could create things like buttons, lasers, funnels, bridges, paint and cube droppers that would be properly aligned and placed on walls or ceilings or floors made from flat partial blocks.

obviously this would be pretty hard to pull off with angled partial blocks since you would also have to rotate the angle of the item too.

**Comment by Luke18033** [comment] 2021-08-09 19:40
Duplicate of #1485. You already duplicated that issue once with #2390, please stop doing this.

**Closed** 2021-08-09 19:40 UTC
Labels: Enhancement
