### ISSUE TITLE
Suggestion: Add bomb droppers!

### ISSUE THREAD

**Issue by Voidliest** [BEEmod/BEE2-items#3150] opened 2019-11-23 00:02 UTC
Suggestion: Add bomb droppers where instead of cubes coming out it's the bombs as seen in the chapter: The Part Where He Kills You. This would greatly benefit boss fights. boss fights, as new boss fights could be made with bombs as a method of attacking back. Another thing you could add is fire. And my last suggestion, make it so you can switch between normal turrets, and the turrets that are placed down with droppers, and maybe even rocket turrets.

**Comment by Luke18033** [comment] 2019-11-23 00:16
Duplicate of #95. Puzzlemaker isn't for making boss fights...

**Closed by Luke18033** 2019-11-23 00:16 UTC
Labels: Enhancement
