### ISSUE TITLE
[PRL22 Bug] BTS bottomless pit not being placed in map, still generating skybox pit...

### ISSUE THREAD

**Issue by Electricianfromhell** [BEEmod/BEE2-items#789] opened 2016-09-10 18:22 UTC
bug: bts bottomless pit not being placed in map, still generating skybox pit... Also Texure Mismatch between pit and skybox, also light from pit needs better smoothing...

I like your idea of placing the bottomless pit right into the map for ones like this, it will allow paint and lasers to enter the pit...

![preview0011](https://cloud.githubusercontent.com/assets/11165643/18412653/160cb53e-7762-11e6-9d50-a34b234b45f6.jpg)

**Comment by TheDarkBomber** [comment] 2016-09-10 18:30
Duplicate of #788.

**Comment by LautaroL20** [comment] 2016-09-10 18:47
@TheDarkBomber - I would not be so sure. One talks about bottomless pit not being placed in map, and the other is about something "Mysterious" happening when placing a pillar that is under goo in deep Bottomless Pits.

**Comment by TheDarkBomber** [comment] 2016-09-10 20:40
Same picture

**Comment by ZombiePwner1** [comment] 2016-09-12 03:15
It does not matter @TheDarkBomber

**Comment by Luke18033** [comment] 2020-07-09 04:11
Not really a bug, this is going to be implemented at some point anyway.

**Closed by Luke18033** 2020-07-09 04:11 UTC
Labels: Bug
