### ISSUE TITLE
Vactubes in 1950s (possibly other Old Aperture eras) sometimes get messed up

### ISSUE THREAD

**Issue by snorepion** [BEEmod/BEE2-items#1795] opened 2017-04-02 03:31 UTC
Occasionally, when going around a bend, vactubes in Old Aperture use the New Aperture designs. These segments don't have suction, which breaks tube rides for players and items. They also sometimes use regular Old Aperture designs randomly. This doesn't only happen with a certain orientation, it happens no matter what direction the tube is going in, from what I've seen. Pic below.
![brokenvactube](https://cloud.githubusercontent.com/assets/24462989/24584179/46573b0a-1722-11e7-95bc-5240eec8c4f0.png)

**Comment by TeamSpen210** [comment] 2017-04-02 03:44
I never made the correct versions of the large bends.

**Comment by Luke18033** [comment] 2017-04-02 13:52
Duplicate of #1356.

**Comment by Luke18033** [comment] 2017-04-02 16:34
Lol, forgot to actually close the issue

**Closed** 2017-04-02 16:34 UTC
Labels: Bug, Duplicate, Old Aperture, Unstyled Item
