### ISSUE TITLE
Implement "Centered" and "Left corner" variants for the Wall Observation Room from P1 Style 

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#936] opened 2016-10-16 17:28 UTC

**Comment by ZombiePwner1** [comment] 2016-10-28 03:18
I suggested an idea similar to this.

**Comment by Luke18033** [comment] 2020-08-25 19:44
Is this suggesting the corner observation room from P1 chamber 15, or something else?

**Comment by Luke18033** [comment] 2020-08-25 20:15
Ah, you're suggesting centered and left-aligned variants of the P1 small obs room. In that case this would be a duplicate of #459, since the plan is to switch the existing observation room to cover the full block.

**Closed by Luke18033** 2020-08-25 20:15 UTC
Labels: Enhancement, Portal 1
