### ISSUE TITLE
Visible nodraw in Portal 1 Dropper

### ISSUE THREAD

**Issue by PixelHUN** [BEEmod/BEE2-items#3175] opened 2019-12-23 21:26 UTC
I found visible nodraw... Latest Release, and Packages.
Hope it will be fixed!
![BEE](https://user-images.githubusercontent.com/59181913/71381281-16426a80-25d3-11ea-8209-71859ecc31a2.png)

**Comment by Luke18033** [comment] 2019-12-23 21:59
This would I think indicate there's a leak. Place goo in the map, does it also show nodraw?

**Comment by PixelHUN** [comment] 2019-12-23 22:38
> This would I think indicate there's a leak. Place goo in the map, does it also show nodraw?

![image](https://user-images.githubusercontent.com/59181913/71383559-3c6d0800-25dd-11ea-9c71-1988f5673eff.png)
![image](https://user-images.githubusercontent.com/59181913/71383569-44c54300-25dd-11ea-8127-5324d7cac90d.png)

Nope! It's just the dropper...

**Comment by Luke18033** [comment] 2019-12-23 22:44
Huh, strange. I don't think there's actually any nodraw there, it appeared fine for me last time I checked. Can you upload a copy of `Portal 2/sdk_content/maps/styled/preview.vmf`?

**Comment by LautaroL20** [comment] 2019-12-23 22:45
Yep, i´ve tested this 5 minutes ago and it indicates that the leak/nodraw is not a problem with the P1 Dropper itself, but something else in the map may be causing it to occur. However, testing on this made me noticed another issue on the P1 Dropper, and it is that you can´t turn its boxel to white in-game:

Editor:
![20191223185741_1](https://user-images.githubusercontent.com/12244376/71383745-81347700-25bc-11ea-8902-09213f375ecd.jpg)

In-game result:
![20191223185806_1](https://user-images.githubusercontent.com/12244376/71382496-f7ce7600-25b6-11ea-9a28-72b13bca1dc0.jpg)

**Comment by Luke18033** [comment] 2019-12-23 22:47
That's actually an issue with all cube droppers, not just the P1 ones.

**Comment by TeamSpen210** [comment] 2019-12-23 22:52
It's from the areaportal, which I've just removed since it's actually useless.

**Comment by PixelHUN** [comment] 2019-12-23 23:10
Yeah... I made a temporary fix with removing the areaportal. It solved the problem

**Comment by Luke18033** [comment] 2020-04-26 20:42
Duplicate of #3175

**Comment by Luke18033** [comment] 2020-04-26 20:42
Wait huh?

**Comment by Luke18033** [comment] 2020-04-26 20:42
Stupid mobile app

**Closed** 2020-07-19 08:30 UTC
Labels: Bug, Fixed, Portal 1
