### ISSUE TITLE
overgrown & 80s style cube button model has bug

### ISSUE THREAD

**Issue by 1209-57238032** [BEEmod/BEE2-items#4047] opened 2022-01-07 04:50 UTC
### BEE2 Application Version

4.41.0 32 & 64

### BEE2 Package Version

4.41.0

### What operating system are you running on?

Windows 7 (32bit)

### Description of the bug

overgrown & 80s style cube button model has bug

### Expected behavior

skip

### Steps to reproduce

skip

### Logs and Reports

```shell
.nut
Error Vertex File for 'bee2/props_overgrown/box_socket.mdl' checksum 204864610 should be -357578265
U
```

### Additional information

i used overgrown or 80's style

**Comment by Luke18033** [comment] 2022-01-07 05:20
Duplicate of #3645

**Closed by Luke18033** 2022-01-07 05:20 UTC
Labels: Bug
