### ISSUE TITLE
Cubes missing collision with Grating (Overgrown)

### ISSUE THREAD

**Issue by ImDaveead** [BEEmod/BEE2-items#2072] opened 2017-06-18 18:15 UTC
I have only tested the Overgrown Style, but cubes just go right through grating, but not glass.![ezgif com-
video-to-gif 2](https://user-images.githubusercontent.com/24465214/27263092-3a9259e8-5431-11e7-82f6-5d1a48edc5ad.gif)

**Comment by ZombiePwner1** [comment] 2017-06-18 22:54
Duplicate of https://github.com/BEEmod/BEE2-items/issues/1929

**Closed by ZombiePwner1** 2017-06-18 22:54 UTC
Labels: Bug, Duplicate
