### ISSUE TITLE
BTS Pedestal Button Crash with XBOX 360 Controller

### ISSUE THREAD

**Issue by Neightro** [BEEmod/BEE2-items#2545] opened 2018-03-09 03:50 UTC
While I was testing a map I was working on, I activated a pedestal button set to one second. Right about when it deactivated, my game crashed. From my testing, it seems to happen whenever the button is pressed using my wired XBOX 360 controller. I can't say whether it applies to all controllers.

Here is my crash log; just rename it to remove the .txt file extension. (If you're looking into this, then I'm sure you know to do that. Just in case.)

[crash_portal2.exe_20180308182629_1.dmp.txt](https://github.com/BEEmod/BEE2-items/files/1795449/crash_portal2.exe_20180308182629_1.dmp.txt)

I'm not sure whether this issue applies specifically to my puzzle (I haven't done the testing), so here is the portion of the puzzle where I encountered the error.

![neightro_puzzle_bts_ingame](https://user-images.githubusercontent.com/23202923/37187649-08b5de9c-2300-11e8-8166-6109101a341d.png)

**Comment by TeamSpen210** [comment] 2018-03-09 04:07
That's an  interesting bug. Unfortunately we can't really actually use the dumps the game produces. But that does make sense as something that could break stuff.

**Comment by Neightro** [comment] 2018-03-09 04:16
Is there anything I can get to help you, then? A more helpful error log if one exists? The Steam dumps are all I was able to find.

**Comment by TeamSpen210** [comment] 2018-03-09 04:16
I'll have to look at the logic and try and see where the problem occurs.

**Comment by Neightro** [comment] 2018-03-09 04:30
Alright. I hope it goes quickly. Thanks for looking into it.

**Comment by Luke18033** [comment] 2020-05-15 02:09
Probably a duplicate of #347 (gel on pedestal buttons crashing, which you can see would be the case here)

**Closed by Luke18033** 2020-05-15 02:09 UTC
Labels: Game Crash
