### ISSUE TITLE
Grating is permeable

### ISSUE THREAD

**Issue by toncica2** [BEEmod/BEE2-items#1974] opened 2017-05-19 00:40 UTC
Tested in original P2 style, there is no collision between grating and all cubes.

I've searched but I didn't find this critical issue addressed.

**Comment by ZombiePwner1** [comment] 2017-05-19 01:46
Duplicate of: https://github.com/BEEmod/BEE2-items/issues/1929

**Closed by ZombiePwner1** 2017-05-19 01:46 UTC
Labels: Bug, Duplicate
