### ISSUE TITLE
New Item: Turret Switch

### ISSUE THREAD

**Issue by ZipZoptheCat** [BEEmod/BEE2-items#2789] opened 2018-08-05 18:43 UTC
I was watching a video of lego dimensions and in their portal levels they have a switch you can activate by picking up a turret and pointing it at the switch for it to shoot.

I was thinking perhaps you could use the turret target practice mannequins for this purpose?

**Comment by Luke18033** [comment] 2018-08-05 18:46
Duplicate of #2620.

**Closed by Luke18033** 2018-08-05 18:46 UTC
