### ISSUE TITLE
Players can stand on large glass panels when retracted.

### ISSUE THREAD

**Issue by FrozenDragon0** [BEEmod/BEE2-items#3064] opened 2019-07-15 14:38 UTC
![20190715223116_1](https://user-images.githubusercontent.com/18079316/61224401-16e7f280-a751-11e9-8b4e-cf8fd2a3c581.jpg)

Happens to both double and single.

![20190715223658_1](https://user-images.githubusercontent.com/18079316/61224434-2830ff00-a751-11e9-9818-88e055a97d7f.jpg)

**Comment by underlineGalaxy** [comment] 2019-07-17 19:41
Altough not optimal, a possible workaround is using a lightbridge.

**Comment by Luke18033** [comment] 2019-07-17 19:47
Do normal glass panels also have this problem? This is probably caused by the fact that they start in the extended position, then are retracted in-game if set to start disabled (which is something I was going to change anyway). Another workaround would be to use double panels recessed into the wall 1 block.

**Comment by gustofair** [comment] 2019-07-21 02:17
If I'm correct, thats just a prop_dynamic with a player clip on top. The playerclip is probably on-top of the panel rather then in it, causing a extended clip of 1 unit that players can stand on.

**Comment by ZombiePwner1** [comment] 2019-08-11 23:13
@Luke18033 Normal glass panels don't have this issue as far as I know.

**Comment by Luke18033** [comment] 2020-04-03 19:56
This would be fixed by #3261.

**Closed** 2022-03-26 23:26 UTC
Labels: Bug
