### ISSUE TITLE
Portal 1 angled panel makes static-y noises changing the angle

### ISSUE THREAD

**Issue by dsagfa** [BEEmod/BEE2-items#4372] opened 2023-10-08 22:25 UTC
Steps to reproduce:
Place an Angled Panel while the Portal 1 style is active
Try to change the angle
Lie down, apply pressure to your temples once the blood starts running from your ears and down your neck

**Comment by Luke18033** [comment] 2023-10-13 03:00
Duplicate of #1361

**Closed by Luke18033** 2023-10-13 03:00 UTC
Labels: Bug, Portal 1
