### ISSUE TITLE
Toxic Goo renders as a leak

### ISSUE THREAD

**Issue by annihilatered** [BEEmod/BEE2-items#4028] opened 2021-11-28 23:48 UTC
### BEE2 Application Version

4.41.1 64bit

### BEE2 Package Version

4.41.0

### What operating system are you running on?

Windows 10 (64bit)

### Logs and Reports

```shell
It does not have a log.
```

### Additional information

https://user-images.githubusercontent.com/86435827/143791243-eb370ed8-a630-4095-807c-edbf3bf58346.mp4

As you can see in this video, the toxic goo is very glitchy and repeats whatever is on my screen coming from portal at the moment. Even when I open the menu, the effects continue, regardless of the pause menu. The menu also is effected by the mirror goo.

**Comment by LautaroL20** [comment] 2021-11-29 07:34
Something in your map is causing a leak which makes the toxic goo appearing like that. Please, upload a screenshot from your puzzle to see which elements did you use in your map.

**Comment by Luke18033** [comment] 2021-11-29 18:37
There's a [leak](https://developer.valvesoftware.com/wiki/Leak) in your map. Try removing any items from custom packages to see if they're the cause of the leak. If the issue persists, go to `Portal 2/sdk_content/maps/styled`, put `preview.vmf` and `preview.lin` in a ZIP, then upload that here.

**Comment by annihilatered** [comment] 2021-12-02 13:54
> Try removing any items from custom packages

I do not even know how to add custom packages, but that would be cool. I do not have any custom packages. Currently I am away from my home computer, so i do not have an image of the map and items. Although i can remember the items used:

Laser
Laser cube
Funnel (Gel carry)
Toxic Goo
Regular Cube
Button (input)
Cube Button (input)
Repulsion gel: Heavy: No streaks (Only gel, carried)
Glass panel (output): 90 degrees: acting as see-through door
Light bridge permanent switch (output) (light bridge starting enabled, with cube on top. when a button pressed, light bridge will deactivate, causing cube to fall onto button. there is glass blocking access to said switch-cube. there are lights here. there are two of these items,)
Exit door (sp:1)
Starting door (sp:1)
Large Obs. Room (3)
Light strip (around every goo pit for design)

I tried clean style, clean(valve) style, nothing worked. I think it is because the goo is trying to use the bottomless pit texture, but since it doesn't exist, it has a leak.

**Comment by LautaroL20** [comment] 2021-12-02 14:58
> annihilatered said: " Currently I am away from my home computer, so i do not have an image of the map and items."

When you are at home, try building your map again and if the toxic goo problem is still there, go to `Portal 2/sdk_content/maps/styled`, put `preview.vmf` and `preview.lin` in a ZIP, then upload that here.

**Comment by LautaroL20** [comment] 2021-12-11 01:31
Closing due to lack of interest from the issue's author which doesn't respond. Also, does anyone know if it is Github who automatically hides certain comments from an issue or it is an actual member of the BEEmod organization who can do that?

**Closed by LautaroL20** 2021-12-11 01:31 UTC
Labels: Bug, Compile Error, More Info Needed

**Comment by TeamSpen210** [comment] 2021-12-11 01:37
You should be able to, in the ... button in the upper-right.
