### ISSUE TITLE
Rocket Turret Is Bugged As Hell!

### ISSUE THREAD

**Issue by ZFM2004** [BEEmod/BEE2-items#1984] opened 2017-05-21 13:58 UTC
The rocket turret's rocket does not work at ALL!!!!! please fix it

__________________________________________________________________________________________

- "In some styles. like 1950's, the rocket turret doesn't show up either. It's just a black hole in the ground with an invisible collision mesh on top that you can stand on and collide into"

- "And if it appears in the map, its really buggy"

**Comment by LautaroL20** [comment] 2017-05-21 14:29
This is a duplicate of: https://github.com/BEEmod/BEE2-items/issues/1986

**Comment by LautaroL20** [comment] 2017-05-21 14:30
Well, maybe its not since it doesn´t reffer to any style in particular.

**Comment by hop193** [comment] 2017-05-21 16:48
I like how you said it was a duplicate, even though this post was first.

**Comment by ZFM2004** [comment] 2017-05-21 21:27
I tried it in multiple styles

**Comment by vtipoman** [comment] 2017-05-22 16:11
Same here. The visuals and sounds are present, but the rocket doesn't appear

**Comment by LautaroL20** [comment] 2017-05-22 17:42
Yep, and it is very bugged if it appears...

**Comment by ZFM2004** [comment] 2017-05-22 19:08
thank you for noticing

**Comment by LautaroL20** [comment] 2017-05-22 20:16
anytime

**Comment by Endermage77** [comment] 2017-05-23 13:25
In some styles. like 1950's, the rocket turret doesn't show up either.

**Comment by IceTudor** [comment] 2017-10-08 13:51
For me the rocket turret does a muzzle flash and then no rocket, also aims wrongly, like offset to the right a bit. One level it didn't even hurt me, even if I restarted my Portal 2. It's incredibly broken. Has to be fixed ASAP

**Comment by Fazbear189** [comment] 2017-11-08 00:11
I get that too.

**Comment by PGRedYT** [comment] 2019-01-22 21:08
there is a rocket entity but for some reason whenever the rocket turret is present ingame, it completely breaks the entity, not letting it be able to spawn. (i have a bind key set to shoot rockets)

**Comment by ZombiePwner1** [comment] 2019-01-23 02:42
@PGRedYT Funnily enough the rocket turret was set to play a major role during portal 2's development but it was then removed. I believe parts of it's code has been removed causing it to behave the way it is rather than it's portal 1 variant.

**Comment by PGRedYT** [comment] 2019-01-29 22:37
so why does the turret break the rocket entity? and what use does it have in a puzzle if its broken?

**Comment by ZombiePwner1** [comment] 2019-01-29 23:32
@PGRedYT Mostly a bug with the rocket turret not firing it's rockets properly we have tried to fix it but it's not easy.

**Comment by Luke18033** [comment] 2020-06-15 19:16
Duplicate of #1238 pretty much

**Closed by Luke18033** 2020-06-15 19:16 UTC
Labels: Bug

**Comment by Luke18033** [comment] 2021-07-14 17:58
Literally 1984
