### ISSUE TITLE
Object Sensor Field

### ISSUE THREAD

**Issue by MemeticGitHubUser** [BEEmod/BEE2-items#2946] opened 2019-03-18 19:45 UTC
Like the Lifeform sensor but it detects physics objects (such as cubes and turrets) that pass through it instead of players

**Comment by kdabest2** [comment] 2019-03-18 19:46
instead of players

**Comment by xDadiKx** [comment] 2019-03-18 19:46
Pretty sure it wouldn't be called "lifeform sensor" since, obvious reasons.
I think this was suggested before although.

**Comment by Libbybapa** [comment] 2019-06-07 22:55
I've seen that used to good effect before in a hammer map.

**Comment by Luke18033** [comment] 2021-08-14 23:56
There was a cube sensor in BEE2.2, so sorta a duplicate of #95?

**Comment by Konclan** [comment] 2021-08-15 01:16
I'd say so

**Closed by Konclan** 2021-08-15 01:16 UTC
Labels: New Item

**Comment by Libbybapa** [comment] 2021-08-15 01:37
I couldn't fine a 'cube sensor' on the list.  If you're talking about cube triggers, this is not at all the same thing.  What is described is a field that when a cube or other physics object passes to one side of the field, it outputs a connection.  When an object passes back the other way it turns off the connection.  The resulting logic is VERY different from a cube trigger which activates when a cube is in a zone and deactivates when the cube leaves that zone.  The similarity is the same as the similarity between a player trigger and a lifeform sensor.

**Comment by Konclan** [comment] 2021-08-15 01:54
No cube sensors are on the list which are fields as you described

**Comment by Libbybapa** [comment] 2021-08-15 01:55
Ok, sounds good.
