### ISSUE TITLE
Weighted button placement

### ISSUE THREAD

**Issue by Cellolide** [BEEmod/BEE2-items#2483] opened 2018-02-03 17:55 UTC
Is there a way to remove that extra height all types of weighted buttons have?
So the button is directly on the floor.
![20180203185238_1](https://user-images.githubusercontent.com/33907318/35769982-c95824ea-0913-11e8-9295-09f89f8ec19d.jpg)

**Comment by Cellolide** [comment] 2018-02-03 19:17
1. It would look better.
2. If I place a grating/glass (whatever) on the same tile the textures are just buggy.
 
There were other reasons why I needed it, but the two above are definitly the main reasons.
By the way: The same would also be proper for pedestal buttons.

**Comment by TeamSpen210** [comment] 2018-02-04 00:17
It would be useful, the only thing is that 1950s and Art Therapy (though unreleased) both have flush buttons. So not sure what to do with them.

**Comment by Endermage77** [comment] 2018-02-04 03:02
Add the option for them to be raised?
This could be an itemvar, perhaps.

**Comment by LautaroL20** [comment] 2018-02-05 17:54
This is a good suggestion, and a duplicate of: https://github.com/BEEmod/BEE2-items/issues/845

**Closed by LautaroL20** 2018-02-05 17:54 UTC
Labels: Enhancement
