### ISSUE TITLE
Show "Preview images" for Corridors and Player Model when "Mousing over"

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#1088] opened 2016-11-29 00:44 UTC
This will gonna help A LOT to identify wich exact corridor we want to use / edit for our maps. Also, this will solve the annoyance of having to open each corridor instance in hammer just to examinate what corridor is using beemod. 

### Suggested preview resolution: 218x218

_______________________________________________________________________________________

## Concept Art:
![art](https://cloud.githubusercontent.com/assets/12244376/20692004/d94975ac-b5b3-11e6-922b-acb167ce97de.png)

**Comment by TeamSpen210** [comment] 2016-11-29 00:49
It's a little big - I'd want it to be on mouseover instead or something.

**Comment by Luke18033** [comment] 2016-11-29 04:16
@LautaroL20 This is a good idea. It should use actual screenshots though.

**Comment by Luke18033** [comment] 2016-12-02 01:02
@TeamSpen210 Yeah that would be really big, make it on mouseover.

**Comment by LautaroL20** [comment] 2016-12-02 01:44
Well, i think i might have a little better idea than mouseover, maybe add a Checkbox option like: "Show preview images". So that way users can appreciate a nice 218x218 resolution, leaving users identify each corridors with much more pressure.

**Comment by Luke18033** [comment] 2016-12-02 02:57
No, that wouldn't work very well. The window would become huge, and it would look terrible.

**Comment by LautaroL20** [comment] 2016-12-02 03:10
Thats why its called an aditional "Checkbox option". It means that no one will be obligated to see the preview images, so everyone will be free to using or not using this option. Believe me, a smaller size than "218x218" will make the corridors images begins to be unrecognizable.

**Comment by Luke18033** [comment] 2016-12-02 03:40
It doesn't need to be smaller, it just needs to be hidden unless mousing over the corridor.

**Comment by LautaroL20** [comment] 2016-12-02 03:46
Alright, as long as its not a smaller size than 218x218, mousing over is fine i guess.

**Comment by Luke18033** [comment] 2017-01-25 23:56
This is a duplicate of BEEmod/BEE2.4#216.

**Comment by HugoBDesigner** [comment] 2017-03-14 19:45
I figured that, since the duplicate was closed, this should be reopened. Additionally, if you guys want, I can provide the screenshots. For now I have the SP entry and exit for Clean and Portal 1.

**Comment by HugoBDesigner** [comment] 2017-03-14 19:47
I apologize, I just realized this was the one posted after the first one, not the other way around. My bad.

**Closed** 2017-03-14 19:46 UTC
Labels: Duplicate, Enhancement, Suggestion
