### ISSUE TITLE
Multipulcation of Green Energy Pellets

### ISSUE THREAD

**Issue by hop193** [BEEmod/BEE2-items#1720] opened 2017-03-13 23:39 UTC
When a green energy pellet has connections linked to it, and you activate and deactivate it quickly, the green energy will multiply.

Images:
![20170313193617_1](https://cloud.githubusercontent.com/assets/25728252/23879642/bee8da72-0824-11e7-95df-e37c545829f1.jpg)
![20170313193621_1](https://cloud.githubusercontent.com/assets/25728252/23879646/c3d8928e-0824-11e7-8d19-64a358c37e81.jpg)

**Comment by Luke18033** [comment] 2017-03-13 23:41
Duplicate of #1627.

**Closed by Luke18033** 2017-03-13 23:41 UTC

**Comment by TeamSpen210** [comment] 2017-03-14 00:42
I've effectively rebuilt how the item works, so there's no chance it can duplicate pellets. I've tested it with a input pulsing at 0.01 second intervals (the fastest possible delay), and it still works fine.
