### ISSUE TITLE
The map editor is broken (more precisely, map testing).

### ISSUE THREAD

**Issue by MikeAvtone** [BEEmod/BEE2-items#3784] opened 2021-05-12 09:04 UTC
![20210512192809_1](https://user-images.githubusercontent.com/84069529/117947926-52d24b80-b319-11eb-868e-ef20488920f1.jpg)
![20210512192813_1](https://user-images.githubusercontent.com/84069529/117947933-549c0f00-b319-11eb-9526-a1c264db1132.jpg)
![20210512192815_1](https://user-images.githubusercontent.com/84069529/117947934-5534a580-b319-11eb-81ca-7b873d413b40.jpg)
Every time I start testing the game, I am constantly behind and in the textures, and they are still shifted into each other( most of the map, you can't move without noclip. At first, the fields didn't work.

**Comment by FrozenDragon0** [comment] 2021-05-12 09:16
Duplicate of https://github.com/BEEmod/BEE2-items/issues/3783 I transferred your issue already. And your still not explaining what style or items you are using.

**Closed by FrozenDragon0** 2021-05-12 09:16 UTC

**Comment by MikeAvtone** [comment] 2021-05-12 09:22
i used style: Clean

**Comment by FrozenDragon0** [comment] 2021-05-12 09:43
And what items?

**Comment by MikeAvtone** [comment] 2021-05-12 09:45
![Uploading 1620812729322775381846149253061.jpg…]()

**Comment by MikeAvtone** [comment] 2021-05-12 09:47
![16208128016915706127449084083824](https://user-images.githubusercontent.com/84069529/117954917-365b0100-b363-11eb-8593-77843610451a.jpg)

**Comment by TeamSpen210** [comment] 2021-05-13 00:15
This looks like your FGD files are invalid. Can you try verifying your game cache, and then exporting again?

**Comment by MikeAvtone** [comment] 2021-05-13 00:46
How to check and clear the game cache?
