### ISSUE TITLE
Portal 1 coop exit door doesn't open.

### ISSUE THREAD

**Issue by ZombiePwner1** [BEEmod/BEE2-items#3249] opened 2020-03-22 01:18 UTC
![image](https://user-images.githubusercontent.com/18079316/77240188-10821280-6c1e-11ea-9004-1005b617ab94.png)

**Comment by ZombiePwner1** [comment] 2020-03-22 07:59
Happens in 1980's old aperture aswell.

**Comment by Luke18033** [comment] 2020-03-31 01:02
Duplicate of #2989. It's a pinned issue, can you please pay more attention to that?

**Closed by Luke18033** 2020-03-31 01:02 UTC
Labels: Bug, CO-OP, Old Aperture, Portal 1
