### ISSUE TITLE
Cubes get through gratings

### ISSUE THREAD

**Issue by 0Festive** [BEEmod/BEE2-items#2101] opened 2017-07-22 13:04 UTC

**Comment by LautaroL20** [comment] 2017-07-22 16:38
Oh no, here we go again...... I might know what is causing you from getting that duplicate issue. and it is when you were using past Bee2´s releases, those resouces are still in the Portal 2 sub-folders, and since the latest PRL26 does not have the ability to overwritte old resources anymore, the app its now using them. 

The solution to this annoyance:  

You will have to manually delete the following folders from Portal 2: bee2 (located at "Portal 2\sdk_content\maps\instances"), bin and bee2 (located in the main Portal 2 folder). After this, verify the game cache files, then launch Bee PRL26 and make it to export the full resources. Now you should not get those weird issues anymore.

This is a duplicate of: https://github.com/BEEmod/BEE2-items/issues/1929 and https://github.com/BEEmod/BEE2-items/issues/1974

**Closed by LautaroL20** 2017-07-22 16:38 UTC
Labels: Bug, Duplicate

**Comment by Luke18033** [comment] 2017-07-22 18:54
You can also just do File>Remove Game (Uninstall from Selected Game in dev) and that'll delete all the files for you. Re-add it and export, and it'll copy over the new versions.
