### ISSUE TITLE
Logic Gates causes "Failure To Compile"

### ISSUE THREAD

**Issue by FierceThundr** [BEEmod/BEE2-items#3425] opened 2020-08-02 16:08 UTC
I currently just updated from beemod 4.36.1 to version 4.37.0 and tried to work on one of my maps made during the former version. 

I'm currently experiencing this error report when I try to compile the map in question.

(I'm unaware of whether this should be considered an application bug or one related to items. But my standard method of mitigating compile errors has not worked)

> VBSP failed.
> 
> [I] vbsp.main(): BEE2 v VBSP hook initiallised.
> [I] cond.core.import_conditions(): Imported all conditions modules!
> [I] vbsp.main(): Map path is "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf"
> [I] vbsp.main(): New path: "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
> [I] vbsp.main(): PeTI map detected!
> [I] vbsp.main(): Loading settings...
> [W] texturing.load_config(): overlays: Unknown texture names faithfling, faithland
> [W] texturing.load_config(): special: Unknown texture names edge_special, pedestalside
> [W] vbsp_options.load(): Extra config options: {'glass_scale': '0.15', 'staticpan': 'instances/BEE2/clean/static_panel/'}
> [I] cond.core.build_itemclass_dict(): Read 30 item IDs, with 48 embeds!
> [W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_ANGLED_BLOCK_60", which is no longer used.
> [W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_ANGLED_BLOCK_45", which is no longer used.
> [W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_ANGLED_BLOCK_30", which is no longer used.
> [W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_ANGLED_BLOCK_CORNER_60", which is no longer used.
> [W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_ANGLED_BLOCK_CORNER_60", which is no longer used.
> [W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_ANGLED_BLOCK_CORNER_45", which is no longer used.
> [W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_ANGLED_BLOCK_CORNER_45", which is no longer used.
> [W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_ANGLED_BLOCK_CORNER_30", which is no longer used.
> [W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_ANGLED_BLOCK_CORNER_30", which is no longer used.
> [W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_FLAT_QUARTER", which is no longer used.
> [W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_FLAT_HALF", which is no longer used.
> [W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_FLAT_THREE_QUARTER", which is no longer used.
> [W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE_PGUN_BASE", which is no longer used.
> [W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE_PGUN_BASE", which is no longer used.
> [I] cubes.parse_conf(): Parsed 7 cube types, 1 dropper types and 4 addons.
> [I] fizzler.read_configs(): Loaded 14 fizzlers.
> [I] vbsp.load_settings(): Settings Loaded!
> [I] vbsp.load_map(): Parsing Map...
> [I] vbsp.load_map(): Reading Map...
> [I] vbsp.load_map(): Loading complete!
> [I] antlines.parse_antlines(): Parsing antlines...
> [I] antlines.parse_antlines(): Done! (5 antlines)
> [I] vbsp.get_map_info(): Forcing elevator spawn!
> [I] vbsp.mod_entryexit(): Setting Coop Exit to 4
> [I] vbsp.get_map_info(): Game Mode: COOP
> [I] vbsp.get_map_info(): Is Preview: False
> [I] brushLoc.read_from_map(): Analysed map, filling air... (906 starting positions..)
> [I] brushLoc.read_from_map(): Air filled!
> [I] texturing.setup(): Generating texture clumps...
> [I] texturing.setup(): NORMAL.FLOOR.BLACK: 100 Clumps for 2455 tiles
> [I] texturing.setup(): Generating texture clumps...
> [I] texturing.setup(): NORMAL.CEILING.WHITE: 97 Clumps for 2455 tiles
> [I] texturing.setup(): Generating texture clumps...
> [I] texturing.setup(): NORMAL.CEILING.BLACK: 97 Clumps for 2455 tiles
> [I] texturing.setup(): Generating texture clumps...
> [I] texturing.setup(): NORMAL.WALL.WHITE: 147 Clumps for 2455 tiles
> [I] texturing.setup(): Generating texture clumps...
> [I] texturing.setup(): NORMAL.WALL.BLACK: 147 Clumps for 2455 tiles
> [I] texturing.setup(): Generating texture clumps...
> [I] texturing.setup(): PANEL.FLOOR.BLACK: 100 Clumps for 2455 tiles
> [I] texturing.setup(): Generating texture clumps...
> [I] texturing.setup(): PANEL.CEILING.BLACK: 97 Clumps for 2455 tiles
> [I] texturing.setup(): Generating texture clumps...
> [I] texturing.setup(): PANEL.WALL.WHITE: 147 Clumps for 2455 tiles
> [I] texturing.setup(): Generating texture clumps...
> [I] texturing.setup(): PANEL.WALL.BLACK: 147 Clumps for 2455 tiles
> [I] cond.core.check_all(): Checking Conditions...
> [I] cubes.link_cubes(): SPLAT File: ['instances/bee2/logic/gel_splat.vmf']
> [I] cond.catwalks.res_make_catwalk(): Starting catwalk generator...
> [I] cond.scaffold.res_unst_scaffold(): Running Scaffold Generator (BEE2_SCAFFOLD)...
> [I] cond.scaffold.res_unst_scaffold(): Finished Scaffold generation!
> [I] connections.gen_item_outputs(): Generating item IO...
> [I] connections.add_item_inputs(): LOGIC counter: lg577
> [I] connections.add_item_inputs(): LOGIC counter: lg578
> [I] connections.add_item_inputs(): LOGIC counter: lg579
> [I] connections.add_item_inputs(): LOGIC counter: lg580
> [I] connections.add_item_inputs(): LOGIC counter: lg581
> [I] connections.add_item_inputs(): LOGIC counter: lg585
> [I] connections.add_item_inputs(): LOGIC counter: lg588
> [I] connections.add_item_inputs(): LOGIC counter: lg589
> [I] connections.add_item_inputs(): LOGIC counter: lg554
> [I] connections.add_item_inputs(): LOGIC counter: lg556
> [I] connections.add_item_inputs(): LOGIC counter: lg557
> [I] connections.add_item_inputs(): LOGIC counter: lg558
> [I] connections.add_item_inputs(): LOGIC counter: lg560
> [I] connections.add_item_inputs(): LOGIC counter: lg561
> [I] connections.add_item_inputs(): LOGIC counter: lg562
> [I] connections.add_item_inputs(): LOGIC counter: lg564
> [I] connections.add_item_inputs(): LOGIC counter: lg565
> [I] connections.add_item_inputs(): LOGIC counter: lg566
> [I] connections.add_item_inputs(): LOGIC counter: lg568
> [I] connections.add_item_inputs(): LOGIC counter: lg569
> [I] connections.add_item_inputs(): LOGIC counter: lg570
> [I] connections.add_item_inputs(): LOGIC counter: lg571
> [I] connections.add_item_inputs(): LOGIC counter: lg572
> [I] connections.add_item_inputs(): LOGIC counter: lg573
> [I] connections.add_item_inputs(): LOGIC counter: lg574
> [I] connections.add_item_inputs(): LOGIC counter: lg575
> [I] connections.add_item_inputs(): LOGIC counter: lg576
> [I] connections.add_item_inputs(): LOGIC counter: lg532
> [I] connections.add_item_inputs(): LOGIC counter: lg533
> [I] connections.add_item_inputs(): LOGIC counter: lg534
> [I] connections.add_item_inputs(): LOGIC counter: lg535
> [I] connections.add_item_inputs(): LOGIC counter: lg536
> [I] connections.add_item_inputs(): LOGIC counter: lg538
> [I] connections.add_item_inputs(): LOGIC counter: lg539
> [I] connections.add_item_inputs(): LOGIC counter: lg540
> [I] connections.add_item_inputs(): LOGIC counter: lg541
> [I] connections.add_item_inputs(): LOGIC counter: lg542
> [I] connections.add_item_inputs(): LOGIC counter: lg543
> [I] connections.add_item_inputs(): LOGIC counter: lg544
> [I] connections.add_item_inputs(): LOGIC counter: lg545
> [I] connections.add_item_inputs(): LOGIC counter: lg546
> [I] connections.add_item_inputs(): LOGIC counter: lg547
> [I] connections.add_item_inputs(): LOGIC counter: lg548
> [I] connections.add_item_inputs(): LOGIC counter: lg549
> [I] connections.add_item_inputs(): LOGIC counter: lg550
> [I] connections.add_item_inputs(): LOGIC counter: lg552
> [I] connections.add_item_inputs(): LOGIC counter: lg553
> [I] connections.gen_item_outputs(): Item IO generated.
> [I] vbsp.set_elev_videos(): Elevator type: FORCE
> [W] cond.positioning.flag_brush_at_loc(): Using type=same in posIsSolid is deprecated, put this in mode!
> [I] voiceLine.add_voice(): Adding Voice Lines!
> [W] BEE2_config.load(): Config "bee2\voice.cfg" not found! Using defaults...
> [W] BEE2_config.load(): Config "bee2\mid_voice.cfg" not found! Using defaults...
> [I] voiceLine.add_voice(): Quote events: []
> [I] voiceLine.add_voice(): 0 Mid quotes
> [I] voiceLine.add_voice(): Done!
> [I] vbsp.set_player_portalgun(): Setting Portalgun:
> [I] vbsp.set_player_portalgun(): Blue: Y, Orange: Y
> [I] vbsp.set_player_portalgun(): Done!
> [I] cond.core.check_all(): Map has attributes: ['fizzler', 'fr_fdf', 'tdb_ff', 'glass', 'grating', 'cube', 'cubereflect', 'cubedropper', 'cubedropperreflect', 'cubenotcompanion', 'cubecompanion', 'cubedroppercompanion', 'cubesphere', 'cubedroppersphere', 'cubesphereshaped', 'laseremitter', 'laser', 'deadly', 'weightedbutton', 'floorbutton', 'buttonacceptscube', 'buttonacceptsball', 'cubebutton', 'ballbutton', 'faith', 'catapult', 'faithplate', 'gel', 'geldropper', 'bouncegel', 'bluegel', 'pedestalbutton', 'lasercatcher', 'bridge', 'hardlight', 'water', 'watergel', 'cleargel', 'spawn_dual']
> [I] cond.core.check_all(): instanceLocs cache: CacheInfo(hits=154577, misses=363, maxsize=256, currsize=256)
> [I] cond.core.check_all(): Style Vars: {'doorcameras': True, 'restartonexit': True, 'multiversecave': True, 'fixfizzlerbump': False, 'nomidvoices': False, 'unlockdefault': False, 'allowgoomist': True, 'funnelallowswitchedlights': True, 'enableshapesignageframe': True}
> [I] cond.core.check_all(): Global instances: {'instances/bee2/logic/reflection_cube_wake.vmf'}
> [I] vbsp.add_extra_ents(): Adding Music...
> [I] vbsp.add_extra_ents(): Adding global ents...
> [I] vbsp.add_extra_ents(): Adding Global PTI Ents
> [I] vbsp.change_ents(): Editing Other Entities...
> [I] tiling.generate_brushes(): Generating tiles...
> [I] tiling.generate_brushes(): Generating goop...
> [I] vbsp.change_overlays(): Editing Overlays...
> [I] vbsp.fix_worldspawn(): Editing WorldSpawn
> [I] vbsp.save(): Saving New Map...
> [I] vbsp.save(): Complete!
> [I] <Valve>.run_compiler(): Calling original VBSP...
> [I] <Valve>.run_compiler(): Args: '-game', 'C:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/', 'C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\\maps\\styled\\preview.vmf'
> [I] <valve>.vbsp(): Valve Software - vbsp.exe (Nov 12 2019)
> [I] <valve>.vbsp(): 4 threads
> [I] <valve>.vbsp(): materialPath: C:\Program Files (x86)\Steam\steamapps\common\Portal 2\portal2\materials
> [I] <valve>.vbsp(): Loading C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf
> [I] <valve>.vbsp(): ConVarRef gpu_level doesn't point to an existing ConVar
> [I] <valve>.vbsp(): material "bee2/nodraw_glass" not found.
> [I] <valve>.vbsp(): Material not found!: BEE2/NODRAW_GLASS
> [I] <valve>.vbsp(): "materials/bee2/water_clear_refract_flowing.vtf": cached version doesn't exist
> [I] <valve>.vbsp(): Could not open instance file instances/BEE2/logic/bee/logic_or.vmf
> [I] <valve>.vbsp():

**Comment by LautaroL20** [comment] 2020-08-02 23:17
> `Could not open instance file instances/BEE2/logic/bee/logic_or.vmf`

Here is the problem that causes your building error.

**Comment by Luke18033** [comment] 2020-08-02 23:21
Duplicate of #3359

**Closed by Luke18033** 2020-08-02 23:21 UTC
Labels: Compile Error

**Comment by LautaroL20** [comment] 2020-08-02 23:26
@FierceThundr - Your issue will be fixed for the next release.

**Comment by FierceThundr** [comment] 2020-08-03 10:26
Ok thank you
