### ISSUE TITLE
New Item: Angled Panel attached to Piston/Retractable Panel

### ISSUE THREAD

**Issue by hop193** [BEEmod/BEE2-items#1759] opened 2017-03-18 01:18 UTC
Since I figured out a Portable Wall on a Piston is being remade from BEE2 Addons (even with one with an auto portal), so I decided to recommend this. It's an angled panel that is attached to a piston. Simple enough.

Looks like this (taken from Portal 2 Chapter I):
![20170317210010_1](https://cloud.githubusercontent.com/assets/25728252/24067720/a5d6686c-0b56-11e7-8727-e79da0f8d6b9.jpg)
On top of being attached to a piston, it's possible for it to be retractable. It would be interesting to see. Plus, it is a possibility for it also to have an auto portal.
One last thing, the original piston could be retractable. I'm not sure if it was there before, I honestly don't remember. It would be terrific to see, though.

I'm sorry if I asked for a lot, you don't have to add all of it.

**Comment by Luke18033** [comment] 2017-03-18 01:20
Duplicate of #593.

**Closed by Luke18033** 2017-03-18 01:20 UTC
