### ISSUE TITLE
Radiative Flux Rectangle has no sound on activation.

### ISSUE THREAD

**Issue by CreepiX987** [BEEmod/BEE2-items#2115] opened 2017-07-31 09:37 UTC
Instead it plays the "Oh, fiddlesticks" sound. In the console it writes:
> CSoundEmitterSystemBase::GetParametersForSound:  No such sound BEE2.p1.rex_field_activate

**Comment by Luke18033** [comment] 2017-07-31 14:52
Duplicate of #1615.

**Closed by Luke18033** 2017-07-31 14:52 UTC
