### ISSUE TITLE
Improve Unstationary Scaffold Piston Emitter's Speed

### ISSUE THREAD

**Issue by hop193** [BEEmod/BEE2-items#1819] opened 2017-04-07 20:34 UTC
Add the Pedestal Button's Timer widget to adjust the speed of the platform.

**Comment by Luke18033** [comment] 2017-04-07 23:45
Two things:
1. Duplicate of #504.
2. The Slot item already uses the timer.

**Closed by Luke18033** 2017-04-07 23:45 UTC

**Comment by hop193** [comment] 2017-04-08 00:28
Oh, it does?
