### ISSUE TITLE
Overgrown Signage doesn't work on same block as laser catcher etc.

### ISSUE THREAD

**Issue by cartman1337** [BEEmod/BEE2-items#2461] opened 2018-01-26 23:03 UTC
This is with 2.4.0pr28.

As an alternative to cluttering the walls with too many antlines and automatic signage, I thought I wanted to place informative Signage close to some laser catchers. Doing so in the editor yields no errors or crashes (not even when placing them directly on top of the catcher, something that probably SHOULD cause a crash), and there's no problem compiling.
![Signage placed with laser catchers](https://i.imgur.com/z6i0wFj.jpg)

However, in the compiled map, the Signage is nowhere to be seen.
![Compiled - Signage missing](https://i.imgur.com/4h6xgxG.jpg)

I got the same issue placing Signage on a block with Square Light on it, and there might be other items that causes the issue too, however placing Signage on a square with for instance Fizzler or Glass on it works fine.

**Comment by TeamSpen210** [comment] 2018-01-27 00:31
Duplicate of #555

**Comment by TeamSpen210** [comment] 2018-01-27 00:32
It's a issue with how the compiler is written. I'm working on a rework which solves this along with other improvements.

**Closed by TeamSpen210** 2018-01-27 00:32 UTC
