### ISSUE TITLE
1/4 wall sized trigger with 8 positions gyzmo

### ISSUE THREAD

**Issue by Libbybapa** [BEEmod/BEE2-items#2413] opened 2017-11-29 00:07 UTC
Maybe it's impossible but it would sometimes be helpful to add a movement handle (8 positions) to triggers.  I have had a couple different uses for that.  If necessary I can go into details on situations where it would be desirable.

**Comment by Konclan** [comment] 2017-11-29 00:47
I'm not adding to the suggestion just wanting to inform. You can do this yourself pretty easily if you wanted to. In the Bee2 root folder open packages\beemod\items\trigger\editoritems.txt and change "MovementHandle" "HANDLE_NONE" to "MovementHandle" "HANDLE_8_POSITIONS". You'll want 7zip to extract the beemod package.

**Comment by Starchasm** [comment] 2017-11-29 00:49
Thanks for the suggestion.  I wish it were that easy.  I actually already tried that.  It works for some other items (logic gates) but the handle is not added even when the line is changed in the editoritems file for triggers.

**Comment by Konclan** [comment] 2017-11-29 00:55
Interesting, I'll take a look.

**Comment by Konclan** [comment] 2017-11-29 01:16
It worked perfectly for me
![capture](https://user-images.githubusercontent.com/16567080/33352856-88f47854-d470-11e7-88c0-bf4f060c9494.png)

Try using this editoritems.txt paste https://pastebin.com/9FdFi8jW

**Comment by Starchasm** [comment] 2017-11-29 06:52
Wow, that's weird.  I triple-checked that I edited the correct file with the correct syntax.  Hmmm.

**Comment by Starchasm** [comment] 2017-11-29 07:12
I rechecked the file, and then restarted everything.  Yup, it's working now.  I'm not sure what changed but thanks.  One issue I see is that the trigger keeps popping back to the 'normal' position when you change other geometry in the map.  It would be great if it could be made to stay put.

**Comment by LautaroL20** [comment] 2017-11-29 16:36
@Starchasm - Some examples of situations would help to understand if we should implement thin 1/4 trigger variants or not. Since i think this could be a fine suggestion but i need to be sure.

@Konclan - Currently it does not work perfectly, since their selection meshes are interfering too much with the 8 positions gyzmo, making it almost unrotable.

**Comment by Starchasm** [comment] 2017-11-29 16:50
One situation is at a door between tutorial room and main puzzle.  I have encountered the situation where I want the tutorial room exit door to be triggered closed permanently when the player passes through it.  If the player _almost_  passes through the door just far enough to touch the trigger, but not far enough to allow the door to close, and then they back up into the tutorial room, the player is trapped permanently.  There are obviously ways to adjust geometry and the placement of the trigger but those can be problematic depending on the overall layout of the map.  Much more convenient would be to move the trigger 1/4 voxel away from the door so the player needs to touch it when leaving the tutorial room, but cannot touch it prior to being out of the way of the door closing.  It is not strictly necessary as there are workarounds but it would be more convenient in some cases with no downsides that I can see.

**Comment by Starchasm** [comment] 2017-11-29 17:07
I'm curious what you mean by "1/4 trigger variants".  If by that you mean a 1/4 wall sized trigger that could be placed in any of the 8 positions of a light strip, that would be fantastic.  Please add that.  :)

**Comment by Starchasm** [comment] 2017-11-29 19:26
It's strange to me that adding a movement handle and having the item stay where the movement handle places it need to be two separate items, but whatever floats your boat.

**Comment by Starchasm** [comment] 2017-11-29 19:29
So you're saying that a trigger that has the 8 position movement cannot be made so it can anchor on barriers, but the ones without movement handle can?

**Comment by Luke18033** [comment] 2017-11-29 19:32
Yep. It's a bug with the editor, we can't fix it.

**Comment by Starchasm** [comment] 2017-11-29 19:36
Interesting.  If I change ["CanAnchorOnBarriers"	"1"] to ["CanAnchorOnBarriers"	"0"] will it stop the trigger from reverting back to the normal position?

**Comment by LautaroL20** [comment] 2017-11-29 20:13
Or you also can get rid from that line directly ("CanAnchorOnBarriers" "1"). This fixes the reverting back issue.

**Comment by Starchasm** [comment] 2017-11-29 21:36
Ok.  Thanks.  I can see how anchoring on barriers would be usepful and can also see how the movement handle would be beneficial.  I guess I'll have to switch on a per map basis.  :-P

**Comment by Luke18033** [comment] 2019-11-28 01:41
Duplicate of #300

**Closed by Luke18033** 2019-11-28 01:41 UTC
Labels: New Item Variant
