### ISSUE TITLE
Hitscan Portal 1 rockets

### ISSUE THREAD

**Issue by RmxMi** [BEEmod/BEE2-items#3346] opened 2020-06-29 19:18 UTC
I see. (referring to my last suggestion).

But the turrets are hitscanners and do not have a visible flying rocket so maybe fix that if you wanna add the rocket box or the breakable glass.

**Comment by RmxMi** [comment] 2020-06-29 19:19
Also, they take AGES to fire so balance that.

**Comment by Luke18033** [comment] 2020-06-29 19:25
Duplicate of #1238. They're not hitscan, the rockets were spawning outside the map.

**Closed by Luke18033** 2020-06-29 19:25 UTC
