### ISSUE TITLE
Connected up auto-save checkpoints

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#1244] opened 2016-12-22 00:12 UTC
Moved from the BenVlodgi´s section: https://github.com/BEEmod/BEE2.4/issues/206

Original post by @Venima:

"So the basic idea is that the auto-save or checkpoint object should be able to be connected up to a signal, so that it'll only auto-save if a certain 'something' is true (being always-active if there is no signal). 

Reason:
I love building large or complex portal maps, but I often struggle to place checkpoints in the right places so that they're not triggered before/after a certain risky task has been completed. Sometimes the player would even cross the same path twice. With my solution, you could have multiple checkpoints even in the same space, and just have them connected up to different events, like when a weighted button is pressed. This would allow a map-maker to make their chambers much more forgiving on the player, and fine-tune their auto-save events based on specific chamber requirements."

**Comment by Byzarru** [comment] 2016-12-22 02:24
Duplicate of #1077 and confirmed by TeamSpen210.

**Closed** 2016-12-22 02:27 UTC
Labels: confirmed, duplicate, Suggestion
