### ISSUE TITLE
Script error with Faith Plate-targeted Brush-Top Piston Platforms due to unnamed prop

### ISSUE THREAD

**Issue by The1stWii2** [BEEmod/BEE2-items#4380] opened 2023-10-22 04:13 UTC
### BEE2 Application Version

4.43.0 64-bit

### BEE2 Package Version

4.43.0

### What operating system are you running on?

Windows 10 (64bit)

### Description of the bug

Targeting a Brush-Top Piston Platform (i.e, "Companion" & "Reflective" cube types) causes the VScript that drives them, `common.nut`, to break. If the target height is 3 or 4 voxels (other heights and directions don't throw errors don't produce errors, but are still subject to the bug), the script throws a `DoEntFire was passed an invalid entity instance`.
A deeper analysis reveals that the piston tip prop—normally named `pl[n]-pist4`—for some reason goes unnamed.

Perhaps due to, or a related bug, is the given Piston Platform will also rise 1 less than the intended height.

This bug does not affect untargeted Brush-Top Piston Platforms nor targeted regular (i.e., "Standard" cube type) Piston Platforms.

## Video Demo
https://github.com/BEEmod/BEE2-items/assets/109736937/df556998-cf2b-4c68-8af6-af3aa1a39cc4

## Puzzlemaker Layout
<img width="464" alt="puzzlemaker" src="https://github.com/BEEmod/BEE2-items/assets/109736937/964e99fa-2060-442e-8beb-7652ffe876c2">

### Expected behavior

Targeting a Brush-Top Piston Platform with a Faith Plate should not result in errors.

## In Puzzlemaker
1. Place Piston Platform (rising to 3 voxels or higher).
2. Set Cube Type to "Companion" or "Reflective".
3. Disable "Auto-drop first cube".
4. Place Faith Plate.
5. Place Faith Plate on Piston Platform.
6. Add any input to Piston Platform.

## In-game
1. Activate input.

## Console log
<details>
<summary>Log from Video Demo</summary>

```

Faith plate launch
==============================
(21.90) output: (trigger_catapult,fp5-trigger) -> (fp5-arm,SetAnimation)(angled)
(21.90) output: (trigger_catapult,fp5-trigger) -> (@music_faith_play,Trigger)()
(21.90) input fp5-trigger: fp5-arm.SetAnimation(angled)
unhandled input: (Trigger) -> (@music_faith_play), from (trigger_catapult,fp5-trigger); target entity not found


Pick up cube
==============================
(27.92) input : cu15483-box.Use()
(27.92) output: (prop_weighted_cube,cu15483-box) -> (@voice_anycube_pickup,FireUser1)()
Removing from action list: (prop_weighted_cube,cu15483-box) -> (@voice_anycube_pickup,FireUser1)
unhandled input: (FireUser1) -> (@voice_anycube_pickup), from (prop_weighted_cube,cu15483-box); target entity not found


Place cube on Button
==============================
(30.03) output: (prop_floor_button,bt10674-btn) -> (toggle_bt10674,SetTextureIndex)(1)
(30.03) output: (prop_floor_button,bt10674-btn) -> (pl7-proxy,OnProxyRelay1)()
(30.03) output: (prop_floor_button,bt10674-btn) -> (@voice_floor_button,FireUser1)()
(30.03) input bt10674-btn: toggle_bt10674.SetTextureIndex(1)
(30.03) input bt10674-btn: pl7-proxy.OnProxyRelay1()
(30.03) output: (prop_floor_button,bt10674-btn) -> (pl7-counter,Add)(1)
unhandled input: (FireUser1) -> (@voice_floor_button), from (prop_floor_button,bt10674-btn); target entity not found
(30.03) input bt10674-btn: pl7-counter.Add(1)
(30.03) output: (math_counter,pl7-counter) -> (pl7-script,FireUser2)()
(30.03) input pl7-counter: pl7-script.FireUser2()
(30.03) output: (ambient_generic,pl7-script) -> (!self,RunScriptCode)(moveto(3))
(30.03) input pl7-script: pl7-script.RunScriptCode(moveto(3))
Moving: 0 -> 3
_up() called.
-----------
i = 1;
positions[i] = -1;
(30.03) input pl7-script: pl7-script.PlaySound()
(30.03) input pl7-script: pl7-wake_trig.Enable()
(30.03) input pl7-script: pl7-pist1.Open()
(30.13) input pl7-script: pl7-wake_trig.Disable()
(30.90) output: (func_movelinear,pl7-pist1) -> (pl7-script,RunScriptCode)(positions[1]=1;_up())
(30.90) output: (func_movelinear,pl7-pist1) -> (pl7-script,RunScriptCode)(positions[1]=1;_up())
(30.90) input pl7-pist1: pl7-script.RunScriptCode(positions[1]=1;_up())
_up() called.
-----------
i = 1;
positions[i] = 1;
i = 2;
positions[i] = -1;
(30.90) input pl7-pist1: pl7-script.RunScriptCode(positions[1]=1;_up())
_up() called.
-----------
i = 1;
positions[i] = 1;
i = 2;
positions[i] = 0;
(30.90) input pl7-script: pl7-pist2.Open()
(30.90) input pl7-script: pl7-pist2.Open()
(31.77) output: (func_movelinear,pl7-pist2) -> (pl7-script,RunScriptCode)(positions[2]=1;_up())
(31.77) output: (func_movelinear,pl7-pist2) -> (pl7-script,RunScriptCode)(positions[2]=1;_up())
(31.77) input pl7-pist2: pl7-script.RunScriptCode(positions[2]=1;_up())
_up() called.
-----------
i = 1;
positions[i] = 1;
i = 2;
positions[i] = 1;
i = 3;
positions[i] = -1;
VScript error: DoEntFire was passed an invalid entity instance.
(31.77) input pl7-pist2: pl7-script.RunScriptCode(positions[2]=1;_up())
_up() called.
-----------
i = 1;
positions[i] = 1;
i = 2;
positions[i] = 1;
i = 3;
positions[i] = 0;
VScript error: DoEntFire was passed an invalid entity instance.

Faith Plate launch
============================== 
(35.68) output: (trigger_catapult,fp5-trigger) -> (fp5-arm,SetAnimation)(angled)
(35.68) output: (trigger_catapult,fp5-trigger) -> (@music_faith_play,Trigger)()
(35.70) input fp5-trigger: fp5-arm.SetAnimation(angled)
unhandled input: (Trigger) -> (@music_faith_play), from (trigger_catapult,fp5-trigger); target entity not found


Remove Cube from Button
============================== 
An error occurred while attempting to download a file from the UGC server!
(45.25) input : cu15483-box.Use()
(45.30) output: (prop_floor_button,bt10674-btn) -> (toggle_bt10674,SetTextureIndex)(0)
(45.30) output: (prop_floor_button,bt10674-btn) -> (pl7-proxy,OnProxyRelay2)()
(45.30) input bt10674-btn: toggle_bt10674.SetTextureIndex(0)
(45.30) input bt10674-btn: pl7-proxy.OnProxyRelay2()
(45.30) output: (prop_floor_button,bt10674-btn) -> (pl7-counter,Subtract)(1)
(45.30) input bt10674-btn: pl7-counter.Subtract(1)
(45.30) output: (math_counter,pl7-counter) -> (pl7-script,FireUser1)()
(45.30) input pl7-counter: pl7-script.FireUser1()
(45.30) output: (ambient_generic,pl7-script) -> (!self,RunScriptCode)(moveto(0))
(45.30) input pl7-script: pl7-script.RunScriptCode(moveto(0))
Moving: 3 -> 0
_dn() called.
-----------
i = 4;
positions[i] = -1;
i = 3;
positions[i] = 0;
VScript error: DoEntFire was passed an invalid entity instance.

AN ERROR HAS OCCURED [the index 'GetOrigin' does not exist]

CALLSTACK
*FUNCTION [_dn()] common.nut line [176]
*FUNCTION [moveto()] common.nut line [128]
*FUNCTION [main()] InputRunScript line [1]

LOCALS
[i] 3
[this] TABLE
[old_pos] 3
[new_pos] 0
[this] TABLE
[this] TABLE
 Entity pl7-script encountered an error in RunScript()


Faith plate launch
============================== 
(49.43) output: (trigger_catapult,fp5-trigger) -> (fp5-arm,SetAnimation)(angled)
(49.43) output: (trigger_catapult,fp5-trigger) -> (@music_faith_play,Trigger)()
(49.43) input fp5-trigger: fp5-arm.SetAnimation(angled)
unhandled input: (Trigger) -> (@music_faith_play), from (trigger_catapult,fp5-trigger); target entity not found


End demo
============================== 

``` 

</details>

### Additional information

`common.nut` was edited to spit out more debugging information. No logic was modified.

**Comment by TeamSpen210** [comment] 2023-10-22 05:14
Thanks for the detailed report, though actually this is a duplicate of #3482, and is a `srctools` bug. The piston moving only 1 block is because the VScript fails to find it, breaks, and so never gets to telling the next piston to move. Currently bullseyes don't attach to "glass" platforms, only white/black ones.

**Closed by TeamSpen210** 2023-10-22 05:14 UTC
Labels: Bug, Done in next release
