### ISSUE TITLE
Add Squarebeams

### ISSUE THREAD

**Issue by Milkman68** [BEEmod/BEE2-items#2308] opened 2017-10-23 19:41 UTC
you could place this anywhere like grating but it has larger frames 
<img width="138" alt="capture 57" src="https://user-images.githubusercontent.com/31172185/31909550-54b781a0-b7ef-11e7-8475-c5c7a526da28.PNG">

**Comment by LautaroL20** [comment] 2017-10-23 22:31
This is a duplicate of: https://github.com/BEEmod/BEE2-items/issues/1752

**Comment by BETTEREXTENEDEDITORMOD** [comment] 2017-10-24 07:12
No this has the same function as grating you place it like Grating it works like grating but the frames are larger

**Comment by ZombiePwner1** [comment] 2017-10-24 07:14
@BETTEREXTENEDEDITORMOD I can see where your going with this but it's similar to: #1752

**Comment by IceTudor** [comment] 2017-10-25 18:07
What's the use of this? It's just a grating, nothing else.

**Comment by Endermage77** [comment] 2017-10-25 19:29
It's a structural grating.
It could be  BTS style variant, perhaps?

**Comment by BETTEREXTENEDEDITORMOD** [comment] 2017-10-25 21:11
i just wanted this because i like this type of grating more than the regular one it looks better anyways

**Comment by awesomedoctorx3** [comment] 2017-10-27 17:34
I would like this as well. however, a cube can fit through the square holes, so we'd want to fix that.

**Comment by Endermage77** [comment] 2017-10-27 22:24
Eh, we can just put a grating collider over the whole thing so you can't stick cubes in.

**Comment by BETTEREXTENEDEDITORMOD** [comment] 2017-10-28 18:34
we could merge this with grating with start enabled or something like that

**Comment by Endermage77** [comment] 2017-10-28 19:01
Stylevar, perhaps?

**Comment by BETTEREXTENEDEDITORMOD** [comment] 2017-10-28 23:03
i think start enabled because what if you want to use both in one map?

**Comment by TeamSpen210** [comment] 2017-10-28 23:59
I was going to use this for BTS grating. But as @awesomedoctorx3 said, cubes can clearly fit through it so it's not very realistic. It might make sense if there was grating inside, but by that point it's not really worth it anymore.

**Comment by awesomedoctorx3** [comment] 2017-10-29 00:03
I'd like to this item still implemented. it'd be like a permanent death grid, since cubes can go through.

**Comment by TeamSpen210** [comment] 2017-10-29 00:04
That would actually be nice interesting, a grating that only blocks players, or that you can crawl through but can't fling through.

**Comment by BETTEREXTENEDEDITORMOD** [comment] 2017-10-29 01:19
and you couldn't keep speed through propulsion gel

**Comment by Endermage77** [comment] 2017-10-29 02:34
Hmmm...

... Some sort of testing element that would actually elicit the need for crawling.

Interesting...

**Comment by IceTudor** [comment] 2017-11-02 15:25
Now that I think about it, it seems useful. It should split gel bombs as seen in chapter 9 where you spill repulsion gel onto the turrets.

**Comment by BETTEREXTENEDEDITORMOD** [comment] 2017-11-03 19:11
this is basically an anti momentum grating

**Comment by awesomedoctorx3** [comment] 2017-11-03 19:15
it'd be more like a laserfield that never turns off, since cubes can go
through.

**Comment by BETTEREXTENEDEDITORMOD** [comment] 2017-11-03 19:29
but you could still crawl through it

**Comment by awesomedoctorx3** [comment] 2017-11-03 19:31
No, the holes are too small to crawl through.

**Comment by BETTEREXTENEDEDITORMOD** [comment] 2017-11-03 19:38
that only if you shrink the size down like some maps do so you can't crawl through them the regular size is big enough

**Comment by awesomedoctorx3** [comment] 2017-11-03 19:40
No, the default size is too small.

**Comment by BETTEREXTENEDEDITORMOD** [comment] 2017-11-03 19:53
<img width="682" alt="capture 63" src="https://user-images.githubusercontent.com/31172185/32393186-cc479292-c095-11e7-83a0-f03dd7a4ac28.PNG">
you can fit but there's grating inside the frame stopping you

**Comment by awesomedoctorx3** [comment] 2017-11-03 19:53
No, you can't fit. even if the wall was clear, you couldn't fit.

**Comment by Luke18033** [comment] 2021-10-03 21:42
I'll probably use squarebeams with grating inside as the Art Therapy grating variant, but otherwise I don't see much use for this. Squarebeams which you need to crawl through could be confusing to players since normally you never need to do that.

**Closed** 2024-04-04 05:13 UTC
Labels: New Feature
