### ISSUE TITLE
Weight Detection Field

### ISSUE THREAD

**Issue by TheLoafLord** [BEEmod/BEE2-items#2122] opened 2017-08-01 22:53 UTC
A fizzler style item that requires use of the fizzler output in order to work. Basically, when a cube moves through the fizzler, it will activate the output. It does not fizzle the cube that goes through. This could make for some nice puzzles, plus I'm pretty sure this could be done, too.

Colour would be a triangle pattern. (Arrows that meet the other arrows on the other side in the middle.) Green when activated, red when not.

**Comment by TheLoafLord** [comment] 2017-08-02 00:33
Changed it so when activated triangles are green, when not triangles are red.

**Comment by Konclan** [comment] 2021-03-20 20:19
Extremely confusing descripting but its basically the RFR but for cubes, I don't see why this couldn't or shouldn't be added

**Comment by Luke18033** [comment] 2021-03-20 20:21
BEE2.2 had a Cube Sensor item which did this.

**Comment by Konclan** [comment] 2021-03-20 20:25
Then this is a duplicate of #95's Cube Sensor

**Closed by Konclan** 2021-03-20 20:25 UTC
Labels: New Item
