### ISSUE TITLE
Flip Panels will not flip if connected with a Trigger Once

### ISSUE THREAD

**Issue by MERNY** [BEEmod/BEE2-items#2849] opened 2018-10-28 11:52 UTC
I have a one time trigger connected to the flip panel, but the flip panel just stays the same tile once activated. lol help pls
Example: https://steamcommunity.com/sharedfiles/filedetails/?id=1549683684

**Comment by Luke18033** [comment] 2018-10-29 19:37
Does the Trigger Once work if it's connected to a different item? If not, this would be a duplicate of #2844.

**Comment by LautaroL20** [comment] 2018-10-29 20:38
The Trigger Once works pretty well with other items, the bug only affects if it is connected to the flip panel. That is why i keep up fervently with the idea that issue #2844 is something that obeys only to old resources from past releases not being overwritten by the Prl30. I have requested HugoBDesigner on that issue to provide with evidence (a screenshot) what i am affirming, but sadly, hasn't had the courage to do it because i think he don't want to look bad at the eyes of TeamSpen210 who re-open the issue even when i pointed out it's not a real bug.

If HugoBDesigner is reading at this, sorry from what i said above, but i really dislike when someone leaves me alone in something that i am 100% sure that is right.

**Comment by MERNY** [comment] 2018-10-29 23:39
Example: 
![screenshot 5](https://user-images.githubusercontent.com/44384404/47686562-d556ed80-dba9-11e8-829d-3a2cbfd15459.png)
Level: https://steamcommunity.com/sharedfiles/filedetails/?id=1549683684

**Comment by Konclan** [comment] 2018-10-30 00:40
What on earth are you talking about Lautaro. Why do assume Hugo is a coward or think that helping you would make TeamSpen displeased. Nothing you said makes sense at all.

**Comment by TeamSpen210** [comment] 2018-10-30 04:43
This is a duplicate of #2842, trigger once just never deactivates so it'll never flip.

**Closed by TeamSpen210** 2018-10-30 04:43 UTC
Labels: Bug

**Comment by LautaroL20** [comment] 2018-10-30 11:06
I will spend a bit of my time to reply Konclan's comment point by point, to clarify things.

> Konclan said: "What on earth are you talking about Lautaro. Nothing you said makes sense at all."

Well, i could not expect anything else of a person who hasn't been active in the repositorie's issues for months. So, what actually doesn't make sense is you appearing out of nowhere and trying to bring an opinion on something where you clearly seem to not have a slightest idea about of what i was pointing out. If i were you, i would inform myself very well before giving precipitate opinions that lacks all sustenance.

> Konclan said:  "Why do assume Hugo is a coward or think that helping you would make TeamSpen displeased."

I never called him "coward", so don't try putting me words i've never said. 
From my perspective, after having been observing his activity on Discord along with many other users there, i came to the conclusion that he's someone who really admires TeamSpen a lot, and therefore i doubt he would leave a small space where TS could feel a bit displaced, however i respect his posture although i like neutral people.

**Comment by Konclan** [comment] 2018-10-30 19:58
👌

**Comment by Konclan** [comment] 2018-10-30 20:14
This will be my last comment on this discussion.

I am missinformed apperently but the way you worded your message doesn’t look good. I’m on github reading all the time. I normally never reply because I have nothing to reply to. Also I have been out of portal for a bit so I couldn’t confirm nor deny any bugs because I haven’t experienced them myself

“I have requested HugoBDesigner on that issue to provide with evidence (a screenshot) what i am affirming, but sadly, hasn't had the courage to do”

The definition of coward is someone who lacks courage. You still made assumptions about people which isn’t something I agree with.

**Comment by Tebmn** [comment] 2020-08-04 17:21
This isn;t fixed. These flip panels are sill being pieces of crap in my PeTI

**Comment by Tebmn** [comment] 2020-08-04 17:22
Don't think this is fixed... I know it's been two years but my flip panels are 100% broken in my test editor and i'm curious if they work for anyone else.

**Comment by Luke18033** [comment] 2020-08-05 00:25
Flip panels are somewhat broken now I think, it's an unrelated issue though.
