### ISSUE TITLE
[All Styles] Laser items stop signage items from being generated if the signage is place on the same voxel as the laser item.

### ISSUE THREAD

**Issue by iEnderMan06** [BEEmod/BEE2-items#2066] opened 2017-06-15 15:55 UTC
http://i.imgur.com/zYudhBv.jpg
Puzzlemaker should generate them - however, it fails to do so.
http://i.imgur.com/qoI18LE.jpg

**Comment by Luke18033** [comment] 2017-06-16 01:48
Duplicate of #555.

**Closed by Luke18033** 2017-06-16 01:48 UTC
Labels: Bug

**Comment by iEnderMan06** [comment] 2017-06-16 19:39
@Luke18033 You changed his title when it was completely different - he had it working on the same voxel, but not the single dot signage, this post was about ALL signage items being stopped - although his post is rather confusing.

**Comment by TeamSpen210** [comment] 2017-06-16 21:37
It's a general problem, and actually requires some deep changes to fix.

**Comment by iEnderMan06** [comment] 2017-06-17 11:20
well ok  @TeamSpen210
