### ISSUE TITLE
cannot connect Sendificator to laser

### ISSUE THREAD

**Issue by FlukAHHHHHHHH** [BEEmod/BEE2-items#3790] opened 2021-05-20 03:29 UTC
I don't know why I cant connect Sendificator to laser I have tried in all style and still can't connect.
version that i use is 2.39.2

**Comment by LautaroL20** [comment] 2021-05-20 03:54
You are talking about that the Sendificator doesn´t have a connection option, or it is just that when you connect them it will result in a building error?

**Comment by FlukAHHHHHHHH** [comment] 2021-05-20 03:56
it doesn't  option to connect

**Comment by Konclan** [comment] 2021-05-20 04:25
duplicate of #3670

**Closed by Konclan** 2021-05-20 04:25 UTC
Labels: Bug
