### ISSUE TITLE
Portal 1 panel issues

### ISSUE THREAD

**Issue by TheSpacedOutEgg** [BEEmod/BEE2-items#2818] opened 2018-09-23 22:38 UTC
The panels for the P1 theme are somewhat broken, and I have notices two things after using them.

The sounds for the panels while changing their angle are corrupted, playing sounds like the portal gun shots, or sometimes even static.

The glass panel doesn't correctly deflect Energy Pellets on contact, like if the panel is 90 degrees, it will deflect the pellet 25 additional degrees in the air. NOTE: This only happens when it is hooked up to an output and is active when a pellet hits it.

I hope you can find the time to fix these bugs, and improve the mod to its finest. Thanks again!

**Comment by Luke18033** [comment] 2018-09-23 22:41
Duplicate of #1361 and #1113.

**Closed by Luke18033** 2018-09-23 22:41 UTC
