### ISSUE TITLE
Portal 1 turret droppers turrets are still using the portal 2 turret.

### ISSUE THREAD

**Issue by ZombiePwner1** [BEEmod/BEE2-items#1935] opened 2017-05-07 02:02 UTC
![20170507100052_1](https://cloud.githubusercontent.com/assets/18079316/25777311/38309d7c-330c-11e7-8231-1aa73af438cc.jpg)

**Comment by Luke18033** [comment] 2017-05-07 02:03
Duplicate of #1806.

**Closed by Luke18033** 2017-05-07 02:03 UTC
Labels: Bug, Portal 1
