### ISSUE TITLE
Multi-Cube Dropper: A dropper that can drop multiple cubes with one input

### ISSUE THREAD

**Issue by villager103** [BEEmod/BEE2-items#2575] opened 2018-03-18 21:37 UTC
These have been seen a few times in Portal 2, almost exclusively in Co-Op. There was one that dropped a bunch of edgeless safety cubes, and another in an overgrown map that dropped a variety of cubes.

These would save space in a few scenarios, namely puzzles that involve multiple reflector cubes, which would normally have to be placed individually(which is bad if there's a way to destroy them) or have many droppers, or puzzles where cubes must be flung through the air to press buttons or knock over turrets, allowing the player to send more cubes quicker.

The timer widget changes the number of cubes. It starts at 01, like the pedestal button does, so you can make it drop 2 cubes. Infinite allows the player to drop as many cubes as they like by pressing the button multiple times. Otherwise, giving an input will drop all the cubes at once. Pressing the button again will fizzle all the cubes at once. Destroying one of the cubes will make it come out the dropper again on it's own.

The reason for making this a separate item is because the timer is already used by cube droppers to sync pre-placed cubes to droppers. If possible, this could be worked around by having a "Start Reversed" option, or some other setting not normally on cube droppers that can change it to a multi-cube dropper.

By default, the dropper opens, then all the cubes come out, then it closes again. In the Old Aperture styles, the dropper has some sort of spraypainted decal on the sides that indicate that it drops multiple cubes. The Overgrown variant can sometimes drop rocks, chairs, radios or other junk.

**Comment by TeamSpen210** [comment] 2018-03-18 22:48
I don't really think it's a good idea to encourage lots of cubes. From what I've seen, generally more cubes is not better. I might want to resurrect the old Global Item Dropper, which replaces any dropperless cube placed in the map.

**Comment by TeamSpen210** [comment] 2018-03-18 22:48
Duplicate of #95

**Closed by TeamSpen210** 2018-03-18 22:48 UTC
Labels: Duplicate, Missing Instance, New Item
