### ISSUE TITLE
Portal 1 Style Publishing Glitch?

### ISSUE THREAD

**Issue by King0191** [BEEmod/BEE2-items#2571] opened 2018-03-18 00:51 UTC
So. I can test out the puzzle perfectly fine. But it just gives me an Error message when I try to Publish it.

CONSOLE RESPONSE:
VVIS failed.

Valve Software - vvis.exe (Mar  1 2018)
8 threads
reading c:\program files (x86)\steam\steamapps\common\portal 2\sdk_content\maps\1521327427.bsp
reading c:\program files (x86)\steam\steamapps\common\portal 2\sdk_content\maps\1521327427.prt
LoadPortals: couldn't read c:\program files (x86)\steam\steamapps\common\portal 2\sdk_content\maps\1521327427.prt

This is really annoying considering it STILL happens if I uninstall. Verify Files, and Reinstall

**Comment by Luke18033** [comment] 2018-03-18 03:17
Something is causing a leak. Do you have any items in weird positions? Cutout Tiles are also known to cause leaks, although you're probably not using those in P1.

**Comment by King0191** [comment] 2018-03-18 04:06
Ah... How would I fix that? Or do I have to remove it?

**Comment by ZombiePwner1** [comment] 2018-03-18 04:18
@King0191 If you know how to use hammer you could fix it however if you don't the only thing you can do is remove it from the chamber and wait till next release.

**Comment by King0191** [comment] 2018-03-18 04:25
Darn that's a shame, I guess I can save it for later. Because its a map dedicated to the Neurotoxin but I don't have ANY clue how to use Hammer.

**Comment by ZombiePwner1** [comment] 2018-03-18 05:33
@King0191 Oh well you'll have to wait till next release.

**Comment by LautaroL20** [comment] 2018-03-18 15:54
This is a duplicate of: https://github.com/BEEmod/BEE2.4/issues/867

**Closed by LautaroL20** 2018-03-18 15:54 UTC
Labels: Duplicate, Leak, Portal 1

**Comment by ZombiePwner1** [comment] 2018-04-29 00:03
@LautaroL20 LOL
