### ISSUE TITLE
Chamberlock causes "Failure To Compile" in Overgrown Style...

### ISSUE THREAD

**Issue by Chertov2018** [BEEmod/BEE2-items#3153] opened 2019-11-24 15:05 UTC
Could not open instance file `instances/BEE2/clean/items/tSpen/chamberlock_black.vmf`
Could not open instance file `instances/BEE2/clean/items/tSpen/chamberlock_white.vmf`
_____________________________________________________________________________________

Hello! I decided to make a test chamber in the overgrown style and took the Chamber Block (for me it is a door checkpoint) and the chamber does not work! Issues an error "There was an error building the puzzle", this problem is familiar to me, but did not know because of what it, I started deleting from the chamber subjects and reached ChamberLock and deleted it and the chamber worked. Before (ex. Release 4.35.1) it worked and now it doesn't.
Sorry for the crooked translation

**Comment by Luke18033** [comment] 2019-11-24 17:37
Post the console log, that generic error message is useless on its own.

**Comment by Chertov2018** [comment] 2019-11-24 18:17
> Post the console log, that generic error message is useless on its own.

And how to open the log? I was in all tabs and did not find the "log" button, the only way I have is to do something wrong and because of this, a fatal error will open and BEE2 will close, then starting again and already BEE2 starts with the log

**Comment by LautaroL20** [comment] 2019-11-24 18:37
In order to find the log, you have to enable the Portal 2´s console, start building your puzzle then as soon as you get the error, open the Portal 2´s console and paste the full log message, here.

**Comment by Chertov2018** [comment] 2019-11-24 18:41
time (after export): 108 (ms)

VBSP failed.

[I] vbsp.main(): BEE2 v4.36.0 VBSP hook initiallised.
[I] cond.core.import_conditions(): Imported all conditions modules!
[I] vbsp.main(): Map path is "D:/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf"
[I] vbsp.main(): New path: "D:/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[I] vbsp.main(): Clearing inject/ directory..
[I] vbsp.main(): PeTI map detected!
[I] vbsp.main(): Loading settings...
[I] cubes.parse_conf(): Parsed 7 cube types, 1 dropper types and 4 addons.
[W] fizzler.parse(): No base instance set! for "BEE2_PRO_LIFEFORM_SENSOR"!
[I] fizzler.read_configs(): Loaded 14 fizzlers.
[I] vbsp.load_settings(): Settings Loaded!
[I] vbsp.load_map(): Parsing Map...
[I] vbsp.load_map(): Reading Map...
[I] vbsp.load_map(): Loading complete!
[I] vbsp.get_map_info(): Forcing elevator spawn!
[I] vbsp.mod_entryexit(): Setting SP Entry to 2
[I] vbsp.mod_entryexit(): Setting SP Exit to 4
[I] vbsp.get_map_info(): Game Mode: SP
[I] vbsp.get_map_info(): Is Preview: False
[I] brushLoc.read_from_map(): Analysed map, filling air... (238 starting positions..)
[I] brushLoc.read_from_map(): Air filled!
[I] cond.core.check_all(): Checking Conditions...
[I] cubes.link_cubes(): SPLAT File: ['instances/bee2/logic/gel_splat.vmf']
[I] cond.catwalks.res_make_catwalk(): Starting catwalk generator...
[I] cond.monitor.mon_camera_link(): Bullseye defaultdict(<class 'int'>, {Vec_tuple(x=1088.0, y=1216.0, z=0.0): 1})
[I] connections.gen_item_outputs(): Generating item IO...
[I] connections.gen_item_outputs(): Item IO generated.
[I] cond.monitor.mon_remove_bullseyes(): Pos: Vec_tuple(x=1088.0, y=1216.0, z=0.0) -> 
[I] cond.monitor.mon_remove_bullseyes(): Pos: Vec_tuple(x=2496.0, y=1600.0, z=640.0) -> 
[I] cond.monitor.mon_remove_bullseyes(): Pos: Vec_tuple(x=1344.0, y=1472.0, z=640.0) -> 
[I] cond.core.res_goo_debris(): GooDebris: 23/48 locations
[W] template.retexture_template(): Realign face in template "bee_door_cowl_clean" (1426 in final) is not on grid!
[W] template.retexture_template(): Realign face in template "bee_door_cowl_clean" (1464 in final) is not on grid!
[W] template.retexture_template(): Realign face in template "bee_door_cowl_clean" (1579 in final) is not on grid!
[W] template.retexture_template(): Realign face in template "bee_door_cowl_clean" (1516 in final) is not on grid!
[W] template.retexture_template(): Realign face in template "bee_door_cowl_clean" (76 in final) is not on grid!
[W] template.retexture_template(): Realign face in template "bee_door_cowl_clean" (93 in final) is not on grid!
[W] template.retexture_template(): Realign face in template "bee_door_cowl_clean" (103 in final) is not on grid!
[W] template.retexture_template(): Realign face in template "bee_door_cowl_clean" (138 in final) is not on grid!
[W] template.retexture_template(): Realign face in template "bee_door_cowl_clean" (222 in final) is not on grid!
[W] template.retexture_template(): Realign face in template "bee_door_cowl_clean" (239 in final) is not on grid!
[W] template.retexture_template(): Realign face in template "bee_door_cowl_clean" (249 in final) is not on grid!
[W] template.retexture_template(): Realign face in template "bee_door_cowl_clean" (284 in final) is not on grid!
[W] template.retexture_template(): Realign face in template "bee_door_cowl_clean" (388 in final) is not on grid!
[W] template.retexture_template(): Realign face in template "bee_door_cowl_clean" (405 in final) is not on grid!
[W] template.retexture_template(): Realign face in template "bee_door_cowl_clean" (415 in final) is not on grid!
[W] template.retexture_template(): Realign face in template "bee_door_cowl_clean" (450 in final) is not on grid!
[W] template.retexture_template(): Realign face in template "bee_door_cowl_clean" (534 in final) is not on grid!
[W] template.retexture_template(): Realign face in template "bee_door_cowl_clean" (551 in final) is not on grid!
[W] template.retexture_template(): Realign face in template "bee_door_cowl_clean" (561 in final) is not on grid!
[W] template.retexture_template(): Realign face in template "bee_door_cowl_clean" (596 in final) is not on grid!
[W] template.retexture_template(): Realign face in template "bee_door_cowl_clean" (680 in final) is not on grid!
[W] template.retexture_template(): Realign face in template "bee_door_cowl_clean" (697 in final) is not on grid!
[W] template.retexture_template(): Realign face in template "bee_door_cowl_clean" (707 in final) is not on grid!
[W] template.retexture_template(): Realign face in template "bee_door_cowl_clean" (742 in final) is not on grid!
[W] barriers.test_hole_spot(): No center barrier at 1216 1600 704, 0 0 -1
[I] cond.scaffold.res_unst_scaffold(): Running Scaffold Generator (BEE2_SCAFFOLD)...
[I] cond.scaffold.res_unst_scaffold(): Finished Scaffold generation!
[I] cond.vactubes.res_make_vactubes(): Running Generator (BEE2_VACTUBES)...
[W] packing.pack_list(): Packlist "PACK_BEE2_OVER_CATAPULT_TOGGLE" does not exist!
[W] packing.pack_list(): Packlist "PACK_JOSE_WASTED_CATAPULT_WORLD" does not exist!
[W] packing.pack_list(): Packlist "PACK_BEE2_MODERN_DROPPER_WRECKED" does not exist!
[W] cond.core.resolve_value(): Invalid fixup ($color) in the "cd73" instance:
 | <Entity>: 
 | {
 | 	 classname = "func_instance"
 | 	 targetname = "cd73"
 | 	 file = "instances/BEE2/over/items/cube/dropper.vmf"
 | 	 origin = "64 1984 448"
 | 	 angles = "0 180 180"
 | 	 $connectioncount = "1"
 | 	 $item_fall_straight_down = "1"
 | 	 $disable_autodrop = "0"
 | 	 $disable_autorespawn = "0"
 | }
 | 
 | {'connectioncount': FixupTuple(var='connectioncount', value='1', id=1), 'item_fall_straight_down': FixupTuple(var='item_fall_straight_down', value='1', id=5), 'disable_autodrop': FixupTuple(var='disable_autodrop', value='0', id=4), 'disable_autorespawn': FixupTuple(var='disable_autorespawn', value='0', id=3)}
 |___

[W] cond.core.resolve_value(): Invalid fixup ($color) in the "cd71" instance:
 | <Entity>: 
 | {
 | 	 classname = "func_instance"
 | 	 targetname = "cd71"
 | 	 file = "instances/BEE2/over/items/cube/dropper.vmf"
 | 	 origin = "960 1984 320"
 | 	 angles = "0 180 180"
 | 	 $connectioncount = "0"
 | 	 $item_fall_straight_down = "1"
 | 	 $disable_autodrop = "0"
 | 	 $disable_autorespawn = "0"
 | }
 | 
 | {'connectioncount': FixupTuple(var='connectioncount', value='0', id=1), 'item_fall_straight_down': FixupTuple(var='item_fall_straight_down', value='1', id=5), 'disable_autodrop': FixupTuple(var='disable_autodrop', value='0', id=4), 'disable_autorespawn': FixupTuple(var='disable_autorespawn', value='0', id=3)}
 |___

[W] cond.core.resolve_value(): Invalid fixup ($color) in the "cd75" instance:
 | <Entity>: 
 | {
 | 	 classname = "func_instance"
 | 	 targetname = "cd75"
 | 	 file = "instances/BEE2/over/items/cube/dropper.vmf"
 | 	 origin = "704 1344 320"
 | 	 angles = "0 180 180"
 | 	 $connectioncount = "2"
 | 	 $item_fall_straight_down = "1"
 | 	 $disable_autodrop = "1"
 | 	 $disable_autorespawn = "0"
 | }
 | 
 | {'connectioncount': FixupTuple(var='connectioncount', value='2', id=1), 'item_fall_straight_down': FixupTuple(var='item_fall_straight_down', value='1', id=5), 'disable_autodrop': FixupTuple(var='disable_autodrop', value='1', id=4), 'disable_autorespawn': FixupTuple(var='disable_autorespawn', value='0', id=3)}
 |___

[W] cond.core.resolve_value(): Invalid fixup ($color) in the "cd10" instance:
 | <Entity>: 
 | {
 | 	 classname = "func_instance"
 | 	 targetname = "cd10"
 | 	 file = "instances/BEE2/over/items/cube/dropper.vmf"
 | 	 origin = "2624 1344 1088"
 | 	 angles = "0 180 180"
 | 	 $connectioncount = "0"
 | 	 $item_fall_straight_down = "1"
 | 	 $disable_autodrop = "0"
 | 	 $disable_autorespawn = "0"
 | }
 | 
 | {'connectioncount': FixupTuple(var='connectioncount', value='0', id=1), 'item_fall_straight_down': FixupTuple(var='item_fall_straight_down', value='1', id=5), 'disable_autodrop': FixupTuple(var='disable_autodrop', value='0', id=4), 'disable_autorespawn': FixupTuple(var='disable_autorespawn', value='0', id=3)}
 |___

[W] cond.core.resolve_value(): Invalid fixup ($color) in the "cd82" instance:
 | <Entity>: 
 | {
 | 	 classname = "func_instance"
 | 	 targetname = "cd82"
 | 	 file = "instances/BEE2/over/items/cube/dropper.vmf"
 | 	 origin = "832 832 320"
 | 	 angles = "0 180 180"
 | 	 $connectioncount = "0"
 | 	 $item_fall_straight_down = "1"
 | 	 $disable_autodrop = "0"
 | 	 $disable_autorespawn = "0"
 | }
 | 
 | {'connectioncount': FixupTuple(var='connectioncount', value='0', id=1), 'item_fall_straight_down': FixupTuple(var='item_fall_straight_down', value='1', id=5), 'disable_autodrop': FixupTuple(var='disable_autodrop', value='0', id=4), 'disable_autorespawn': FixupTuple(var='disable_autorespawn', value='0', id=3)}
 |___

[W] packing.pack_list(): Packlist "PACK_BEE2_TRIPLE_WALLPIPE_STRAIGHT_A" does not exist!
[W] packing.pack_list(): Packlist "PACK_BEE2_OVER_CATWALK_SP_ELEVATOR" does not exist!
[W] packing.pack_list(): Packlist "PACK_BEE2_RUSTY_TRUSS" does not exist!
[W] packing.pack_list(): Packlist "PACK_BEE2_TRIPLE_WALLPIPE_STRAIGHT_C" does not exist!
[W] packing.pack_list(): Packlist "PACK_BEE2_ELEVATOR_DIRTY" does not exist!
[W] packing.pack_list(): Packlist "PACK_BEE2_TRIPLE_WALLPIPE_STRAIGHT_D" does not exist!
[W] template.retexture_template(): Realign face in template "bee2_over_observation_ceiling_tiles_1" (6071 in final) is not on grid!
[W] packing.pack_list(): Packlist "PACK_BEE2_TRIPLE_WALLPIPE_STRAIGHT_D" does not exist!
[W] template.retexture_template(): Realign face in template "bee2_over_observation_ceiling_tiles_1" (6083 in final) is not on grid!
[W] packing.pack_list(): Packlist "PACK_BEE2_TRIPLE_WALLPIPE_STRAIGHT_D" does not exist!
[W] template.retexture_template(): Realign face in template "bee2_over_observation_ceiling_tiles_1" (6095 in final) is not on grid!
[W] packing.pack_list(): Packlist "PACK_BEE2_TRIPLE_WALLPIPE_STRAIGHT_D" does not exist!
[W] template.retexture_template(): Realign face in template "bee2_over_observation_ceiling_tiles_1" (6107 in final) is not on grid!
[W] packing.pack_list(): Packlist "PACK_BEE2_TRIPLE_WALLPIPE_STRAIGHT_D" does not exist!
[W] template.retexture_template(): Realign face in template "bee2_over_observation_ceiling_tiles_1" (6119 in final) is not on grid!
[I] brushes.res_import_template(): IDS: set()
[W] packing.pack_list(): Packlist "PACK_BEE2_TRIPLE_WALLPIPE_STRAIGHT_B" does not exist!
[W] packing.pack_list(): Packlist "PACK_BEE2_TRIPLE_WALLPIPE_STRAIGHT_c" does not exist!
[W] packing.pack_list(): Packlist "PACK_BEE2_TRIPLE_WALLPIPE_STRAIGHT_A" does not exist!
[I] vbsp.set_elev_videos(): Elevator type: RAND
[I] voiceLine.add_voice(): Adding Voice Lines!
[I] voiceLine.add_voice(): Quote events: []
[I] voiceLine.add_voice(): No responses data..
[I] voiceLine.add_voice(): 0 Mid quotes
[I] voiceLine.add_voice(): Done!
[W] packing.pack_list(): Packlist "PACK_TULEBY_ABS_FIZZ_CLEAN" does not exist!
[W] packing.pack_list(): Packlist "PACK_TULEBY_ABS_FIZZ_MDL_CLEAN" does not exist!
[W] packing.pack_list(): Packlist "PACK_TULEBY_ABS_FIZZ_CLEAN" does not exist!
[W] packing.pack_list(): Packlist "PACK_TULEBY_ABS_FIZZ_MDL_CLEAN" does not exist!
[W] packing.pack_list(): Packlist "PACK_TULEBY_ABS_FIZZ_CLEAN" does not exist!
[W] packing.pack_list(): Packlist "PACK_TULEBY_ABS_FIZZ_MDL_CLEAN" does not exist!
[I] vbsp.set_player_portalgun(): Setting Portalgun:
[I] vbsp.set_player_portalgun(): Blue: Y, Orange: Y
[I] vbsp.set_player_portalgun(): Done!
[I] cond.core.check_all(): Map has attributes: ['goo', 'fizzler', 'fr_csf', 'tuleby_abs_fizz', 'needsportalman', 'glass', 'grating', 'cube', 'cubestandard', 'cubedropper', 'cubedropperstandard', 'cubenotcompanion', 'cubesphere', 'cubedroppersphere', 'cubesphereshaped', 'monitor', 'funnel', 'excursionfunnel', 'weightedbutton', 'floorbutton', 'buttonacceptscube', 'buttonacceptsball', 'ballbutton', 'faith', 'catapult', 'faithplate', 'pedestalbutton', 'pistonplatform', 'piston', 'panel', 'portalgunonoff', 'portalgunonoffblue', 'portalgunonofforange', 'spawn_dual']
[I] cond.core.check_all(): instanceLocs cache: CacheInfo(hits=39161, misses=420, maxsize=256, currsize=256)
[I] cond.core.check_all(): Style Vars: {'bee2_goo_debris': True, 'overfunnelflicker': False, 'restartonexit': True, 'multiversecave': False, 'fixfizzlerbump': False, 'nomidvoices': False, 'unlockdefault': True, 'allowgoomist': True, 'funnelallowswitchedlights': True, 'enableshapesignageframe': True}
[I] cond.core.check_all(): Global instances: {'instances/BEE2/over/global_ents.vmf'}
[I] vbsp.add_extra_ents(): Adding Music...
[I] vbsp.add_extra_ents(): Adding global ents...
[I] vbsp.add_extra_ents(): Adding Global PTI Ents
[I] vbsp.change_ents(): Editing Other Entities...
[I] vbsp.fixup_goo_sides(): Changing goo sides...
[I] vbsp.fixup_goo_sides(): Done!
[I] vbsp.change_brush(): Editing Brushes...
[I] vbsp.change_brush(): Make Bottomless Pit: False
[I] vbsp.change_brush(): Goo heights: 608.0 <- Counter({608.0: 47, 96.0: 1})
[I] vbsp.change_brush(): Adding Goo Mist...
[I] vbsp.change_brush(): Done!
[I] vbsp.change_overlays(): Editing Overlays...
[I] vbsp.collapse_goo_trig(): Collapsing goo triggers...
[I] vbsp.collapse_goo_trig(): Done!
[I] vbsp.change_func_brush(): Editing Brush Entities...
[I] vbsp.fix_worldspawn(): Editing WorldSpawn
[I] vbsp.save(): Saving New Map...
[I] vbsp.save(): Complete!
[I] <Valve>.run_compiler(): Calling original VBSP...
[I] <Valve>.run_compiler(): Args: '-game', 'D:/Steam/steamapps/common/Portal 2/portal2/', 'D:/Steam/steamapps/common/Portal 2/sdk_content\\maps\\styled\\preview.vmf'
[I] <valve>.vbsp(): Valve Software - vbsp.exe (Oct 26 2018)
[I] <valve>.vbsp(): 8 threads
[I] <valve>.vbsp(): materialPath: D:\Steam\steamapps\common\Portal 2\portal2\materials
[I] <valve>.vbsp(): Loading D:/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf
[I] <valve>.vbsp(): ConVarRef gpu_level doesn't point to an existing ConVar
[I] <valve>.vbsp(): Could not open instance file instances/BEE2/clean/items/tSpen/chamberlock_black.vmf
[I] <valve>.vbsp():

**Comment by Chertov2018** [comment] 2019-11-24 18:45
I hope that all log was copied because at me it was very strange copied: I did not allocate "time (after export): 108 (ms)", and it was copied

**Comment by LautaroL20** [comment] 2019-11-24 18:46
At the end of your log, it says that the error has occur due to being on a black surface (Could not open instance file instances/BEE2/clean/items/tSpen/chamberlock_black.vmf).  I was wondering if you try moving the Chamberlock item to a white surface, would this error still persist?

**Comment by Chertov2018** [comment] 2019-11-24 18:51
> At the end of your log, it says that the error has occur due to being on a black surface (Could not open instance file instances/BEE2/clean/items/tSpen/chamberlock_black.vmf). I was wondering if you try moving the Chamberlock item to a white surface, would this error still persist?

Tried, all the same there is this error, but only already with white instanse (Could not open instance file instances/BEE2/clean/items/tSpen/chamberlock_white.vmf)

**Comment by LautaroL20** [comment] 2019-12-25 16:26
I think that the Chamberlook´s brush should probably be more of a template thing rather than being treated via instances.

**Comment by Luke18033** [comment] 2019-12-26 07:44
It probably does, but the instance isn't getting swapped to a version without the brush for whatever reason.

**Comment by Luke18033** [comment] 2020-01-17 02:26
Duplicate of #2962

**Closed by Luke18033** 2020-01-17 02:26 UTC
Labels: Compile Error, Overgrown
