### ISSUE TITLE
Old aperture 1980's coop spawn room still contains a mysterious texture overlap.

### ISSUE THREAD

**Issue by FrozenDragon0** [BEEmod/BEE2-items#3254] opened 2020-03-22 07:54 UTC
![image](https://user-images.githubusercontent.com/18079316/77244918-6faf4980-6c55-11ea-9e80-9ab70e5e7546.png)

**Comment by Konclan** [comment] 2021-08-13 11:57
Duplicate of #1671

**Closed by Konclan** 2021-08-13 11:57 UTC
Labels: Bug, Old Aperture, Co-Op
