### ISSUE TITLE
(Clean) (Missing Editor Model) Chamber-Lock door missing model in editor

### ISSUE THREAD

**Issue by iEnderMan06** [BEEmod/BEE2-items#1696] opened 2017-03-11 20:26 UTC
![Photographed here](https://cloud.githubusercontent.com/assets/26350889/23826664/fa1f073e-0698-11e7-8221-a861a4bb640f.jpg)

**Comment by Luke18033** [comment] 2017-03-11 20:28
Duplicate of literally the previous open issue, #1694.

**Closed by Luke18033** 2017-03-11 20:28 UTC
