### ISSUE TITLE
Auto Portals are still Bugged

### ISSUE THREAD

**Issue by RAOIMbutReal** [BEEmod/BEE2-items#3935] opened 2021-09-14 06:13 UTC
### BEE2 Application Version

4.40.0 64bit

### BEE2 Package Version

4.40.0

### What operating system are you running on?

Windows 10 (64bit)

### Description of the bug

Auto Portals in The Portal 1 Style Are still bugged and do not open some how?

### Expected behavior

Open's a Portal

### Steps to reproduce

1be in portal 1 style
2Place a auto Portal 
3make it open some how
4it just doesn't work

### Logs and Reports

```shell
AOIM unpaused the game
[PORTAL2 PUZZLEMAKER]  CVoxelTestChamber::Export VMF C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf ...
[PORTAL2 PUZZLEMAKER]  CVoxelTestChamber::Export VMF success, chamber size: (9,12,3)
[PORTAL2 PUZZLEMAKER]  Compilation time (after export): 41 (ms)
[PORTAL2 PUZZLEMAKER]  Compilation canceled
RAOIM unpaused the game
RAOIM unpaused the game
RAOIM unpaused the game
[PORTAL2 PUZZLEMAKER]  CVoxelTestChamber::Export VMF C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf ...
[PORTAL2 PUZZLEMAKER]  CVoxelTestChamber::Export VMF success, chamber size: (9,12,3)
[PORTAL2 PUZZLEMAKER]  Compilation time (after export): 51 (ms)
[PORTAL2 PUZZLEMAKER]  Compilation time (after VBSP): 8037 (ms)
[PORTAL2 PUZZLEMAKER]  Compilation time (after VVIS): 8243 (ms)
[PORTAL2 PUZZLEMAKER]  Compilation time (after VRAD): 27481 (ms)
[PORTAL2 PUZZLEMAKER]  Compilation time (complete): 27912 (ms) ...launching map!
Error: Operator stop_entry, unknown sound operator attribute input_start
SV_StartSound: player/fling_whoosh.wav not precached (0)
---- Host_Changelevel ----
exec: couldn't exec skill1.cfg
==== calling mapspawn.nut
Attempted to create unknown entity type playtest_manager!
Can't init playtest_manager
Couldn't find any entities named cd20-cube_addon_*, which point_template cd20-cube_maker is specifying.
Commentary: Could not find commentary data file 'maps/puzzlemaker/preview_commentary.txt'. 
Can't find factory for entity: wearable_item
NULL Ent in UTIL_PrecacheOther
[PORTAL2 PUZZLEMAKER]  --------START loading assets--------

[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_selection_over_pedestal_button_middle.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_selection_over_pedestal_button_middle.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_turret.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_turret.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_bts_opening.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_bts_opening.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_debris0.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_debris0.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_debris1.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_debris1.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_debris2.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_debris2.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_debris3.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_debris3.3ds
[PORTAL2 PUZZLEMAKER]  ---------END loading assets---------

=
```

### Additional information

I'm using the Portal 1 style

**Comment by Konclan** [comment] 2021-09-14 06:15
Duplicate of #3835

**Closed by Konclan** 2021-09-14 06:15 UTC
Labels: Bug
