### ISSUE TITLE
P1 Sphere cubes mysteriously become invisible after being fizzled in a fizzler.

### ISSUE THREAD

**Issue by ZombiePwner1** [BEEmod/BEE2-items#1382] opened 2017-01-11 07:20 UTC
![20170111151912_1](https://cloud.githubusercontent.com/assets/18079316/21839199/73898fce-d811-11e6-9b21-b633ed2a7b8a.jpg)

![20170111151917_1](https://cloud.githubusercontent.com/assets/18079316/21839194/688f820e-d811-11e6-8ebe-15cb00075ab0.jpg)

**Comment by Luke18033** [comment] 2017-01-11 20:03
Duplicate of #1368.

**Comment by ZombiePwner1** [comment] 2017-01-20 01:06
@Luke18033 This isn't a duplicate of #1368 the weighted cubes never turn invisible if you fizzle them in a fizzler while the sphere cubes do turn invisible if fizzled in a fizzler.

**Comment by TeamSpen210** [comment] 2017-01-20 03:25
It is a duplicate, it's caused by the same issue.

**Closed** 2017-01-20 03:25 UTC
Labels: Bug, Portal 1
