### ISSUE TITLE
Make all Overgrown Fizzlers use Checkered Wall even when they re placed on the ceiling

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#708] opened 2016-08-20 14:01 UTC
Currently, they re not using checkered walls on the prl21.5:

![20160820102502_1](https://cloud.githubusercontent.com/assets/12244376/17831538/d2a60738-66c1-11e6-95a5-b949b71f139c.jpg)

**Comment by Konclan** [comment] 2019-08-30 17:44
This is a duplicate of #518

**Closed by Konclan** 2019-08-30 17:44 UTC
Labels: Enhancement, Overgrown
