### ISSUE TITLE
Outside style?

### ISSUE THREAD

**Issue by PorTalZ101** [BEEmod/BEE2-items#2056] opened 2017-06-10 18:31 UTC
Maybe, add a style where you're outside Aperture like in no money for chambers

**Comment by Luke18033** [comment] 2017-06-10 18:37
Don't think this would work very well for PeTi either.

**Comment by Luke18033** [comment] 2017-06-10 18:38
Duplicate of #1329 anyway.

**Comment by Luke18033** [comment] 2017-06-10 18:38
Also, issue #2056!

**Closed by Luke18033** 2017-06-10 18:38 UTC
