### ISSUE TITLE
Prevent Pedestal Buttons to get re-pushed while the countdown is running.

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#2417] opened 2017-12-06 02:02 UTC

**Comment by Luke18033** [comment] 2017-12-06 03:34
Duplicate of #1217 (which was closed as invalid).

**Closed by Luke18033** 2017-12-06 03:34 UTC
Labels: Itemvar

**Comment by LautaroL20** [comment] 2017-12-06 07:47
Nice memory. It was about 1 year ago so i couldn´t remember.

**Comment by TeamSpen210** [comment] 2017-12-06 09:10
As I said in that issue, probably it's best to not have this - all it does is force players to wait around. Maybe there are some situations where it's needed, but I don't think those would really work that well anyway.
