### ISSUE TITLE
Overgrown Laserfield´s frames gets packed as "Mysterious Blue Errors" when its resized.

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#1887] opened 2017-04-25 15:29 UTC
![Image](https://cloud.githubusercontent.com/assets/12244376/25591468/08da4378-2e8b-11e7-8529-199d3b01165a.jpg)

**Comment by ZombiePwner1** [comment] 2017-04-25 22:54
HAHA LOL

**Comment by LautaroL20** [comment] 2017-05-01 19:28
![Image](https://cloud.githubusercontent.com/assets/12244376/25591483/1c505212-2e8b-11e7-9338-4860cc1ebbdc.jpg)

**Comment by LautaroL20** [comment] 2017-05-01 19:29
This issue now happens everytime its rezised:
![20170501161640_1](https://cloud.githubusercontent.com/assets/12244376/25591527/525b48bc-2e8b-11e7-950a-61246d67691c.jpg)

**Comment by LautaroL20** [comment] 2018-02-13 19:52
Now fixed. However, the laserfield model looks darker than normal, ill see if i can make it look not too dark.

**Comment by ZombiePwner1** [comment] 2018-02-19 07:11
This is actually sort of a duplicate of https://github.com/BEEmod/BEE2-items/issues/1855

**Comment by LautaroL20** [comment] 2018-02-19 15:46
No wheels, thats about another unfinished game, this is beemod running on Portal 2.

**Comment by ZombiePwner1** [comment] 2018-02-19 22:39
@LautaroL20 It's still on portal 2 wheels.

**Closed by ZombiePwner1** 2018-02-19 22:39 UTC
Labels: Bug, Duplicate, Fixed, Missing Resource, Overgrown
