### ISSUE TITLE
When Rocket Turret fires, the rockets will be invisible in a "Mysterious Way"

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#1909] opened 2017-05-03 19:42 UTC
Originallly posted by @TessilnTheMaskMaker:
(https://github.com/BEEmod/BEE2.4/issues/596)
___________________________________________________________________________________

"When Rocket Turrets fire the rockets will be invisible."

**Comment by Luke18033** [comment] 2019-12-28 23:21
Placed the instance in a Hammer map, this doesn't seem to be an issue anymore.

**Comment by Luke18033** [comment] 2020-06-15 19:16
Duplicate of #1238

**Closed by Luke18033** 2020-06-15 19:16 UTC
Labels: Bug
