### ISSUE TITLE
Old Aperture BTS

### ISSUE THREAD

**Issue by ThatOneRetro** [BEEmod/BEE2-items#3746] opened 2021-04-14 12:43 UTC
**Description of the item:**
Old Aperture BTS would probably be hard to pull off due to the scale of the facility when outside of the test chambers, however you could style it similar to the old offices like in "the pit" in portal stories Mel.
Most of the items would be either similar or taken from BTS or Old Aperture.

**Item options:**
As a transition I suppose, you could have the option to choose an Old Aperture non-elevator entrance or an elevator entrance as a tick box. Same would go for the exit. It could just be one tick box for both exit and entrance or two separate choices.

**Comment by FrozenDragon0** [comment] 2021-04-14 13:41
Duplicate of https://github.com/BEEmod/BEE2-items/issues/2744

**Closed by FrozenDragon0** 2021-04-14 13:41 UTC
Labels: Duplicate, New Style
