### ISSUE TITLE
Add curved surfaces.

### ISSUE THREAD

**Issue by ZombiePwner1** [BEEmod/BEE2-items#2232] opened 2017-09-21 13:01 UTC
![20170921204936_1](https://user-images.githubusercontent.com/18079316/30696945-f331f64c-9f0f-11e7-8e16-371591e6dbcf.jpg)

**Comment by LautaroL20** [comment] 2017-09-21 13:17
This is a duplicate of: https://github.com/BEEmod/BEE2-items/issues/1391

**Closed by LautaroL20** 2017-09-21 13:17 UTC
Labels: New item, Suggestion
