### ISSUE TITLE
"AND" logic and trigger bug

### ISSUE THREAD

**Issue by sent44** [BEEmod/BEE2-items#2159] opened 2017-08-23 18:44 UTC
Here proof:
http://plays.tv/video/599dcb2c6e1437e70d/-and-logic-and-trigger-bug
I don't know if someone report this before.

**Comment by Byzarru** [comment] 2017-08-24 02:46
Here's how you find out:
![image](https://user-images.githubusercontent.com/22107242/29646999-58b6ad62-884c-11e7-9826-fffa44e54683.png)
Duplicate of #1062.

**Comment by Byzarru** [comment] 2017-08-24 02:47
Handy reference picture:

**Closed** 2017-08-24 02:48 UTC
Labels: Bug, Duplicate
