### ISSUE TITLE
Error building level

### ISSUE THREAD

**Issue by TheGamesLiker** [BEEmod/BEE2-items#2637] opened 2018-04-13 23:10 UTC
Every time I place a delayer, and rebuild the puzzle, I just get the error "there was an error building the puzzle" here is what the console gave me

VBSP failed.

[INFO] vbsp.main(): BEE2.4.0pr29 VBSP hook initiallised.
[INFO] cond.core.import_conditions(): Imported all conditions modules!
[INFO] vbsp.main(): Map path is "J:/SteamLibrary/steamapps/common/Portal 2/sdk_content\maps/preview.vmf"
[INFO] vbsp.main(): New path: "J:/SteamLibrary/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[INFO] vbsp.main(): Clearing inject/ directory..
[INFO] vbsp.main(): PeTI map detected!
[INFO] vbsp.main(): Loading settings...
[WARNING] vbsp_options.load(): Extra config options: {'glass_scale': '0.15', 'voice_pack': 'BEE2_GLADOS_CLEAN'}
[WARNING] instanceLocs.get_subitems(): Invalid custom instance name - "piston_grate_low" for <item_rex_pellet_destroyer> (Valid: {'head': 'instances/bee2/clean/items/rex/pellet_dest/head.vmf', 'common': 'instances/bee2/clean/items/rex/pellet_dest/common.vmf', 'piston_bottom_0': 'instances/bee2/clean/items/rex/pellet_dest/pist_0.vmf', 'piston_bottom_1': 'instances/bee2/clean/items/rex/pellet_dest/pist_1.vmf', 'piston_bottom_2': 'instances/bee2/clean/items/rex/pellet_dest/pist_2.vmf', 'piston_bottom_3': 'instances/bee2/clean/items/rex/pellet_dest/pist_3.vmf', 'piston_static_0': 'instances/bee2/clean/items/rex/pellet_dest/static_0.vmf', 'piston_static_1': 'instances/bee2/clean/items/rex/pellet_dest/static_1.vmf', 'piston_static_2': 'instances/bee2/clean/items/rex/pellet_dest/static_2.vmf', 'piston_static_3': 'instances/bee2/clean/items/rex/pellet_dest/static_3.vmf', 'piston_static_4': 'instances/bee2/clean/items/rex/pellet_dest/static_4.vmf', 'piston_logic_0': 'instances/bee2/clean/items/rex/pellet_dest/logic_0.vmf', 'piston_logic_1': 'instances/bee2/clean/items/rex/pellet_dest/logic_1.vmf', 'piston_logic_2': 'instances/bee2/clean/items/rex/pellet_dest/logic_2.vmf', 'piston_logic_3': 'instances/bee2/clean/items/rex/pellet_dest/logic_3.vmf'})
[WARNING] instanceLocs.get_subitems(): Invalid custom instance name - "piston_grate_high" for <item_rex_pellet_destroyer> (Valid: {'head': 'instances/bee2/clean/items/rex/pellet_dest/head.vmf', 'common': 'instances/bee2/clean/items/rex/pellet_dest/common.vmf', 'piston_bottom_0': 'instances/bee2/clean/items/rex/pellet_dest/pist_0.vmf', 'piston_bottom_1': 'instances/bee2/clean/items/rex/pellet_dest/pist_1.vmf', 'piston_bottom_2': 'instances/bee2/clean/items/rex/pellet_dest/pist_2.vmf', 'piston_bottom_3': 'instances/bee2/clean/items/rex/pellet_dest/pist_3.vmf', 'piston_static_0': 'instances/bee2/clean/items/rex/pellet_dest/static_0.vmf', 'piston_static_1': 'instances/bee2/clean/items/rex/pellet_dest/static_1.vmf', 'piston_static_2': 'instances/bee2/clean/items/rex/pellet_dest/static_2.vmf', 'piston_static_3': 'instances/bee2/clean/items/rex/pellet_dest/static_3.vmf', 'piston_static_4': 'instances/bee2/clean/items/rex/pellet_dest/static_4.vmf', 'piston_logic_0': 'instances/bee2/clean/items/rex/pellet_dest/logic_0.vmf', 'piston_logic_1': 'instances/bee2/clean/items/rex/pellet_dest/logic_1.vmf', 'piston_logic_2': 'instances/bee2/clean/items/rex/pellet_dest/logic_2.vmf', 'piston_logic_3': 'instances/bee2/clean/items/rex/pellet_dest/logic_3.vmf'})
[INFO] cubes.parse_conf(): Parsed 7 cube types, 1 dropper types and 4 addons.
[WARNING] fizzler.parse(): No base instance set! for "BEE2_PRO_LIFEFORM_SENSOR"!
[INFO] fizzler.read_configs(): Loaded 14 fizzlers.
[INFO] vbsp.load_settings(): Settings Loaded!
[INFO] vbsp.load_map(): Parsing Map...
[INFO] vbsp.load_map(): Reading Map...
[INFO] vbsp.load_map(): Loading complete!
[INFO] vbsp.get_map_info(): Forcing elevator spawn!
[INFO] vbsp.mod_entryexit(): Setting SP Exit to 4
[INFO] vbsp.mod_entryexit(): Setting SP Entry to 5
[INFO] vbsp.get_map_info(): Game Mode: SP
[INFO] vbsp.get_map_info(): Is Preview: False
[INFO] brushLoc.read_from_map(): Analysed map, filling air... (71 starting positions..)
[INFO] brushLoc.read_from_map(): Air filled!
[INFO] cond.core.check_all(): Checking Conditions...
[INFO] cubes.link_cubes(): SPLAT File: ['instances/bee2/logic/gel_splat.vmf']
[INFO] cond.catwalks.res_make_catwalk(): Starting catwalk generator...
[INFO] cond.scaffold.res_unst_scaffold(): Running Scaffold Generator (BEE2_SCAFFOLD)...
[INFO] cond.scaffold.res_unst_scaffold(): Finished Scaffold generation!
[INFO] cond.vactubes.res_make_vactubes(): Running Generator (BEE2_VACTUBES)...
[INFO] cond.vactubes.res_make_vactubes(): Markers: dict_keys(['vac5', 'vac6', 'vac201266', 'vac206523'])
[INFO] cond.vactubes.res_make_vactubes(): Outputs: {'vac201266', 'it1577952'}
[INFO] cond.vactubes.res_make_vactubes(): Outputs: set()
[INFO] cond.vactubes.res_make_vactubes(): Outputs: {'it1577953', 'vac206523'}
[INFO] cond.vactubes.res_make_vactubes(): Outputs: {'it1577954', 'vac6'}
[INFO] vbsp.set_elev_videos(): Elevator type: FORCE
[INFO] voiceLine.add_voice(): Adding Voice Lines!
[INFO] voiceLine.add_voice(): Adding Base instance!
[INFO] voiceLine.add_voice(): Quote events: []
[INFO] voiceLine.add_voice(): No responses data..
[INFO] voiceLine.find_group_quotes(): "ENTRY": 4/15 quotes..
[INFO] voiceLine.add_quote(): Adding quote: "Line"
 | 	{
 | 	"ID" "TURRET_1"
 | 	"Choreo" "scenes/npc/glados/mp_coop_tbeam_end12.vcd"
 | 	}
 |_

[INFO] voiceLine.find_group_quotes(): "EXIT": 2/5 quotes..
[INFO] voiceLine.add_quote(): Adding quote: "Line_SP"
 | 	{
 | 	"ID" "DEADLY_1"
 | 	"Choreo" "scenes/npc/glados/mp_coop_wall_block03.vcd"
 | 	}
 |_

[INFO] voiceLine.find_group_quotes(): "MIDCHAMBER": 2/9 quotes..
[INFO] voiceLine.add_voice(): 1 Mid quotes
[INFO] voiceLine.add_quote(): Adding quote: "Line"
 | 	{
 | 	"Name" "Horrible Machine"
 | 	"Choreo_Name" "@voice_franken_pickup"
 | 	"OnlyOnce" "1"
 | 	"Choreo" "scenes/npc/glados/mp_subterfuge06.vcd"
 | 	}
 |_

[INFO] voiceLine.add_voice(): Done!
[INFO] cond.monitor.mon_camera_link(): Bullseye defaultdict(<class 'int'>, {})
[INFO] vbsp.set_player_portalgun(): Setting Portalgun:
[INFO] vbsp.set_player_portalgun(): Blue: Y, Orange: Y
[INFO] vbsp.set_player_portalgun(): Done!
[INFO] cond.core.check_all(): Map has attributes: ['fizzler', 'cube', 'cubestandard', 'cubedropperlessstandard', 'cubenotcompanion', 'cubedropper', 'cubedropperstandard', 'cubesphere', 'cubedroppersphere', 'cubesphereshaped', 'cubefranken', 'cubedropperfranken', 'weightedbutton', 'floorbutton', 'buttonacceptscube', 'buttonacceptsball', 'rocketturret', 'turret', 'deadly', 'spawn_dual']
[INFO] cond.core.check_all(): instanceLocs cache: CacheInfo(hits=19136, misses=367, maxsize=256, currsize=256)
[INFO] cond.core.check_all(): Style Vars: {'doorcameras': True, 'restartonexit': True, 'multiversecave': False, 'fixfizzlerbump': False, 'nomidvoices': False, 'unlockdefault': False, 'allowgoomist': True, 'funnelallowswitchedlights': True, 'enableshapesignageframe': True}
[INFO] cond.core.check_all(): Global instances: {'instances/bee2/clean/items/rocket_turret/logic.vmf', 'instances/BEE2/logic/goo_fade.vmf'}
[INFO] vbsp.add_extra_ents(): Adding Music...
[INFO] vbsp.add_extra_ents(): Adding global ents...
[INFO] vbsp.add_extra_ents(): Adding Global PTI Ents
[INFO] vbsp.change_ents(): Editing Other Entities...
[INFO] vbsp.fixup_goo_sides(): Changing goo sides...
[INFO] vbsp.fixup_goo_sides(): Done!
[INFO] vbsp.change_brush(): Editing Brushes...
[INFO] vbsp.change_brush(): Make Bottomless Pit: True
[INFO] vbsp.change_brush(): Goo heights: 0 <- Counter()
[INFO] vbsp.change_brush(): Creating Bottomless Pits...
[INFO] bottomlessPit.make_bottomless_pit(): Pit instances: {<CONN_TYPES.side: 1>: ['instances/BEE2/bts/sky/side_1.vmf', 'instances/BEE2/bts/sky/side_1.vmf', 'instances/BEE2/bts/sky/side_2.vmf', 'instances/BEE2/bts/sky/side_3.vmf', 'instances/BEE2/bts/sky/side_4.vmf'], <CONN_TYPES.corner: 3>: ['instances/BEE2/bts/sky/corner_1.vmf', 'instances/BEE2/bts/sky/corner_1.vmf', 'instances/BEE2/bts/sky/corner_2.vmf', 'instances/BEE2/bts/sky/corner_3.vmf'], <CONN_TYPES.straight: 2>: ['instances/BEE2/bts/sky/side_1.vmf', 'instances/BEE2/bts/sky/side_1.vmf', 'instances/BEE2/bts/sky/side_2.vmf', 'instances/BEE2/bts/sky/side_3.vmf', 'instances/BEE2/bts/sky/side_4.vmf'], <CONN_TYPES.triple: 4>: ['instances/BEE2/bts/sky/triple_1.vmf', 'instances/BEE2/bts/sky/triple_2.vmf'], <CONN_TYPES.all: 5>: ['instances/BEE2/bts/sky/pillar_1.vmf', 'instances/BEE2/bts/sky/pillar_2.vmf', 'instances/BEE2/bts/sky/pillar_2.vmf', 'instances/BEE2/bts/sky/pillar_3.vmf', 'instances/BEE2/bts/sky/pillar_3.vmf']}
[INFO] vbsp.change_brush(): Done!
[INFO] vbsp.clump_walls(): Clumping: 450 clumps (+ 0 special)
[INFO] vbsp.change_overlays(): Editing Overlays...
[INFO] vbsp.collapse_goo_trig(): Collapsing goo triggers...
[INFO] vbsp.collapse_goo_trig(): Done!
[INFO] vbsp.change_func_brush(): Editing Brush Entities...
[INFO] vbsp.remove_static_ind_toggles(): Removing static indicator toggles...
[INFO] vbsp.remove_static_ind_toggles(): Done!
[INFO] vbsp.fix_worldspawn(): Editing WorldSpawn
[INFO] vbsp.make_packlist(): Making Pack list...
[INFO] vbsp.make_packlist(): "materials/BEE2/fizz/fizz_side.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/fizz_sides/side_color_06141A.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/tile_noise.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/tile_noise_2x1.vtf"
[INFO] vbsp.make_packlist(): "materials/bee2/clean/black_1x1.vmt"
[INFO] vbsp.make_packlist(): "materials/bee2/clean/black_1x2.vmt"
[INFO] vbsp.make_packlist(): "materials/bee2/clean/black_ceil.vmt"
[INFO] vbsp.make_packlist(): "materials/models/props_bts/rocket_sentry.vmt"
[INFO] vbsp.make_packlist(): "materials/models/props_bts/rocket_sentry.vtf"
[INFO] vbsp.make_packlist(): "materials/models/props_bts/rocket_sentry_b.vmt"
[INFO] vbsp.make_packlist(): "materials/models/props_bts/rocket_sentry_b.vtf"
[INFO] vbsp.make_packlist(): "materials/models/props_bts/rocket_sentry_c.vmt"
[INFO] vbsp.make_packlist(): "materials/models/props_bts/rocket_sentry_c.vtf"
[INFO] vbsp.make_packlist(): "materials/models/props_bts/rocket_sentry_exponent.vtf"
[INFO] vbsp.make_packlist(): "materials/models/props_bts/rocket_sentry_inactive.vmt"
[INFO] vbsp.make_packlist(): "materials/models/props_bts/rocket_sentry_inactive.vtf"
[INFO] vbsp.make_packlist(): "materials/models/props_bts/rocket_sentry_normal.vtf"
[INFO] vbsp.make_packlist(): "models/BEE2/panels/static_norm_45.mdl"
[INFO] vbsp.make_packlist(): "models/BEE2/panels/static_phys.mdl"
[INFO] vbsp.make_packlist(): "models/props_bts/rocket_sentry.mdl"
[INFO] vbsp.make_packlist(): "models/props_bts/vactube_glass_bothsides/vactube_128_straight_glass.mdl"
[INFO] vbsp.make_packlist(): "models/props_bts/vactube_glass_bothsides/vactube_90deg_05_glass.mdl"
[INFO] vbsp.make_packlist(): "scripts/vscripts/BEE2/video_splitter_specific.nut"
[INFO] vbsp.make_packlist(): "scripts/vscripts/bee2/rocket_turret.nut"
[INFO] vbsp.make_packlist(): "sound/weapons/rocket/rocket_fire1.wav"
[INFO] vbsp.make_packlist(): "sound/weapons/rocket/rocket_fly_loop1.wav"
[INFO] vbsp.make_packlist(): "sound/weapons/rocket/rocket_locked_beep1.wav"
[INFO] vbsp.make_packlist(): Packlist written!
[INFO] vbsp.save(): Saving New Map...
[INFO] vbsp.save(): Complete!
[INFO] vbsp.run_vbsp(): Calling original VBSP...
[INFO] vbsp.run_vbsp(): Arguments: "J:\SteamLibrary\steamapps\common\Portal 2\bin\vbsp_original.exe" -game "J:/SteamLibrary/steamapps/common/Portal 2/portal2/" "J:/SteamLibrary/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[ERROR] <Valve>.run_vbsp(): Valve Software - vbsp.exe (Mar  1 2018)
 | 4 threads
 | materialPath: J:\SteamLibrary\steamapps\common\Portal 2\portal2\materials
 | Loading J:/SteamLibrary/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf
 | ConVarRef gpu_level doesn't point to an existing ConVar
 | Could not open instance file instances/BEE2/logic/bee/trigger_multiple.vmf
 | 
 |_

[ERROR] vbsp.run_vbsp(): VBSP failed! (1)

**Comment by TheGamesLiker** [comment] 2018-04-13 23:12
It seems it wasn't the delayer by itself, I tested without it and still got an error.

**Comment by Luke18033** [comment] 2018-04-13 23:16
Duplicate of #1550.

**Closed by Luke18033** 2018-04-13 23:16 UTC
