### ISSUE TITLE
Reclined fizzler goes missing when two of them are connected to the same fizzler

### ISSUE THREAD

**Issue by NeoKat75** [BEEmod/BEE2-items#3533] opened 2020-09-29 16:08 UTC
Reclined fizzler sometimes goes missing, seems to be random. A death laserfield is connected to this one. [Picture.](https://imgur.com/a/SoPEDuB)

**EDIT:** This happens when you connect the same laserfield to multiple reclined fizzlers.

**Comment by Thedoczek** [comment] 2020-10-18 18:57
Because one fizzler is one fizzler

Just create two laserfields and clost this ticket

**Comment by Luke18033** [comment] 2020-10-18 19:30
Duplicate of BEEmod/BEE2.4#1343

**Closed by Luke18033** 2020-10-18 19:30 UTC
Labels: Bug
