### ISSUE TITLE
dont mind this nothing

### ISSUE THREAD

**Issue by MarcusKubis9** [BEEmod/BEE2-items#3640] opened 2021-02-18 08:13 UTC
nothing

**Comment by seagemgames** [comment] 2021-02-18 08:14
Duplicate of #3638... (your own issue with the exact same text..?)

**Closed** 2021-02-18 08:26 UTC
Labels: New Item

**Comment by FrozenDragon0** [comment] 2021-02-18 08:59
Issues cannot be deleted unfortunately.

**Comment by Luke18033** [comment] 2021-02-18 17:01
They can, but only by admins.
