### ISSUE TITLE
BTS Entry Door Skybox Leak

### ISSUE THREAD

**Issue by ellingtonvengaboysmuseum** [BEEmod/BEE2-items#1449] opened 2017-01-22 21:04 UTC
BTS Entry Door Skybox Leak (with entry door 1)

![preview0074](https://cloud.githubusercontent.com/assets/11165643/22185949/7290575c-e0bc-11e6-8ec2-7335467bcff2.jpg)

**Comment by Luke18033** [comment] 2017-01-22 21:08
Duplicate of #1222. Make sure to search before opening issues.

**Closed by Luke18033** 2017-01-22 21:08 UTC

**Comment by TheDarkBomber** [comment] 2017-01-22 22:16
Still needs `Leak` label.
