### ISSUE TITLE
movable glass

### ISSUE THREAD

**Issue by MarcusKubis9** [BEEmod/BEE2-items#3638] opened 2021-02-15 00:30 UTC
this glass could be connected to anything that has an output and it acts like normals glass you can resize it change where is it hell even make it grating and then when your done fire up the level and if you put it on the floor I would move down into the floor same with roof and walls and also maybe it can move between 2 areas, of course, this would take up space under it depending on how big it is a and also maybe a setting that moves it between 2 areas? maybe?

**Comment by Konclan** [comment] 2021-08-15 13:05
Duplicate of #2671

**Closed by Konclan** 2021-08-15 13:05 UTC
Labels: New Item
