### ISSUE TITLE
"Weighted/Cube/Sphere" option for observation rooms. This lets you change the color of the light, including warm(orange) cool(white) and cold(blue)

### ISSUE THREAD

**Issue by villager103** [BEEmod/BEE2-items#2519] opened 2018-02-25 04:30 UTC
This would be great to go with the different colored light strips and square lights, with the added bonus of being able to light up an entire room with a single color of light without having to put light strips everywhere, or not use any observation rooms. The only issue I can see here would be ceiling observation rooms in the Overgrown style, but you could dim the light a little and just say it's dusk/nighttime. Perhaps a stylevar to change the lights in the entrances/exits to go with it?

**Comment by LautaroL20** [comment] 2018-02-25 05:39
This is a duplicate of: https://github.com/BEEmod/BEE2-items/issues/1701

**Closed by LautaroL20** 2018-02-25 05:39 UTC
Labels: Duplicate
