### ISSUE TITLE
Deadly Goo renders as a leak

### ISSUE THREAD

**Issue by Auratmos** [BEEmod/BEE2-items#4116] opened 2022-04-21 12:36 UTC
### BEE2 Application Version

4.41.0 64bit

### BEE2 Package Version

4.41.0

### What operating system are you running on?

Windows 10 (64bit)

### Description of the bug

OS: Windows 11 (64-bit)

---
In-game, deadly goo does not appear, and is replace with glowing visual tearing (or whatever it's called). I've seen this on a custom map on the Steam Workshop so I assume that BEE2 is interfering with original game files relating to goo.

### Expected behavior

*See description

### Steps to reproduce

Place deadly goo in a custom chamber. Build and preview.

### Additional information

Clean style and skybox.

**Comment by Areng14** [comment] 2022-04-21 13:45
btw @Auratmos you have a leak

**Comment by Auratmos** [comment] 2022-04-21 14:17
> btw @Auratmos you have a leak

What does that mean?

**Comment by Auratmos** [comment] 2022-04-21 14:17
> btw @Auratmos you have a leak

@Areng14
Meaning?

**Comment by LautaroL20** [comment] 2022-04-21 22:07
There's a [leak](https://developer.valvesoftware.com/wiki/Leak) in your map. Try removing any items from user created packages to see if they're the cause of the leak. If the issue persists, go to `Portal 2/sdk_content/maps/styled`, put `preview.vmf` and `preview.lin` in a ZIP, then upload that here.

**Comment by joethegamer100** [comment] 2022-04-21 22:43
or just remove items until it works 
(the superior option)

**Comment by LautaroL20** [comment] 2022-04-21 22:48
> joethegamer100 Said: "or just remove items until it works (the superior option)"

That will only allow compiling the puzzle temporarily but will not get the problem fixed so what you said is actually the inferior option.

**Comment by Areng14** [comment] 2022-04-21 22:59
Okay compile your map and open hammer then in hammer open the map that is in the styled folder called preview.vmf then go to map>load pointfile and follow the red line the red line should lead you to the leak what you have to do now is find the spot in puzzlemaker and fix it

**Comment by Luke18033** [comment] 2022-04-21 23:08
Also please tell us what's leaking, items in the puzzlemaker should never be able to cause leaks, if one can then it's a bug.

**Comment by LautaroL20** [comment] 2022-04-25 23:57
Closing because the issue's author doesn't respond.

**Closed by LautaroL20** 2022-04-25 23:57 UTC
Labels: Bug
