### ISSUE TITLE
Music not looping.

### ISSUE THREAD

**Issue by Master65** [BEEmod/BEE2-items#3215] opened 2020-02-04 20:54 UTC
I've read pretty much every thread about this, but it seems like nobody has an actual answer for this. I've got it worked out to where the music does get imported into the map correctly (via BMMC), but for some reason, it doesn't loop. Something else to note is that I thought it may be because I don't have the most up-to-date version of BMMC (I do have the latest version of BEE2), but if I try to update it, I just get a runtime error (for the time being, I'm stuck on 1.3.1). Another thing I've tried to do is to copy a music package already in BEE2, but that doesn't work out for me since it doesn't copy the info.txt that I'd have to have (due to an error). Perhaps there is something that needs to be added to info.txt, I'm not sure. If anyone has got any clue, please reply.

**Comment by Flash4433** [comment] 2020-02-04 21:05
Uh, I think this is more of an issue with BMMC. I've already sent Aerond, the creator of BMMC, this issue, as it seems I can't ping him here. Also, this looping problem was also reported in the BEE2 Discord Server. 

![image](https://user-images.githubusercontent.com/38331230/73786877-11580580-4792-11ea-8146-3ef96875f359.png)

**Comment by aerond7** [comment] 2020-02-04 21:38
Hello. Please describe to me how and when your error when updating BMMC happens. Also, go into the "bmmc" folder in Beemod's folder and send me a file called "application.log", as that will help me understand what's going wrong. :) 

-aerond, BMMC developer

**Comment by Master65** [comment] 2020-02-05 00:52
The error occurs if I click the "Update" button within the launcher.
https://cdn.discordapp.com/attachments/506828759555375114/674416513557463045/bmmcbreaking.jpg

I hope that the solution for fixing the looping music isn't going to take too long, since one of my levels I was going to make revolves around the music :/

**Comment by aerond7** [comment] 2020-02-05 13:03
Please message me on Discord in DMs so I can more easily help with this issue. You can find me in the BEEMod Discord server, I have the "contributor" role on there, so you'll easily find me.

**Comment by Flash4433** [comment] 2020-02-05 13:06
( aerond#0115 )

**Comment by Luke18033** [comment] 2020-04-26 01:28
Not caused by BEEmod, closing.

**Closed by Luke18033** 2020-04-26 01:28 UTC
Labels: Bug, Music
