### ISSUE TITLE
Funnel SFX bug Wheatley SFX playing with There She is sound track.

### ISSUE THREAD

**Issue by FrozenDragon0** [BEEmod/BEE2-items#1468] opened 2017-01-23 06:41 UTC
Why is one of wheatleys SFX playing inside a funnel with There She is sound track?

**Comment by Luke18033** [comment] 2020-07-09 04:27
Not sure what the issue is here? It's probably fixed now, or intentional.

**Closed by Luke18033** 2020-07-09 04:27 UTC
Labels: Bug, Clean, Overgrown
