### ISSUE TITLE
New 3D Skyboxes

### ISSUE THREAD

**Issue by Endermage77** [BEEmod/BEE2-items#2077] opened 2017-06-26 14:57 UTC
Currently, we have a small selection of 3D skyboxes (for a total of one 3D Factory). However, 3D factory may not be an ideal skybox for every chamber. Here, I shall propose a few more 3D skybox ideas.

So far, every single one of them would have a bottomless pit of some kind.

1. Old Aperture 3D Sphere Interior: Kind of goes without saying. This wouldn't really alter much about the existing  Old Aperture Styles, except that goo pits now drop into the enrichment sphere outside of the enclosed chamber. This would do the same for all styles, although some may look more ridiculous than others. You can mix 3D Factory with Old Aperture, after all.

2. 3D Chamber Exterior: Vaguely similar to 3D Factory except it reflects the more open spaces that chambers are more commonly suspended in rather than the cramped assembly line spaces, like the Co-Op hub area and some of the early sections of chapter 5.

3. Wheatley/Reconstructing Exterior: Exactly like it is in the campaign, in that it reflects the exterior of the chamber that has been quite damaged. Features heavily in chapter 8 of the campaign.

4. Portal 1 Glow: Same as the original portal 1: but now some goo pits are replaced with glow pits that look like the other glow holes scattered around chambers. Still just as deadly. Will likely need variants for the type of glow to use (eg. White glow used for Portalable chambers or Orange glow used for Non-Portalable chambers.)

5. Portal 1 Fire Pit: Exactly like the pit in Portal 1, as a Goo pit replacement.

6. 3D Overgrown Exterior: Looks more or less like the intro sequence in the campaign; Most of the space outside of the chamber is filled with broken machinery, plants, and off-kilter cryogen storage units. Top half will have light coming down, whilst the lower half will drop into the usual infinite darkness of Aperture.

7. Citadel Bowels: In the event that a HL2 Citadel style crops up, this would be a pit that drops past Combine machinery into the bowels of the Citadel.

8. Bottomless 80's exterior: The bottom of the sphere has dropped out, meaning that bottomless pits will actually drop you down to the shaft below.

**Comment by Luke18033** [comment] 2017-07-08 17:00
Or for 4 it could be a fire pit like the one at the end of chamber 19. Fire pits are actually used as a substitute for goo pits quite often in Portal Pro.

**Comment by Endermage77** [comment] 2017-07-08 20:38
That would also be good. List updated.

**Comment by Neightro** [comment] 2018-03-01 19:54
These are some great ideas! I really think BEE2 needs a 3D enrichment sphere skybox; the Old Aperture chambers don't quite feel right to me without one. Would it be difficult to implement, though? I've noticed that the chamber interiors and exteriors seem to be connected by world portals, so it might not look good.

**Comment by maxdevgithub** [comment] 2020-09-21 16:59
https://github.com/BEEmod/BEE2-items/issues/2646 P1 Pit kinda exists.

**Comment by Luke18033** [comment] 2021-02-10 19:25
Kind of a duplicate of #87

**Comment by Konclan** [comment] 2021-08-15 16:55
#3891

**Closed** 2021-08-15 16:56 UTC
Labels: Enhancement
