### ISSUE TITLE
[Bug] No env_cubemaps in portal 1 style coop.

### ISSUE THREAD

**Issue by ZombiePwner1** [BEEmod/BEE2-items#622] opened 2016-07-18 05:47 UTC
Theres no env_cubemaps in portal 1 style if making a coop map.

**Comment by LautaroL20** [comment] 2016-07-18 06:42
This is a duplicate of: https://github.com/TeamSpen210/BEE2-items/issues/284

**Comment by ZombiePwner1** [comment] 2016-07-18 07:02
Lautaro come online

**Closed** 2017-04-06 13:50 UTC
Labels: Bug, Portal 1
