### ISSUE TITLE
Sendificator Unable To Attach To Laser Emitter

### ISSUE THREAD

**Issue by gradeabeef** [BEEmod/BEE2-items#3812] opened 2021-06-03 05:58 UTC
Hi,
The sendificator is unable to attach to the laser emitter in the editor, making use of the sendificator impossible on the current version.
![sendificatorlaserissuereport](https://user-images.githubusercontent.com/85274463/120594541-eddcb380-c3f5-11eb-927f-5fab03f687a7.png)
Version: 1.39.1
Package: 1.39.1
-GAB

**Comment by FrozenDragon0** [comment] 2021-06-03 07:36
Duplicate of https://github.com/BEEmod/BEE2-items/issues/3670 

Please look through the github issues before posting your own to make sure that your not posting a duplicate.

**Closed by FrozenDragon0** 2021-06-03 07:36 UTC
Labels: Duplicate
