### ISSUE TITLE
Lifeform Sensor not activating.

### ISSUE THREAD

**Issue by XtraXD1** [BEEmod/BEE2-items#3631] opened 2021-02-07 22:34 UTC
When I pass through a Lifeform Sensor it beeps, but in the Console, the next error appears:

CSoundEmitterSystemBase::GetParametersForSound:  No such sound Error
VScript error: DoEntFire was passed an invalid entity instance.

I was using BEE2 4.38.1 when the bug ocurred.

**Comment by Luke18033** [comment] 2021-02-07 22:36
Duplicate of #3463

**Closed by Luke18033** 2021-02-07 22:36 UTC
Labels: Bug, Compile Error
