### ISSUE TITLE
Piston mounted trigger

### ISSUE THREAD

**Issue by ghost** [BEEmod/BEE2-items#526] opened 2016-05-02 15:38 UTC
The Piston Is Invisible, But The Trigger Counts, It Would Be Like If Its Floating Without Any Blocks, Used For Flinging And In Middle A Trigger Activates...

Idea By Me ( Pls No Steal )

**Comment by xDadiKx** [comment] 2016-05-02 15:40
??? It's almost the same as I posted #525

**Comment by TheReviewers** [comment] 2016-05-02 15:43
@xDadiKx I DIDNT SEE IT! 

Still you never asked for a piston

**Comment by TheReviewers** [comment] 2016-05-02 15:44
@xDadiKx Its my original idea then...

**Comment by BenVlodgi** [comment] 2016-05-02 16:14
This sort of thing has been asked before.
If this piston is invisible, what is the point of it being a piston?
invisible and nonsolid?

instead do you want a way to float a trigger like @xDadiKx  requested?

**Comment by Konclan** [comment] 2016-05-02 16:37
Well I don't think its supposed to be a piston, but rather acts like how you would place the piston plateform in PeTI so you can adjust the height of the trigger.

**Comment by TeamSpen210** [comment] 2016-05-02 19:30
What I might want to add is an 'invisible' light bridge instead. That also allows you to place things on it, but doesn't take up as much space and can be more easily removed.

**Comment by Konclan** [comment] 2019-08-29 04:26
Duplicate of #300

**Closed by Konclan** 2019-08-29 04:26 UTC
Labels: Enhancement, New Item
