### ISSUE TITLE
[Suggestion] Relaxation Vault

### ISSUE THREAD

**Issue by MrKrunk** [BEEmod/BEE2-items#398] opened 2016-03-16 01:03 UTC
I was wondering if it would be possible to include the relaxation vault as a spawn location. Why I'm saying spawn location is because it wouldn't make much sense to enter a chamber through other means if a vault is present.

**Comment by towergame** [comment] 2016-03-17 08:18
Yeah but what if it's a BTS section. It would be really nice if you could place a section with relaxation vaults.

**Comment by ZipZoptheCat** [comment] 2018-08-05 21:29
Relaxation Vault could be a setting where it's simply an entrance type. Downside is you can't really build around it.

BTS could be an employee break room?

**Comment by Konclan** [comment] 2019-08-29 02:42
Duplicate of #1245

**Closed by Konclan** 2019-08-29 02:42 UTC
Labels: Duplicate, Enhancement
