### ISSUE TITLE
End doors not opening co-op

### ISSUE THREAD

**Issue by Anus95** [BEEmod/BEE2-items#3191] opened 2020-01-10 08:26 UTC
I have made an overgrown, co-op chamber with the only custom objects being the, coop checkpoint, cold strip light, warm strip light, and the half panel. The issue is that when the final button that unlocks the doors is clicked and both players are in front of the door (the camera detects them and shows it should be opening) the doors are just closed. Thanks. (edit: checked with clean and it works so its only overgrown)

Here are the photos.

![PORTAL 2 10 01 2020 18_25_04](https://user-images.githubusercontent.com/59677445/72137509-a7d51900-33d6-11ea-964f-36debac2c2c4.png)

![PORTAL 2 10 01 2020 18_25_15](https://user-images.githubusercontent.com/59677445/72137521-ac013680-33d6-11ea-83bf-145eca184aa1.png)

![PORTAL 2 10 01 2020 18_25_35](https://user-images.githubusercontent.com/59677445/72137523-aefc2700-33d6-11ea-84dd-ad5e8e22ac0c.png)

**Comment by LautaroL20** [comment] 2020-01-10 12:04
Which item did you have connected to the exit door?

**Comment by Luke18033** [comment] 2020-01-10 17:19
Duplicate of #2989

**Closed by Luke18033** 2020-01-10 17:19 UTC
Labels: Bug, CO-OP, Overgrown

**Comment by Anus95** [comment] 2020-01-11 07:46
LautaroL20 deafult pedestal button placed on a wall on a wall
