### ISSUE TITLE
Overgrown players can get stuck on entry doors camera.

### ISSUE THREAD

**Issue by FrozenDragon0** [BEEmod/BEE2-items#1484] opened 2017-01-24 03:50 UTC
![20170124114940_1](https://cloud.githubusercontent.com/assets/18079316/22233463/4d93c0ea-e22b-11e6-827f-df5a3c521891.jpg)

**Comment by Luke18033** [comment] 2022-03-28 18:25
Duplicate of #1482

**Closed by Luke18033** 2022-03-28 18:25 UTC
Labels: Bug, Overgrown
