### ISSUE TITLE
Cube's go's through Grate's in the funnel beam

### ISSUE THREAD

**Issue by RAOIMbutReal** [BEEmod/BEE2-items#3995] opened 2021-11-15 01:20 UTC
### BEE2 Application Version

4.40.2

### BEE2 Package Version

4.40.0

### What operating system are you running on?

Windows 10 (64bit)

### Description of the bug

Cube's go's through Grate's in the funnel beam the player is fine its just the cube

### Expected behavior

Cube's dont go through Grate's in the funnel beam

### Steps to reproduce

place cube in the funnel w the grated panel w/ a contend portal

### Additional information

in clean

**Comment by TeamSpen210** [comment] 2021-11-15 01:46
Which kind of grate? Which style?

**Comment by Luke18033** [comment] 2021-11-15 02:03
Duplicate of #3264 most likely

**Closed by Luke18033** 2021-11-15 02:03 UTC
Labels: Bug
