### ISSUE TITLE
The New BTS Coop Spawn Room doesn´t work well

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#1869] opened 2017-04-19 17:19 UTC
Players can´t do anything since they becomes "Stagnant Forever" .
![Image](https://cloud.githubusercontent.com/assets/12244376/25192797/02664cc8-250b-11e7-9edb-80f279205ccd.jpg)

**Comment by ZombiePwner1** [comment] 2017-04-19 21:04
Duplicate of https://github.com/BEEmod/BEE2-items/issues/1405

**Comment by TeamSpen210** [comment] 2017-04-20 04:03
No, it's a new chamber. And I forgot to push a compiler change.

**Comment by LautaroL20** [comment] 2017-04-20 08:30
@ZombiePwner1 - Heh, before i checked my notifications i was pretty much sure someone would wrongly close this. This is about the new BTS Coop Spawn Room that Spencer added recently, you wheely!

**Comment by ZombiePwner1** [comment] 2017-04-20 10:11
@LautaroL20 Says the wheely.

**Comment by Luke18033** [comment] 2017-04-20 17:39
Please, stop calling each other "wheely". It's really starting to bug me.

**Comment by LautaroL20** [comment] 2017-04-20 18:19
> Luke18033: "It's really starting to bug me."

Ok, what is really starting to bug me are the tons of "Turrets Suggestions" that were maded here.

 It´s an item that doesn´t really provide any logical function into a Puzzle rather than annoying the player, and still people keeps posting things related to this. I don´t know why Valve included it into the puzzlemaker instead of others great elements that were cutted.

**Comment by Luke18033** [comment] 2017-04-20 18:22
The problem is that people misuse them. If you use turrets correctly they can actually make for a good puzzle element. I see so many maps where people surround the entry door in turrets and expect you to kill them.

**Comment by ZombiePwner1** [comment] 2017-04-20 23:38
@Luke18033 Only skilled players like me know how to use turrets properly since most people suck at using turrets.

**Comment by LautaroL20** [comment] 2017-04-21 00:58
> ZombiePwner1 said: "Only skilled players like me know how to use turrets properly"

Ok.

**Comment by ZombiePwner1** [comment] 2017-04-21 01:27
@LautaroL20 lol even though you hate turrets. Come on steam.

**Closed** 2017-06-05 08:13 UTC
Labels: BTS, bug, co-op, development version
