### ISSUE TITLE
chamber lock breaks deadly goo

### ISSUE THREAD

**Issue by appleanimations** [BEEmod/BEE2-items#3665] opened 2021-02-27 23:05 UTC
why does this happen?
![Screenshot (109)](https://user-images.githubusercontent.com/73008977/109402732-dd5ffd00-791d-11eb-91b8-de5298424aa7.png)

**Comment by Konclan** [comment] 2021-02-28 02:33
Duplicate of #3615

**Closed by Konclan** 2021-02-28 02:33 UTC
