### ISSUE TITLE
Allow Vac-tubes to turn ON/OFF

### ISSUE THREAD

**Issue by WhoozYerBuddy** [BEEmod/BEE2-items#2205] opened 2017-09-11 18:06 UTC
I don't know if it is possible but if you could turn vac tubes off/on, then it would open up a LOT more puzzle options with them, especially if players could enter them against their normal flow when off.

**Comment by Luke18033** [comment] 2017-09-11 18:27
Duplicate of #1597.

**Closed by Luke18033** 2017-09-11 18:27 UTC

**Comment by WhoozYerBuddy** [comment] 2017-09-11 18:35
Not quite a duplicate, but ok.
