### ISSUE TITLE
Far panels.

### ISSUE THREAD

**Issue by IceTudor** [BEEmod/BEE2-items#2298] opened 2017-10-21 08:12 UTC
Think of it as an angled panel, with the normal 30, 60 and 90, along with 120 and 180 but the actual panel is farther away by a half voxel from the actual wall its on.
Seems useful, considering how horrible panels are at catching objects, and how drawbridges don't have angled forms,

**Comment by Endermage77** [comment] 2017-10-21 16:42
So, it's a panel mounted on a half-block?
Noice.

**Comment by IceTudor** [comment] 2017-10-21 20:11
Nope, think of it as a drawbrige, with the first 2 tiles at the corner between the wall and panel are missing. That's what I mean.

**Comment by Endermage77** [comment] 2019-09-15 20:43
Ah, I think I understand: This item (if I get it right) is an angled panel that is 2 voxels long, except that the panel nearer to the base is missing.

**Comment by Konclan** [comment] 2019-09-15 22:53
Sounds basically like a piston mounted angled panel

**Comment by Konclan** [comment] 2021-08-14 21:41
This suggestion is too vague, I'm just gonna call this a duplicate of #593

**Closed** 2021-08-14 21:41 UTC
