### ISSUE TITLE
Large crusher

### ISSUE THREAD

**Issue by IceTudor** [BEEmod/BEE2-items#2382] opened 2017-11-04 08:59 UTC
A 4x4 crusher that extends 3 or 4 voxels. As seen in the panels trailer.

**Comment by TeamSpen210** [comment] 2017-11-04 10:33
This is the "Slow Crusher" in issue #95.

**Comment by TeamSpen210** [comment] 2017-11-04 10:33
Duplicate of #95

**Closed** 2017-11-04 10:33 UTC
Labels: Duplicate, New Item

**Comment by IceTudor** [comment] 2017-11-04 15:28
It's not slow, it's just as fast as the regular crusher.

**Comment by TeamSpen210** [comment] 2017-11-04 23:47
There's only actually one size of crusher in the game.

**Comment by IceTudor** [comment] 2017-11-10 12:15
Really?
