### ISSUE TITLE
Signatures disappear near various items

### ISSUE THREAD

**Issue by Cellolide** [BEEmod/BEE2-items#2527] opened 2018-02-28 15:19 UTC
If you place a signature on the same tile, for example a laser receiver or a visible AND/OR/XOR Gate is on, the signature will not be visible ingame. This might also happen with some other items like the square light.
![20180228161737_1](https://user-images.githubusercontent.com/33907318/36795354-1fa63db2-1ca3-11e8-9c81-03980fe10fc7.jpg)
![20180228161838_1](https://user-images.githubusercontent.com/33907318/36795355-1fcbe8d2-1ca3-11e8-8793-bc306c790821.jpg)

**Comment by Luke18033** [comment] 2018-02-28 15:24
Already known, duplicate of #555.

**Closed by Luke18033** 2018-02-28 15:24 UTC
