### ISSUE TITLE
Partial Blocks no longer transfer Antlines and Signage

### ISSUE THREAD

**Issue by jalapeno-github** [BEEmod/BEE2-items#3867] opened 2021-08-04 23:20 UTC
**BEE2 version:** 2.4.40.2

**Description of the bug:**
Partial Blocks (1/4, 1/2, 3/4 Bolcks) do not transfer any antlines or signage to their front face, regardless of whether or not "Start Enabled" is turned on.

![620_20210804235646_1](https://user-images.githubusercontent.com/47536167/128266511-346a08a9-2815-4cd3-8492-5efb0579385a.png)

**Expected behavior:**
By checking "Start Enabled" the partial block should transfer any antlines or signage underneath to the front of the block, as described in the items description.

![app](https://user-images.githubusercontent.com/47536167/128266693-30c24ace-823f-4f7c-9c6d-fd7f19bb24f8.png)

**Steps to reproduce:**
Create a chamber with some antlines, add partial block (1/4, 1/2, 3/4 block)

![620_20210804235602_1](https://user-images.githubusercontent.com/47536167/128267879-1992e83e-65fd-44e2-bf02-7824e572903c.png)

Edit: Changed the editor screenshot to a different one without the context menu blocking the way
Edit 2: Wrong screenshot. Should reaaaally use that preview feature

**Comment by LautaroL20** [comment] 2021-11-19 08:45
This is a duplicate of: https://github.com/BEEmod/BEE2-items/issues/3051

**Closed by LautaroL20** 2021-11-19 08:45 UTC
Labels: Bug, Duplicate
