### ISSUE TITLE
Surface Marker doesn't work

### ISSUE THREAD

**Issue by Krypt0nC0R3** [BEEmod/BEE2-items#3673] opened 2021-03-01 08:36 UTC
**BEE2 version:** 4.39.2

**Description of the bug:** Surface Marker does not mark surfaces

**Expected behavior:** Surface Marker marks surfaces

**Steps to reproduce:** Place Surface Marker on map and run game

**Additional information:**

Editor view:
![image](https://user-images.githubusercontent.com/46594859/109471726-c0553680-7aa3-11eb-885d-4bb5517b0cb3.png)

Ingame view:
![image](https://user-images.githubusercontent.com/46594859/109471784-d3680680-7aa3-11eb-8cd5-e7466041083b.png)

**Comment by FrozenDragon0** [comment] 2021-03-01 08:49
Duplicate of: https://github.com/BEEmod/BEE2-items/issues/3476

**Closed by FrozenDragon0** 2021-03-01 08:49 UTC
Labels: Bug, Duplicate
