### ISSUE TITLE
P1 Reclined Fizzler is still using the ButtonType property

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#3438] opened 2020-08-04 11:32 UTC
![Image](https://user-images.githubusercontent.com/12244376/89288721-7c44a500-d62c-11ea-9fb5-cd73839744c9.jpg)

**Comment by Luke18033** [comment] 2020-08-04 21:36
Duplicate of #3391

**Closed by Luke18033** 2020-08-04 21:36 UTC
Labels: Bug, Portal 1
