### ISSUE TITLE
HEP Goes Through Angled Panels On The P1 Style

### ISSUE THREAD

**Issue by CardsAndGamesYT** [BEEmod/BEE2-items#3876] opened 2021-08-11 18:23 UTC
BEE2 version: 4.20.2

Description of the bug: The HEP does not act/collide with the Angled Panel correctly in the P1 style.

Expected behavior: HEP bounce off 90* panel and go back to where it came from.

Steps to reproduce: HEP hits 90* panel strait on.

Additional information: The HEP also does not work correctly with other degrees on the panel.

https://user-images.githubusercontent.com/74144694/129082664-8e461420-2a3b-4c3c-b886-d27e346480ca.mp4

**Comment by CardsAndGamesYT** [comment] 2021-08-16 03:38
i know this is a bit odd, but it also collides differently depending on the texture idk. just found this out

**Comment by Luke18033** [comment] 2021-08-16 03:50
Duplicate of #1113

**Closed by Luke18033** 2021-08-16 03:50 UTC
Labels: Bug, Portal 1
