### ISSUE TITLE
BEE2mod Compiler ERROR 

### ISSUE THREAD

**Issue by richter24** [BEEmod/BEE2-items#2839] opened 2018-10-14 01:53 UTC
This appears in the console when I compiled the map:

VBSP failed.
Traceback (most recent call last):
File "C:\Users\Spencer Brown.virtualenvs\BEE2\lib\site-packages\cx_Freeze\initscripts_startup_.py", line 12, in 
File "C:\Users\Spencer Brown.virtualenvs\BEE2\lib\site-packages\cx_Freeze\initscripts\Console.py", line 20, in 
zipimport.ZipImportError: not a Zip file

please help!!

**Comment by LautaroL20** [comment] 2018-10-14 13:15
This is a duplicate of: https://github.com/BEEmod/BEE2.4/issues/1005

**Closed by LautaroL20** 2018-10-14 13:15 UTC
Labels: Application Issue, Compile Error, Duplicate

**Comment by richter24** [comment] 2018-10-14 13:29
So How can I fix it?

**Comment by LautaroL20** [comment] 2018-10-14 14:16
Ask Spencer.
