### ISSUE TITLE
Portal 1 GLaDOS on monitor.

### ISSUE THREAD

**Issue by KaziPlays** [BEEmod/BEE2-items#3733] opened 2021-04-04 13:57 UTC
Self explanatory.

Description:

When Portal 1 GLaDOS voicelines selected, add her on the monitor screen.

I think this is already planned but I wanted to confirm.

**Comment by KaziPlays** [comment] 2021-04-04 14:08
If this is planned but not done yet, I'll contribute by making it myself, then sharing it on here

**Comment by FrozenDragon0** [comment] 2021-04-04 15:34
This would be a duplicate of https://github.com/BEEmod/BEE2-items/issues/2021

**Closed by FrozenDragon0** 2021-04-04 15:34 UTC
Labels: Duplicate, Enhancement

**Comment by KaziPlays** [comment] 2023-12-19 00:26
Actually this is mot a duplicate, this one only makes p1 glados appear if the P1 glados lines are selected.
