### ISSUE TITLE
Cube-only buttons often turning into no-draw and missing the actual button model in overgrown style

### ISSUE THREAD

**Issue by TPEcool** [BEEmod/BEE2-items#3903] opened 2021-08-30 08:44 UTC
**BEE2 version: 4.40.2**

**Description of the bug:If I place a cube-only button in the overgrown style, only the platform for the button is visible. The spot where the button itself should be is a no-draw.**

**Expected behavior: The button should appear normally.**

**Steps to reproduce: 1. Make a palette with any settings and set the style to "Overgrown". 2. Make a new chamber. 3. Place a cube-only button. 4. Compile the chamber. 5. You will (probably) see a no-draw.**

**Additional information: Here are a few screenshots:
![20210829124007_2](https://user-images.githubusercontent.com/75689188/131312228-5fbdbede-e8d8-4f63-8f40-bdce08240cb0.jpg)

![20210829124008_1](https://user-images.githubusercontent.com/75689188/131312271-05f6f283-fdce-44c4-85d5-08ab320833bf.jpg)

![20210829124008_2](https://user-images.githubusercontent.com/75689188/131312317-2e84d915-cb6b-4ed6-ad00-5df77920df3f.jpg)**

**Comment by Konclan** [comment] 2021-08-30 08:51
Duplicate of #3645

**Closed by Konclan** 2021-08-30 08:51 UTC
Labels: Bug
