### ISSUE TITLE
1980's chamberlock is broken

### ISSUE THREAD

**Issue by HalfLife3IsNotHappening** [BEEmod/BEE2-items#4052] opened 2022-01-09 18:26 UTC
### BEE2 Application Version

4.41.0

### BEE2 Package Version

4.41.0

### What operating system are you running on?

Windows 10 (64bit)

### Description of the bug

The wall clips into the chamberlock, blocking your path.
![Captura de pantalla (34)](https://user-images.githubusercontent.com/97404792/148695287-deab5c98-c17e-4d3b-af02-81b0c1f0e742.png)

### Expected behavior

The chamberlock does not block you.

### Steps to reproduce

1. Add a chamberlock to the chamber  (start enabled or by input)
2. Compile

**Comment by FrozenDragon0** [comment] 2022-01-10 06:55
Duplicate of https://github.com/BEEmod/BEE2-items/issues/3712

**Comment by Luke18033** [comment] 2022-01-10 07:26
Not a duplicate, that issue is about 70s style which does this differently and works correctly.

**Closed** 2022-10-18 03:37 UTC
Labels: Bug, Old Aperture, Done
