### ISSUE TITLE
NoDraw in button side.

### ISSUE THREAD

**Issue by Komos63** [BEEmod/BEE2-items#4306] opened 2023-04-03 19:21 UTC
### BEE2 Application Version

4.43.0 64bit

### BEE2 Package Version

4.43.0

### What operating system are you running on?

Windows 10 (64bit)

### Description of the bug

![steamuserimages-a akamaihd](https://user-images.githubusercontent.com/78902172/229606286-db2f668b-82c2-4ffa-9f16-a61276054f49.jpg)

### Expected behavior

I expected no hole to the void

### Steps to reproduce

Place a button, thats it.

### Logs and Reports

```shell
None
```

### Additional information

Using clean style, have not tested others nor have I tested different buttons.

**Comment by LautaroL20** [comment] 2023-11-14 18:45
This is a duplicate of: https://github.com/BEEmod/BEE2-items/issues/4025

**Closed by LautaroL20** 2023-11-14 18:45 UTC
Labels: Bug, Done in next release
