### ISSUE TITLE
1980's Old Aperture Conveyor belt doesn't work.

### ISSUE THREAD

**Issue by wowemain** [BEEmod/BEE2-items#4041] opened 2021-12-27 06:35 UTC
### BEE2 Application Version

4.41.0

### BEE2 Package Version

4.41.0

### What operating system are you running on?

Windows 10 (64bit)

### Logs and Reports

```shell
None
```

### Additional information

I'm using 1980's Old Aperture style. When I use clean, the conveyor belt works just fine, but when I change it to another style, it just don't work. I tried to activate it, to activate it manually, re-export once more, but it didn't help.

**Comment by FrozenDragon0** [comment] 2021-12-27 07:48
What other styles does this affect? Is it just Clean that has a working conveyor belt?

**Comment by wowemain** [comment] 2021-12-27 07:54
I think yes, all Old Aperture don't have working conveyor belt

**Comment by Konclan** [comment] 2022-08-19 19:47
Duplicate of #3977

**Closed** 2022-08-19 19:47 UTC
Labels: Bug, Old Aperture, Compile Error
