### ISSUE TITLE
Cube droppers on wall

### ISSUE THREAD

**Issue by SCIENTIST2004** [BEEmod/BEE2-items#2751] opened 2018-07-16 18:51 UTC
Please make possible to se cube dropper on the wall Like gel dropper.
![exp](https://user-images.githubusercontent.com/35931028/42777352-6f78a954-8942-11e8-8d89-5704ab0f9a3e.png)

**Comment by Luke18033** [comment] 2018-07-16 19:01
Duplicate of #1276

**Closed by Luke18033** 2018-07-16 19:01 UTC
