### ISSUE TITLE
Radiative Flux Rectangle is missing it's sound.

### ISSUE THREAD

**Issue by ZombiePwner1** [BEEmod/BEE2-items#2063] opened 2017-06-12 12:30 UTC
field_activate
CSoundEmitterSystemBase::GetParametersForSound:  No such sound BEE2.p1.rex_field_activate
S

**Comment by Luke18033** [comment] 2017-06-12 13:51
Duplicate of #1615.

**Closed by Luke18033** 2017-06-12 13:51 UTC
Labels: Bug, Missing sound, Portal 1
