### ISSUE TITLE
New idea for items: Combine several items in one.

### ISSUE THREAD

**Issue by revaru** [BEEmod/BEE2-items#2786] opened 2018-08-04 11:33 UTC
You already did this. For example here is,

> ![image](https://user-images.githubusercontent.com/41899094/43676018-7d13ca20-9802-11e8-9b2a-ace4e502f165.png)

But don't all items are combined.
And this my ideas for combine items,
**Antline Router** (two in one) - using _"type of barrier: glass or grid"_
**FourthReaper's custom fizzlers + Physics Repulsion Field + Closed Solid Field** 
(five in one) - using _"type of cube"_
**Coop Checkpoints** (two in one) - using _"type of barrier: glass or grid"_
**Light Strips (Warm, Cold, Standart)** - using _"type of button"_

**Comment by ZombiePwner1** [comment] 2018-08-04 12:30
@revaru Problem with the light strips is if they have that option antlines will no longer ignore the model and will get placed on them if there is a connection between the light strip.

**Comment by Endermage77** [comment] 2018-08-04 19:15
We can't merge the fizzlers either because they need to be Fizzler type to function correctly.

**Comment by ZipZoptheCat** [comment] 2018-08-04 20:30
Angled Items such as the angled hard light bridge could either be merged this way or possibly they could automatically become angled when placed inside of an angled decorative element.

Turret droppers and base turret should be merged. After all the laser cube can be pointed to face a certain direction just like the turret can.

Pedastal buttons could do with some merging. I'm not sure how exactly, tho.

Is there any reason the triple and single faith plates can't be merged?

Half Grate and Static Half Panel can probably be merged. Possibly with a glass varient?

Is it possible to merge things like Lasers and HEPs? Pretty much any map that needs an emmiter need a catcher.

What about the three varients of unstationary scaffold emmiters?

Can angled panels (and perhaps drawbridges) be merged with their glass varients?

@ZombiePwner1 Could the antline router simply be incorporated into the light element for the same effect? There's a strip shaped one already.

@Endermage77 Twos maybe? Switch between fizzler and laser grid

Also is it possible to disable a built in option that has no function. Such as the gel type selection on the reflection gel?

**Comment by HugoBDesigner** [comment] 2018-08-04 20:32
@ZipZoptheCat Most of your suggestions wouldn't work because angled items already use the property required to merge multiple items

**Comment by Luke18033** [comment] 2018-08-04 20:38
Most items that are able to be combined have already been. The only exceptions I think are light strips (which can use Cube Type, if we can figure out what the fourth and fifth variants would be) and custom fizzlers (which are now able to have two variants using Hazard Type, but don't). The main reason items can't be combined is because properties and collisions are the same across all variants, so we can't combine items where those are different.

**Comment by ZipZoptheCat** [comment] 2018-08-04 20:44
dunno about a fifth light but I miss the purple light from b2. Perhaps White, Orange, Blue, Purple and Green. Those seem like the colours most mapper would want. Or perhaps Red.

So like for the faith plate the reason is the different size hitbox?

What about the turret dropped? Can you tell the game a turret dropper is a laser cube and just have dropper enabled turned off by default?

What about the static half panel? The game has built in variants between glass and grating, right?

**Comment by TeamSpen210** [comment] 2018-08-04 21:25
The ability to merge things is extremely limited.

**Comment by ZipZoptheCat** [comment] 2018-08-05 20:47
Wait a second, why is the square light already button sellectable? Does it not cause the same ant-line routing problem?

**Comment by TeamSpen210** [comment] 2018-08-05 21:09
No: because the problem is only present when it's able to shift around insidenthe block. Square lights only rotate (which doesn't change the collision shape). Note that the default laser items actually are each two items internally - one centered, and one offset to the side.

**Comment by ZipZoptheCat** [comment] 2018-08-05 21:19
Are the four centered settings of a laser effectively identical? I've never noticed a difference between those inner four on the eight selector.

**Comment by ZipZoptheCat** [comment] 2018-08-05 21:46
oh, cool. Thanks for the information.

**Comment by CreepiX987** [comment] 2018-08-06 16:50
@TeamSpen210 you could make the other two light strip variants customizable, just like the cube colorizer.

**Comment by King0191** [comment] 2018-08-06 16:52
If we're getting Light Strips of multiple colors. Would we be able to get Square Lights of multiple colors as well?

**Comment by Luke18033** [comment] 2019-03-10 02:12
Light strips have now been combined and most of the other stuff suggested here isn't possible.

**Closed by Luke18033** 2019-03-10 02:12 UTC
Labels: Suggestion
