### ISSUE TITLE
BTS coop spawns are very broken.

### ISSUE THREAD

**Issue by ZombiePwner1** [BEEmod/BEE2-items#1541] opened 2017-02-05 09:32 UTC
![20170205172839_1](https://cloud.githubusercontent.com/assets/18079316/22625147/0c25beea-ebc9-11e6-96ba-905d57fe8e46.jpg)

The spawns don't work correctly anymore and you get stuck in a black box the only way to get out is to use noclip.

**Comment by Luke18033** [comment] 2017-02-05 15:29
Duplicate of #1405.

**Closed by Luke18033** 2017-02-05 15:29 UTC
Labels: BTS, Bug, CO-OP
