### ISSUE TITLE
Original clean coop exit door does not open when there is a button connected to it.

### ISSUE THREAD

**Issue by ZombiePwner1** [BEEmod/BEE2-items#1743] opened 2017-03-15 10:32 UTC
![20170315183144_1](https://cloud.githubusercontent.com/assets/18079316/23944424/cb24fc28-09ad-11e7-81ff-005afa0a65da.jpg)

**Comment by LautaroL20** [comment] 2017-03-15 10:37
Lol, this is a super trite duplicate of: https://github.com/BEEmod/BEE2-items/issues/1392

**Closed by LautaroL20** 2017-03-15 10:37 UTC
Labels: Bug, Clean, CO-OP, Duplicate
