### ISSUE TITLE
add portal 1 square door frame 

### ISSUE THREAD

**Issue by mariovct** [BEEmod/BEE2-items#2168] opened 2017-08-27 03:29 UTC
![screenshot 2](https://user-images.githubusercontent.com/31172185/29754431-99826cb0-8b39-11e7-8225-b1f56b9fff3d.png)

**Comment by Luke18033** [comment] 2017-08-27 03:42
I hate how we close [an issue](https://github.com/BEEmod/BEE2-items/issues/2166) for being a duplicate, just to then have somebody open the SAME issue 3 hours later.

**Comment by Luke18033** [comment] 2017-08-27 03:43
Like, seriously, searching to see if your issue is a duplicate is NOT that hard!

**Comment by BETTEREXTENEDEDITORMOD** [comment] 2017-08-27 03:58
NO i read that issue this is the door frames you see at the start of 1x1 hallways

**Comment by Luke18033** [comment] 2017-08-27 03:59
Oh, sorry, I didn't realize, the name was so similar. It's usually a good idea to include an image of what you're referring to, that way things like this won't happen.

**Comment by BETTEREXTENEDEDITORMOD** [comment] 2017-08-27 04:11
ah thanks ill do that next time... btw is this being added?

**Comment by LautaroL20** [comment] 2017-08-27 12:46
Maybe, but it could take a hell of time, who knows.

**Comment by LautaroL20** [comment] 2017-08-27 12:46
Pls, include a screenshot on yor description, this looks like a duplicate of an already closed issue.

**Comment by BETTEREXTENEDEDITORMOD** [comment] 2017-08-27 19:15
it's just those rectangular archways you see in portal 1

**Comment by BETTEREXTENEDEDITORMOD** [comment] 2017-08-27 19:19
![screenshot 2](https://user-images.githubusercontent.com/31172185/29753248-f81de3fc-8b21-11e7-9017-9d5cecb5cb2e.png)

**Comment by Endermage77** [comment] 2017-08-28 01:30
What would this item translate into in other styles?
Enlarged vitrified door frames in 60's, maybe?
Although, from what I can currently think of, almost all of the other styles would probably use a door-less version of their original doors.

Better ideas would be appreciated.

**Comment by Endermage77** [comment] 2017-08-30 15:54
Better ideas than the ones <b>I</b> postulated, I meant.

**Comment by TeamSpen210** [comment] 2017-08-30 21:09
Ideally we'd want to detect these hallways perhaps, and generate them dynamically.

**Comment by BETTEREXTENEDEDITORMOD** [comment] 2017-08-30 21:54
there's a way to generate them how would that work you can't detect a hallway right?

**Comment by TeamSpen210** [comment] 2017-08-30 22:04
We can.

**Comment by BETTEREXTENEDEDITORMOD** [comment] 2017-08-30 22:14
will this be a part of the decoration system you suggested if so will it be toggleable?

**Comment by Luke18033** [comment] 2020-01-23 00:21
Another option for these would be to make them a static variant of P1 doors, generating when it's set to start open with no connections.

**Closed** 2020-07-19 08:15 UTC
Labels: Implemented, New Item Variant
