### ISSUE TITLE
Dropper Head

### ISSUE THREAD

**Issue by IceTudor** [BEEmod/BEE2-items#2312] opened 2017-10-25 18:32 UTC
An item/option to let you place a dropper head on the end/start of a vactube, you would need to power it to open it.

**Comment by Endermage77** [comment] 2017-10-25 19:31
Sounds like you'd just have to connect it at the end of a tube line.
I like.

**Comment by IceTudor** [comment] 2017-10-26 13:36
Yep, and connect it to something else
Start enabled is exactly what it does.
Start reversed could just auto drop cubes/turrets/players/"""cubes""" when they get near, like a trigger.

**Comment by Luke18033** [comment] 2017-10-27 00:16
Duplicate of #1597.

**Closed by Luke18033** 2017-10-27 00:16 UTC
