### ISSUE TITLE
Angled Panel changes and additions

### ISSUE THREAD

**Issue by villager103** [BEEmod/BEE2-items#2569] opened 2018-03-17 12:23 UTC
1. New angled panel type: Grating Panel. These appear in the vanilla Portal 2 game, especially in the Co-Op campaign. These are no different to the standard Angled Panel, but you can shoot portals through it.

2. If Grating Panels are added, then would it be possible to collapse all angled panel types into one item, then use a Weighted/Cube/Sphere option to change them?

3. Is it possible to apply the Angled Panel's properties to the Static Half Panel? If so, could there also be glass/grating versions of the half panel? The Static Half Panel's original use is still available, by having it deployed without an input, but with more options regarding angle, looks and inputs.

4. The addition of sound effects for the Clean/Overgrown panels. They are completely silent, while the Old Aperture/Portal 1 style panels not only have sound effects, but unique ones for their own styles. There are a few panel sound effects in the Portal 2 files that could be used.

5. Glass/Grating varieties of the Drawbridge. These aren't technically angled panels, but they're similar.

**Comment by Endermage77** [comment] 2018-03-17 15:24
1. Duplicate of #1590.
2. I don't think that can be done, because the angled panels rely on being an Angled Panel Type to be able to change angles. You could hypothetically apply start reversed to the Glass Panel to make this work, though.
3. Interesting.
4. That should probably have something done about it.
5. Indeed. Good idea.

I should warn you, however, that @LautaroL20 gets rather annoyed every time someone inevitably compiles a suggestions list and demands they split the post, so that they can be easily closed as they get dealt with.

**Comment by LautaroL20** [comment] 2018-03-17 15:30
@villager103 - If you have multiple bug reports or feature requests which are not related to each other, **please create separate issues instead of combining them.** This allows us to individually label the issues, and close them once they are fixed/implemented. Combined issues will immediately be closed, no matter how elaborate the post may be.

**Closed by LautaroL20** 2018-03-17 15:30 UTC
Labels: Duplicate, Invalid
