### ISSUE TITLE
chamber lockes are bugged out

### ISSUE THREAD

**Issue by CardsAndGamesYT** [BEEmod/BEE2-items#3846] opened 2021-07-12 06:42 UTC
i was using beemod 4.20.2 when i found this bug. when ever you put in more then 1 chamber lock the game gets bugged out. i was making a map when i put in a chamber lock. everything worked fine. then i added another chamber lock in another place on the map. but that time when i started the game the the chamber locks were unrefreshed voids. but when i got close to the first one it fixed its self. however when the second chamber lock opened all i saw was the unrefreshed void and when i walked in to it i fell out of the map. i expected the chamber lock to open like the first one but instead the void came up. all i did was add 2 chamber locks and when i played my map with the second chamber lock again, it showed me the unrefreshed void. and also the beginning like by the elevator was bugged out a little too.

![PORTAL 2 - Direct3D 9 7_12_2021 2_41_45 AM](https://user-images.githubusercontent.com/74144694/125242483-c31a3080-e2ba-11eb-9ea5-2c11ff0f971f.png)
![PORTAL 2 - Direct3D 9 7_12_2021 2_41_52 AM](https://user-images.githubusercontent.com/74144694/125242493-c7464e00-e2ba-11eb-88b9-7342e9787194.png)
![PORTAL 2 - Direct3D 9 7_12_2021 2_42_16 AM](https://user-images.githubusercontent.com/74144694/125242507-cb726b80-e2ba-11eb-8f8f-d5958792730e.png)
![PORTAL 2 - Direct3D 9 7_12_2021 2_42_29 AM](https://user-images.githubusercontent.com/74144694/125242525-d0371f80-e2ba-11eb-93d6-1154bcba96b6.png)
![PORTAL 2 - Direct3D 9 7_12_2021 2_42_33 AM](https://user-images.githubusercontent.com/74144694/125242536-d2997980-e2ba-11eb-9df2-9b73778a3509.png)
![PORTAL 2 - Direct3D 9 7_12_2021 2_42_38 AM](https://user-images.githubusercontent.com/74144694/125242546-d5946a00-e2ba-11eb-8cfd-80b8be25d42f.png)

**Comment by CardsAndGamesYT** [comment] 2021-07-12 06:44
also there is a room on the other side of the chamber lock

**Comment by FrozenDragon0** [comment] 2021-07-12 08:20
Duplicate of https://github.com/BEEmod/BEE2-items/issues/3615

**Closed by FrozenDragon0** 2021-07-12 08:20 UTC
Labels: Bug, Duplicate
