### ISSUE TITLE
Placing a monitor in a black wall makes the wall float

### ISSUE THREAD

**Issue by KaziPlays** [BEEmod/BEE2-items#3607] opened 2021-01-27 12:30 UTC
If I place a monitor in a black wall, when the monitor appears, the wall will appear floating.

It happens on all styles, and I don't know why.

**Comment by KaziPlays** [comment] 2021-01-27 12:33
I've put compile error by accident, please disregard.

**Comment by LautaroL20** [comment] 2021-01-27 12:36
No problem, i´ve corrected it.

**Comment by TeamSpen210** [comment] 2021-01-27 12:45
This is a duplicate of #3568.

**Closed by TeamSpen210** 2021-01-27 12:45 UTC
Labels: Bug, Clean
