### ISSUE TITLE
The funnel´s in-game model does not appear

### ISSUE THREAD

**Issue by ihatemondays72** [BEEmod/BEE2-items#4250] opened 2022-11-06 03:25 UTC
### BEE2 Application Version

BEE2.4.42.0 64bit

### BEE2 Package Version

BEE2.4.42.0

### What operating system are you running on?

Windows 10 (64bit)

### Description of the bug

When I playtest and I have funnels in the chamber, they don't appear - the funnels don't have any texture and have a no-draw texture instead (I think). (PS. I am using the overgrown style)

![Screenshot (3297)](https://user-images.githubusercontent.com/117554744/200152458-193770bf-dabb-4173-9de7-e52116d66dfb.png)

### Expected behavior

Funnels are supposed to appear with textures

### Steps to reproduce

Step 1. Install BEEMOD2.4.42.0 64bit (Windows 10 OS)
Step 2. Open BEEMOD
Step 3. Select "Overgrown"
Step 4. Open Portal 2
Step 5. Make a community map
Step 6. Use the funnel

### Logs and Reports

```shell
Couldn't find any log output
```

### Additional information

I'm using the overgrown style

**Comment by Andrei030x** [comment] 2022-11-15 01:32
REVERSE POLARITY
![20221115042929_1](https://user-images.githubusercontent.com/64521437/201804578-bdb210fa-b756-44d0-90a9-9e664c13c9dd.jpg)

**Comment by FrozenDragon0** [comment] 2022-11-24 04:03
This is technically a duplicate of https://github.com/BEEmod/BEE2-items/issues/4241, the reverse polarity issue is a separate issue.

**Closed by FrozenDragon0** 2022-11-24 04:03 UTC
Labels: Bug, Duplicate
