### ISSUE TITLE
BTS Sytle Error while constructing map with nothing inside

### ISSUE THREAD

**Issue by AeroGas** [BEEmod/BEE2-items#3738] opened 2021-04-07 08:37 UTC
Hi,
I have the version 4.39.1 of BEE2 and when i choose BTS style for portal 2 always show : An error occurenced while building this puzzle. For no reason. I even don't need to place something.
Screenshot:
![screenshot](https://user-images.githubusercontent.com/82058507/113836011-cc13d700-978c-11eb-9158-0bb4aac4fd2d.png)

I have also an error in the console:
[error.txt](https://github.com/BEEmod/BEE2-items/files/6270186/error.txt)

To make the bug, i just choose the bts style and launch the game.
Then build it to preview and then the bug!
I don't know what to do. Please help me!

**Comment by LautaroL20** [comment] 2021-04-07 09:00
This is a duplicate of: https://github.com/BEEmod/BEE2-items/issues/3739

**Closed by LautaroL20** 2021-04-07 09:00 UTC
Labels: BTS, Bug
