### ISSUE TITLE
Entrance door gone.

### ISSUE THREAD

**Issue by keifersisawesome** [BEEmod/BEE2-items#2680] opened 2018-05-02 04:58 UTC
I installed the 29 patch, and upon opening the puzzle editor, I find the entrance door is missing entirely. The exit dor is present, but the lack of an entrance door keeps the puzzle from loading at all.

**Comment by LautaroL20** [comment] 2018-05-02 05:06
This is a duplicate of: https://github.com/BEEmod/BEE2.4/issues/908

**Closed by LautaroL20** 2018-05-02 05:06 UTC
Labels: Duplicate
