### ISSUE TITLE
Overgrown Track Platform unstyled

### ISSUE THREAD

**Issue by mario2582** [BEEmod/BEE2-items#66] opened 2015-07-07 23:47 UTC
wrong type of track platform in overgrown

![preview0009](https://cloud.githubusercontent.com/assets/11165643/8559952/eb928222-24e0-11e5-9586-dfb4a0643589.jpg)
![20160821003845_1](https://cloud.githubusercontent.com/assets/12244376/17835233/da6ef67e-6738-11e6-9c0e-29bf8e2c3f6e.jpg)

**Comment by ellingtonisland** [comment] 2015-07-11 17:36
will be fixed eventually

**Comment by ZombiePwner1** [comment] 2016-08-30 00:52
This is a duplicate of https://github.com/TeamSpen210/BEE2-items/issues/715.

**Comment by Luke18033** [comment] 2017-03-16 19:54
@ZombiePwner1 - Nope, other way around.

**Comment by Konclan** [comment] 2017-03-16 20:41
Holy crap guys a little communication never hurt anybody, just stop closing and opening things without saying something first

**Comment by Luke18033** [comment] 2017-03-17 16:00
Also note the Clean tiles around the track.

**Comment by ZombiePwner1** [comment] 2019-01-03 05:02
@Luke18033 Actually this is a duplicate since @LautaroL20's post wa smade in 2016 this was in 2015 lmao.

**Comment by Konclan** [comment] 2019-08-29 01:09
This has been fixed
![20190828200839_1](https://user-images.githubusercontent.com/16567080/63902526-af6bc680-c9cf-11e9-93ef-49fad35da05f.jpg)

**Closed by Konclan** 2019-08-29 01:09 UTC
Labels: Overgrown, Unstyled
