### ISSUE TITLE
More observation room sizes

### ISSUE THREAD

**Issue by JesseRoxII** [BEEmod/BEE2-items#2891] opened 2019-01-16 04:38 UTC
There should be a way to resize observation rooms. For example: the "small observation room" item is 1x1 square in Clean style, but only half the width in Portal 1 style. There should be an option to choose _any_ size in _any_ style.

There's more than just normal, half-width, and double-width rooms. I've gone through both games, and found 5 different observation room types. Here are screenshots of them all:

![observation room screenshots](https://user-images.githubusercontent.com/27767153/51225947-e0483100-1901-11e9-8a7e-f974736df60e.png)

There was also a 4x1 room in older versions of BEEmod, but I don't think that ever appears in the original games. (Maybe it's in co-op. I wouldn't know, I've never played it.)

**Comment by ZombiePwner1** [comment] 2019-01-16 04:49
Duplicate of https://github.com/BEEmod/BEE2-items/issues/1165

**Closed by ZombiePwner1** 2019-01-16 04:49 UTC
Labels: Duplicate
