### ISSUE TITLE
Change 'Cube Cleaner' to 'Cube Painter'

### ISSUE THREAD

**Issue by TeamEXAngus** [BEEmod/BEE2-items#4112] opened 2022-04-19 23:51 UTC
Add a 'gel type' option to the 'cube cleaner' item, so that liquids other than water/cleaning gel can be dispensed from it. 

This would be useful for puzzles where a player needs to apply bounce/speed gel to a cube, especially to make it more obvious to the player. 

One puzzle where this would come in handy is the puzzle element in Coop and Portal Stories: Mel where you need to slide an orange cube down a slope to block multiple lasers.

**Comment by Luke18033** [comment] 2022-04-20 00:04
Duplicate of #1325, the issue is closed although nobody explained why...

Note if you want a cube to be immediately painted with a certain gel, you can place a splat of that gel on the same ceiling tile as the dropper.

**Closed by Luke18033** 2022-04-20 00:04 UTC
