### ISSUE TITLE
Pellets Glitch Through Panels

### ISSUE THREAD

**Issue by hop193** [BEEmod/BEE2-items#1670] opened 2017-03-06 20:35 UTC
I was testing out a level when I noticed the pellet went through the angled panel.
![20170304143456_1](https://cloud.githubusercontent.com/assets/25728252/23628441/4d42a12a-0282-11e7-9fff-d2120cb8ae68.jpg)
It, instead, hits the robotic arm behind the panel and flies all over the room. This is very annoying. This glitch doesn't happen if the panel has no inputs, but happens if it has inputs, which doesn't matter if is it set to "Start Deployed" or not. Does this have anything to do with the Portal 1 style? Is there a possible fix?

**Comment by ZombiePwner1** [comment] 2017-03-06 22:21
This is abit of a duplicate of https://github.com/BEEmod/BEE2-items/issues/1376 considering that the panels are very buggy and the pellets are the same as the cubes.

**Closed** 2017-03-06 22:21 UTC
Labels: Bug, Duplicate

**Comment by TheDarkBomber** [comment] 2017-03-07 18:50
This isn't a duplicate, this is about HEPs, not cubes.

**Comment by ZombiePwner1** [comment] 2017-03-07 22:48
@TheDarkBomber The panels collisons are buggy for both.

**Comment by hop193** [comment] 2017-03-09 22:00
Huh. Interesting. Is there a possible fix?
