### ISSUE TITLE
error

### ISSUE THREAD

**Issue by fswerrw-alt** [BEEmod/BEE2-items#3956] opened 2021-09-30 14:30 UTC
Traceback (most recent call last):
  File "app\UI.py", line 829, in export_editoritems
  File "app\gameMan.py", line 698, in export
  File "packages\signage.py", line 221, in export
  File "packages\signage.py", line 295, in build_texture
  File "srctools\vtf.py", line 841, in save
  File "srctools\_py_vtf_readwrite.py", line 129, in save
NotImplementedError: Saving DXT1 not implemented!

**Comment by fswerrw-alt** [comment] 2021-09-30 14:38
@FrozenDragon0

**Comment by LautaroL20** [comment] 2021-09-30 15:40
You have posted in the wrong section, anything related to the BEEmod user interface must be posted on the interface repository, here: https://github.com/BEEmod/BEE2.4/issues

The section where you have posted is for things related to items or styles, only.

Also, this is a duplicate of: https://github.com/BEEmod/BEE2.4/issues/1660

**Closed** 2021-09-30 15:40 UTC
Labels: Duplicate
