### ISSUE TITLE
Radiative Flux Rectangle Error

### ISSUE THREAD

**Issue by Tjmcnee** [BEEmod/BEE2-items#2259] opened 2017-10-08 22:57 UTC
I'm having an issue where everytime a pellet passes a Radiative Flux Rectangle it plays "Oh fiddlesticks, what now?" Which is apparently the error sound. Why is this error happening?

**Comment by ZombiePwner1** [comment] 2017-10-08 23:06
Because the sound for pellets passing through whenever the game detects a missing sound model or texture it will make the Oh fiddlesticks sound.

**Comment by Tjmcnee** [comment] 2017-10-08 23:15
@ZombiePwner1 Is there a way to put in the sound to fix it? I have rexura so I can get the sound from that.

**Comment by ZombiePwner1** [comment] 2017-10-08 23:35
@Tjmcnee It is fixed in the next prl which should be out soon.

**Comment by LautaroL20** [comment] 2017-10-09 03:41
@ZombiePwner1 - Hey wheels, how do you know this is fixed for next release?

**Comment by TeamSpen210** [comment] 2017-10-09 04:49
It's a duplicate of #1615.

**Comment by TeamSpen210** [comment] 2017-10-09 04:50
Duplicate of #1615

**Closed by TeamSpen210** 2017-10-09 04:49 UTC
Labels: Bug, Missing sound

**Comment by ZombiePwner1** [comment] 2017-10-09 07:37
@LautaroL20 Says the wheels.

**Comment by Tjmcnee** [comment] 2017-10-09 08:25
I didn't know it was a duplicate, Because I thought only I had the error.
