### ISSUE TITLE
Logic gates and Logic gate strips cause build error when connected to any input/output

### ISSUE THREAD

**Issue by MemeticGitHubUser** [BEEmod/BEE2-items#3590] opened 2021-01-13 23:13 UTC
**BEE2 Version: 4.3.7.0**

<details>
<summary>Error Log</summary>

VBSP failed.

[I] vbsp.main(): BEE2 v VBSP hook initiallised.
[I] cond.core.import_conditions(): Imported all conditions modules!
[I] vbsp.main(): Map path is "D:/SteamLibrary/steamapps/common/Portal 2/sdk_content\maps/preview.vmf"
[I] vbsp.main(): New path: "D:/SteamLibrary/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[I] vbsp.main(): PeTI map detected!
[I] vbsp.main(): Loading settings...
[W] texturing.load_config(): overlays: Unknown texture names faithfling, faithland
[W] texturing.load_config(): special: Unknown texture names edge_special, pedestalside
[W] vbsp_options.load(): Extra config options: {'glass_scale': '0.15', 'staticpan': 'instances/BEE2/clean/static_panel/', 'voice_pack': 'BEE2_GLADOS_CLEAN'}
[I] cond.core.build_itemclass_dict(): Read 30 item IDs, with 61 embeds!
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_ANGLED_BLOCK_60", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_ANGLED_BLOCK_45", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_ANGLED_BLOCK_30", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_ANGLED_BLOCK_CORNER_60", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_ANGLED_BLOCK_CORNER_60", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_ANGLED_BLOCK_CORNER_45", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_ANGLED_BLOCK_CORNER_45", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_ANGLED_BLOCK_CORNER_30", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_ANGLED_BLOCK_CORNER_30", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_FLAT_QUARTER", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_FLAT_HALF", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_FLAT_THREE_QUARTER", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE_PGUN_BASE", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE_PGUN_BASE", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE_PGUN_BASE", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE_PGUN_BASE", which is no longer used.
[I] cubes.parse_conf(): Parsed 7 cube types, 1 dropper types and 4 addons.
[I] fizzler.read_configs(): Loaded 14 fizzlers.
[I] vbsp.load_settings(): Settings Loaded!
[I] vbsp.load_map(): Parsing Map...
[I] vbsp.load_map(): Reading Map...
[I] vbsp.load_map(): Loading complete!
[I] antlines.parse_antlines(): Parsing antlines...
[I] antlines.parse_antlines(): Done! (0 antlines)
[I] vbsp.mod_entryexit(): Setting SP Entry to 4
[I] vbsp.mod_entryexit(): Setting SP Exit to 1
[I] vbsp.get_map_info(): Game Mode: SP
[I] vbsp.get_map_info(): Is Preview: True
[I] brushLoc.read_from_map(): Analysed map, filling air... (15 starting positions..)
[I] brushLoc.read_from_map(): Air filled!
[I] texturing.setup(): Generating texture clumps...
[I] texturing.setup(): NORMAL.FLOOR.BLACK: 15 Clumps for 370 tiles
[I] texturing.setup(): Generating texture clumps...
[I] texturing.setup(): NORMAL.CEILING.WHITE: 17 Clumps for 370 tiles
[I] texturing.setup(): Generating texture clumps...
[I] texturing.setup(): NORMAL.CEILING.BLACK: 17 Clumps for 370 tiles
[I] texturing.setup(): Generating texture clumps...
[I] texturing.setup(): NORMAL.WALL.WHITE: 37 Clumps for 370 tiles
[I] texturing.setup(): Generating texture clumps...
[I] texturing.setup(): NORMAL.WALL.BLACK: 37 Clumps for 370 tiles
[I] texturing.setup(): Generating texture clumps...
[I] texturing.setup(): PANEL.FLOOR.BLACK: 15 Clumps for 370 tiles
[I] texturing.setup(): Generating texture clumps...
[I] texturing.setup(): PANEL.CEILING.BLACK: 17 Clumps for 370 tiles
[I] texturing.setup(): Generating texture clumps...
[I] texturing.setup(): PANEL.WALL.WHITE: 37 Clumps for 370 tiles
[I] texturing.setup(): Generating texture clumps...
[I] texturing.setup(): PANEL.WALL.BLACK: 37 Clumps for 370 tiles
[I] cond.core.check_all(): Checking Conditions...
[I] cubes.link_cubes(): SPLAT File: ['instances/bee2/logic/gel_splat.vmf']
[I] cond.catwalks.res_make_catwalk(): Starting catwalk generator...
[I] cond.scaffold.res_unst_scaffold(): Running Scaffold Generator (BEE2_SCAFFOLD)...
[I] cond.scaffold.res_unst_scaffold(): Finished Scaffold generation!
[I] connections.gen_item_outputs(): Generating item IO...
[I] connections.add_item_inputs(): LOGIC counter: lg6527
[I] connections.gen_item_outputs(): Item IO generated.
[I] vbsp.set_elev_videos(): Elevator type: FORCE
[W] template.retexture_template(): Realign face in template "bee_door_cowl_clean" (1426 in final) is not on grid!
[W] template.retexture_template(): Realign face in template "bee_door_cowl_clean" (1464 in final) is not on grid!
[W] template.retexture_template(): Realign face in template "bee_door_cowl_clean" (1579 in final) is not on grid!
[W] template.retexture_template(): Realign face in template "bee_door_cowl_clean" (1516 in final) is not on grid!
[I] voiceLine.add_voice(): Adding Voice Lines!
[I] voiceLine.add_voice(): Adding Base instance!
[I] voiceLine.add_voice(): Quote events: []
[I] voiceLine.find_group_quotes(): Line "??" is disabled..
[I] voiceLine.find_group_quotes(): Line "??" is disabled..
[I] voiceLine.find_group_quotes(): Line "??" is disabled..
[I] voiceLine.find_group_quotes(): Line "??" is disabled..
[I] voiceLine.find_group_quotes(): Line "??" is disabled..
[I] voiceLine.find_group_quotes(): Line "??" is disabled..
[I] voiceLine.find_group_quotes(): Line "??" is disabled..
[I] voiceLine.find_group_quotes(): Line "??" is disabled..
[I] voiceLine.find_group_quotes(): Line "??" is disabled..
[I] voiceLine.find_group_quotes(): "ENTRY": 1/15 quotes..
[I] voiceLine.add_quote(): Adding quote: "Line"
 | 	{
 | 	"ID" "GENERIC_NOBEL_PRIZE"
 | 	"Choreo" "scenes/npc/glados/testchambermisc39.vcd"
 | 	}
 | 
 |___

[I] voiceLine.find_group_quotes(): "EXIT": 1/5 quotes..
[I] voiceLine.add_quote(): Adding quote: "Line"
 | 	{
 | 	"ID" "GENERIC_WADDLE"
 | 	"Choreo" "scenes/npc/glados/testchambermisc12.vcd"
 | 	}
 | 
 |___

[I] voiceLine.find_group_quotes(): "MIDCHAMBER": 1/9 quotes..
[I] voiceLine.add_voice(): 1 Mid quotes
[I] voiceLine.add_quote(): Adding quote: "Line"
 | 	{
 | 	"ID" "MULTI_CAVE"
 | 	"File" "clean/cave_reaction.vmf"
 | 	}
 | 
 |___

[I] voiceLine.add_voice(): Done!
[I] vbsp.set_player_portalgun(): Setting Portalgun:
[I] vbsp.set_player_portalgun(): Blue: Y, Orange: Y
[I] vbsp.set_player_portalgun(): Done!
[I] cond.core.check_all(): Map has attributes: ['weightedbutton', 'floorbutton', 'buttonacceptscube', 'buttonacceptsball', 'spawn_dual']
[I] cond.core.check_all(): instanceLocs cache: CacheInfo(hits=4461, misses=377, maxsize=256, currsize=256)
[I] cond.core.check_all(): Style Vars: {'doorcameras': True, 'restartonexit': True, 'multiversecave': True, 'fixfizzlerbump': False, 'nomidvoices': False, 'unlockdefault': False, 'allowgoomist': True, 'funnelallowswitchedlights': True, 'enableshapesignageframe': True}
[I] cond.core.check_all(): Global instances: set()
[I] vbsp.add_extra_ents(): Adding Music...
[I] vbsp.add_extra_ents(): Adding global ents...
[I] vbsp.add_extra_ents(): Adding Global PTI Ents
[I] vbsp.change_ents(): Editing Other Entities...
[I] tiling.generate_brushes(): Generating tiles...
[I] tiling.generate_brushes(): Generating goop...
[I] vbsp.change_overlays(): Editing Overlays...
[I] vbsp.fix_worldspawn(): Editing WorldSpawn
[I] vbsp.save(): Saving New Map...
[I] vbsp.save(): Complete!
[I] <Valve>.run_compiler(): Calling original VBSP...
[I] <Valve>.run_compiler(): Args: '-game', 'D:/SteamLibrary/steamapps/common/Portal 2/portal2/', 'D:/SteamLibrary/steamapps/common/Portal 2/sdk_content\\maps\\styled\\preview.vmf'
[I] <valve>.vbsp(): Valve Software - vbsp.exe (Nov 12 2019)
[I] <valve>.vbsp(): 12 threads
[I] <valve>.vbsp(): materialPath: D:\SteamLibrary\steamapps\common\Portal 2\portal2\materials
[I] <valve>.vbsp(): Loading D:/SteamLibrary/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf
[I] <valve>.vbsp(): ConVarRef gpu_level doesn't point to an existing ConVar
[I] <valve>.vbsp(): Could not open instance file instances/BEE2/logic/bee/logic_or.vmf
[I] <valve>.vbsp(): 

</details>

**Additional information:** This happens with the invisible AND, OR, and NOT gates and their strip variants

**Comment by seagemgames** [comment] 2021-01-13 23:17
This is a known issue, AFAIK, it's a compiler issue as they were meant to be moved instead of using instances.

**Comment by Luke18033** [comment] 2021-01-14 06:14
Duplicate of #3359, fixed in 4.38.

**Closed by Luke18033** 2021-01-14 06:14 UTC
Labels: Bug, Compile Error
