### ISSUE TITLE
No goo, no bottomless pit, just bright light

### ISSUE THREAD

**Issue by Emma-Walker** [BEEmod/BEE2-items#3117] opened 2019-09-23 06:55 UTC
I use BEE2_4.35.1_win and BEE2_v4.35.0_packages

Instead of goo or a bottomless pit, only bright light is shown, see
http://imgbox.com/P0NJirVg

**Comment by Luke18033** [comment] 2019-09-24 00:55
In Source, maps need to be completely "sealed" from the outside void in order to work properly. A leak occurs when this isn't the case, indicated by broken goo textures and a build error when publishing, among other things. They're kind of hard to debug without access to the original map file. Just randomly deleting items doesn't really give any useful information, since it's usually a certain item placement or a combination of items that causes the leak.  Can you send a screenshot of your map?

**Comment by Emma-Walker** [comment] 2019-09-24 05:34
I caused the leak by switching from clean to BTS. The leak already exists in the corridor.

By the way, there is a Crusher in the map. And when I switch to 1970s, the crusher sound never stops, no matter how far away I am. Don't know if it's a BEE bug or a portal 2 bug.

Link to the map (the map works, except for the leaks in non-Clean styles):
https://steamcommunity.com/sharedfiles/filedetails/?id=478128808

Link to images of the map from every side:
http://imgbox.com/g/wQOD4B1aXy

**Comment by Luke18033** [comment] 2019-09-30 05:06
BTS style as a whole is really buggy and generally known to cause leaks, but might as well try to debug this anyway. First make sure the entrance/exit corridor in the compile window are set to options that are actually implemented - these are the ones that show proper previews (rather than a door). If the issue persists, recompile the map, then upload a copy of `Portal 2/sdk_content/maps/styled/preview.vmf`.

**Comment by Luke18033** [comment] 2019-10-12 23:17
Not sure what the problem is here, closing.

**Closed by Luke18033** 2019-10-12 23:17 UTC
Labels: BTS, Bug, Leak

**Comment by LautaroL20** [comment] 2019-10-12 23:25
Probably a leak caused by an item placed in a weird position and the author will not be able to remember which items and positions were those in theri map, making this issue useless.
