### ISSUE TITLE
Faith plate is white when small space around it

### ISSUE THREAD

**Issue by Thedoczek** [BEEmod/BEE2-items#3548] opened 2020-10-17 21:08 UTC
**BEE2 version:** 4.37.0

**Description of the bug:** Sometimes faith plates make that white as in the screenshots. I think that's because of small space around it.

**Additional information:**
* When white wall: ![obraz](https://user-images.githubusercontent.com/69758777/96353337-35166e00-10cb-11eb-9c4a-fe21e3271570.png)

* When black: ![2020-10-17 (4)](https://user-images.githubusercontent.com/69758777/96353691-bb807f00-10ce-11eb-9528-1c790c5e964b.png)

**Comment by Thedoczek** [comment] 2020-10-17 21:16
I put the wrong reason. It's because of three walls around, or just because of small space for this.
![2020-10-17 (4)](https://user-images.githubusercontent.com/69758777/96353691-bb807f00-10ce-11eb-9528-1c790c5e964b.png)

**Comment by Luke18033** [comment] 2020-10-17 21:22
No, it's because you have an input connected.
Duplicate of #3455

**Closed by Luke18033** 2020-10-17 21:22 UTC
Labels: Bug

**Comment by Thedoczek** [comment] 2020-10-17 21:28
Luke, did you read #3541?

**Comment by Luke18033** [comment] 2020-10-17 21:40
I just didn't notice? Not sure why you seem so annoyed about it.
