### ISSUE TITLE
New item variant: human button (reacts on humans only)

### ISSUE THREAD

**Issue by SCIENTIST2004** [BEEmod/BEE2-items#2493] opened 2018-02-09 18:02 UTC
![portal_button_bendy](https://user-images.githubusercontent.com/35931028/36042325-2476efae-0dd4-11e8-81ed-fbc3dab74554.png)

**Comment by Luke18033** [comment] 2018-02-09 18:19
Duplicate of #457

**Closed by Luke18033** 2018-02-09 18:19 UTC

**Comment by SCIENTIST2004** [comment] 2018-02-09 18:23
oh...

**Comment by xGARDYx** [comment] 2018-02-11 16:12
tho this icon looks better than the one on that issue
