### ISSUE TITLE
Surface Lacquer has a missing texture.

### ISSUE THREAD

**Issue by supersean08-pro** [BEEmod/BEE2-items#3680] opened 2021-03-05 09:44 UTC
![20210305112402_1](https://user-images.githubusercontent.com/63530071/110097672-6cc05100-7df3-11eb-997e-8247c090ad51.jpg)
![20210305112417_1](https://user-images.githubusercontent.com/63530071/110097687-70ec6e80-7df3-11eb-9f12-2743e5759f1e.jpg)

**Comment by LautaroL20** [comment] 2021-03-05 15:50
@supersean08-pro - Which version of Beemod and packages are you using?

**Comment by Greypilgrim228** [comment] 2021-03-05 18:08
This version happens on mine too. I'm using 4.39.1 with 4.39.2 packages. The gel splash icon doesn't appear when placed in the editor, it instead places a blue "error" icon you can move around the room. When rendering the map, the gel seems to give off the effect in the picture, similar to toxic goo not rendering when leaking occurs.

**Comment by Irixue** [comment] 2021-03-06 11:19
I'm having this same problem and I have no idea what causes it. I've tried completely reinstalling the app and packages, the patch, I have all of the most recent files, it happens in all styles. When applied to a panel it will instead have a wireframe appearance. 

In the palette and editor it looks fine, showing the pant can icon, but as soon as I load in game, it's the same as this.

**Comment by LautaroL20** [comment] 2021-04-21 17:47
This is a duplicate of: https://github.com/BEEmod/BEE2-items/issues/3655

**Closed by LautaroL20** 2021-04-21 17:47 UTC
Labels: Bug
