### ISSUE TITLE
Portal 1 Chell as a playable character

### ISSUE THREAD

**Issue by KaziPlays** [BEEmod/BEE2-items#3703] opened 2021-03-15 20:36 UTC
Self-explanatory.

**Comment by supersean08-pro** [comment] 2021-03-15 21:42
Duplicate of #536

**Comment by supersean08-pro** [comment] 2021-03-15 21:44
im sure this was a duplicate of something

**Comment by supersean08-pro** [comment] 2021-03-15 21:44
https://github.com/BEEmod/BEE2.4/issues/536

**Comment by KaziPlays** [comment] 2021-03-15 21:50
I'm pretty sure I can find something that can help do this.

**Comment by KaziPlays** [comment] 2021-03-15 21:59
https://gamebanana.com/skins/180693

**Comment by KaziPlays** [comment] 2021-03-15 22:05
Just put that onto BEE2 and call it Portal 1 Chell

**Comment by KaziPlays** [comment] 2021-03-15 22:06
I've actually seen somewhere a Portal 1 chell skin For Portal 2 but I can't find it.

**Comment by seagemgames** [comment] 2021-03-15 22:34
It's still a duplicate.

**Closed** 2021-03-15 22:39 UTC
Labels: Enhancement
