### ISSUE TITLE
Is combining the other type of Fizzlers possible?

### ISSUE THREAD

**Issue by MoonstreamJustNotInSpace** [BEEmod/BEE2-items#3355] opened 2020-07-06 16:49 UTC
Basically what the title says. Would it be possible to make it so that, for example, the Physler and Compressed smoke field were part of the same fizzler (e.g. laser->Physler, normal fizzler -> CSF)? And also do the same for the Force Deflection and Closed Solid Fields as well? It would be nice to have them take up one slot instead of two, and I've seen other toggleable things like this done before.

**Comment by Flash4433** [comment] 2020-07-06 16:52
Yes. #1596

**Comment by Luke18033** [comment] 2020-07-06 17:23
This would be a duplicate of that issue.

**Closed by Luke18033** 2020-07-06 17:23 UTC
