### ISSUE TITLE
Autoportal failure bug.

### ISSUE THREAD

**Issue by PortalPuzzleMan** [BEEmod/BEE2-items#3776] opened 2021-05-04 20:35 UTC
**BEE2 version:**

V4.39.2

**Expected behavior:**

The autoportal would be activated and make an orange portal when I press the pedestal button.

**Steps to reproduce:**

Pedestal button, connected to the autoportal and simply press the pedestal button. In case it's important, there's an blue portal gun you have to pick up before pressing the button.

**Additional information:**
 An copypaste of the console with me booting the map, getting blur portal gun, and then pressing the autoportal's connected pedestal button.

=======================Trying to GivePlayerPortalgun
=======================Trying to UpgradePlayerPortalgun
Updating sound cache [8759 entries]
Found 8748 sound files on disk
Updated 0 out of 8748 cached files [495.291 msec]
Redownloading all lightmaps
-------
Scaling type: 10
-------
SAVEGAME:  710.8kb,  190.3kb used by 454 entities (puzzlemaker/preview)
SAVEGAME:   28.8kb,   15.4kb used by 179 entities (puzzlemaker/preview)
SAVEGAME:    1.0kb,    0.0kb used by   0 entities (puzzlemaker/preview)
VScript error: DoEntFire was passed an invalid entity instance.
VScript error: DoEntFire was passed an invalid entity instance.

**Comment by HeimlichLaboratories** [comment] 2021-05-04 20:52
Already reported

**Comment by Luke18033** [comment] 2021-05-04 20:58
Duplicate of #3672

**Closed by Luke18033** 2021-05-04 20:58 UTC
Labels: Bug
