### ISSUE TITLE
BTS Gel Crashes game if hits Pedestal Button

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#347] opened 2016-03-13 18:07 UTC
**To replicate this bug:** ~~Connect a timered pedestal to the reflection gel dropper, then press the button and by using your portals, make the reflection gel to splash in the player´s face as is showin in this GIF:~~ Hit a pedestal button with gel

![gif 3](https://cloud.githubusercontent.com/assets/12244376/13730281/e53d402a-e929-11e5-9e00-175d1a24e8bc.gif)

**Comment by LautaroL20** [comment] 2016-03-14 07:18
let me clarify i was not being dummy by using lot of reflection gel droppers to force the game crash by taken all the ram memory. In this case, for the reflection gel test in BTS Style ive used only 3 Droppers in the map, this amount of 3 droppers could not crash the game.

**Comment by Konclan** [comment] 2016-04-25 19:22
*Timed

**Comment by ZombiePwner1** [comment] 2016-08-31 10:12
This happens with other gels aswell since my game crashed asoon as the button made it's beeping sound.

**Comment by Luke18033** [comment] 2017-03-06 01:51
I think this is fixed now?

**Comment by Luke18033** [comment] 2019-08-04 01:58
Has anyone figured out why this happens?

**Comment by LautaroL20** [comment] 2019-08-04 05:39
No, but i am starting to feel that this bug who i´ve reported in 2016, knowing now that many of these issues are usually hardcoded in the source code, seems now unlikely that would be getting a fix for this.

**Comment by Luke18033** [comment] 2019-08-04 05:43
It seems kind of weird though - how does this differ in BTS style from other styles? It's the exact same entity dispensing the gel, with the exact same properties.

**Comment by LautaroL20** [comment] 2019-08-04 07:06
Maybe that could mean that the BTS Style is not enough optimized so when the reflective gel shots the player´s face, it would overcharge the Ram memory causing this crash? Otherwise, i don´t know...

**Comment by ZombiePwner1** [comment] 2019-08-04 08:09
@LautaroL20 That is highly unlikely it's most likely to do with the entities in the instance that's causing a problem.

**Comment by LautaroL20** [comment] 2019-08-04 13:47
Do you think the problem is in the Reflection Gel´s instances or in the timed Ped Button?

**Comment by ZombiePwner1** [comment] 2019-08-04 23:02
Most likely both.

**Comment by Konclan** [comment] 2019-08-29 02:05
I actually discovered something, covering the button is what crashes the game.

**Comment by Konclan** [comment] 2019-08-29 02:10
It happens with literally any gel
![BTS Gel Crash](https://user-images.githubusercontent.com/16567080/63904963-49d00800-c9d8-11e9-99e6-d62444c843aa.gif)

**Comment by Konclan** [comment] 2019-08-29 02:13
I assume it has something to do with the button model not liking gel

**Comment by LautaroL20** [comment] 2019-08-29 02:44
Good one! I wonder what the hell is the defective thing here, if the pedestal button or the reflection gel... maybe both?

**Comment by Konclan** [comment] 2019-08-29 02:46
It has nothing to do with Reflection Gel specifically, its gel covering the bts style pedestal button

**Comment by ZombiePwner1** [comment] 2019-08-29 05:13
That's one of the most weird bugs I've seen. This is actually a source code issue which obviously we can't fix. We need to put a invisible paint fizzler around the button that stops it from being coated.

**Comment by Luke18033** [comment] 2019-08-29 05:15
What entity exactly is causing this? One of the props, the actual button, something unrelated?

**Comment by ZombiePwner1** [comment] 2019-08-29 05:21
@luke18033 The actual button model and the button itself is most likely the issue.

**Comment by LautaroL20** [comment] 2019-08-29 13:11
Spencer should really check this to determine what the hell is really happening behind this big mystery to tell us the real cause...

**Comment by Luke18033** [comment] 2020-08-26 01:10
Figured out the cause of this, the gel system apparently doesn't like props set to QPhysics collisions. I switched it to Bounding Box, that works fine and should be identical.

**Comment by Luke18033** [comment] 2020-08-26 01:16
![image](https://user-images.githubusercontent.com/19228201/91243559-20d37780-e6ff-11ea-8cff-b7b9dd2b60fc.png)

**Comment by LautaroL20** [comment] 2020-08-26 01:52
Nice.

**Closed** 2021-01-14 04:56 UTC
Labels: BTS, Bug, Done, Game Crash
