### ISSUE TITLE
Portal 1 engine error 

### ISSUE THREAD

**Issue by BETTEREXTENEDEDITORMOD** [BEEmod/BEE2-items#2862] opened 2018-11-16 04:52 UTC
Tride making a coop map for p1 style, then the game crashed with this error

Engine Error

  142/lc135647-laser_catcher - prop_laser_catcher:  UTIL_SetModel:  not
  precached: models/bee2/prop_p1/laser_catcher.mld

**Comment by Luke18033** [comment] 2018-11-16 05:09
Duplicate of #2856

**Closed by Luke18033** 2018-11-16 05:09 UTC
