### ISSUE TITLE
Closed Solid Field: add a thin cattapult trigger that kicks the player a bit earlier from a possible trap when the fizzler activates.

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#2074] opened 2017-06-24 10:42 UTC
![20170106112549_1](https://cloud.githubusercontent.com/assets/12244376/21720625/fc794c7e-d402-11e6-80c1-7a018a2764c6.jpg)

**Comment by Luke18033** [comment] 2017-06-24 15:24
Duplicate of #1520 (you're even using the same image...)

**Closed by Luke18033** 2017-06-24 15:24 UTC
Labels: Enhancement

**Comment by LautaroL20** [comment] 2017-06-24 20:40
> Luke18033 Said: you're even using the same image..."

Obviously i will not wasting my time at launching the game each time i need to post an image for an issue if there is already an equivalent image to reuse....
