### ISSUE TITLE
Logic gates cause compiler errors

### ISSUE THREAD

**Issue by mjcox244** [BEEmod/BEE2-items#3587] opened 2020-12-27 18:11 UTC
when i use logic gates (the rainbow icon and strip icon) even if i have them hookded up conectly (2 inputs 1 output) it causes a compiler error on the building geomitry part

Im useing stock portal 2 with the compressed pre-set with logic gates added

(the game im patching is stock portal 2)

**Comment by Konclan** [comment] 2020-12-27 18:11
duplicate of #3359

**Closed** 2020-12-27 18:11 UTC
