### ISSUE TITLE
 Standing fizzler has only x1 variant

### ISSUE THREAD

**Issue by SCIENTIST2004** [BEEmod/BEE2-items#3395] opened 2020-07-19 19:51 UTC
the other 4 can be obtained by changing the cube type

**Comment by LautaroL20** [comment] 2020-07-19 19:53
This is a duplicate of: https://github.com/BEEmod/BEE2-items/issues/3394

**Closed by LautaroL20** 2020-07-19 19:53 UTC
Labels: Duplicate

**Comment by SCIENTIST2004** [comment] 2020-07-19 20:00
you were 6 minutes ahead of me
