### ISSUE TITLE
High Energy Pellet Catchers do not catch the pellets

### ISSUE THREAD

**Issue by barn-advisor** [BEEmod/BEE2-items#2357] opened 2017-11-01 16:43 UTC
im using pr 27

**Comment by IceTudor** [comment] 2017-11-01 17:43
This was already issued before.

**Comment by barn-advisor** [comment] 2017-11-01 19:08
still not resolved so

**Comment by Luke18033** [comment] 2017-11-01 21:06
This would probably be a duplicate of #1724.

**Closed by Luke18033** 2017-11-01 21:06 UTC
