### ISSUE TITLE
[PRL21.5 Bug] 70´s Old Aperture: The SP Entry corridor N°5 is missing its "Frames"

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#768] opened 2016-09-04 17:31 UTC
![20160904142644_1](https://cloud.githubusercontent.com/assets/12244376/18232715/4870a95a-72ac-11e6-8c23-46da21a3f07f.jpg)

**Comment by TheDarkBomber** [comment] 2016-09-04 19:29
Duplicate of #747.

**Comment by LautaroL20** [comment] 2016-09-04 19:33
No.

**Comment by TheDarkBomber** [comment] 2016-09-04 19:40
Yes, it is the same bug.

**Comment by LautaroL20** [comment] 2016-09-04 19:47
Thats is 60´s... This is 80´s, the title clearly says it. Id suggest to get a pair of glasses.

**Comment by TheDarkBomber** [comment] 2016-09-04 20:16
It's still the same bug. Still Old Aperture.

**Comment by Luke18033** [comment] 2017-03-06 02:37
Indeed, this is a duplicate.

**Closed by Luke18033** 2017-03-06 02:37 UTC
Labels: Bug, Old Aperture
