### ISSUE TITLE
PRL27 Bug: Overgrown COOP Checkpoint´s Pipes are using a clean version

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#2266] opened 2017-10-10 12:09 UTC
![20171010081928_1](https://user-images.githubusercontent.com/12244376/31385061-0bbd2790-ad98-11e7-9115-dcfe8dde0ef3.jpg)

**Comment by Konclan** [comment] 2017-11-25 15:26
Duplicate of #1823

**Closed** 2017-11-25 16:10 UTC
Labels: CO-OP, Fixed, Overgrown, Unstyled Item
