### ISSUE TITLE
Cause of science music doesn't play.

### ISSUE THREAD

**Issue by FrozenDragon0** [BEEmod/BEE2-items#3253] opened 2020-03-22 07:48 UTC
PrecacheScriptSound 'music.BEE2' failed, no such sound script entry

**Comment by Luke18033** [comment] 2020-04-26 06:04
What specific combination of variant tracks are you using? I don't have any problems with this.

**Comment by Luke18033** [comment] 2020-05-19 19:27
Closing due to lack of info

**Comment by FrozenDragon0** [comment] 2020-05-19 23:03
Wasn't using any combination just the music on it's own.

**Comment by Luke18033** [comment] 2020-05-19 23:10
So just Cause of Science as the base track, with no variant tracks?

**Comment by FrozenDragon0** [comment] 2020-05-19 23:17
Yes

**Comment by Luke18033** [comment] 2020-05-31 19:14
I can't reproduce this.

**Closed by Luke18033** 2020-05-31 19:14 UTC
Labels: Bug, More Info Needed
