### ISSUE TITLE
add old aperture version rocket turret and add alternate turret for old aperture in portal 2(from tag and mel)

### ISSUE THREAD

**Issue by 1209-57238032** [BEEmod/BEE2-items#4062] opened 2022-01-17 02:52 UTC
### Description of the feature

alternate for rocket turret in old aperture ,alternate skeleton turret for old aperture in portal 2 but can changed 2 versions namely tommy turret(mel and tag) and skeleton turret(human vault)

### Why should this be implemented

i think add these items and 2 versions for old aperture turret and alternate old aperture version rocket turret

### Additional information

alternate old aperture version rocket turret,alternate skeleton turret for old aperture in portal 2(from tag and mel tommy turret) can change 2 versions for old aperture turret
![20220117101147_1](https://user-images.githubusercontent.com/96955851/149701435-5e427ed0-aa04-410b-80b4-33e637700684.jpg)

**Comment by FrozenDragon0** [comment] 2022-01-17 03:32
We cannot add the Old Aperture turret from Tag/Mel as we are not allowed to use that model, and what do you mean Old Aperture rocket turret?

**Comment by Luke18033** [comment] 2022-01-17 03:37
We're not actually sure whether or not we're allowed to use it. Regardless, this would be a duplicate of #2750.

**Closed by Luke18033** 2022-01-17 03:37 UTC
Labels: Enhancement

**Comment by 1209-57238032** [comment] 2022-01-17 03:42
ok i will change my idea

**Comment by 1209-57238032** [comment] 2022-01-17 03:43
nah

**Comment by HeimlichLaboratories** [comment] 2022-01-17 13:38
yes it is lol, both mention the rocket turret

**Comment by 1209-57238032** [comment] 2022-01-18 08:00
@HeimlichLaboratories say can you test this npc model in portal2? (p1 style has own turret model used) so can you add that turret in the old ap styles? if working please tell them

**Comment by 1209-57238032** [comment] 2022-01-18 08:08
@HeimlichLaboratories and don't care the custom voice lines because they aren't possible. ap tag's old turret can talking but mel can't talking so use tags old ap turret voice lines

**Comment by Luke18033** [comment] 2022-01-18 08:11
Please stop pinging random people telling them to "test the model", we know it works fine... It's also already been said in the main issue that the voicelines can't be used.

**Comment by 1209-57238032** [comment] 2022-01-18 08:15
ok whatever

**Comment by 1209-57238032** [comment] 2022-01-18 08:44
the custom voice lines aren't possible in beemod so mel can't talking but ap tag's old turret can talking but so tag's old turret can talking because aptag old ap turret installed the "talking system"

**Comment by 1209-57238032** [comment] 2022-01-18 08:50
nah whatever

**Comment by 1209-57238032** [comment] 2022-01-19 00:34
nah

**Comment by 1209-57238032** [comment] 2022-01-19 00:37
nah forget it
