### ISSUE TITLE
Too small hitboxes on pellet catchers

### ISSUE THREAD

**Issue by snorepion** [BEEmod/BEE2-items#1949] opened 2017-05-09 21:58 UTC
Even if you're perfectly precise with redirection of pellets via portals or cubes, you actually have to position the pellet slightly to the left of the center of the launcher for it to recognize the pellet. Added to this, the reception area is very small, making it hard to complete pellet-based tests. I don't think this was present in the last version, but it breaks a lot of tests because Rexaura cube deflectors aren't compatible with the positioning of the hitbox.

**Comment by Luke18033** [comment] 2017-05-10 01:37
What style is this on? I didn't have this issue in an overgrown map I was working on a while ago.

**Comment by snorepion** [comment] 2017-05-10 01:49
BEE2 clean map (not original clean). I'll upload a video of the issue soon.

**Comment by HugoBDesigner** [comment] 2017-05-10 21:05
Possibly duplicate of #1724 ?

**Comment by snorepion** [comment] 2017-05-10 21:52
Basically, yeah. I'll have to go into Hammer and adjust the positions of the pellet catchers in my map.

**Closed** 2019-01-27 04:35 UTC
Labels: Duplicate
