### ISSUE TITLE
[Suggestion] Beta Style Theme (or more customizable item Properties)

### ISSUE THREAD

**Issue by CS117** [BEEmod/BEE2-items#2969] opened 2019-04-20 05:14 UTC
In several Beta Videos & Trailers, Several Items are using Portal 1 models yet the Tests are using the Final Theme.
Example: In the Portal 1 Reveal Trailer & Co-op Trailer, several test chambers used Portal 1 Fizzlers, Chamber Doors, Turrets, Portal Guns & Buttons, yet we see Portal 2 Cubes, Light Strips, panels, & Elevator Lifts.

![uno](https://user-images.githubusercontent.com/48505717/56453043-30170980-62f0-11e9-9e87-6fde38be2ba4.png)
![dos](https://user-images.githubusercontent.com/48505717/56453046-34432700-62f0-11e9-866b-feb3b2743a91.png)
![tres](https://user-images.githubusercontent.com/48505717/56453048-373e1780-62f0-11e9-8518-3a3ea3af8106.png)
![quadro](https://user-images.githubusercontent.com/48505717/56453050-3ad19e80-62f0-11e9-969f-e321c622ebf3.png)

Is it possible to be able to implement the ability to recreate the beta style test Elements? If not, is it possible to implement additional Item Properties to replicate this style?

**Comment by Konclan** [comment] 2019-04-20 05:35
Duplicate of #741

**Closed** 2019-04-20 06:40 UTC

**Comment by LautaroL20** [comment] 2019-04-20 12:38
@TeamSpen210 - Do not forget to apply the label after closing an issue; since although it may sounds unbelievable, there are some people who still checks inside the "closed issues" tab in order to see which issues were solved/closed and their reasons. So, having them shorted with the proper label after closing will help people to understand the real cause of its closure.

There is no need to apply aditional labels such as "enhancement", "new item" etc, when the issue is invalid/duplicate. The "invalid" or "duplicate" labels are just enough to clarify a reason for it.
