### ISSUE TITLE
Logic Strip OR compile error

### ISSUE THREAD

**Issue by pansong291** [BEEmod/BEE2-items#3412] opened 2020-07-21 11:35 UTC
when i connected them like the follow pic, compile error just occurred.  
![or-gate-feedback-compile-error.jpg](https://github.com/pansong291/Pictures/raw/master/github/BEEmod/BEE2-items/or-gate-feedback-compile-error.jpg)

**Comment by FrozenDragon0** [comment] 2020-07-21 11:46
Console log? That picture isn't alot of info.

**Comment by pansong291** [comment] 2020-07-21 12:05
```
[PORTAL2 PUZZLEMAKER]  New chamber!
[PORTAL2 PUZZLEMAKER] (Save Changes) (  Untitled puzzle has unsaved changes.	 )
[PORTAL2 PUZZLEMAKER]  Discarding existing puzzle 
Unknown command "cl_puzzlemaker_activate"
[PORTAL2 PUZZLEMAKER]  New chamber!
maxplayers set to 1
---- Host_NewGame ----
Network: IP 192.168.43.129, mode SP, dedicated No, ports 0 SV / 0 CL
Opened Steam Socket NS_SERVER ( socket 2864 )
Opened Steam Socket NS_CLIENT ( socket 1744 )
Network: IP 192.168.43.129, mode MP, dedicated No, ports 27015 SV / 27005 CL
Couldn't get HDR 'maps\newchamber/c-1904_2096_-48.hdr' -- Trying non HDR 'maps\newchamber/c-1904_2096_-48'
Failed, using default cubemap 'engine/defaultcubemap'
Couldn't get HDR 'maps\newchamber/c-2032_-2032_-31.hdr' -- Trying non HDR 'maps\newchamber/c-2032_-2032_-31'
Failed, using default cubemap 'engine/defaultcubemap'
Host_NewGame on map puzzlemaker\newchamber
exec: couldn't exec skill1.cfg
==== calling mapspawn.nut
Attempted to create unknown entity type playtest_manager!
Can't init playtest_manager
Couldn't find any entities named doorentry0-player_start_teleport, which point_template @player_start_template is specifying.
Commentary: Could not find commentary data file 'maps/puzzlemaker\newchamber_commentary.txt'. 
1.000:  Sending UDP connect to public IP 127.0.0.1:27015
Server using '<none>' lobbies, requiring pw no, lobby id 0
RememberIPAddressForLobby: lobby 0 from address loopback
Can't find factory for entity: wearable_item
NULL Ent in UTIL_PrecacheOther
[PORTAL2 PUZZLEMAKER]  --------START loading assets--------

[PORTAL2 PUZZLEMAKER]  ---------END loading assets---------

==== calling mapspawn.nut
[PORTAL2 PUZZLEMAKER]  Saved puzzle: D:/Program Files/Steam/steamapps/common/Portal 2/portal2/puzzles\76561198391583576\autosave.p2c
***********************************
*         NO GAME SESSION         *
* some features might be disabled *
* (achievements, stats, UI, etc.) *
***********************************
Redownloading all lightmaps
[PORTAL2 PUZZLEMAKER]  Saved puzzle: D:/Program Files/Steam/steamapps/common/Portal 2/portal2/puzzles\76561198391583576\autosave.p2c
[PORTAL2 PUZZLEMAKER]  CVoxelTestChamber::Export VMF D:/Program Files/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf ...
[PORTAL2 PUZZLEMAKER]  CVoxelTestChamber::Export VMF success, chamber size: (8,6,4)
[PORTAL2 PUZZLEMAKER]  Compilation time (after export): 56 (ms)

VBSP failed.

[I] vbsp.main(): BEE2 v VBSP hook initiallised.
[I] cond.core.import_conditions(): Imported all conditions modules!
[I] vbsp.main(): Map path is "D:/Program Files/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf"
[I] vbsp.main(): New path: "D:/Program Files/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[I] vbsp.main(): PeTI map detected!
[I] vbsp.main(): Loading settings...
[W] texturing.load_config(): Could not parse texture generator type "bullsye.white.floor"!
[W] texturing.load_config(): overlays: Unknown texture names faithfling, faithland
[W] texturing.load_config(): special: Unknown texture names edge_special, pedestalside
[W] vbsp_options.load(): Extra config options: {'glass_scale': '0.15', 'staticpan': 'instances/BEE2/clean/static_panel/'}
[I] cond.core.build_itemclass_dict(): Read 30 item IDs, with 48 embeds!
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_ANGLED_BLOCK_60", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_ANGLED_BLOCK_45", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_ANGLED_BLOCK_30", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_ANGLED_BLOCK_CORNER_60", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_ANGLED_BLOCK_CORNER_60", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_ANGLED_BLOCK_CORNER_45", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_ANGLED_BLOCK_CORNER_45", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_ANGLED_BLOCK_CORNER_30", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_ANGLED_BLOCK_CORNER_30", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_FLAT_QUARTER", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_FLAT_HALF", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_FLAT_THREE_QUARTER", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE_PGUN_BASE", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE_PGUN_BASE", which is no longer used.
[I] cubes.parse_conf(): Parsed 7 cube types, 1 dropper types and 4 addons.
[I] fizzler.read_configs(): Loaded 14 fizzlers.
[I] vbsp.load_settings(): Settings Loaded!
[I] vbsp.load_map(): Parsing Map...
[I] vbsp.load_map(): Reading Map...
[I] vbsp.load_map(): Loading complete!
[I] antlines.parse_antlines(): Parsing antlines...
[I] antlines.parse_antlines(): Done! (3 antlines)
[I] vbsp.mod_entryexit(): Setting SP Entry to 1
[I] vbsp.mod_entryexit(): Setting SP Exit to 1
[I] vbsp.get_map_info(): Game Mode: SP
[I] vbsp.get_map_info(): Is Preview: True
[I] brushLoc.read_from_map(): Analysed map, filling air... (17 starting positions..)
[I] brushLoc.read_from_map(): Air filled!
[I] cond.core.check_all(): Checking Conditions...
[I] cubes.link_cubes(): SPLAT File: ['instances/bee2/logic/gel_splat.vmf']
[I] cond.catwalks.res_make_catwalk(): Starting catwalk generator...
[I] cond.scaffold.res_unst_scaffold(): Running Scaffold Generator (BEE2_SCAFFOLD)...
[I] cond.scaffold.res_unst_scaffold(): Finished Scaffold generation!
[I] connections.gen_item_outputs(): Generating item IO...
[I] connections.add_item_inputs(): LOGIC counter: lg14087
[I] connections.gen_item_outputs(): Item IO generated.
[I] vbsp.set_elev_videos(): Elevator type: RAND
[I] voiceLine.add_voice(): Adding Voice Lines!
[W] BEE2_config.load(): Config "bee2\voice.cfg" not found! Using defaults...
[W] BEE2_config.load(): Config "bee2\mid_voice.cfg" not found! Using defaults...
[I] voiceLine.add_voice(): Quote events: []
[I] voiceLine.add_voice(): 0 Mid quotes
[I] voiceLine.add_voice(): Done!
[I] vbsp.anti_fizz_bump(): Adding Portal Bumpers to fizzlers...
[I] vbsp.anti_fizz_bump(): Done!
[I] vbsp.set_player_portalgun(): Setting Portalgun:
[I] vbsp.set_player_portalgun(): Blue: Y, Orange: Y
[I] vbsp.set_player_portalgun(): Done!
[I] cond.core.check_all(): Map has attributes: ['glass', 'weightedbutton', 'floorbutton', 'buttonacceptscube', 'buttonacceptsball', 'spawn_dual']
[I] cond.core.check_all(): instanceLocs cache: CacheInfo(hits=3744, misses=332, maxsize=256, currsize=256)
[I] cond.core.check_all(): Style Vars: {'doorcameras': False, 'restartonexit': True, 'multiversecave': True, 'fixfizzlerbump': True, 'nomidvoices': False, 'unlockdefault': False, 'allowgoomist': False, 'funnelallowswitchedlights': True, 'enableshapesignageframe': True}
[I] cond.core.check_all(): Global instances: set()
[I] vbsp.add_extra_ents(): Adding Music...
[I] vbsp.add_extra_ents(): Adding global ents...
[I] vbsp.add_extra_ents(): Adding Global PTI Ents
[I] vbsp.change_ents(): Editing Other Entities...
[I] tiling.generate_brushes(): Generating tiles...
[I] tiling.generate_brushes(): Generating goop...
[I] vbsp.change_overlays(): Editing Overlays...
[I] vbsp.fix_worldspawn(): Editing WorldSpawn
[I] vbsp.save(): Saving New Map...
[I] vbsp.save(): Complete!
[I] <Valve>.run_compiler(): Calling original VBSP...
[I] <Valve>.run_compiler(): Args: '-game', 'D:/Program Files/Steam/steamapps/common/Portal 2/portal2/', 'D:/Program Files/Steam/steamapps/common/Portal 2/sdk_content\\maps\\styled\\preview.vmf'
[I] <valve>.vbsp(): Valve Software - vbsp.exe (Nov 12 2019)
[I] <valve>.vbsp(): 4 threads
[I] <valve>.vbsp(): materialPath: D:\Program Files\Steam\steamapps\common\Portal 2\portal2\materials
[I] <valve>.vbsp(): Loading D:/Program Files/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf
[I] <valve>.vbsp(): ConVarRef gpu_level doesn't point to an existing ConVar
[I] <valve>.vbsp(): Could not open instance file instances/BEE2/logic/bee/logic_or.vmf
[I] <valve>.vbsp(): 
[I] BEE2_config.save(): Saving changes in config "C:\Users\Administrator\AppData\Roaming\BEEMOD2\config\compile.cfg"!
```

**Comment by FrozenDragon0** [comment] 2020-07-21 12:21
Hmmm looks like @TeamSpen210 Forgot to remove the code in the compiler that asks for the .vmf instances regarding the logic gates.

**Comment by pansong291** [comment] 2020-07-21 12:34
@FrozenDragon0 thank you.

**Comment by FrozenDragon0** [comment] 2020-07-21 12:37
@pansong291 You're welcome.

**Comment by Luke18033** [comment] 2020-07-21 17:21
Duplicate of #3359

**Closed** 2020-07-21 17:21 UTC
Labels: Compile Error, Duplicate
