### ISSUE TITLE
The lower and top part of the field in almost all the fizzlers are showing a mysterious checkered texture for people who do not have Beemod installed

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#3155] opened 2019-12-06 08:19 UTC
**This issue will only affect people who play Beemod maps without having it installed,** and it happens to the following fizzlers:

* Vanilla Fizzler
* Laserfield
* Force Deflection Field
* Matter Inquisition Field
* Compressed Smoke Field
* Closed Solid Field
* Pysics Rhepulsion Field

### **Screenshot (make sure to see it in full resolution to understand where the issue is):**
![Custom Fizzlers Issue](https://user-images.githubusercontent.com/12244376/70306338-65bc2480-17e5-11ea-88db-e7d4c9a7f7fd.jpg)

**Comment by ZombiePwner1** [comment] 2019-12-06 08:33
LOL.

**Comment by HelloIamaPersonThatIsAliveAndHealthily** [comment] 2019-12-06 09:40
Nice find! I doubt i could have easily find it since i have Beemod installed with all the resources so it will not let me see this problem.

**Comment by Luke18033** [comment] 2019-12-09 01:10
Duplicate of BEEmod/BEE2.4#1184.

Also...does anyone else feel like HelloIamapersonthatisalive is Lautaro's alt? They write similarly, and seem to always comment on each other's stuff...

**Closed by Luke18033** 2019-12-09 01:10 UTC
Labels: Bug

**Comment by LautaroL20** [comment] 2019-12-09 01:22
That issue is in the wrong repro, also i will re-use the screenshot of my post who is more detailed.

**Comment by LautaroL20** [comment] 2019-12-09 01:58
>Luke18033 said: "Also...does anyone else feel like HelloIamapersonthatisalive is Lautaro's alt? They write similarly, and seem to always comment on each other's stuff..."

It is interesting seeing the people´s imagination in action... they can even see small conspirations where they aren´t like this case. The similar writting can be easily explained as not all the Bee´s community is natively english, so they will writte as best as they can. Also, another thing that could result similar, is the type of apostrophe ( ´ ), and that is also due that some keyboard and system configuration are not in english entirely, and therefore characters will vary.

Regardless of the explained above, i do not have the time (although i wish i had, who wouldn´t like having lot of free time?) to making a clone account to post comments when i could perfectly do them with my main one.

However, if you prefer to keep having that mental fantasy about me, who am i to stop you from keep thinking into that small conspiration...

**Comment by LautaroL20** [comment] 2019-12-09 02:15
@Luke18033 - Also, do not forget to apply the corresponding label after closing an issue.

**Comment by Luke18033** [comment] 2019-12-09 04:44
It's not just that. HelloIamaPersonThatIsAlive the only other user I've seen using "mysterious" and "stagnant forever", quotes included, unironically. There's another, probably more important fact: The entire account is an impostor. [Here's the original user, with a slightly different name](https://github.com/HelloIamapersonthatisalive) - notice their bio, I previously had a discussion with this person on Discord and they added that to prove it was really them. They joined GitHub a year earlier, and used to have the same profile picture, with one difference: It had a transparent background instead of white. This wouldn't have been visible on GitHub's default theme, but the [dark theme](https://github.com/StylishThemes/GitHub-Dark) that I use made it obvious. This would imply that the newer account's avatar was screenshotted from the site, rather than an original file.

This isn't a "conspiracy", it's pretty obvious at this point that something fishy is going on here, even if they aren't your alt. This, combined with the fact that they haven't really added anything constructive to the issue tracker here as far as I can remember, make me personally want to ban them. That's of course just my opinion, and I don't have the ability to do that - but we'll have to see what TeamSpen thinks about all this.

**Comment by LautaroL20** [comment] 2019-12-09 05:35
Since i decided to voluntarily join this Beemod community in september 2015 (https://github.com/BEEmod/BEE2.4/issues/80)  to participate on different stuff here, a long time has passed since then and i can say that on the way, i got some Steam friend´s requests of unknown people telling me they are "my secret admirers", and crazy stuff like that who do not make much sense. I mean, i would not be surprised if there could be that kind of people who repeat words and characteristic phrases  of those people who they "admire" as ridiculous as it may seem. 

Respect to the user "HelloIamaPersonThatIsAlive", between the few comments i could have ever read about him posting here and at the Discord, i do not remember him personally insulting others or harassing anyone. Of course, TeamSpen210 can ban him anytime if he wanted to, but i do not see a substantial reason to ban an user as long as they don´t break the community rules. This is just my point of view though...

**Comment by Luke18033** [comment] 2019-12-09 19:47
Okay, now you're just making excuses. Admit it, he's your alt. Nobody is so much of a "secret admirer" of another person that they start copying exactly what they say, at least not with random people on the internet like us. Besides, if HelloIAmAPersonThatIsAlive is actually another user, don't you think it's a bit suspicious that they haven't responded to give their own opinion on this at all? If you can find a way to absolutely, 100 percent confirm that he isn't your alt, feel free, but I doubt you'll be able to.
