### ISSUE TITLE
Grating is permeable

### ISSUE THREAD

**Issue by ZombiePwner1** [BEEmod/BEE2-items#1929] opened 2017-05-07 00:57 UTC
Cubes now mysterious go through grating.

![20170507085516_1](https://cloud.githubusercontent.com/assets/18079316/25777041/3056d390-3303-11e7-82c3-8fe9d7dac9a9.jpg)

**Comment by LautaroL20** [comment] 2017-05-07 02:54
From PRL25: 
![Image](https://cloud.githubusercontent.com/assets/12244376/25777570/49963cde-32b7-11e7-83a3-6f39efb6759c.jpg)

**Comment by LautaroL20** [comment] 2017-05-29 14:51
This issue has to do with the Game using old resources from past releases, the guy that did the duplicate of this, added me recently on Steam and we solved this by deleting old stuff from the game and making Beemod re-export full resources again. See discord Off-Topic chat messages for more info.

**Closed by LautaroL20** 2017-05-29 14:51 UTC
Labels: bug, fixed
