### ISSUE TITLE
Empty portal gun pedestals

### ISSUE THREAD

**Issue by mariovct** [BEEmod/BEE2-items#2672] opened 2018-04-29 01:12 UTC
This would be an empty portal gun pedestal until you place your portal gun on-it at witch point you can pick it back up again and sends and output and when you grab it back it doesn't send an output. This could be used in interesting puzzle where for certain sections you don't have your portal gun and you have to find a way you can get it back

**Comment by Nikita74Russian** [comment] 2018-04-29 05:35
Duplicate of my issue.

**Comment by BETTEREXTENEDEDITORMOD** [comment] 2018-04-29 05:36
Why?

**Comment by HugoBDesigner** [comment] 2018-04-29 05:36
Not quite a duplicate. It's an empty podium that gets the gun from you, outputs, then you can grab it back. It's not an upgrade/downgrade podium

**Comment by Nikita74Russian** [comment] 2018-04-29 05:37
Oh.

**Comment by Luke18033** [comment] 2019-12-07 06:01
You can kind of do this with On/Off buttons already, using a setup like this:
![image](https://user-images.githubusercontent.com/19228201/70369552-4ae2c200-1870-11ea-91da-1a6ac49fa560.png)
It's probably kind of hard to tell what's going on here, so let me explain. The pedestal button is connected to the toggle latch, which is connected to the door and the funnel's polarity input. When the button is pressed, the door will open, but reversing the funnel will pull the cube off the On/Off button, deactivating the player's gun. Pressing the button again will reactivate the gun, but close the door. While not visible here, I also have a MIF placed behind the door, to ensure the player can't quickly fire portals through while the door is moving.

**Comment by Konclan** [comment] 2021-08-14 23:57
I believe this is already a UCP

**Closed** 2021-08-14 23:57 UTC
Labels: Enhancement, New Item
