### ISSUE TITLE
Funnel Variant: Fan

### ISSUE THREAD

**Issue by Endermage77** [BEEmod/BEE2-items#1557] opened 2017-02-06 22:58 UTC
This is basically an excursion funnel redone as a very powerful fan.

If <s>the player</s> objects can have acceleration as opposed to steady velocity applied, that would be preferable.

**Comment by Byzarru** [comment] 2017-02-06 23:04
Duplicate of #1137.

**Closed by Byzarru** 2017-02-06 23:04 UTC

**Comment by TheDarkBomber** [comment] 2017-02-07 16:23
Plus, the Fan will be implemented already, as the BP Pack.
