### ISSUE TITLE
1970s Aperture Entry and Exit cause leak

### ISSUE THREAD

**Issue by seagemgames** [BEEmod/BEE2-items#3602] opened 2021-01-20 23:27 UTC
**BEE2 Version:** 4.38.1

The 70s Aperture door causes a leak if it is indented into the wall like this
![image](https://user-images.githubusercontent.com/32136200/105253106-b112cd00-5b76-11eb-9404-6915b50c142d.png)
This is due to a speaker that generates on the tile to the right of the door, which gets cut off and placed in the void in this position.
This happens with both entry, and exit, and I will check if it happens on other Old Aperture styles too.

**Comment by Luke18033** [comment] 2021-01-20 23:30
Duplicate of #3495

**Comment by seagemgames** [comment] 2021-01-20 23:31
Ah, that only specified 50s.

**Closed by Luke18033** 2021-01-20 23:30 UTC
Labels: Bug, Compile Error
