### ISSUE TITLE
Weird Antlines with Slopes

### ISSUE THREAD

**Issue by hop193** [BEEmod/BEE2-items#1660] opened 2017-03-04 14:32 UTC
I like how you were able to put the antline on the slope but seeing the antline also go through the slope (in a way) bothers me a lot.
![20170304104056_1](https://cloud.githubusercontent.com/assets/25728252/23579525/653fe51a-00bd-11e7-8b4e-353709abf34e.jpg)
![20170304104110_1](https://cloud.githubusercontent.com/assets/25728252/23579526/689318b8-00bd-11e7-826f-428e3ae2cfa3.jpg)
![20170224205417_1](https://cloud.githubusercontent.com/assets/25728252/23579529/6d564758-00bd-11e7-9cff-90195d648b35.jpg)

**Comment by Luke18033** [comment] 2017-03-04 16:26
Duplicate of #1458.

**Closed by Luke18033** 2017-03-04 16:26 UTC
