### ISSUE TITLE
60´s Old Aperture DeadlyGoo renders as a leak is back

### ISSUE THREAD

**Issue by epicGamingA** [BEEmod/BEE2-items#4057] opened 2022-01-15 01:12 UTC
i am too dumb to find out how to ask someone to reopen a bug but here is the flie
[goobug.zip](https://github.com/BEEmod/BEE2-items/files/7873990/goobug.zip)

**Comment by LautaroL20** [comment] 2022-01-15 04:05
> epicGamingA said: "i am too dumb to find out how to ask someone to reopen a bug but here is the flie"

Well, you just leave a comment asking someone to re-open the issue, and if I am the first one who reads that comment and if it makes sense, I will open it. Now this is a duplicate of: https://github.com/BEEmod/BEE2-items/issues/4056

**Closed by LautaroL20** 2022-01-15 04:05 UTC
Labels: Duplicate
