### ISSUE TITLE
Standing and reclined fizzlers causes compile error in Old Aperture if frames are over a wall

### ISSUE THREAD

**Issue by ZombiePwner1** [BEEmod/BEE2-items#2451] opened 2018-01-23 06:38 UTC
No center barrier at 1984 320 192, -1 -0 -0
[WARNING] barriers.test_hole_spot(): No center barrier at 1984 192 192, -1 -0 -0
[WARNING] barriers.test_hole_spot(): No center barrier at 1856 192 192, 1 0 0
[INFO] brushes.res_import_template(): IDS: {'1'}
[INFO] cond.scaffold.res_unst_scaffold(): Running Scaffold Generator (BEE2_SCAFFOLD)...
[INFO] cond.scaffold.res_unst_scaffold(): Finished Scaffold generation!
[INFO] cond.vactubes.res_make_vactubes(): Running Generator (BEE2_VACTUBES)...
[INFO] cond.vactubes.res_make_vactubes(): Markers: dict_keys(['vac65', 'vac60'])
[INFO] cond.vactubes.res_make_vactubes(): Outputs: set()
[INFO] cond.vactubes.res_make_vactubes(): Outputs: {'it66825', 'vac65'}
[ERROR] cond.core.check_all(): Error in <LAUTARO_STANDING_RECLINED_FIZZLERS>/items/standing_fizzler_50s:
Traceback (most recent call last):
  File "F:\Git\BEE2.4\src\template_brush.py", line 220, in visgrouped
KeyError: 'black_frame_left_double'

**Comment by LautaroL20** [comment] 2018-01-23 14:58
Can you please writte "developer 2" (without quotes), clear the console then re-build the map to see the detailed log?

**Comment by LautaroL20** [comment] 2018-01-23 15:02
Well, if its what i think then ive found the cause of the issue, now its fixed for next-release 29.

**Comment by LautaroL20** [comment] 2018-02-02 00:50
Now fixed, only happens in Old Aperture if frames are over a wall.

**Closed** 2018-03-29 09:12 UTC
Labels: Compile Error, Fixed, Old Aperture, Portal 1
