### ISSUE TITLE
Suggestion: warning signs/posters etc.

### ISSUE THREAD

**Issue by andremiles1** [BEEmod/BEE2-items#1638] opened 2017-02-28 07:46 UTC
Just for decoration. You can put on your walls different warning signs that changes according the style you're using. That would be fun to use.

1950s Old Aperture style: Repulsion Gel funny signs and/or these "Did You Know?" signs (like this: https://s-media-cache-ak0.pinimg.com/originals/89/7e/2f/897e2f5334c38e9184c542e977e12e66.jpg)
  
1960s Old Aperture style: Vitrification signs and condemned signs.

1970s Old Aperture style: "Know Your..." signs (like this: http://www.notcot.com/images/2011/04/aperture4.jpg)

1980s Old Aperture style: "Remember!" signs (like this: https://s-media-cache-ak0.pinimg.com/originals/82/e6/f1/82e6f1609997b30fd357771f8efb15a2.jpg, and this: https://s-media-cache-ak0.pinimg.com/originals/11/d8/38/11d8386fbf322ab1b7e5a939b59ac091.jpg)

Portal 1 style: Rattman warnings and arrows signs, The cake is a lie.

Clean/Original style: Funny "Robot cowokers" posters (like this: http://www.thinkgeek.com/images/products/additional/large/e918_portal2_poster_kit_num1.jpg) and other warnings about A.I.

BTS: Funny posters about investigations and accidents (like this: http://i.imgur.com/7bPfm.jpg)

Overgrown: Rattman warning/arrows signs, and A.I. warnings.

Hope you guys consider my request.
Thank you. Much love.

**Comment by ZombiePwner1** [comment] 2017-02-28 09:46
The funny Robot coworkers posters are for 80's style since they appear in the conversion gel level when your at the hatch near the modern facility.

**Comment by Byzarru** [comment] 2017-02-28 15:47
Duplicate of #1096.

**Closed** 2017-02-28 15:47 UTC
Labels: Duplicate, Suggestion
