### ISSUE TITLE
Antlines and signage don't transfer to the front of flat or angled blocks

### ISSUE THREAD

**Issue by thesamfizz** [BEEmod/BEE2-items#3796] opened 2021-05-22 21:29 UTC
**BEE2 version:** 4.39.2

**Description of the bug:** Antlines and signage don't transfer to the front of flat or angled blocks.

**Expected behavior:** Per the description of flat blocks and angled blocks, setting "Start Enabled" to true should make antlines and signage transfer to the front of the blocks. For angled blocks, I would expect this means the antline goes across the sloped surface. This doesn't currently work for either--the antlines stay on the wall behind the blocks regardless of whether "Start Enabled" is true or false.

**Steps to reproduce:** Have antlines go behind a flat or angled block, set the block to "Start Enabled" true.

**Additional information:**
Both the flat block and angled block in the screenshot have "Start Enabled" set to true:

![image](https://user-images.githubusercontent.com/83612383/119241166-89327680-bb22-11eb-8479-b356d43bf364.png)

![image](https://user-images.githubusercontent.com/83612383/119241171-92234800-bb22-11eb-9562-946cb8527aea.png)

**Comment by FrozenDragon0** [comment] 2021-05-23 01:14
This would be a duplicate of https://github.com/BEEmod/BEE2-items/issues/3051

Depending on how those blocks are placed the antlines won't generate at all or may generate incorrectly.

**Closed by FrozenDragon0** 2021-05-23 01:14 UTC
Labels: Bug, Duplicate

**Comment by thesamfizz** [comment] 2021-05-23 01:36
Whoops, didn't see that post when I searched.
