### ISSUE TITLE
The Rocket Turrets Rocket Disappears in a "Mysterous Way" in P1 Style

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#1986] opened 2017-05-21 14:25 UTC
Original report by @ZFM2004 - Source: https://github.com/BEEmod/BEE2-items/issues/1983

"The Rocket Turrets Rocket Disappears in Portal 1 Style"

**Comment by Luke18033** [comment] 2017-06-12 00:32
Duplicate of #1984.

**Closed by Luke18033** 2017-06-12 00:32 UTC
Labels: Bug, Portal 1

**Comment by LautaroL20** [comment] 2017-06-12 01:01
@Luke18033 - Do not forget to apply the label.
