### ISSUE TITLE
Coop exit not opening when something is connected to it.

### ISSUE THREAD

**Issue by bleutwo** [BEEmod/BEE2-items#1538] opened 2017-02-04 13:45 UTC
When something is connected to the exit door in Coop mode, the door does not open. The exit door does open when nothing is connected to it. The exit door also appears to have 2 cameras instead of one.

![20170204141448_1](https://cloud.githubusercontent.com/assets/25549100/22618731/700fb89c-eae4-11e6-98a6-f658b3f37ba0.jpg)

**Comment by TheDarkBomber** [comment] 2017-02-04 15:33
The label was `CO-OP` last time I checked...

**Comment by Luke18033** [comment] 2017-02-04 15:35
It still is :)

**Comment by TheDarkBomber** [comment] 2017-02-04 15:36
You just renamed it back. :)

**Comment by LautaroL20** [comment] 2017-02-06 12:39
@TheDarkBomber @Luke18033 - Lol, you guys didn´t notice that this is a duplicate of: https://github.com/BEEmod/BEE2-items/issues/1392

**Closed by LautaroL20** 2017-02-06 12:39 UTC
Labels: Bug, CO-OP, Duplicate
