### ISSUE TITLE
Both types of P1 Co-op Checkpoints are unstyled

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2-items#1800] opened 2017-04-02 22:59 UTC
![20170402155456_1](https://cloud.githubusercontent.com/assets/19228201/24591734/31247784-17bd-11e7-90c9-d0301db7582d.jpg)

**Comment by ZombiePwner1** [comment] 2017-04-02 23:06
This is a duplicate of https://github.com/BEEmod/BEE2-items/issues/640

**Closed by ZombiePwner1** 2017-04-02 23:06 UTC
Labels: Duplicate, Portal 1, Unstyled Item

**Comment by Luke18033** [comment] 2017-04-02 23:10
That's specifically referring to the normal version though.

**Comment by ZombiePwner1** [comment] 2017-04-02 23:17
@Luke18033 It's still a duplicate.
