### ISSUE TITLE
Faith-Plate Target Refusing To Intersect

### ISSUE THREAD

**Issue by gradeabeef** [BEEmod/BEE2-items#3811] opened 2021-06-03 05:54 UTC
Hi,
The faith-plate placeable target in the editor is unable to intersect objects, and thus makes base-game editor faith-plate chaining impossible. Camera targets, as they use a similar element, also cannot focus on a face that is not occupied.
![faithplateissuereport1](https://user-images.githubusercontent.com/85274463/120594162-6000c880-c3f5-11eb-8573-39ed5731269b.png)
![faithplateissuereport2](https://user-images.githubusercontent.com/85274463/120594169-63944f80-c3f5-11eb-84d3-98e6a82df2f6.png)
Version: 1.39.1
Package: 1.39.1
-GAB

**Comment by FrozenDragon0** [comment] 2021-06-03 07:37
Duplicate of https://github.com/BEEmod/BEE2-items/issues/3674

**Closed by FrozenDragon0** 2021-06-03 07:37 UTC
Labels: Duplicate
