### ISSUE TITLE
Teleportation Displacement Field

### ISSUE THREAD

**Issue by Byzarru** [BEEmod/BEE2-items#1251] opened 2016-12-22 03:19 UTC
Would it be possible to implement the Teleportation Displacement Field from PS:VR as a fizzler that lets all objects and players through, but blocks portals?

**Comment by TheDarkBomber** [comment] 2016-12-22 20:13
Yes, very possible.

**Comment by Byzarru** [comment] 2016-12-23 05:12
Then, might it be implemented? That beautiful red hexagonal field.

**Comment by ellingtonvengaboysmuseum** [comment] 2016-12-23 20:52
there would be no purpose for portal stories vr's field it in the regular portal 2 because the player can't teleport, also there already is a modded field like this. @TeamSpen210 or @LautaroL20 - please close this, this item is not possible without valve's VR headset

**Comment by TeamSpen210** [comment] 2016-12-23 20:53
It'd be a fizzler which blocks portal shots and resets the gun, that's all.

**Comment by Konclan** [comment] 2016-12-23 21:51
This is a duplicate of #475

**Comment by Byzarru** [comment] 2016-12-23 21:57
Not necessarily, as that was a fizzler idea you had and this is a fizzler featured in a mod.

**Comment by Konclan** [comment] 2021-08-15 04:10
We don't need more fields

**Closed by Konclan** 2021-08-15 04:10 UTC
Labels: New Item
