### ISSUE TITLE
New Player Detector Item

### ISSUE THREAD

**Issue by hop193** [BEEmod/BEE2-items#1686] opened 2017-03-09 22:14 UTC
I forgot what it was called, but if the player would pass through the field, it would send an output connection. If the player were to pass through it again, it would deactivate the output connection. It could also have a 'Start Enabled' tick box, to choose whether it starts sending an output connection or not. I've found it in a hack called Portal Pro, and I'll show you an image now:
![20170304171331_1](https://cloud.githubusercontent.com/assets/25728252/23773116/ccb5f1f8-04eb-11e7-99f3-4ff0c9f86f84.jpg)
This shows it deactivated.
![20170304171459_1](https://cloud.githubusercontent.com/assets/25728252/23773789/cb6a83e2-04ee-11e7-9e94-91203f237d1d.jpg)
This shows it activated.

**Comment by Byzarru** [comment] 2017-03-09 23:17
Duplicate of #1529.

**Closed** 2017-03-09 23:17 UTC
Labels: Duplicate, New Item
