### ISSUE TITLE
Portalgun Pedestal in Portal 1 Style causes Compile Errors

### ISSUE THREAD

**Issue by blocker2225** [BEEmod/BEE2-items#3814] opened 2021-06-04 18:39 UTC
VBSP failed.

[I] vbsp.main(): BEE2 v4.39.1 VBSP hook initiallised.
[I] cond.core.import_conditions(): Imported all conditions modules!
[I] vbsp.main(): Map path is "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf"
[I] vbsp.main(): New path: "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[I] vbsp.main(): PeTI map detected!
[I] vbsp.main(): Loading settings...
[W] texturing.load_config(): overlays: Unknown texture names faithfling, faithland
[W] options.load(): Extra config options: {'remove_pedestal_plat': '1', 'voice_pack': 'BEE2_GLADOS_CLEAN'}
[I] cubes.parse_conf(): Parsed 7 cube types, 1 dropper types and 4 addons.
[I] fizzler.read_configs(): Loaded 14 fizzlers.
[I] vbsp.load_settings(): Settings Loaded!
[I] vbsp.load_map(): Parsing Map...
[I] vbsp.load_map(): Reading Map...
[I] vbsp.load_map(): Loading complete!
[I] antlines.parse_antlines(): Parsing antlines...
[I] antlines.parse_antlines(): Done! (1 antlines)
[I] vbsp.get_map_info(): Forcing elevator spawn!
[I] vbsp.mod_entryexit(): Setting Coop Exit to 1
[I] vbsp.get_map_info(): Game Mode: COOP
[I] vbsp.get_map_info(): Is Preview: False
[I] brushLoc.read_from_map(): Analysed map, filling air... (11 starting positions..)
[I] brushLoc.read_from_map(): Air filled!
[I] cond.core.check_all(): Checking Conditions...
[I] cond.core.check_all(): -----------------------
[I] cubes.link_cubes(): SPLAT File: ['instances/bee2/logic/gel_splat.vmf']
[I] cond.catwalks.res_make_catwalk(): Starting catwalk generator...
[I] cond.scaffold.res_unst_scaffold(): Running Scaffold Generator (BEE2_SCAFFOLD)...
[I] cond.scaffold.res_unst_scaffold(): Finished Scaffold generation!
[W] instanceLocs.get_subitems(): Invalid custom instance name - "tim_start" for <item_bee2_scaffold_slot> (Valid: {'bee2_tim_starVBSP failed.

[I] vbsp.main(): BEE2 v4.39.1 VBSP hook initiallised.
[I] cond.core.import_conditions(): Imported all conditions modules!
[I] vbsp.main(): Map path is "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf"
[I] vbsp.main(): New path: "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[I] vbsp.main(): PeTI map detected!
[I] vbsp.main(): Loading settings...
[W] texturing.load_config(): overlays: Unknown texture names faithfling, faithland
[W] options.load(): Extra config options: {'remove_pedestal_plat': '1', 'voice_pack': 'BEE2_GLADOS_CLEAN'}
[I] cubes.parse_conf(): Parsed 7 cube types, 1 dropper types and 4 addons.
[I] fizzler.read_configs(): Loaded 14 fizzlers.
[I] vbsp.load_settings(): Settings Loaded!
[I] vbsp.load_map(): Parsing Map...
[I] vbsp.load_map(): Reading Map...
[I] vbsp.load_map(): Loading complete!
[I] antlines.parse_antlines(): Parsing antlines...
[I] antlines.parse_antlines(): Done! (1 antlines)
[I] vbsp.get_map_info(): Forcing elevator spawn!
[I] vbsp.mod_entryexit(): Setting Coop Exit to 1
[I] vbsp.get_map_info(): Game Mode: COOP
[I] vbsp.get_map_info(): Is Preview: False
[I] brushLoc.read_from_map(): Analysed map, filling air... (11 starting positions..)
[I] brushLoc.read_from_map(): Air filled!
[I] cond.core.check_all(): Checking Conditions...
[I] cond.core.check_all(): -----------------------
[I] cubes.link_cubes(): SPLAT File: ['instances/bee2/logic/gel_splat.vmf']
[I] cond.catwalks.res_make_catwalk(): Starting catwalk generator...
[I] cond.scaffold.res_unst_scaffold(): Running Scaffold Generator (BEE2_SCAFFOLD)...
[I] cond.scaffold.res_unst_scaffold(): Finished Scaffold generation!
[W] instanceLocs.get_subitems(): Invalid custom instance name - "tim_start" for <item_bee2_scaffold_slot> (Valid: {'bee2_tim_start': 'instances/BEE2/clean/items/scaffold/tim_start.vmf'})
[I] cond.scaffold.res_unst_scaffold(): Running Scaffold Generator (BEE2_SCAFFOLD)...
[I] cond.scaffold.res_unst_scaffold(): Finished Scaffold generation!
[I] cond.scaffold.res_unst_scaffold(): Running Scaffold Generator (BEE2_SCAFFOLD)...
[I] cond.scaffold.res_unst_scaffold(): Finished Scaffold generation!
[W] cond.vactubes.get_temp(): Invalid template "BEE2_VACTUBE_CORNER_CLEAN:small" for vactube group BEE2_VACTUBES!
[W] cond.vactubes.get_temp(): Invalid template "BEE2_VACTUBE_CORNER_CLEAN:medium" for vactube group BEE2_VACTUBES!
[W] cond.vactubes.get_temp(): Invalid template "BEE2_VACTUBE_CORNER_CLEAN:large" for vactube group BEE2_VACTUBES!
[I] connections.gen_item_outputs(): Generating item IO...
[I] connections.gen_item_outputs(): Item IO generated.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE_PGUN_BASE", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE_PGUN_BASE", which is no longer used.
[E] cond.core.check_all(): Error in <Item ITEM_BEE2_PORTALGUN all_conf>:
Traceback (most recent call last):
  File "precomp\conditions\__init__.py", line 511, in check_all
  File "precomp\conditions\__init__.py", line 300, in test
  File "precomp\conditions\__init__.py", line 289, in test_result
  File "<string>", line 1, in <lambda>
  File "precomp\conditions\__init__.py", line 1092, in res_sub_condition
  File "precomp\conditions\__init__.py", line 300, in test
  File "precomp\conditions\__init__.py", line 289, in test_result
  File "precomp\conditions\brushes.py", line 108, in res_fix_rotation_axis
TypeError: type srctools._math.Matrix doesn't define __round__ method

t': 'instances/BEE2/clean/items/scaffold/tim_start.vmf'})
[I] cond.scaffold.res_unst_scaffold(): Running Scaffold Generator (BEE2_SCAFFOLD)...
[I] cond.scaffold.res_unst_scaffold(): Finished Scaffold generation!
[I] cond.scaffold.res_unst_scaffold(): Running Scaffold Generator (BEE2_SCAFFOLD)...
[I] cond.scaffold.res_unst_scaffold(): Finished Scaffold generation!
[W] cond.vactubes.get_temp(): Invalid template "BEE2_VACTUBE_CORNER_CLEAN:small" for vactube group BEE2_VACTUBES!
[W] cond.vactubes.get_temp(): Invalid template "BEE2_VACTUBE_CORNER_CLEAN:medium" for vactube group BEE2_VACTUBES!
[W] cond.vactubes.get_temp(): Invalid template "BEE2_VACTUBE_CORNER_CLEAN:large" for vactube group BEE2_VACTUBES!
[I] connections.gen_item_outputs(): Generating item IO...
[I] connections.gen_item_outputs(): Item IO generated.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE_PGUN_BASE", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE_PGUN_BASE", which is no longer used.
[E] cond.core.check_all(): Error in <Item ITEM_BEE2_PORTALGUN all_conf>:
Traceback (most recent call last):
  File "precomp\conditions\__init__.py", line 511, in check_all
  File "precomp\conditions\__init__.py", line 300, in test
  File "precomp\conditions\__init__.py", line 289, in test_result
  File "<string>", line 1, in <lambda>
  File "precomp\conditions\__init__.py", line 1092, in res_sub_condition
  File "precomp\conditions\__init__.py", line 300, in test
  File "precomp\conditions\__init__.py", line 289, in test_result
  File "precomp\conditions\brushes.py", line 108, in res_fix_rotation_axis
TypeError: type srctools._math.Matrix doesn't define __round__ method

**Comment by LautaroL20** [comment] 2021-06-04 19:17
This is a duplicate of: https://github.com/BEEmod/BEE2-items/issues/3667

**Closed by LautaroL20** 2021-06-04 19:17 UTC
Labels: Compile Error, Duplicate
