### ISSUE TITLE
Game errors with floor/ceiling obs rooms in overgrown

### ISSUE THREAD

**Issue by Endermage77** [BEEmod/BEE2-items#1502] opened 2017-01-26 22:54 UTC
The small observation rooms, when placed on the floor or ceiling, with an Overgrown style, causes the game to throw a "There was an error building the puzzle."

**Comment by Luke18033** [comment] 2017-01-26 23:12
Duplicate of #1423.

**Closed by Luke18033** 2017-01-26 23:12 UTC
