### ISSUE TITLE
P1 Style: Void Leak by Camera

### ISSUE THREAD

**Issue by Shards-Box** [BEEmod/BEE2-items#3767] opened 2021-05-02 06:03 UTC
Thanks to: @Luke18033#2342 & @Rolo#3120 on the discord with help regarding this issue

Attached below is images of an Orange Portal breaking space-time.

![20210502021947_1](https://user-images.githubusercontent.com/83502177/116804021-18d1a000-aaf6-11eb-8a23-a11bafadb17b.jpg)
![20210502022719_1](https://user-images.githubusercontent.com/83502177/116804019-14a58280-aaf6-11eb-9f6b-43876f269872.jpg)

How is this happening you might ask? because a camera is rendered within the void

To Reproduce:
1: Load Portal 1 Style
2: Use Doorless Entrance & Exit
3: Move exit into a player walkway (Pictured under: To Fix) while having portals placed a distance away from you and behind a wall
4: Compile Map 
5: Place portals, walk behind a wall and find the angle while the exit is close to you (exit behind you not within view)
6: See the render show

This is due to the Camera at the exit being rendered within the void.
![image](https://user-images.githubusercontent.com/83502177/116804070-7b2aa080-aaf6-11eb-836d-fec39d4b2be1.png)

To fix, either:
1. Disable Door Cameras
2. Don't have a solid block above the exit
![image](https://user-images.githubusercontent.com/83502177/116804112-cf358500-aaf6-11eb-8f47-0049f99589b9.png)

Not sure if this is a Compiler Error since you can play the level but it is something to take note of

**Comment by Luke18033** [comment] 2021-05-02 06:11
Disabling doorless exit doesn't stop the leak, it just causes those worldportals to close so there's no indication that the leak is there.

**Comment by Luke18033** [comment] 2021-05-02 06:19
Also see #3495, this is sort of a duplicate of that. I think the reason these things happen is because of the embed box there, it might be considered a solid surface for the camera to attach to even though it's outside the map.

**Closed** 2021-11-16 07:33 UTC
Labels: Bug, Portal 1, Done
