### ISSUE TITLE
Portal Gun Activation Fields

### ISSUE THREAD

**Issue by MarcusKubis9** [BEEmod/BEE2-items#3636] opened 2021-02-11 22:10 UTC
the portal gun deactivator/activator would be like the paint gun deactivator/activator but for portals

you could make it so you have a blue portal gun then it switches to an orange portal gun

now for the new portal gun pedestal items

The first one: fake portal gun pedestal it would be like the portal gun pedestal but it has no portal gun in it

The second one: no portal gun it would be like the portal gun but with no portals so it would act like a troll portal gun

**Comment by Konclan** [comment] 2021-08-14 23:07
Duplicate of #2561

**Closed by Konclan** 2021-08-14 23:07 UTC
Labels: New Item
