### ISSUE TITLE
Logic gates showing up as missing texture on the side pannel

### ISSUE THREAD

**Issue by KingMonkeyBug** [BEEmod/BEE2-items#4412] opened 2024-02-24 19:55 UTC
### BEE2 Application Version

4.44.1 64bit

### BEE2 Package Version

4.40.0

### What operating system are you running on?

Windows 11

### Description of the bug

I installed BEE2 for like the 10th time but the logic gates icon is just a missing texture
![image](https://github.com/BEEmod/BEE2-items/assets/146986052/cf8f8dc8-60b1-4b38-9b8e-b2add126931d)

### Expected behavior

I expected for the logic gates icon be normal but you know, source spaggeti

### Steps to reproduce

I have no idea what i did for it to happen

### Additional information

Im using the default style (Clean)

**Comment by vrad-exe** [comment] 2024-02-25 00:11
Duplicate of #4403

**Closed by vrad-exe** 2024-02-25 00:11 UTC
Labels: Bug
