### ISSUE TITLE
New Stylevar to remove entry and exit corridors

### ISSUE THREAD

**Issue by ellingtonvengaboysmuseum** [BEEmod/BEE2-items#2355] opened 2017-11-01 13:28 UTC
i had this idea - if even possible, a New Stylevar that removes the entry and exit corridors and links the elevators directly to the map... i got the idea because of the idea of building custom entry and exit corridors... the only new item we need for this is test chamber signage which can be placed in the test chamber itself...

**Comment by BETTEREXTENEDEDITORMOD** [comment] 2017-11-01 20:26
Duplicate of #2283

**Comment by Luke18033** [comment] 2017-11-01 20:55
More specifically #605, the issue which yours was also a duplicate of. See [TeamSpen210's comment](https://github.com/BEEmod/BEE2-items/issues/605#issuecomment-230186306) for why it won't be added.

**Closed by Luke18033** 2017-11-01 20:55 UTC
