### ISSUE TITLE
Rotating Light Bridge

### ISSUE THREAD

**Issue by PieCreeper12** [BEEmod/BEE2-items#3563] opened 2020-11-21 05:29 UTC
I have a new item idea for BEE2. It is a rotating light bridge. A rotating light bridge can switch from normal to sideways by changing its polarity. Starting it as reversed will make it start sideways.

**Comment by Luke18033** [comment] 2020-11-21 05:30
Duplicate of #2368

**Closed by Luke18033** 2020-11-21 05:30 UTC
Labels: New Item
