### ISSUE TITLE
Portal magnet cause compile error

### ISSUE THREAD

**Issue by RustyNova016** [BEEmod/BEE2-items#3669] opened 2021-02-28 20:08 UTC
**BEE2 Version: 3.9.2**

<details>
<summary>Error Log</summary>
VBSP failed.

[I] vbsp.main(): BEE2 v4.39.1 VBSP hook initiallised.
[I] cond.core.import_conditions(): Imported all conditions modules!
[I] vbsp.main(): Map path is "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf"
[I] vbsp.main(): New path: "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[I] vbsp.main(): PeTI map detected!
[I] vbsp.main(): Loading settings...
[W] texturing.load_config(): Could not parse texture generator type "bullsye.white.floor"!
[W] texturing.load_config(): overlays: Unknown texture names faithfling, faithland
[W] texturing.load_config(): special: Unknown texture names edge_special, pedestalside
[W] options.load(): Extra config options: {'glass_scale': '0.15', 'staticpan': 'instances/BEE2/clean/static_panel/', 'voice_pack': 'BEE2_GLADOS_CLEAN'}
[I] cubes.parse_conf(): Parsed 7 cube types, 1 dropper types and 4 addons.
[I] fizzler.read_configs(): Loaded 14 fizzlers.
[I] vbsp.load_settings(): Settings Loaded!
[I] vbsp.load_map(): Parsing Map...
[I] vbsp.load_map(): Reading Map...
[I] vbsp.load_map(): Loading complete!
[I] antlines.parse_antlines(): Parsing antlines...
[I] antlines.parse_antlines(): Done! (0 antlines)
[I] vbsp.get_map_info(): Forcing elevator spawn!
[I] vbsp.mod_entryexit(): Setting SP Entry to 7
[I] vbsp.mod_entryexit(): Setting SP Exit to 1
[I] vbsp.get_map_info(): Game Mode: SP
[I] vbsp.get_map_info(): Is Preview: False
[I] brushLoc.read_from_map(): Analysed map, filling air... (12 starting positions..)
[I] brushLoc.read_from_map(): Air filled!
[I] cond.core.check_all(): Checking Conditions...
[I] cond.core.check_all(): -----------------------
[I] cubes.link_cubes(): SPLAT File: ['instances/bee2/logic/gel_splat.vmf']
[I] cond.catwalks.res_make_catwalk(): Starting catwalk generator...
[I] cond.scaffold.res_unst_scaffold(): Running Scaffold Generator (BEE2_SCAFFOLD)...
[I] cond.scaffold.res_unst_scaffold(): Finished Scaffold generation!
[W] instanceLocs.get_subitems(): Invalid custom instance name - "tim_start" for <item_bee2_scaffold_slot> (Valid: {'bee2_tim_start': 'instances/BEE2/clean/items/scaffold/tim_start.vmf'})
[I] cond.scaffold.res_unst_scaffold(): Running Scaffold Generator (BEE2_SCAFFOLD)...
[I] cond.scaffold.res_unst_scaffold(): Finished Scaffold generation!
[I] cond.scaffold.res_unst_scaffold(): Running Scaffold Generator (BEE2_SCAFFOLD)...
[I] cond.scaffold.res_unst_scaffold(): Finished Scaffold generation!
[W] cond.vactubes.get_temp(): Invalid template "BEE2_VACTUBE_CORNER_CLEAN:small" for vactube group BEE2_VACTUBES!
[W] cond.vactubes.get_temp(): Invalid template "BEE2_VACTUBE_CORNER_CLEAN:medium" for vactube group BEE2_VACTUBES!
[W] cond.vactubes.get_temp(): Invalid template "BEE2_VACTUBE_CORNER_CLEAN:large" for vactube group BEE2_VACTUBES!
[I] connections.gen_item_outputs(): Generating item IO...
[I] connections.gen_item_outputs(): Item IO generated.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE_PGUN_BASE", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE_PGUN_BASE", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_ANGLED_BLOCK_60", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_ANGLED_BLOCK_45", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_ANGLED_BLOCK_30", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_ANGLED_BLOCK_CORNER_60", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_ANGLED_BLOCK_CORNER_60", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_ANGLED_BLOCK_CORNER_45", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_ANGLED_BLOCK_CORNER_45", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_ANGLED_BLOCK_CORNER_30", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_ANGLED_BLOCK_CORNER_30", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_FLAT_QUARTER", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_FLAT_HALF", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_FLAT_THREE_QUARTER", which is no longer used.
[E] cond.core.check_all(): Error in <HMW_MOD>/items/portal_magnet:
Traceback (most recent call last):
  File "precomp\conditions\__init__.py", line 511, in check_all
  File "precomp\conditions\__init__.py", line 300, in test
  File "precomp\conditions\__init__.py", line 289, in test_result
  File "<string>", line 1, in <lambda>
  File "precomp\conditions\__init__.py", line 1092, in res_sub_condition
  File "precomp\conditions\__init__.py", line 300, in test
  File "precomp\conditions\__init__.py", line 289, in test_result
  File "<string>", line 1, in <lambda>
  File "precomp\conditions\__init__.py", line 1092, in res_sub_condition
  File "precomp\conditions\__init__.py", line 300, in test
  File "precomp\conditions\__init__.py", line 289, in test_result
  File "<string>", line 1, in <lambda>
  File "precomp\conditions\brushes.py", line 922, in res_add_placement_helper
  File "precomp\tiling.py", line 1367, in add_portal_helper
ValueError: ('Portal orient of {} is not flat on a plane with normal of {}!', Vec(0, 6.12323e-17, 1), Vec(-0, -1, -0))

</details>

**Additional information: My portal magnet is like this: 
![image](https://user-images.githubusercontent.com/50844553/109431890-fd201f80-7a08-11eb-8805-4bc632caefc2.png)
**

**Comment by DrMeepster** [comment] 2021-03-14 23:11
This is probably caused by cosine of 90 degrees being calculated somewhere. I think this could be fixed by rounding numbers slightly

**Closed** 2021-11-16 08:06 UTC
Labels: Compile Error, Done
