### ISSUE TITLE
Drawbridge does not work in Portal 1 style

### ISSUE THREAD

**Issue by cartman1337** [BEEmod/BEE2-items#2477] opened 2018-02-01 15:09 UTC
`Could not open instance file instances/BEE2/p1/items/bee/drawbridge/black.vmf`
`Could not open instance file instances/BEE2/p1/items/bee/drawbridge/white.vmf`

**Comment by Luke18033** [comment] 2019-09-24 02:35
Duplicate of #1933

**Closed by Luke18033** 2019-09-24 02:35 UTC
Labels: Compile Error, Portal 1
