### ISSUE TITLE
water level control, or the acid slurry

### ISSUE THREAD

**Issue by I-love-bee-2** [BEEmod/BEE2-items#1199] opened 2016-12-14 14:25 UTC

**Comment by Luke18033** [comment] 2016-12-14 16:40
What?

**Comment by TheDarkBomber** [comment] 2016-12-14 16:43
Water level control.

**Comment by Luke18033** [comment] 2016-12-14 16:46
@I-love-bee-2 If you are referring to Goo which can be filled or drained, then this is a duplicate of #584.

**Comment by I-love-bee-2** [comment] 2016-12-14 16:48
this element will be added?

**Comment by TheDarkBomber** [comment] 2016-12-14 16:49
Maybe????????????????????????????????????????????**???????????????**

**Comment by I-love-bee-2** [comment] 2016-12-14 16:51
@TheDarkBomber When draining slurry occurs dirty wall must be

**Comment by LautaroL20** [comment] 2016-12-14 16:59
@Luke18033 - Nope, its not a duplicate..... With "water level control" he probably means a static resizeable version of Deadly Goo from a 1/4 or 2/4 of a block.

**Comment by TheDarkBomber** [comment] 2016-12-14 17:00
@LautaroL20 Probably.

**Comment by Luke18033** [comment] 2016-12-17 01:23
@I-love-bee-2 I don't understand what this suggestion is supposed to be...what does "water level control" refer to? If it refers to drainable/fillable goo, then this is a duplicate of #584. If it refers to multiple water levels within a block, could you explain that?

**Comment by Luke18033** [comment] 2019-02-17 21:51
This suggestion is incredibly vague and hasn't been touched in over 2 years, so I'm going to close it.

**Closed by Luke18033** 2019-02-17 21:51 UTC
Labels: Enhancement
