### ISSUE TITLE
Give a light strip input

### ISSUE THREAD

**Issue by Nikita74RU** [BEEmod/BEE2-items#2608] opened 2018-03-31 17:23 UTC
Make light strip to accept input to turn on and off.
May be usefull to make a shutdown effect.

**Comment by Luke18033** [comment] 2018-03-31 17:36
Duplicate of #333. Please stop opening duplicate issues, it's not that hard to do a search.

**Comment by Nikita74RU** [comment] 2018-03-31 17:36
I am not to blame, that i didnt see it.

**Closed by Luke18033** 2018-03-31 17:36 UTC
