### ISSUE TITLE
P1 exit signage clips through low ceiling

### ISSUE THREAD

**Issue by Lieutenant-L-T-Smash** [BEEmod/BEE2-items#3734] opened 2021-04-05 17:01 UTC
Create a chamber in P1 style. Place the exit door directly below the ceiling. The exit signage (running man + arrow) will exist mostly above the ceiling tile (visible with noclip). Only a small portion of the frame will be visible within the normal map.

Expected behavior: Exit signage should automatically move to the side of the door if there is no room above it. (This shows correctly in the editor, but not in the generated map.)

BEE2 version: 4.39.2

**Comment by Lieutenant-L-T-Smash** [comment] 2021-04-28 21:55
Just found out this can cause leaks due to the signage being outside the map.

**Comment by Luke18033** [comment] 2021-04-28 22:16
Duplicate of #969

**Closed by Luke18033** 2021-04-28 22:16 UTC
Labels: Bug
