### ISSUE TITLE
Cutout tile causes massive leaks!!!! In entry hallway and goo pits.......

### ISSUE THREAD

**Issue by TheManOfGan** [BEEmod/BEE2-items#2441] opened 2018-01-13 02:09 UTC
This happened once when I had a bumble ball in the chamber. Now I don't, but the issue is back so...
![door1](https://user-images.githubusercontent.com/24685304/34901763-d0a60818-f7c3-11e7-9918-a2aaeaff98b2.jpg)
![door2](https://user-images.githubusercontent.com/24685304/34901765-d22587d6-f7c3-11e7-89ec-a6f843cc47b7.jpg)
![goo](https://user-images.githubusercontent.com/24685304/34901766-d37cfb64-f7c3-11e7-8800-a7efaa203873.jpg)

**Comment by LautaroL20** [comment] 2018-01-13 18:03
Try removing the cutout tile item entirely from your map, and see if the leak stop. I had same issues in the DeadlyGoo pits when i used the cutout tile item but removing it solved the problem. Seriously, the item really needs to get a revision since its leaking all maps.

**Comment by TheManOfGan** [comment] 2018-01-13 19:28
So, after I put this issue up, I continued to build my map, and the leaks stopped; there are still cutout tiles in the map. However, I do have another map, which never had cutout tiles, and has these leaks.

**Comment by LautaroL20** [comment] 2018-01-13 19:43
When using BEE2.4 after installing a new version, old resources from past releases will not be overwritten, resulting in bugs that were fixed still being present and some things not working correctly. Your issue clearly seems te be related to this, so in order to solving this annoyance, you will have to do the following:

1 - Open Beemod and click on: `File ----> Uninstall From Selected Game ----> "Are you sure you want to delete "PORTAL 2"? ----> YES`.

2 - Wait 1 minute while Beemod removes their resources from Portal 2.

3 - Verify the Game Cache Files. 

4 - Make sure to have downloaded and unzipped the latest Item's Packages and Application version of BEE2.4, and both must be from the same Pre-Release Version, otherwise bugs may occur. Links:

https://github.com/BEEmod/BEE2.4/releases (Application) 
https://github.com/BEEmod/BEE2-items/releases (Item's Packages)

Note that if you are running Beemod on Linux or Mac Os X, issues can occur. Beemod currently works well only on Windows 7, 8 and 10.

5 - Click on: `File ----> Options ----> Development`, then uncheck the option: `Preserve Game Directories`.

6 - Now choose your favorite Items & Style and export your palette to the game.

7 - Make sure to save these steps in a text file in case you get similar issues in the future.

8 - Happy mapmaking!

**Comment by TheManOfGan** [comment] 2018-01-13 20:03
I did this like a week ago, and again right now, but same leaks happen.

**Comment by LautaroL20** [comment] 2018-01-13 20:32
However, keep these steps for when a next pre release is available, it will ensure to make it work well.

**Comment by Luke18033** [comment] 2020-07-09 03:35
Duplicate of #1700

**Closed by Luke18033** 2020-07-09 03:35 UTC
Labels: Bug, Leak
