### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by IceTudor** [BEEmod/BEE2-items#2253] opened 2017-10-07 19:26 UTC
Alright, I'm sorta new to the site and suck at coding and hammer, but I do have some suggestions (and a bug)

~Adhesion Gel: If you can create this, it would be a PERFECT addition to BEEmod, could be a subtype of the reflection gel item, could have a spilled can on a wall as the icon.~

Hit Button: A button that can be placed on walls, when hit at with great force (about how much it takes to break monitors), it activates for a period of time (Infinity - 30 sec). It would look like a square (like a 
regular button, but square, not the cube receptacle) button on a wall.

~Portal Reset~ Bullet Ricochet Field: All it does is ~fizzle your portals~ block bullets, it would have a navy color.

Bug: Portals in P1 Style bug out objects, they get stuck inside them and get launched at high speeds if they get out

**Comment by Axolotlus** [comment] 2017-10-07 20:01
These should really be separate issues, as it would be easier for the devs to label progress. Also, the bug seems to be a duplicate of #2248.

**Comment by ZombiePwner1** [comment] 2017-10-07 22:59
Adhesion gel can't be made in the puzzlemaker due to the way people have re-made it.

**Comment by BETTEREXTENEDEDITORMOD** [comment] 2017-10-07 23:20
how much force would it take to activate a hit button? you could use timer value to measure in hammer units

**Comment by BETTEREXTENEDEDITORMOD** [comment] 2017-10-07 23:23
how much force would it take to activate a hit button? you could measure the speed by using hammer units with timer value

**Comment by Luke18033** [comment] 2017-10-08 00:11
1. Can't be implemented, see [FAQ: Can you add Adhesion Gel to BEE2.4?](https://github.com/BEEmod/BEE2-items/wiki/FAQ#can-you-add-adhesion-gel-to-bee24)
2. This is possible, but I'm not sure how useful it would be.
3. This is possible, although we'd need to make it also block portal shots to work correctly.

For that bug, does it happen only with portals on angled panels or just anywhere?

**Comment by IceTudor** [comment] 2017-10-08 08:22
@Luke18033 
1. Aw, could've been awesome, tho could you still create something like panels you stick to?
2. Kinda useful actually, I always tried to make tests like that
3. Wait why though? The matter inquisition field blocks portals but doesn't fizzle them, can it not be done vice-versa?

For the bug, it happens ANYWHERE, it's quite annoying, no idea why it happens

**Comment by TeamSpen210** [comment] 2017-10-08 08:25
The fizzler entity always blocks your portals, no matter what you set.

**Comment by IceTudor** [comment] 2017-10-08 11:33
Huh, maybe a fizzler that only blocks bullets then, that seems useful actually, much more than the block portals one, yeah that's better

**Comment by IceTudor** [comment] 2017-10-10 14:47
Also, can custom light-bridges be made or is it just not possible?

**Comment by TeamSpen210** [comment] 2017-10-10 20:11
No.

**Comment by IceTudor** [comment] 2017-10-17 08:04
Darn. By the way, what's wrong with the Rocket Sentry and Closed solid field? Both are incredibly broken, rendering too.

**Comment by TeamSpen210** [comment] 2019-03-09 04:18
These aren't going to happen I don't think.

**Closed by TeamSpen210** 2019-03-09 04:18 UTC
