### ISSUE TITLE
A mysterious "nodraw triangle" is being produced in the brush from some items.

### ISSUE THREAD

**Issue by Komos63** [BEEmod/BEE2-items#4025] opened 2021-11-26 13:47 UTC
### BEE2 Application Version

4.41.0 64bit

### BEE2 Package Version

4.41.0

### What operating system are you running on?

Windows 10 (64bit)

### Description of the bug

A weird nodraw triangle is being produced in the brush face from some items like Stairs, Floor Buttons and Adjustable Pedestal Buttons, here are some screenshots:

Adjustable Pedestal Buttons: ![20220118180846_1](https://user-images.githubusercontent.com/78902172/149985864-cca57bfa-b767-4373-a263-6e6b9f1e8b8c.jpg)

Floor buttons: ![Floor button triangle nodraw](https://user-images.githubusercontent.com/12244376/152565207-11a6a647-054e-4a55-9e77-62b9581074ca.png)

Stairs: ![Image](https://user-images.githubusercontent.com/12244376/143929879-d3a53780-585b-45a4-a305-68d5fb150bee.jpg)
![20211126144321_1](https://user-images.githubusercontent.com/78902172/143590472-8be68f93-3289-4dbf-a365-fbaf23739d7c.jpg)

**Comment by FrozenDragon0** [comment] 2021-11-26 13:53
Seems like the texture there was replaced with a Nodraw texture on accident.

**Comment by Luke18033** [comment] 2021-11-29 16:34
This is weird, why is only that one triangle nodraw? Seems like a compiler bug maybe.

**Comment by LautaroL20** [comment] 2021-11-29 19:35
Tested this and it seems that it only happens when the static stair is white, and the nodraw triangle is not being generated in a specific step of the stair, but it can be generated in any of them as showin in this screenshot:

![Image](https://user-images.githubusercontent.com/12244376/143929879-d3a53780-585b-45a4-a305-68d5fb150bee.jpg)

**Comment by Luke18033** [comment] 2021-11-29 19:47
Can you open the map in Hammer, check if there are any nodraw brushes there?

**Comment by LautaroL20** [comment] 2021-11-29 20:04
I opened `preview.vmf` and I did not manage to see any issues, here is an image:

![Preview vmf](https://user-images.githubusercontent.com/12244376/143934726-f762eb60-32aa-45ac-84b3-f9b0a1a3d179.png)

**Comment by RobinRattus** [comment] 2022-01-18 17:15
Found out Adjustable Pedestal Buttons have visible nodraw too
![20220118180846_1](https://user-images.githubusercontent.com/78902172/149985864-cca57bfa-b767-4373-a263-6e6b9f1e8b8c.jpg)

**Comment by LautaroL20** [comment] 2022-01-18 20:44
Something wrong is happening with the compiler...

**Comment by LautaroL20** [comment] 2022-02-04 16:38
A person from the BEEmod discord has confirmed that this issue is also being produced in the Floor Button´s base, so we can confirm that this not noly affects Stairs or the Adjustable Pedestal base. Screenshot:

![Floor button triangle nodraw](https://user-images.githubusercontent.com/12244376/152565207-11a6a647-054e-4a55-9e77-62b9581074ca.png)

**Comment by TeamSpen210** [comment] 2022-02-04 20:03
I expect it's happening with any item, no idea why though.

**Comment by Luke18033** [comment] 2023-01-19 08:10
Fixed in HammerAddons 2.5.2

**Comment by LautaroL20** [comment] 2023-01-19 09:40
> Fixed in HammerAddons 2.5.2

So, what was the cause of this weird issue?

**Comment by TeamSpen210** [comment] 2023-01-19 23:07
It's actually [this `srctools` commit](https://github.com/TeamSpen210/srctools/commit/62e3e40b84a5645e59eecf43a5b24f648b448fff) - when writing out the brush edges, the very first one needs to not be used because of how it's encoded.

**Closed** 2023-12-30 06:11 UTC
Labels: Bug, Clean, Done in next release
