### ISSUE TITLE
Sideways textures on block items when in certain orientations

### ISSUE THREAD

**Issue by Flametusk** [BEEmod/BEE2-items#1253] opened 2016-12-22 06:18 UTC
Whenever I put an angled block on a wall, and have it facing parallel to the floor, the texture is sideways. Also, the 2x2x2 block, at least, in certain positions has the same problem. At least when placed on the ceiling.

**Comment by TeamSpen210** [comment] 2016-12-27 01:32
This is a duplicate of #894.

**Closed by TeamSpen210** 2016-12-27 01:32 UTC
Labels: bug
