### ISSUE TITLE
Wheatley's monitor in CO-OP crashes game when loading map

### ISSUE THREAD

**Issue by Anus95** [BEEmod/BEE2-items#3216] opened 2020-02-09 09:33 UTC

**Comment by Luke18033** [comment] 2020-05-15 02:00
The functionality used for this is probably broken in multiplayer, not sure if much can be done about it. Someone will need to investigate.

**Comment by Luke18033** [comment] 2020-05-15 02:05
Actually, this is a duplicate of #2582.

**Closed by Luke18033** 2020-05-15 02:05 UTC
Labels: CO-OP, Game Crash, More Info Needed
