### ISSUE TITLE
Portals can be placed on the surface with the quarter tiles

### ISSUE THREAD

**Issue by pansong291** [BEEmod/BEE2-items#3405] opened 2020-07-20 14:22 UTC
Maybe swapping the colors of quarter tiles and surfaces can solve this problem. I don't know.
![quarter_tile_portal](https://github.com/pansong291/Pictures/raw/master/github/BEEmod/BEE2-items/quarter_tile_portal.jpg)

**Comment by Flash4433** [comment] 2020-07-20 14:27
Duplicate of #3389, hardcoded

**Closed** 2020-07-20 14:30 UTC
Labels: Duplicate
