### ISSUE TITLE
Thinking With Time Machines style

### ISSUE THREAD

**Issue by SebTheDestroyer** [BEEmod/BEE2-items#3632] opened 2021-02-08 16:26 UTC
Not sure if this is being added or weather there's like a mod _for_ BeeMod that does this but I think it would be cool to see a style added that adds the shiny, new style as seen in the Portal 2 mod Thinking With time Machines but maybe without the cube droppers that assemble the cubes rather than delivering pre-built ones or the windows in the sides of the test chambers.

**Comment by Konclan** [comment] 2021-02-08 18:55
duplicate of #589

**Closed by Konclan** 2021-02-08 18:55 UTC
Labels: Duplicate
