### ISSUE TITLE
Surface Markers do not show up in-game

### ISSUE THREAD

**Issue by TPEcool** [BEEmod/BEE2-items#4228] opened 2022-09-09 07:05 UTC
### BEE2 Application Version

2.4.41.0

### BEE2 Package Version

4.41.0 i think

### What operating system are you running on?

Windows 10 (64bit)

### Description of the bug

Placing surface markers in the styles "Original Clean" and "Clean" does nothing after the chamber is built, it only changes the surface in the editor:
![helper](https://user-images.githubusercontent.com/75689188/189290403-9455e722-cd3f-4ffb-b06d-6b4e03797f0d.png)
![wall](https://user-images.githubusercontent.com/75689188/189290601-40830ac4-14f4-42a2-9c5d-8ee058eda6e1.png)

### Expected behavior

The surface marker should be visible.

### Steps to reproduce

Step 1: add a surface marker into your palette
Step 2: make a test with it and build it
Result: they're invisible/not present

### Additional information

It DID use to work, i have no idea what the heck happened

**Comment by FrozenDragon0** [comment] 2022-09-09 07:21
Duplicate of: https://github.com/BEEmod/BEE2-items/issues/3476

**Closed by FrozenDragon0** 2022-09-09 07:21 UTC
Labels: Bug, Duplicate
