### ISSUE TITLE
Portal stories VR music

### ISSUE THREAD

**Issue by SCIENTIST2004** [BEEmod/BEE2-items#2472] opened 2018-01-30 18:16 UTC
Add please Portal stories VR music
![header](https://user-images.githubusercontent.com/35931028/35583382-700a1356-05fa-11e8-92d7-a6e45e9655d3.jpg)

**Comment by xGARDYx** [comment] 2018-01-30 20:23
i dont know how it the song sound,but i want it too cuz u want it ;3

**Comment by SCIENTIST2004** [comment] 2018-01-30 21:40
https://www.youtube.com/watch?v=HZHNK0RzvCo

**Comment by SCIENTIST2004** [comment] 2018-01-30 21:41
^
|
|
|
portal stories vr music

**Comment by Luke18033** [comment] 2018-01-31 22:57
Duplicate of #1237.

**Closed by Luke18033** 2018-01-31 22:57 UTC
Labels: Enhancement, New Music
