### ISSUE TITLE
bug: bts entry corridor 4 leak and incomplete 

### ISSUE THREAD

**Issue by ellingtonvengaboysmuseum** [BEEmod/BEE2-items#1553] opened 2017-02-05 23:07 UTC
bug: bts entry corridor 4 leak and incomplete

![preview0002](https://cloud.githubusercontent.com/assets/11165643/22630790/eab57e26-ebcd-11e6-8d50-8bc8c7e13517.jpg)

![preview0004](https://cloud.githubusercontent.com/assets/11165643/22630795/fa888816-ebcd-11e6-9685-658f2f94d2c2.jpg)

**Comment by ZombiePwner1** [comment] 2017-02-05 23:09
This is a duplicate of https://github.com/BEEmod/BEE2-items/issues/1222

**Closed by ZombiePwner1** 2017-02-05 23:09 UTC
Labels: Bug, Leak
