### ISSUE TITLE
Sendificator.

### ISSUE THREAD

**Issue by CMSEv7** [BEEmod/BEE2-items#3538] opened 2020-10-09 00:39 UTC
I have a problem with the sendificator. I put it in a test chamber and it makes a building error.

**Comment by FrozenDragon0** [comment] 2020-10-09 00:42
More info please? What does the console say?

**Comment by Luke18033** [comment] 2020-10-09 00:42
Duplicate of #3307

**Comment by CMSEv7** [comment] 2020-10-09 00:43
I didn't check the console.

**Closed by Luke18033** 2020-10-09 00:42 UTC
Labels: More Info Needed
