### ISSUE TITLE
Make deadly goo not deadly, or just add an itemvar option to turn it into water.

### ISSUE THREAD

**Issue by WowThatsCowtastic** [BEEmod/BEE2-items#2973] opened 2019-04-22 16:03 UTC
Title.

**Comment by LautaroL20** [comment] 2019-04-22 16:14
Currently, we can not make deadly goo undangerous, but this could be turned into a suggestion to make it possible.

**Comment by Konclan** [comment] 2019-04-22 17:43
Basically a duplicate of #2139 since the mod features non deadly water

**Comment by Luke18033** [comment] 2019-04-22 18:32
Yeah, and non-deadly normal goo would be confusing.

**Closed by Luke18033** 2019-04-22 18:32 UTC
Labels: Itemvar
