### ISSUE TITLE
Fizzler Output Relay & Radiative Flux Rectangle Problem

### ISSUE THREAD

**Issue by Jinx133** [BEEmod/BEE2-items#2868] opened 2018-12-04 07:31 UTC
I don't know whether this just happens to me or not, but when I use Radiative Flux Rectangle **with Fizzler Output Relay**, the pellet sensor doesn't give the output, it doesn't change colors either. The antlines of the Fizzler Output Relay are visible, but they just don't activate/turn orange at all.

I tried to use the Fizzler Output Relay with Lifeform Sensor instead to see if I was misusing the Fizzler Output Relay, and it worked as intended. Maybe you could interpret this as "the problem isn't with fizzler output relay" as well, I don't know.

Thanks for reading!

**Comment by TeamSpen210** [comment] 2018-12-05 06:31
I can't see any problem with the Flux Rectangle.

**Comment by Jinx133** [comment] 2018-12-05 07:03
https://youtu.be/SwjZrLnHV0Y

This video explains the issue. I did place the fizzler output relay and it still gave me this result. Changing the timer of the relay to 3 (which isn't infinite, unlike this video) didn't result in anything different either.

But I have seen someone else post a similiar issue before, and you replied to it. Here: https://github.com/BEEmod/BEE2-items/issues/2831

**Comment by TeamSpen210** [comment] 2018-12-05 07:30
Ah, yes. This is a duplicate of that, and I did fix it.

**Closed** 2018-12-05 07:30 UTC
Labels: Bug, Duplicate, Fixed
