### ISSUE TITLE
Absolute fizzlers cause unknown bug

### ISSUE THREAD

**Issue by FierceThundr** [BEEmod/BEE2-items#3011] opened 2019-06-05 14:40 UTC
During play testing of a recent level of mine I have found a bug related to absolute fizzlers. I have seen someone post a more specific rendition of what this may be on another site, but I have yet to get someone to personally test it with.

The other post suggested there was a bug where the following crashed the game during play.
1. Peabody places portals.
2. Atlas crosses absolute fizzler.
3. Peabody attempts to place portals again.

**Comment by Konclan** [comment] 2019-06-10 16:44
Duplicate of #2982

**Closed** 2019-06-10 16:45 UTC
Labels: Duplicate
