### ISSUE TITLE
Vanilla Fizzler: when no input is connected, their model frame will look colored

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#3450] opened 2020-08-09 07:47 UTC
![Image](https://user-images.githubusercontent.com/12244376/89727374-8edb2780-d9fa-11ea-8b0f-a249813bb7ec.jpg)

**Comment by FrozenDragon0** [comment] 2020-08-09 08:11
Is this the dev version I gave you?

**Comment by LautaroL20** [comment] 2020-08-09 10:44
> Is this the dev version I gave you?

Using the dev repository + the public release app.

**Comment by Luke18033** [comment] 2020-08-09 17:33
This would be a duplicate of #3449 (they now use the same model)

**Closed by Luke18033** 2020-08-09 17:33 UTC
Labels: Bug, Development Build
