### ISSUE TITLE
Energy Pellet Catchers do not work in 60's style.

### ISSUE THREAD

**Issue by ThatCat287** [BEEmod/BEE2-items#4105] opened 2022-03-21 01:14 UTC
### BEE2 Application Version

4.41.0

### BEE2 Package Version

4.41.0

### What operating system are you running on?

Windows 10 (64bit)

### Description of the bug

When you try to set up a High Energy Pellet launcher and catcher in the 1960's Aperture style, the catcher does not work. It consumes the pellet for the specified length of time, but it can't activate anything connected to it.

### Expected behavior

I expected the catcher to work like it does in all other styles.

### Steps to reproduce

Step 1: Set the chamber to the 1960's aperture style.
Step 2: Open the puzzlemaker and place a High Energy Pellet launcher and catcher.
Step 3: Connect the catcher to anything that can normally be activated or deactivated by such an input.
Step 4: Run the level and put the High Energy Pellet into the catcher.

**Comment by FrozenDragon0** [comment] 2022-03-21 01:53
Duplicate of https://github.com/BEEmod/BEE2-items/issues/3858

**Closed by FrozenDragon0** 2022-03-21 01:53 UTC
Labels: Bug, Duplicate
