### ISSUE TITLE
High Energy Pellet Fizzler

### ISSUE THREAD

**Issue by Nikita74Russian** [BEEmod/BEE2-items#2685] opened 2018-05-06 15:52 UTC
A fizzler that destroys HEP and ONLY HEP nothing else.

**Comment by Luke18033** [comment] 2018-05-06 15:58
#2091 is a suggestion for a fizzler that blocks pellets (rather than destroying them), so this is sort of a duplicate of that.

**Comment by King0191** [comment] 2018-05-06 18:40
Isnt this literally what the Positronic Energy Orb is? Just on a smaller scale? I don't see why we'd need a fizzler for this, If you're just a bit off on your portal shot you wont hit the catcher. So i personally don't see the point?

**Comment by BETTEREXTENEDEDITORMOD** [comment] 2018-05-06 23:08
Duplicate of #2188

**Closed** 2018-05-06 23:10 UTC
Labels: Duplicate, New Item

**Comment by Nikita74Russian** [comment] 2018-05-07 15:15
Dumb? It doesn't fizzle anything but HEP. Read #2188 better, dumb.

**Comment by ZombiePwner1** [comment] 2018-05-07 22:52
@Nikita74Russian You better stop insulting people mate.
