### ISSUE TITLE
50's 3x3 vactube corner is wrong style

### ISSUE THREAD

**Issue by ellingtonvengaboysmuseum** [BEEmod/BEE2-items#2377] opened 2017-11-03 22:46 UTC
i don't know if anyone knows this, but the 50's 3x3 vactube corner is the wrong style, it's the 3x3 clean vactube instead of the old one...

**Comment by Luke18033** [comment] 2017-11-03 23:25
Duplicate of #1356.

**Closed by Luke18033** 2017-11-03 23:25 UTC
Labels: Old Aperture, Unstyled Item

**Comment by LautaroL20** [comment] 2017-11-04 03:50
@Luke18033 - Do not forget to apply the "duplicate" label when closing the issue.
