### ISSUE TITLE
Missing sound in Portal 1 style

### ISSUE THREAD

**Issue by HugoBDesigner** [BEEmod/BEE2-items#1719] opened 2017-03-13 23:22 UTC
Right at the start of the level, in the Portal 1 style, we hear "Oh, fiddlesticks, what now?".
**EDIT:**
`[Sound] S_StartSound(): Failed to load sound 'doors\doormove1.wav'. File is missing from disk/repository.
E`

**Comment by hop193** [comment] 2017-03-13 23:42
Actually, yes, I do hear this. I've had a scenario where  it didn't say it, but it was that only one time.

**Comment by Luke18033** [comment] 2017-03-13 23:42
Duplicate of #354.

**Closed by Luke18033** 2017-03-13 23:42 UTC
Labels: Development Version, Missing Sound, Portal 1
