### ISSUE TITLE
Antline Magnet will cause "Failure To Compile" when more than one input are connected to it

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#3406] opened 2020-07-20 15:38 UTC
`Could not open instance file instances/BEE2/logic/tspen/magnet.vmf`

**Comment by TeamSpen210** [comment] 2020-09-11 22:19
This is actually itself a duplicate of #3359, in that it's the same underlying cause. Magnets are just AND gates really.

**Closed** 2020-09-11 22:19 UTC
Labels: Compile Error, Done, Duplicate

**Comment by LautaroL20** [comment] 2020-09-11 22:38
Interesting. Yep, both items would basically meet the same function although i opened this issue because i thought that both items would use a different base config or so.
