### ISSUE TITLE
Unpaintable tiles.

### ISSUE THREAD

**Issue by ZombiePwner1** [BEEmod/BEE2-items#1690] opened 2017-03-10 09:44 UTC
How this would work is that if you place it will be a special tile that can't be painted. A trigger paint cleanser would be on the front of the tile to prevent paint.

**Comment by andremiles1** [comment] 2017-03-10 11:13
Why don't you use glass?

**Comment by Byzarru** [comment] 2017-03-10 14:06
See #1510.

> Yeah, but glass is also unportalable.
The unpaintable tiles could be portalable or not.
I suppose the main problem is distinguishing paintable and unpaintable tiles.

> There's the paint fizzler and the lcef, but they aren't very flexible.
Ed: Make the tiles pink, because the LCEF is pink.

**Comment by TeamSpen210** [comment] 2017-03-10 20:02
There's a material property which makes it unpaintable. The question is what would be a logically unpaintable surface?

**Comment by ZombiePwner1** [comment] 2017-03-10 22:49
The unpaintable tiles could use a special texture.

**Comment by Byzarru** [comment] 2017-03-10 22:50
> Make the tiles pink, because the LCEF is pink.

**Comment by TheDarkBomber** [comment] 2017-03-11 09:56
Duplicate of #1510.

**Closed** 2017-03-11 10:43 UTC
Labels: Aperture Tag, Duplicate, New Item
