### ISSUE TITLE
Placeable Elevator.

### ISSUE THREAD

**Issue by IceTudor** [BEEmod/BEE2-items#2313] opened 2017-10-26 16:50 UTC
Like the exit/entry elevators *obviously, styled* but placeable, you could place it like piston platforms, it'd start at the primary platform position, once entered, it closes and goes to the secondary position, opens and lets you free, going inside again will do the opposite, close, go to primary, open.
You could also probably make the BTS ones be the escape elevators, since I don't think you could use doors as an elevator.

**Comment by BETTEREXTENEDEDITORMOD** [comment] 2017-10-26 17:41
Duplicate of #1182

**Comment by IceTudor** [comment] 2017-10-26 17:57
I said a placeable elevator to use as test element, not inside chamber entry, not a duplicate.

**Comment by BETTEREXTENEDEDITORMOD** [comment] 2017-10-26 18:02
oh sorry about that

**Comment by IceTudor** [comment] 2017-10-26 18:10
Wait, but you CAN place entries and exits inside, just make a room big enough, the elevator worldportal doesn't care.

**Comment by BETTEREXTENEDEDITORMOD** [comment] 2017-10-26 19:55
true but that doesn't look good

**Comment by TeamSpen210** [comment] 2017-10-26 22:26
Elevators are way too big to fit inside maps, and the different styles have drastically different ones.

**Comment by Endermage77** [comment] 2017-10-26 22:50
In any case, this would still be a duplicate of #942.

Not that I'm down-putting this in any way, I'd actually like to see this.

**Comment by TeamSpen210** [comment] 2017-10-26 23:12
Duplicate of #942

**Comment by IceTudor** [comment] 2017-10-27 10:11
I don't mean a section to transition to another test. I mean, you can't make an easy way to go between 2 places down and below without using autoportals or 2 items in itself. Basically, lets you travel between 2 places in the same chamber, no different test or inside entry.

**Comment by Endermage77** [comment] 2017-10-27 22:17
It's kindof both.
The issue I linked to basically describes a worldportal door that uses an elevator transition.
This would be useful for both connecting multiple small chambers in one map and connecting different parts of a large chamber

**Comment by IceTudor** [comment] 2017-10-29 15:17
Look, mine isn't used as decoration/transition, its just like a very fancy victory lift with a few new features, not a new exit/entry or transition/decoration.

**Comment by Endermage77** [comment] 2017-10-29 15:40
I know.

That's what the worldportal does.
You have an entry and an exit that you can connect from anywhere in the map.

The idea of elevators as lifts was discussed in #942 and it was concluded that they would be far impractically massive, so the topic shifted to elevators as worldportals.

**Comment by IceTudor** [comment] 2017-10-29 19:06
*Facepalm* I mean an actual elevator that you can see in its entirety, vent and all, no doors, worldportals etc. It's not some quirky entry exit thing, its an actual placeable elevator.

**Comment by Endermage77** [comment] 2017-10-29 21:19
Ah.I see now.
In that case, this would <i>not</i> be a duplicate of #942.
Yeah, that would be actually really nice!

Still, that leaves the problem of the P1 elevators, which are far wider than the average size you'd get in every other style.

**Comment by IceTudor** [comment] 2017-10-31 11:44
Soo. would someone remove the duplicate tag and reopen this then? Since it is valid now?

**Comment by Endermage77** [comment] 2017-10-31 23:37
I apologize for the misunderstanding.

**Comment by IceTudor** [comment] 2017-11-01 14:11
Ah no problem, made some of these mistakes too, we all do sometimes.

**Comment by IceTudor** [comment] 2017-11-01 14:13
Portal 1 elevators could be tricky, but I found another elevator texture and model in P2 that's a lot like the P1 one, but slimmer and easier to place without needing a giant space for it like the original P1 Elevator.
This elevator is also preety neat, should be used for 1980's style as it fits more with the "Old portal 2 yet somehow weirdly close to portal 1."
I forgot the file but I'm sure i can find it.

**Comment by Fazbear189** [comment] 2017-11-24 03:40
Why don't you just make the portal 1 elevator massive and the item in the editor massive? That's what you did with the other items.

**Comment by ZombiePwner1** [comment] 2017-11-24 07:25
@Fazbear189 Making the portal 1 elevator massive would ruin the style for portal 1 it needs to be exactly the same as the style was in the original game.

**Comment by V0pT** [comment] 2019-10-28 17:32
I see this kind of elevator a lot in skyferret maps and it works really well, especially in a BTS or Wheatley test setting. A slim portal 1 elevator sound awesome as well, though I'm not sure where the file is. I do hope something like this makes its way into BEE2, it could add a ton of detail to levels.

**Comment by Konclan** [comment] 2021-08-14 22:31
Kind of a duplicate between #942 and #2565

**Closed** 2021-08-14 22:31 UTC
Labels: New Item
