### ISSUE TITLE
Invisible Entry door in 1970's style.

### ISSUE THREAD

**Issue by atomic-cherry** [BEEmod/BEE2-items#2791] opened 2018-08-06 00:30 UTC
**Style:** '1970's Old Aperture'
For some reason, the entry door is completely invisible in the editor. (it's the highlighted yellow square, you can tell because it has the outlined shape through the wall)
![See here](https://i.imgur.com/RQ56DBP.jpg)

However, it looks and functions perfectly fine in game.
![See here as well](https://i.imgur.com/Umseabo.jpg)

Additionally, the Co-Op door appears in the editor with no issues.
![See here one last time](https://i.imgur.com/mcqt3FM.jpg)

I haven't tested with any other 'old aperture' styles.
The large observation room is set as an actual office rather than grating, if that makes any difference.

~~I suppose you could almost say it's invisible in a "mysterious way"...~~

**Comment by Luke18033** [comment] 2018-08-06 01:44
Duplicate of #2626.

**Closed by Luke18033** 2018-08-06 01:44 UTC

**Comment by LautaroL20** [comment] 2018-08-06 07:03
@Luke18033 - Do not forget to apply the label after closing an issue; since although it may sounds unbelievable, there are some people who still checks inside the "closed issues" tab in order to see which issues were solved/closed and their reasons. So, having them shorted with the proper label after closing will help people to understand the real cause of its closure.

There is no need to apply aditional labels such as "enhancement", "new item" etc, when the issue is invalid/duplicate. The "invalid" or "duplicate" labels are just enough to clarify a reason for it.
