### ISSUE TITLE
Missing Texture

### ISSUE THREAD

**Issue by Fazbear189** [BEEmod/BEE2-items#2309] opened 2017-10-24 01:25 UTC
I have a missing texture in the portal 2 overgrown style(http://www.mediafire.com/file/joj7qwby9p99449/20171023211028_1.jpg)

**Comment by TeamSpen210** [comment] 2017-10-24 01:28
This is a duplicate of #2264.

**Closed by TeamSpen210** 2017-10-24 01:28 UTC

**Comment by TeamSpen210** [comment] 2017-10-24 01:29
Duplicate of #2264
