### ISSUE TITLE
Futebol Socket causes Compile Error in Portal 1 Style

### ISSUE THREAD

**Issue by jalapeno-github** [BEEmod/BEE2-items#3879] opened 2021-08-12 03:40 UTC
**BEE2 Version:** 4.40.2

<details>
<summary>Error Log</summary>

VBSP failed.

[I] cond.core._get_cond_group(): No name for module "precomp.faithplate"!
[I] cond.core._get_cond_group(): No name for module "precomp.fizzler"!
[I] vbsp.main(): BEE2 v4.40.2 VBSP hook initiallised.
[I] cond.core.import_conditions(): Imported all conditions modules!
[I] vbsp.main(): Map path is "J:/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf"
[I] vbsp.main(): New path: "J:/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[I] vbsp.main(): PeTI map detected!
[I] vbsp.main(): Loading settings...
[W] texturing.load_config(): overlays: Unknown texture names faithfling, faithland
[W] options.load(): Extra config options: {'remove_pedestal_plat': '1', 'voice_pack': 'BEE2_GLADOS_P1'}
[I] cubes.parse_conf(): Parsed 7 cube types, 1 dropper types and 4 addons.
[I] fizzler.read_configs(): Loaded 14 fizzlers.
[I] vbsp.load_settings(): Settings Loaded!
[I] vbsp.load_map(): Parsing Map...
[I] vbsp.load_map(): Reading Map...
[I] vbsp.load_map(): Loading complete!
[I] antlines.parse_antlines(): Parsing antlines...
[I] antlines.parse_antlines(): Done! (0 antlines)
[I] vbsp.mod_entryexit(): Setting SP Exit to 4
[I] vbsp.mod_entryexit(): Setting SP Entry to 7
[I] vbsp.get_map_info(): Game Mode: SP
[I] vbsp.get_map_info(): Is Preview: True
[I] brushLoc.read_from_map(): Analysed map, filling air... (12 starting positions..)
[I] brushLoc.read_from_map(): Air filled!
[I] cond.core.check_all(): Checking Conditions...
[I] cond.core.check_all(): -----------------------
[I] (MetaCondition "link_cubes") cubes.link_cubes(): SPLAT File: ['instances/bee2/logic/gel_splat.vmf']
[I] (<BEE2_CATWALK>/items/p1) cond.catwalks.res_make_catwalk(): Starting catwalk generator...
[I] cond.scaffold.res_unst_scaffold(): Running Scaffold Generator (BEE2_SCAFFOLD)...
[I] cond.scaffold.res_unst_scaffold(): Finished Scaffold generation!
[I] (<BEE2_UNST_SCAFFOLD>/items/slot_clean) cond.scaffold.res_unst_scaffold(): Running Scaffold Generator (BEE2_SCAFFOLD)...
[I] (<BEE2_UNST_SCAFFOLD>/items/slot_clean) cond.scaffold.res_unst_scaffold(): Finished Scaffold generation!
[I] (<BEE2_UNST_SCAFFOLD>/items/wall_clean) cond.scaffold.res_unst_scaffold(): Running Scaffold Generator (BEE2_SCAFFOLD)...
[I] (<BEE2_UNST_SCAFFOLD>/items/wall_clean) cond.scaffold.res_unst_scaffold(): Finished Scaffold generation!
[I] (MetaCondition "gen_item_outputs") connections.gen_item_outputs(): Generating item IO...
[I] (MetaCondition "gen_item_outputs") connections.gen_item_outputs(): Item IO generated.
[I] (MetaCondition "set_elev_videos") vbsp.set_elev_videos(): Elevator type: NONE
[I] (MetaCondition "add_voice") voice_line.add_voice(): Adding Voice Lines!
[I] (MetaCondition "add_voice") voice_line.add_voice(): Quote events: []
[I] (MetaCondition "add_voice") voice_line.add_voice(): 0 Mid quotes
[I] (MetaCondition "add_voice") voice_line.add_voice(): Done!
[I] (MetaCondition "anti_fizz_bump") vbsp.anti_fizz_bump(): Adding Portal Bumpers to fizzlers...
[I] (MetaCondition "anti_fizz_bump") vbsp.anti_fizz_bump(): Done!
[I] (MetaCondition "set_player_portalgun") vbsp.set_player_portalgun(): Setting Portalgun:
[I] (MetaCondition "set_player_portalgun") vbsp.set_player_portalgun(): Blue: Y, Orange: Y
[I] (MetaCondition "set_player_portalgun") vbsp.set_player_portalgun(): Done!
[I] cond.core.check_all(): ---------------------
[I] cond.core.check_all(): Conditions executed!
[I] cond.core.check_all(): Map has attributes: ['spawn_dual']
[I] cond.core.check_all(): instanceLocs cache: CacheInfo(hits=3996, misses=321, maxsize=256, currsize=256)
[I] cond.core.check_all(): Style Vars: {'doorcameras': False, 'p1_doorless_entry': True, 'p1_old_dissolve': True, 'p1_ported_pgun': True, 'restartonexit': True, 'multiversecave': False, 'fixfizzlerbump': True, 'nomidvoices': True, 'unlockdefault': False, 'allowgoomist': True, 'funnelallowswitchedlights': True, 'enableshapesignageframe': True}
[I] cond.core.check_all(): Global instances: {'instances/BEE2/p1/set_dissolve.vmf', 'instances/BEE2/clean/items/futbol/filter_futbol.vmf', 'instances/BEE2/p1/set_portalgun.vmf', 'instances/bee2/p1/color_correction.vmf'}
[I] music.add(): Adding Music...
[I] vbsp.add_extra_ents(): Adding global ents...
[I] vbsp.add_extra_ents(): Adding Global PTI Ents
[I] vbsp.change_ents(): Editing Other Entities...
[I] tiling.generate_brushes(): Generating tiles...
[I] tiling.generate_brushes(): Generating goop...
[I] vbsp.change_overlays(): Editing Overlays...
[I] barriers.make_barriers(): Adding Glass floor beams...
[I] barriers.make_barriers(): Done!
[I] vbsp.fix_worldspawn(): Editing WorldSpawn
[I] vbsp.save(): Saving New Map...
[I] vbsp.save(): Complete!
[I] <Valve>.run_compiler(): Calling original VBSP...
[I] <Valve>.run_compiler(): Args: '-game', 'J:/Steam/steamapps/common/Portal 2/portal2/', 'J:/Steam/steamapps/common/Portal 2/sdk_content\\maps\\styled\\preview.vmf'
[I] <valve>.vbsp(): Valve Software - vbsp.exe (May 19 2021)
[I] <valve>.vbsp(): 4 threads
[I] <valve>.vbsp(): Using shader api: shaderapiempty.dll
[I] <valve>.vbsp(): materialPath: J:\Steam\steamapps\common\Portal 2\portal2\materials
[I] <valve>.vbsp(): Loading J:/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf
[I] <valve>.vbsp(): ConVarRef gpu_level doesn't point to an existing ConVar
[I] <valve>.vbsp(): Could not open instance file instances/BEE2/p1/items/futbol.vmf
[I] <valve>.vbsp(): 
[I] BEE2_config.save(): Saving changes in config "C:\Users\javie\AppData\Roaming\BEEMOD2\config\compile.cfg"!

</details>

**Additional information:**
This error seems to be caused by the mere presence of the socket, regardless of connections, or whether the socket spawns the futebol.

**Comment by Luke18033** [comment] 2021-09-11 04:02
Duplicate of #3387

**Comment by Luke18033** [comment] 2021-09-11 04:46
This one is better though

**Closed** 2021-11-16 07:33 UTC
Labels: Portal 1, Compile Error, Done
