### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by xVenuss** [BEEmod/BEE2-items#3939] opened 2021-09-18 15:10 UTC
### BEE2 Application Version

Version 4.40.2

### BEE2 Package Version

4.40.0

### What operating system are you running on?

Windows 10 (64bit)

### Logs and Reports

```shell
VBSP failed.

[I] cond.core._get_cond_group(): No name for module "precomp.faithplate"!
[I] cond.core._get_cond_group(): No name for module "precomp.fizzler"!
[I] vbsp.main(): BEE2 v4.40.2 VBSP hook initiallised.
[I] cond.core.import_conditions(): Imported all conditions modules!
[I] vbsp.main(): Map path is "C:/Program Files (x86)/Steam/steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf"
[I] vbsp.main(): New path: "C:/Program Files (x86)/Steam/steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[E] logger.except_handler(): Uncaught Exception:
Traceback (most recent call last):
  File "compiler_launch.py", line 13, in <module>
  File "vbsp.py", line 1898, in main
  File "srctools\game.py", line 23, in __init__
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Program Files (x86)\\Steam\\steam\\steamapps\\common\\Portal 2\\portal2\\gameinfo.txt'
[7012] Failed to execute script compiler_launch
```

### Additional information

I really don't know what is happening

**Comment by xVenuss** [comment] 2021-09-18 17:41
I have Build Error every time

**Comment by xVenuss** [comment] 2021-09-18 17:54
![Screenshot (1399)](https://user-images.githubusercontent.com/90975585/133897997-294ce3d4-75a6-4d49-9c3a-c2e0c9cd6b16.png)

**Comment by Luke18033** [comment] 2021-09-18 17:57
You don't need to post a screenshot of the error message, it's totally useless. Seems like the game path is wrong, why does it go into a second `steam/` directory?

**Comment by xVenuss** [comment] 2021-09-18 18:22
something happend to my steam very long time ago thats wht there is second steam/ directory there are games that I install in my C: disc

**Comment by xVenuss** [comment] 2021-09-18 18:34
I can move Portal 2 install folder to my second disk then re-installing BEEmod2

**Comment by xVenuss** [comment] 2021-09-18 20:54
I restarted my laptop and this popped out Traceback (most recent call last):
  File "BEE2_launch.pyw", line 50, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 531, in exec_module
  File "app\BEE2.py", line 5, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 531, in exec_module
  File "app\gameMan.py", line 35, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 531, in exec_module
  File "app\optionWindow.py", line 17, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 531, in exec_module
  File "app\contextWin.py", line 20, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 531, in exec_module
  File "app\itemconfig.py", line 17, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 531, in exec_module
  File "app\UI.py", line 25, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 531, in exec_module
  File "app\CompilerPane.py", line 78, in <module>
  File "BEE2_config.py", line 180, in set_defaults
  File "BEE2_config.py", line 170, in save_check
  File "BEE2_config.py", line 163, in save
  File "contextlib.py", line 117, in __enter__
  File "atomicwrites\__init__.py", line 166, in _open
  File "atomicwrites\__init__.py", line 183, in get_fileobject
  File "tempfile.py", line 332, in mkstemp
  File "tempfile.py", line 251, in _mkstemp_inner
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Lukas\\AppData\\Roaming\\BEEMOD2\\config\\tmp3_0ztcup'

I didn't do anything

**Comment by LautaroL20** [comment] 2021-09-18 23:13
> xVenuss said: 
> I restarted my laptop and this popped out Traceback (most recent call last):
> File "tempfile.py", line 251, in _mkstemp_inner
> FileNotFoundError: [Errno 2] No such file or directory: 'C:\Users\Lukas\AppData\Roaming\BEEMOD2\config\tmp3_0ztcup'
> 
> I didn't do anything

That would be a duplicate of: https://github.com/BEEmod/BEE2.4/issues/1624, meantwhile, you can try solving that by doing the following:

Press WINDOWS+R
Enter %AppData%\BEEMOD2
Press Enter
Make a new folder and name it "Config"

**Comment by xVenuss** [comment] 2021-09-19 00:29
Thanks . Some how it fixed Build error somehow

**Closed** 2021-09-19 00:55 UTC
Labels: Bug, Duplicate, Compile Error
