### ISSUE TITLE
Lifeform Sensor Editor Model is using a wrong field

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#3400] opened 2020-07-20 13:29 UTC
![Image](https://user-images.githubusercontent.com/12244376/87941298-51c1ec00-ca71-11ea-9f11-6fe4a23aae83.jpg)

**Comment by Luke18033** [comment] 2020-07-20 17:51
You have done a full resources re-export, right? I fixed this and #3401 in the latest release.

**Comment by Luke18033** [comment] 2020-07-20 18:00
Though this would be a duplicate of #3282 either way.

**Closed by Luke18033** 2020-07-20 18:00 UTC
Labels: Bug

**Comment by LautaroL20** [comment] 2020-07-20 18:47
> You have done a full resources re-export, right? I fixed this and #3401 in the latest release.

Yeah, i always make sure to not only doing a full resources export when a new Bee update is released, but also i make sure to do a clean install by "uninstall from selected game", to make sure that any posible issues are 100% latest release´s fault and not me. I even recomend doing this method to anyone who is willing to update their Beemod version.

**Comment by Luke18033** [comment] 2020-07-20 18:50
Yeah, Git decided to just like...delete my commits or something.
