### ISSUE TITLE
The rocket turret's rockets and explosions are invisible on all styles.

### ISSUE THREAD

**Issue by MisterSakamoto** [BEEmod/BEE2-items#2062] opened 2017-06-11 21:30 UTC
The rocket turret's rockets and explosions are invisible on all styles.

**Comment by LautaroL20** [comment] 2017-06-15 04:30
This is a duplicate of: https://github.com/BEEmod/BEE2-items/issues/1984

**Closed by LautaroL20** 2017-06-15 04:30 UTC
Labels: Bug, Duplicate
