### ISSUE TITLE
Make the Catwalk item to generate "Railways Supports" on walls

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#1567] opened 2017-02-09 14:51 UTC
Do not get confused with the actual bottom support wich is also being placed on the wall. This one looks slightly different:

![20170207095012_1](https://cloud.githubusercontent.com/assets/12244376/22788107/5a52d660-eebd-11e6-8340-ec34fbbcdfcc.jpg)

**Comment by ZombiePwner1** [comment] 2017-02-09 23:12
This is a duplicate of https://github.com/BEEmod/BEE2-items/issues/1472

**Closed by ZombiePwner1** 2017-02-09 23:12 UTC
Labels: Duplicate, Enhancement

**Comment by ZombiePwner1** [comment] 2017-02-09 23:18
And the rail supports are part of the catwalk model you wheely.
