### ISSUE TITLE
bottomless pit suggestion for next release

### ISSUE THREAD

**Issue by EllingtonElectrician** [BEEmod/BEE2-items#657] opened 2016-08-04 13:06 UTC
i heard your improving the bottomless pit in next release

make sure to add code to generate pillars properly (force them to generate on sections that are for pillars and corners always and some for the sides etc.)

and if the pit will be able to be made deeper, you will need code to generate skybox on sections such as maps with Wheatley tests etc, so if the player falls in they will be able to see the top part of the skybox briefly...

what else have you done with the pit code since improving it

because eventually i would like to create some skyboxes with moving parts to create dynamic bottomless pits.

**Comment by Konclan** [comment] 2021-02-10 19:14
Duplicate of #87

**Closed** 2021-02-10 19:14 UTC
Labels: Enhancement
