### ISSUE TITLE
Draw bridges Fixed or Broken???

### ISSUE THREAD

**Issue by Bloodstrike2003** [BEEmod/BEE2-items#3657] opened 2021-02-25 02:16 UTC
I have no idea why but this needs to be addressed. So I dunno if it's a fix or not but the draw bridges aren't connected with each other to form a bridge.

**Comment by Luke18033** [comment] 2021-02-25 02:20
What do you mean? If you put two of them on opposite walls 3 blocks apart then they do connect.

**Comment by Bloodstrike2003** [comment] 2021-02-25 02:25
yeah about that, you see there's the red like.. warning thing that is preventing them from being connected

**Comment by Bloodstrike2003** [comment] 2021-02-25 02:26
do I need to show what I mean?

**Comment by Bloodstrike2003** [comment] 2021-02-25 02:28
![20210224182702_1](https://user-images.githubusercontent.com/78393178/109093954-186bf180-76ce-11eb-8d08-41a3b69e404d.jpg)
there

**Comment by Bloodstrike2003** [comment] 2021-02-25 02:28
![20210224182702_1](https://user-images.githubusercontent.com/78393178/109093987-26217700-76ce-11eb-9e58-08a06737c4bd.jpg)

**Comment by Luke18033** [comment] 2021-02-25 02:30
Ah, then that makes this a duplicate of #3652.

**Comment by Bloodstrike2003** [comment] 2021-02-25 02:31
oh, I didn't know

**Closed by Luke18033** 2021-02-25 02:30 UTC
Labels: Bug

**Comment by Bloodstrike2003** [comment] 2021-02-25 02:34
sorry
