### ISSUE TITLE
[PRL22 Bug] Massive leaks from goo in 80s style

### ISSUE THREAD

**Issue by cartman1337** [BEEmod/BEE2-items#858] opened 2016-09-22 21:49 UTC
When working on my latest map, I noticed that goo turned up as a sea of random bleeding colors and next-room textures when I tried it in 80s style, and the lighting takes at least twice as long to compile. I don't know what in my map is causing the issue. Incidentally, the same map also gets goo instead of bottomless pits when compiled in BTS mode.

Here are a couple of pictures of the bleed:
![Bleed1](http://i.imgur.com/J1HaF93.jpg)
![Bleed2](http://i.imgur.com/jHgL5pa.jpg)
![Bleed3](http://i.imgur.com/L2lDmZL.jpg)

Here's the compiler log, if anyone is able to get anything relevant to the issue from it:

```
CGameUIConVarRef mp_gamemode doesn't point to an existing ConVar
maxplayers set to 1
---- Host_NewGame ----
Network: IP 192.168.1.114, mode SP, dedicated No, ports 0 SV / 0 CL
Opened Steam Socket NS_SERVER ( socket 2516 )
Opened Steam Socket NS_CLIENT ( socket 2504 )
Network: IP 192.168.1.114, mode MP, dedicated No, ports 27015 SV / 27005 CL
Couldn't get HDR 'maps\1474028104/c-6376_-220_-1395.hdr' -- Trying non HDR 'maps\1474028104/c-6376_-220_-1395'
Failed, using default cubemap 'engine/defaultcubemap'
Couldn't get HDR 'maps\1474028104/c-6376_-220_-979.hdr' -- Trying non HDR 'maps\1474028104/c-6376_-220_-979'
Failed, using default cubemap 'engine/defaultcubemap'
Couldn't get HDR 'maps\1474028104/c-6192_-16_16.hdr' -- Trying non HDR 'maps\1474028104/c-6192_-16_16'
Failed, using default cubemap 'engine/defaultcubemap'
Couldn't get HDR 'maps\1474028104/c-6086_1560_-596.hdr' -- Trying non HDR 'maps\1474028104/c-6086_1560_-596'
Failed, using default cubemap 'engine/defaultcubemap'
Couldn't get HDR 'maps\1474028104/c-6086_1560_-228.hdr' -- Trying non HDR 'maps\1474028104/c-6086_1560_-228'
Failed, using default cubemap 'engine/defaultcubemap'
Host_NewGame on map puzzlemaker\76561198028597379\1474028104
exec: couldn't exec skill1.cfg
==== calling mapspawn.nut
Unable to load sprite material materials/sprites/gunsmoke.vmt!
Unable to load sprite material materials/sprites/bubble.vmt!
Attempted to create unknown entity type playtest_manager!
Can't init playtest_manager
Couldn't find any entities named cd6-box_ents_*, which point_template cd6-cube_template is specifying.
Couldn't find any entities named cd53-box_ents_*, which point_template cd53-cube_template is specifying.
Couldn't find any entities named cd168-box_ents_*, which point_template cd168-cube_template is specifying.
PrecacheScriptSound 'music.BEE2' failed, no such sound script entry
PrecacheScriptSound 'music.puzzlemaker\76561198028597379\1474028104_tbout' failed, no such sound script entry
Script not found (scripts/vscripts/BEE2/auto_run.nut) 
PrecacheScriptSound 'World.UndergroundElevatorDoorClose' failed, no such sound script entry
Commentary: Could not find commentary data file 'maps/puzzlemaker\76561198028597379\1474028104_commentary.txt'. 
1.000:  Sending UDP connect to public IP 127.0.0.1:27015
Server using '<none>' lobbies, requiring pw no, lobby id 0
RememberIPAddressForLobby: lobby 0 from address loopback
Can't find factory for entity: wearable_item
NULL Ent in UTIL_PrecacheOther
[PORTAL2 PUZZLEMAKER]  --------START loading assets--------

[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_autoportal_orange.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_autoportal_orange.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_autoportal_blue.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_autoportal_blue.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_autoportal_frame.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_autoportal_frame.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_tspen_futbol.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_tspen_futbol.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_bee2_fizz_error.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_bee2_fizz_error.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_portalgun1.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_portalgun1.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_portalgun2.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_portalgun2.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_portalgun3.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_portalgun3.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_under_faith_targ.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_under_faith_targ.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_tspen_ditch.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_tspen_ditch.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_tspen_a.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_tspen_a.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_tspen_b.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_tspen_b.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_tspen_chamberlock.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_tspen_chamberlock.3ds
[PORTAL2 PUZZLEMAKER]  ---------END loading assets---------

==== calling mapspawn.nut
Connection to Steam servers successful.
[PORTAL2 PUZZLEMAKER]  Saved puzzle: C:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/puzzles\76561198028597379\autosave.p2c
Parent cvar in client.dll not allowed (r_shadowlod)
***********************************
*         NO GAME SESSION         *
* some features might be disabled *
* (achievements, stats, UI, etc.) *
***********************************
   VAC secure mode is activated.
Redownloading all lightmaps
[PORTAL2 PUZZLEMAKER]  CVoxelTestChamber::Export VMF C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf ...
[PORTAL2 PUZZLEMAKER]  CVoxelTestChamber::Export VMF success, chamber size: (23,14,11)
[PORTAL2 PUZZLEMAKER]  Compilation time (after export): 188 (ms)
[PORTAL2 PUZZLEMAKER]  Compilation time (after VBSP): 45877 (ms)
[PORTAL2 PUZZLEMAKER]  Compilation time (after VVIS): 53510 (ms)
[PORTAL2 PUZZLEMAKER]  Saved puzzle: C:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/puzzles\76561198028597379\autosave.p2c
[PORTAL2 PUZZLEMAKER]  Saved puzzle: C:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/puzzles\76561198028597379\autosave.p2c
[PORTAL2 PUZZLEMAKER]  Compilation time (after VRAD): 160969 (ms)
[PORTAL2 PUZZLEMAKER]  Compilation time (complete): 161218 (ms) ...launching map!
Error: Operator stop_entry, unknown sound operator attribute input_start
---- Host_Changelevel ----
exec: couldn't exec skill1.cfg
==== calling mapspawn.nut
Attempted to create unknown entity type playtest_manager!
Can't init playtest_manager
Couldn't find any entities named cd6-box_ents_*, which point_template cd6-cube_template is specifying.
Couldn't find any entities named cd53-box_ents_*, which point_template cd53-cube_template is specifying.
Couldn't find any entities named cd168-box_ents_*, which point_template cd168-cube_template is specifying.
PrecacheScriptSound 'music.puzzlemaker/preview_tbout' failed, no such sound script entry
Script not found (scripts/vscripts/BEE2/auto_run.nut) 
Commentary: Could not find commentary data file 'maps/puzzlemaker/preview_commentary.txt'. 
Can't find factory for entity: wearable_item
NULL Ent in UTIL_PrecacheOther
[PORTAL2 PUZZLEMAKER]  --------START loading assets--------

[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_autoportal_orange.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_autoportal_orange.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_autoportal_blue.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_autoportal_blue.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_autoportal_frame.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_autoportal_frame.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_tspen_futbol.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_tspen_futbol.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_bee2_fizz_error.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_bee2_fizz_error.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_portalgun1.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_portalgun1.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_portalgun2.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_portalgun2.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_portalgun3.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_portalgun3.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_under_faith_targ.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_under_faith_targ.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_tspen_ditch.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_tspen_ditch.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_tspen_a.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_tspen_a.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_tspen_b.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_tspen_b.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_tspen_chamberlock.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_tspen_chamberlock.3ds
[PORTAL2 PUZZLEMAKER]  ---------END loading assets---------

==== calling mapspawn.nut
Unknown command "cl_puzzlemaker_start_previewing"
***********************************
*         NO GAME SESSION         *
* some features might be disabled *
* (achievements, stats, UI, etc.) *
***********************************
=======================Trying to GivePlayerPortalgun
=======================Trying to UpgradePlayerPortalgun
51
-2
Updating sound cache [8690 entries]
Found 8681 sound files on disk
 updated 'ui\p2_editor_panel_lower_01.wav'
 updated 'ui\p2_editor_panel_lower_02.wav'
 updated 'ui\p2_editor_panel_lower_03.wav'
 updated 'ui\p2_editor_panel_raise_01.wav'
 updated 'ui\p2_editor_panel_raise_02.wav'
 updated 'ui\p2_editor_panel_raise_03.wav'
Updated 6 out of 8681 cached files [281.678 msec]
Redownloading all lightmaps
Requesting texture value from var "$bumpmap" which is not a texture value (material: maps/preview/concrete/concrete_bts_floor001a_-6192_-16_16)
Requesting texture value from var "$bumpmap" which is not a texture value (material: maps/preview/concrete/concrete_bts_floor001a_-6192_-16_16)
SAVEGAME: 1417.3kb,  735.0kb used by 1593 entities (puzzlemaker/preview)
SAVEGAME:  112.5kb,   65.4kb used by 764 entities (puzzlemaker/preview)
SAVEGAME:    1.0kb,    0.0kb used by   0 entities (puzzlemaker/preview)
!! ERROR: bad input/output link:
!! logic_choreographed_scene(@cave_enter,Trigger) doesn't match type from trigger_once()
Wrote 'screenshots/preview0000.jpg':  6.91 MB (1920x1200) compresssed (quality 90) to 472.55 KB
CSceneEntity @cave_enter_generic unable to find actor named "cave_portal_intro_office"

```

**Comment by ZombiePwner1** [comment] 2016-09-22 22:34
You have an awful leak in your map somewhere.

**Comment by LautaroL20** [comment] 2016-09-22 23:07
Indeed, but for a moment i tought it was the bottomless pit not gettting rendered.

**Comment by ZombiePwner1** [comment] 2016-09-22 23:09
@LautaroL20 Come online @cartman1337 You should find a way to fix your leak.

**Comment by cartman1337** [comment] 2016-09-23 08:42
Well, obviously there's something wrong, but I don't know what could cause a leak. Do you have any examples of typical issues that could cause leaks? Incidentally, the leak only occurs when compiled in 80s style, and BTS style has a different issue where goo becomes goo instead of bottomless pits; all other styles compile normally, save for a separately reported texture bug on Conductive Plates.

In any case, these are the items I've got in my map:
- 3 normal weighted cubes
- 1 light bridge
- 2 piston platforms
- 8 fizzlers
- 15 laser fields
- 18 pedestal buttons
- 3 conductive plates
- 6 buttons (normal)
- 6 goo pits
- 3 trigger once points
- 5 autosave points
- 5 lasers
- 5 laser catchers
- 6 tractor beams, of which 3 start reversed on input, 2 start forward on input, and the last one starts forward on input, and reverses on second input
- 5 small observation rooms
- 1 1/4 flat block
- 8 thin walls (black)
- 4 gratings
- 6 glass/windows
- 15 flip panels (of which only 7 are in use)
- 6 angled panels (of which 5 are in use)
- 8 doors
- 20 square warm light blocks
- 63 normal white light strips
- 3 portal helpers
- 15 surface makers
- 4 turrets
- 1 catwalk (2 points)

I think that's it.

You can try the map, in 70s style, here: http://steamcommunity.com/sharedfiles/filedetails/?id=768175926

I can also share the map with someone, if someone wants to try to figure out what could cause the bleed in it.

**Comment by ZombiePwner1** [comment] 2016-09-23 11:48
Odd not sure what could be causing this is the goo raised up certain heights for seperate pits?

**Comment by cartman1337** [comment] 2016-09-23 12:13
The pits are at two different heights, all of them one block deep. None of the pits connect with each other.

**Comment by ZombiePwner1** [comment] 2016-09-23 12:15
Well i think the 2 pits that are different heights might be causing the leak.

**Comment by LautaroL20** [comment] 2016-09-23 12:38
Ill test out if different heights pits causes leaks...

**Comment by cartman1337** [comment] 2016-09-23 12:47
I've tested a bit on that now. First removing the goo at one height (they are one block higher than the pits on the other altitude), and then the goo on the other height. Still got the bleed. In fact, I even went so far as to remove ALL goo on the map, and it STILL bleeds! How can I tell? Because I can always tell if the map is bleeding as I walk towards the entrance. When it bleeds, this is the sight that greets me:
![bleeding chamber](http://i.imgur.com/m0pydI3.jpg)

In a new chamber, with nothing in it, this is how it looks:
![not bleeding](http://i.imgur.com/Jp8xNb0.jpg)

So, something on my map causes bleeding, even with no goo in there.

**Comment by ZombiePwner1** [comment] 2016-09-23 12:57
It's mostly caused by an area portal leak.

**Comment by cartman1337** [comment] 2016-09-23 13:27
An "area portal leak"? What is that?

I've tried making the map as flat as possible, removing all goo pits and the pit I had made for a fling maneuver, but it still bleeds.

**Comment by LautaroL20** [comment] 2016-09-23 15:39
A leak is basically an item / model that is crossing the limit between the void and the inside of the map. This causes the "Bleeding". TeamSpen probably want to re-check some items positions to see if they re well placed.

**Comment by cartman1337** [comment] 2016-09-23 16:57
I tried a couple of my older maps with 80s style too now. Got leaks there too, even on a chamber made before I started using any mods at all.

**Comment by LautaroL20** [comment] 2016-09-23 17:03
> even on a chamber made before I started using any mods at all.

This is serious. Something must be wrong with your Portal 2 installment, or a video driver isn´t working at all....

**Comment by cartman1337** [comment] 2016-09-23 17:17
Strange that it should only affect 80s style, though...

**Comment by cartman1337** [comment] 2016-09-23 19:23
I tried resetting the game cache and re-adding Beemod. Still the same issue.

**Comment by LautaroL20** [comment] 2016-09-23 21:07
@TeamSpen210 - Is maybe a wrong placement item that causes these massive leaks on cartman1337´s maps?

**Comment by Luke18033** [comment] 2017-01-02 23:14
@LautaroL20 A chamber made before any mods were used is no different than a chamber made after once it's been compiled.

**Comment by Luke18033** [comment] 2019-09-25 00:44
Not sure what the actual issue is here, closing.

**Closed by Luke18033** 2019-09-25 00:44 UTC
Labels: Bug, Leak, Old Aperture
