### ISSUE TITLE
Vactubes that can be turned on and off (suggestion)

### ISSUE THREAD

**Issue by snorepion** [BEEmod/BEE2-items#1902] opened 2017-05-02 16:14 UTC
A large aspect of many of my tests is using vactubes to get around, and it would be awesome if you could make them accept inputs like Pneumatic Diversity Vents. Thoughts?

**Comment by Luke18033** [comment] 2017-05-02 16:16
Duplicate of #1597.

**Closed by Luke18033** 2017-05-02 16:16 UTC
