### ISSUE TITLE
Overgrown ceiling observation rooms cause error

### ISSUE THREAD

**Issue by HugoBDesigner** [BEEmod/BEE2-items#1834] opened 2017-04-10 06:52 UTC
```
[INFO] vbsp.run_vbsp(): Arguments: "C:\Program Files (x86)\Steam\steamapps\common\Portal 2\bin\vbsp_original.exe" -game "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/" "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[ERROR] <Valve>.run_vbsp(): Valve Software - vbsp.exe (Aug 26 2015)
 | 4 threads
 | materialPath: C:\Program Files (x86)\Steam\steamapps\common\Portal 2\portal2\materials
 | Loading C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf
 | ConVarRef gpu_level doesn't point to an existing ConVar
 | Could not open instance file instances/BEE2/over/items/observation_room_128_ceil.vmf
 | 
 |_

[ERROR] vbsp.run_vbsp(): VBSP failed! (1)
```

EDIT: In case there is no ceiling obs. room instance yet, I'd recommend making it look like a broken ceiling with natural light coming to it, and maybe add some vines to it.

**Comment by ZombiePwner1** [comment] 2017-04-10 07:01
Duplicate of https://github.com/BEEmod/BEE2-items/issues/903 and i have made a ceiling variant. Check out that post.

**Closed by ZombiePwner1** 2017-04-10 07:01 UTC
Labels: Bug, Development Version, Duplicate, Overgrown

**Comment by iEnderMan06** [comment] 2017-04-10 13:25
@ZombiePwner1 Not exactly, Since it is causing him a build error...

**Comment by ZombiePwner1** [comment] 2017-04-11 00:04
@iEnderMan06 Build error is the same as a compiler error.

**Comment by LautaroL20** [comment] 2017-04-11 00:29
> ZombiePwner1: "I have made a ceiling variant."

Well, you should commit it then.

**Comment by ZombiePwner1** [comment] 2017-04-11 00:31
@LautaroL20 I'm still working on it u wheely and come on steam.
