### ISSUE TITLE
Music from Blue Portals

### ISSUE THREAD

**Issue by Kalail** [BEEmod/BEE2-items#3080] opened 2019-08-09 12:34 UTC
Why not add music from Blue Portals such as Empty Chasms ? 
If you want to listen here is the link: https://www.youtube.com/watch?v=wM11PT9PjNc&t=12s

**Comment by Luke18033** [comment] 2019-08-09 16:04
Duplicate of #2139 (it's included on the list under "Misc").

**Closed by Luke18033** 2019-08-09 16:04 UTC
