### ISSUE TITLE
Autportal not working

### ISSUE THREAD

**Issue by lillabofinken** [BEEmod/BEE2-items#3710] opened 2021-03-16 23:45 UTC
Auto portals does not work, I have tried having it enabled and disabled and rotated differently but they won't turn on.
I have tried it in portal 1 theme, overgrown theme and in the default theme

![20210317002555_1](https://user-images.githubusercontent.com/80794755/111393656-72eae300-86b9-11eb-916b-8e0201386a27.jpg)

**Comment by deli73** [comment] 2021-03-17 01:19
Also experiencing this issue, autoportals refuse to acitvate under any conditions we've tried

**Comment by supersean08-pro** [comment] 2021-03-17 01:41
using any options with the auto portal, will still make it disabled

**Comment by FrozenDragon0** [comment] 2021-03-17 05:54
Duplicate of: https://github.com/BEEmod/BEE2-items/issues/3672#issuecomment-800723455

**Closed by FrozenDragon0** 2021-03-17 05:54 UTC
Labels: Bug, Duplicate, Portal 1
