### ISSUE TITLE
World Portal item

### ISSUE THREAD

**Issue by jccreszMinecraft** [BEEmod/BEE2-items#306] opened 2016-02-27 19:20 UTC
An item that creates a world portal when linked to another item of the same type. Inputs and logic items can control them to swap worldportals or deactivate. Glass/grating variants can be created too, allowing visual tricks.

A _separate_ decorative item worldportal can be placed to show behind-the-walls areas depending on the theme. this item can have a timer item to determine what it can show behind it. This will need special instances to be placed in the map though.

**Comment by TeamSpen210** [comment] 2016-02-27 19:51
The problem with the last half is that you're limited to 4 portals visible at once. Worldportals also have to be bi-directional, so there's also a small problem there if users place the same scene twice.

**Comment by jccreszMinecraft** [comment] 2016-02-27 21:17
Well, we can warn about that in the item details, and if they place more, disable them completely. There'd have to be a solution to this problem.

**Comment by TristanBomb** [comment] 2016-05-16 04:04
I have to agree that adding a worldportal item would be excellent! If the decorative part is problematic, I think just the gameplay elements (first half) would suffice.

**Comment by Endermage77** [comment] 2018-01-20 04:51
Hang on, this is basically a worldportal door. In that case, it'd be a duplicate of good old #95.

**Comment by Konclan** [comment] 2019-08-29 01:46
Yeah, world portals as its own item aren't a good idea. I think just having the world portal door is enough

**Comment by Konclan** [comment] 2019-08-29 04:25
Actually basically a duplicate of #574

**Closed by Konclan** 2019-08-29 04:25 UTC
Labels: Enhancement

**Comment by KingMonkeyBug** [comment] 2024-02-24 19:21
Hold on, this was posted before #574 so wouldn't that mean #574 is a duplicate if this?
