### ISSUE TITLE
Portal 1 Stairs Antlines Issue

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2-items#1346] opened 2017-01-07 04:44 UTC
I connected a button to some stairs, and this happened:
![20170106204213_1](https://cloud.githubusercontent.com/assets/19228201/21739480/bf1706d4-d450-11e6-9d41-17fbfbcf1b8a.jpg)

**Comment by TeamSpen210** [comment] 2017-01-07 05:45
Makes sense.

**Comment by ZombiePwner1** [comment] 2017-01-07 09:37
Illuminati confirmed.

**Comment by TheDarkBomber** [comment] 2017-01-07 10:13
Yes, since I am a member of the [REDACTED].

**Comment by Luke18033** [comment] 2017-01-07 16:59
Why does it make sense? The antlines don't even touch the stairs.

**Comment by TheDarkBomber** [comment] 2017-01-07 17:01
Makes sense.

**Comment by Jadeygaming** [comment] 2017-01-07 17:31
@Luke18033 @TeamSpen210 Was being sarcastic...

**Comment by TheDarkBomber** [comment] 2017-01-07 17:39
@Jadeygaming Doesn't make sense.

**Comment by TeamSpen210** [comment] 2018-09-15 20:06
Fixed by bd8db1a.

**Closed** 2018-10-04 05:43 UTC
Labels: Bug, Fixed, Portal 1
