### ISSUE TITLE
Coop checkpoints save P-Body's position but not Atlas'

### ISSUE THREAD

**Issue by Greypilgrim228** [BEEmod/BEE2-items#3690] opened 2021-03-06 22:01 UTC
**Version 4.39.1 with 4.39.2 packages**

**What happens:**
Walking through the coop checkpoint with both P-body and Atlas, and then dying after it (either both of them jumping into a pool of goo or being shot by turret etc. etc.) P-body will always respawn within the coop checkpoint room, yet Atlas will respawn at the map entrance point. It doesn't matter whether P-body is first into the coop checkpoint or Atlas, whether they run straight through or both stand on their colour matched Aperture logos before leaving the room.
This bug DOESN'T occur with the separated coop checkpoint, only the coop checkpoint.

**What should happen:**
Both P-body and Atlas should respawn in the coop checkpoint area upon death

**Steps to reproduce the bug:**
Place a coop checkpoint in the middle of the map, and an area of toxic goo on the other side, or a crusher, or some other way of killing players.
Walk into the checkpoint with both characters, walk out the other side, kill them both.

**Comment by FrozenDragon0** [comment] 2021-05-01 15:13
Duplicate of https://github.com/BEEmod/BEE2-items/issues/1564 I'm surprised this issue is still around even after 3 years.

**Closed** 2021-05-01 15:13 UTC
Labels: Bug, Co-Op, Duplicate
