### ISSUE TITLE
Portalable Piston Platform

### ISSUE THREAD

**Issue by awesomedoctorx3** [BEEmod/BEE2-items#1826] opened 2017-04-09 01:34 UTC
A portalable Piston Platform, like this one here:

![p2_lift_standalone_portable](https://cloud.githubusercontent.com/assets/27110077/24833856/2450435e-1ca3-11e7-911e-eacfed113d2f.png)

Maybe  a portalable track platform also?

**Comment by HugoBDesigner** [comment] 2017-04-09 01:40
I very second this. Also non-portalable too. I'm surprised I haven't found other instances of this suggestion, especially since I wanted to ask this myself.

**Comment by awesomedoctorx3** [comment] 2017-04-09 01:41
also, it should be gel-able.

**Comment by Luke18033** [comment] 2017-04-09 02:05
Duplicate of #95 and #674.

**Closed by Luke18033** 2017-04-09 02:05 UTC
