### ISSUE TITLE
[PRL22 Bug] Overgrown Style: Track Platform is not using "Broken Glass"

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#715] opened 2016-08-21 03:51 UTC
![20160821003845_1](https://cloud.githubusercontent.com/assets/12244376/17835233/da6ef67e-6738-11e6-9c0e-29bf8e2c3f6e.jpg)

**Comment by Luke18033** [comment] 2017-03-16 19:55
Duplicate of #66.

**Closed by Luke18033** 2017-03-16 19:55 UTC
Labels: Bug, Overgrown, Unstyled Item
