### ISSUE TITLE
Change Diversity Vents to Physics Only

### ISSUE THREAD

**Issue by ellingtonvengaboysmuseum** [BEEmod/BEE2-items#2358] opened 2017-11-01 20:38 UTC
The current Diversity Vents need to be changed to pick up Physics Only, the player can enter them and get stuck, eventually player transporting tubes should use path_track to transport the player...

also i am going to soon make some patches to the current vac tubes and add the entry and exit tubes and fix the issue with tubes not picking up cubes through portals...

![preview0103](https://user-images.githubusercontent.com/11165643/32296461-b4c187f0-bf22-11e7-85ea-316960cbff87.jpg)

**Comment by Luke18033** [comment] 2017-11-01 21:00
Duplicate of #1597, which includes an option to disable player transport.

**Closed by Luke18033** 2017-11-01 21:00 UTC
