### ISSUE TITLE
Portal 1 cube dropper has a mysterious leak

### ISSUE THREAD

**Issue by ZombiePwner1** [BEEmod/BEE2-items#3246] opened 2020-03-21 10:12 UTC
![image](https://user-images.githubusercontent.com/18079316/77224338-8d21dc00-6b9f-11ea-8034-172511bbadf9.png)

**Comment by Luke18033** [comment] 2020-03-21 16:54
Not a leak, just a visible nodraw. This is also a duplicate of #3175.

**Closed by Luke18033** 2020-03-21 16:54 UTC
Labels: Bug, Portal 1
