### ISSUE TITLE
Remove Annoying Repulsion Gel/ Funnel SFX

### ISSUE THREAD

**Issue by TheReviewers** [BEEmod/BEE2-items#1399] opened 2017-01-14 11:20 UTC
Its annoying that everytime i fling, i have to hear some random music.. i don't mind it when the music is meant for it. but when its p1 music with p2 music? its annoying D:

**Comment by TheReviewers** [comment] 2017-01-14 11:21
@TeamSpen210 Maybe an option to disable it?

**Comment by TeamSpen210** [comment] 2017-01-14 11:25
I should remove it from some tracks where it doesn't match too well.

**Comment by ZombiePwner1** [comment] 2017-01-14 11:27
I actually encountered this issue in some styles where the SFX wasn't even mean't to play. For example in one of the styles can't remember which one it was but when i was sliding on propulsion gel or whatever i heard the classical music SFX like wtf? i didn't even have any music selected.

**Comment by TheReviewers** [comment] 2017-01-14 11:28
I Know Right D:

**Comment by Konclan** [comment] 2017-01-14 19:30
Duplicate of #1104

**Comment by TeamSpen210** [comment] 2017-01-14 19:56
@ZombiePwner1, that's definitely a bug. Can you reproduce it?

**Closed** 2017-01-14 19:55 UTC
Labels: Duplicate, Suggestion

**Comment by ZombiePwner1** [comment] 2017-01-14 23:10
I can try i just need to remeber which style it was.

**Comment by Luke18033** [comment] 2017-01-17 22:56
Was it Portal 1? That style has a lot of issues with item SFX.

**Comment by ZombiePwner1** [comment] 2017-01-17 23:21
Portal 1 style i had a few issues with SFX since i could hear one of the wheatley SFX's playing yet i had no music set.
