### ISSUE TITLE
Elevator

### ISSUE THREAD

**Issue by DigitexStudios** [BEEmod/BEE2-items#3687] opened 2021-03-05 16:21 UTC
**Description of the item:**
Elevator that can carry players up and down to different areas of the chamber

**Item options:**
Start enabled - Whether the elevator starts active. (On by default)
Start deployed - Which side the elevator starts on (Off by default, false = bottom, true = top)
Start reversed - Whether the elevator is for co-op maps (Off by default, false = one elevator for the player, true = two side-by-side elevators)
Cube type - Entrance style (Weighted by default, Weighted = Fizzler only, Cube = Door only, Sphere = Fizzler and door) 
Auto-drop first cube - Behavior (On by default, true = moves when player is standing on it, false = moves only with inputs)
Respawn cube - Style (Off by default, false = style 1, true = style 2)

Input to change which side the elevator is on, or if auto-drop is on, enable/disable.

**Source:**
Found in all single-player worlds

**Additional information:**
- In Clean, Art Therapy, and Overgrown style, the elevator is either a chamber elevator or a lift panel.
- In P1 style, the elevator is either a P1 elevator or a Victory Lift.
- In Old Aperture style, the elevator is either an Old Aperture elevator or a moving platform.
- In BTS style, the elevator is either an elevator platform or a lift panel.
- In BTS style, the elevator is either a

**Comment by seagemgames** [comment] 2021-03-05 16:23
Duplicate of #2313

**Comment by DeliWasTaken** [comment] 2021-03-05 16:44
> Duplicate of #942

to be fair it seems much more detailed than #942.

**Comment by FrozenDragon0** [comment] 2021-03-06 03:05
I believe this would still be a duplicate of https://github.com/BEEmod/BEE2-items/issues/942

**Closed by FrozenDragon0** 2021-03-06 03:05 UTC
Labels: Duplicate, New Item
