### ISSUE TITLE
Input-activated Save Points

### ISSUE THREAD

**Issue by Lieutenant-L-T-Smash** [BEEmod/BEE2-items#3760] opened 2021-04-26 21:12 UTC
The current Save Point item is an area trigger, requiring a player to be in a specific location to activate.

It would be very useful to have a Save Point that accepts an input (from buttons, logic gates, etc.) to trigger the save. In many puzzles, it makes more sense to save when a player has successfully accomplished some task, which isn't necessarily related to reaching a certain area, but rather to activating a puzzle element.

This enhanced Save Point could even replace the existing implementation. A regular Trigger Once item connected to an input Save Point would have the same effect as the current Save Point.

**Comment by Luke18033** [comment] 2021-04-26 21:44
Duplicate of #1077

**Closed by Luke18033** 2021-04-26 21:44 UTC
Labels: Enhancement

**Comment by Lieutenant-L-T-Smash** [comment] 2021-04-26 22:23
Sorry about that. I searched for duplicates, but apparently not well enough.
