### ISSUE TITLE
Texture Sometimes Sideways for Flat or Partial Blocks

### ISSUE THREAD

**Issue by libbybapa** [BEEmod/BEE2-items#1613] opened 2017-02-20 16:03 UTC
Sometimes, when a flat or partial block is placed on a wall, the texture goes the wrong direction:

![20170220090129_1](https://cloud.githubusercontent.com/assets/19520567/23132638/76463d9e-f74b-11e6-9187-aeaadd94f950.jpg)

**Comment by Luke18033** [comment] 2017-02-20 16:11
That's strange that this is happening, the block items should be using brush templates...

**Comment by libbybapa** [comment] 2017-02-20 16:30
It is possible to correct the texture direction on the flat blocks by 'rotating them around a corner' if you know what I mean, but when placed on a wall, they should always have the lines going vertically.

**Comment by LautaroL20** [comment] 2017-02-20 21:33
Duplicate of: https://github.com/BEEmod/BEE2-items/issues/894

**Closed by LautaroL20** 2017-02-20 21:33 UTC
Labels: Bug, Duplicate
