### ISSUE TITLE
Portal 1 Retractable Pedestal Button is missing its Editor Icon 

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#1287] opened 2016-12-26 03:33 UTC
![20161225234736_1](https://cloud.githubusercontent.com/assets/12244376/21474793/c7222946-cb02-11e6-81bc-8a35f4f4a936.jpg)

**Comment by Luke18033** [comment] 2016-12-26 16:35
What are the two items in the bottom-left two slots? I don't think they are in the current main version or dev version.

**Comment by LautaroL20** [comment] 2016-12-26 21:10
Oh, those are part of my addons. Working CO-OP Grates and Half-Grate. Ill probably release them alongside with the Cold Light Strip too.

**Comment by TeamSpen210** [comment] 2016-12-26 21:34
How did you do the coop grating?

**Comment by TheDarkBomber** [comment] 2016-12-26 21:39
@LautaroL20 What is the name of your BEE2.4 Pack? I'm going to develop a tool that can create simple packages for BEE2.4, and it would be able to extract `.bpk` files, so it is not just for creating packages. (`.bpk` = `BEE2.4 Pack`)

**Comment by LautaroL20** [comment] 2016-12-26 21:56
@TeamSpen210 - Ill explain you when i log on Steam, also ill need your help with some things too.

@TheDarkBomber - A tool that can create packages for Bee2.4 would be very helpful, I hope you can finish its development. As for my package´s name, Lautaro.

**Comment by TheDarkBomber** [comment] 2016-12-26 22:33
@LautaroL20 It will be called [WASP](https://github.com/TheDarkBomber/WASP) and will be written in C#, as it doesn't interfere with the BEE2.4 compiler at all.

**Comment by Luke18033** [comment] 2017-04-05 16:24
The problem is that BEE can't actually read `.bpk` files, making WASP kind of useless...

@TheDarkBomber - They're not going to be a separate pack, they're going to be merged into the default pack. Really there's no reason to make anything a separate pack, just fork this repository, make the items on there and then create a pull request to merge them into the default pack.

**Comment by Luke18033** [comment] 2019-09-25 01:58
Now fixed

**Closed by Luke18033** 2019-09-25 01:58 UTC
Labels: Bug, Portal 1
