### ISSUE TITLE
Underground Elevator

### ISSUE THREAD

**Issue by Flametusk** [BEEmod/BEE2-items#1182] opened 2016-12-12 14:39 UTC
It would require the 'allow moving required items' field to be checked, and wouldn't work with the normal entry/exit doors, bexcuse it would move the spawn point to be at that elevator, an case you wanted the entrance/exit to be inside the test chamber, in case you wanted to build your own enrichment "sphere", or, the easier option, an enrichment cube, and have the elevators inside said three-dimensional form.

**Comment by Luke18033** [comment] 2016-12-12 16:11
Hmm. This is an interesting idea.

**Comment by TheDarkBomber** [comment] 2016-12-12 18:24
We should add this as a separate item.

**Comment by TeamSpen210** [comment] 2021-08-14 22:20
Duplicate of #942.

**Closed by TeamSpen210** 2021-08-14 22:20 UTC
Labels: Enhancement, New Item
