### ISSUE TITLE
purple texture on scaffolding in overgrown elevator entry way

### ISSUE THREAD

**Issue by ellingtonvengaboysmuseum** [BEEmod/BEE2-items#2350] opened 2017-10-31 23:54 UTC
missing purple texture found on scaffolding in overgrown elevator entry way

![preview0059](https://user-images.githubusercontent.com/11165643/32254128-52c6c590-be75-11e7-8152-48a98e4d7b81.jpg)

**Comment by TeamSpen210** [comment] 2017-11-01 00:13
Duplicate of #2264

**Closed by TeamSpen210** 2017-11-01 00:13 UTC
