### ISSUE TITLE
creating clean style bottomless pit help

### ISSUE THREAD

**Issue by mario2582** [BEEmod/BEE2-items#327] opened 2016-03-10 02:35 UTC
@TeamSpen210 and @BenVlodgi - i may start working on the clean bottomless pit to assist you a bit...

is bee2 ready to generate a clean style bottomless pit

is there code in bee2 yet besides the walls and corners to place random instances in the pit without collisions like vac tubes, wires, test chambers and the test chamber support beams etc and make it look nice.

if there is I want to know what the code is

we will need about a hundred instances available for bee2 to choose from for this pit for it to look nice and so no two are alike. here is what we're looking at

40 instances for generating walls and corners etc with random holes in them etc.
(we will need some way to clump together area's with holes since that's how some look in game)
30 instances for the other test chambers seen in the pit
20 instances of objects in the pit such as vac tubes and wires
10 instances of the steel beams that support the test chamber (needs to form a nice looking grid)

**Comment by Enterpise** [comment] 2016-03-10 04:02
Thats a challenging development, but i would love to see this on Bee 2.4. Best of lucks with this project!

**Comment by TeamSpen210** [comment] 2016-03-12 23:42
It's not currently implemented, no. Instead of a large number of instances, what I'd want to end up doing is combine multiple ones randomly - for example generate test chamber brushes, and then spawn decorations on the sides of that brush.

**Comment by Konclan** [comment] 2019-08-29 01:50
Duplicate of #87, not really an issue that needs to be open since we can communicate development in discord.

**Closed by Konclan** 2019-08-29 01:50 UTC
Labels: Enhancement, Skybox
