### ISSUE TITLE
Triggers works, but due to old resources from past releases getting mixed with the latest release, it acts as if it wouldn't work...

### ISSUE THREAD

**Issue by Dantido** [BEEmod/BEE2-items#2857] opened 2018-11-11 17:27 UTC
No matter what I do, no matter what I try. Trigger Once won't work with anything. I tried with cube droppers, I tried with stairs. The antline gets orange, but it DOESN'T ACTIVATES. I'm almost done with this error, and I need help. I know there may be any posts related to this, but nothing helps me.

**Comment by Dantido** [comment] 2018-11-11 17:29
What the Volumetric Trigger Once method?

**Comment by LautaroL20** [comment] 2018-11-11 21:11
Trigger Once works fine, see image where an invisible trigger activates 3 items, used PRL31:
![Triggers](https://user-images.githubusercontent.com/12244376/48318271-99298100-e5dc-11e8-9f37-2958338c218c.jpg)

**Comment by LautaroL20** [comment] 2018-11-11 21:11
When using BEE2.4 after installing a new version, old resources from past releases will not be overwritten, resulting in bugs that were fixed still being present and some things not working correctly. In order to solve this annoyance, you will have to do the following:

1 - Make sure your antivirus is not blocking the compiler´s files of Beemod that are located in the `bin` folder inside the Portal 2 game´s directory. Just add the whole `bin` folder in your antivirus exception´s list, because otherwise this can cause a ****"building error"**** issue when building your puzzle.

2 - Open Beemod and click on: `File ----> Uninstall From Selected Game ----> "Are you sure you want to delete "PORTAL 2"? ----> YES`.

3 - Wait 1 minute while Beemod removes their resources from Portal 2.

4 - Verify the Game Cache Files. 

5 - Make sure to have downloaded and unzipped the latest Item's Packages and Application version of BEE2.4, and both must be from the same Pre-Release Version, otherwise bugs may occur. Links:

https://github.com/BEEmod/BEE2.4/releases (Application)  
https://github.com/BEEmod/BEE2-items/releases (Item's Packages)

Note that if you are running Beemod on Linux or Mac Os X, or even on 32 Bit versions of Windows, issues can occur. Beemod currently works well only on 64 Bit versions of Windows 7, 8 and 10.

6 - Click on: `File ----> Options ----> Development`, then uncheck the option: `Preserve Game Directories`.

7 - Now choose your favorite Items & Style and export your palette to the game.

8 - Make sure to save these steps in a text file in case you get similar issues in the future.

9 - Happy mapmaking!

**Comment by Overwatch-C-17** [comment] 2018-11-12 08:42
Ah yes, after I do above comment the 2nd times, it worked. Both Single Block and Volumetric Trigger Once works. I do uninstall from game using latest release of BEE since the previous release seems not clean all the files, feels like there are still leftovers. This issue can be close tho.

**Comment by Overwatch-C-17** [comment] 2018-11-12 09:03
I deleted my previous comment. Have you try Trigger Once to target Stairs and Coop Glass Door? I tested the two, both aren't go active @LautaroL20

**Comment by LautaroL20** [comment] 2018-11-13 21:48
This is a duplicate of: https://github.com/BEEmod/BEE2-items/issues/2844

**Closed by LautaroL20** 2018-11-13 21:48 UTC
Labels: Invalid
