### ISSUE TITLE
Sendifigator dont work on Overgrow

### ISSUE THREAD

**Issue by dunkler-schatten** [BEEmod/BEE2-items#2953] opened 2019-03-27 17:46 UTC
Sendifigator **don't work** on **Overgrown** and **Old Aperture**

In the Styles "**Clean, Original Clean, Portal 1, and BTS**" he **Work Fine**, but has **no Skin**.

Please look at it and fix it. Thank You.

**Comment by LautaroL20** [comment] 2019-03-27 23:27
This is a duplicate of: https://github.com/BEEmod/BEE2-items/issues/2851

**Comment by TeamSpen210** [comment] 2019-03-27 23:29
There's the other problem here too, where Clean doesn't pack.

**Comment by LautaroL20** [comment] 2019-03-27 23:45
The post´s description was probably a wrong copy paste, he most likely were refering to the Slim version which an issue for it was already opened (https://github.com/BEEmod/BEE2-items/issues/2952), because the original Sendificator does have zero problems respect to textures: 

![20190327203943_1](https://user-images.githubusercontent.com/12244376/55119505-e3655780-50d0-11e9-90ef-e4f29e2cb79a.jpg)

If i am correct, then its a duplicate of: https://github.com/BEEmod/BEE2-items/issues/2952

**Comment by LautaroL20** [comment] 2019-03-27 23:47
@dunkler-schatten - Can you confirm if the texture issue you are reffering is about the Sendificator SLIM or it is the big Sendificator?

**Comment by dunkler-schatten** [comment] 2019-03-28 19:07
> @dunkler-schatten - Can you confirm if the texture issue you are reffering is about the Sendificator SLIM or it is the big Sendificator?

I have tested. It is only the slim version. But in Overgrown and Old Aperture Work both not. The big old and the slim Version don't work and Beam a Cube.

**Comment by dunkler-schatten** [comment] 2019-03-28 19:14
![20190328201254_1](https://user-images.githubusercontent.com/18405990/55186093-00179300-5196-11e9-93e3-c22da77c17a9.jpg)

**Comment by therealimaginator** [comment] 2019-03-28 19:24
I can also confirm: Sendificator did not work in Overgrown rendered from BEEMOD 2.434.1. Only tested Large Sendificator. Have not tested Small Sendificator or Old Aperture styles.

Large Sendificator worked flawlessly as described in BEEMOD tooltip upon rendering same level in Clean Style.

Since I work mostly in Overgrown, I assumed the issue was User Error until this post, having not myself used Sendificators previously. Thrilled to see it works in Clean.

**Comment by LautaroL20** [comment] 2019-03-28 22:12
Duplicate of #2952 and #2851 confirmed by author´s post.

**Closed by LautaroL20** 2019-03-28 22:12 UTC
Labels: Bug, Clean, Duplicate, Missing Resource
