### ISSUE TITLE
exit co-op not open with all ✅

### ISSUE THREAD

**Issue by MischaGer** [BEEmod/BEE2-items#3205] opened 2020-01-20 17:47 UTC
have bind my exit with
1x cube_button
1x Ball button
2x laser catcher
and 3 x laser relay

**Comment by LautaroL20** [comment] 2020-01-20 18:16
This is a duplicate of: https://github.com/BEEmod/BEE2-items/issues/2989

**Closed by LautaroL20** 2020-01-20 18:16 UTC
Labels: Duplicate

**Comment by MischaGer** [comment] 2020-01-20 18:27
how fix it?

**Comment by LautaroL20** [comment] 2020-01-20 19:40
Only Spencer could fix it via VScript. However, i have been pinged this issue so people can see it is already reported and is in high priority.

**Comment by MischaGer** [comment] 2020-01-20 20:51
have fix that with another door
