### ISSUE TITLE
Closed Solid Fields don't Appear Correctly

### ISSUE THREAD

**Issue by PieCreeper13** [BEEmod/BEE2-items#2433] opened 2018-01-04 05:36 UTC
The closed solid fields are supposed to appear like normal fields, but white. However, they're showing up as invisible with a few white lines instead.

**Comment by ZombiePwner1** [comment] 2018-01-04 10:12
Duplicate of https://github.com/BEEmod/BEE2-items/issues/1918

**Closed by ZombiePwner1** 2018-01-04 10:12 UTC
Labels: Bug, Duplicate
