### ISSUE TITLE
Invisible trigger_catapult item

### ISSUE THREAD

**Issue by Critfish** [BEEmod/BEE2-items#3750] opened 2021-04-22 12:23 UTC
In some Portal 2 campaign maps, invisible trigger_catapults are used for certain flings in order to ensure that the player can successfully execute a fling consistently. An item like this could be used to add extra polish to flinging puzzles, and make flings more forgiving in general.

In the editor, it would function like the faith plate item, except it is invisible, represented by a trigger block in the editor. They do not produce a bullseye on targeted surfaces.

The trigger would be mounted on a surface(preferably on a portalable surface) and would only enable if a portal is placed on the same tile as the trigger_catapult item.

It could feature a "Button Type" dropdown menu, with each option allowing the user to configure what the trigger_catapult affects.

- Weighted: Players and objects(cubes, turrets, gel bombs) are both affected.
- Cube: Only players are affected, cubes/turrets/gel bombs are unaffected by the catapult.
- Sphere: Only objects are affected, players are not affected by the catapult.

The main uses of this item would be to add polish to flinging-oriented puzzles, making flings more predictable for both players and objects, and making flings more forgiving and less frustrating.

**Comment by seagemgames** [comment] 2021-04-22 12:45
Duplicate of #2795

**Closed** 2021-04-22 15:01 UTC
Labels: New Item
