### ISSUE TITLE
Portal 1 is having "Massive Leaks"

### ISSUE THREAD

**Issue by WafflesAndSyrup** [BEEmod/BEE2-items#2595] opened 2018-03-29 06:41 UTC
I was playing a friend's test chamber, and encountered something interesting
![15218594500000](https://user-images.githubusercontent.com/36249695/38073785-09abd8f0-335f-11e8-9bbd-78f99f643534.jpg)
![15218594500001](https://user-images.githubusercontent.com/36249695/38073808-1dd93174-335f-11e8-9b23-2ffbf96dba31.jpg)
![15218594500002](https://user-images.githubusercontent.com/36249695/38073812-21891820-335f-11e8-9cad-f306d6aed8de.jpg)
![15218594500003](https://user-images.githubusercontent.com/36249695/38073818-2b237a74-335f-11e8-89cb-41eaf3e6dc45.jpg)
![15218594500005](https://user-images.githubusercontent.com/36249695/38073824-2fe53eda-335f-11e8-8771-47b3cc681aaa.jpg)

**Comment by LautaroL20** [comment] 2018-03-29 07:21
Which items the map had on it? Since there was one in PRL28 which were causing leaks and it was the Neurotoxim.

**Comment by LautaroL20** [comment] 2018-03-29 08:04
I would not trust the positronic energy orb because it seems to be a big model, and that could be the cause of the leak. However, to make sure what item is causing it, try removing some of them, then recompile to see if the leak stops at some point.

**Comment by Luke18033** [comment] 2019-09-21 17:54
Not sure what the actual issue is here, closing.

**Closed by Luke18033** 2019-09-21 17:54 UTC
Labels: Leak, Portal 1

**Comment by LautaroL20** [comment] 2019-09-28 03:47
Well, its fixed most likely or maybe it is to do due to a weird item in the map that is leaking somewhere.
