### ISSUE TITLE
Auto-portals not functioning

### ISSUE THREAD

**Issue by TimmyBuildar** [BEEmod/BEE2-items#3672] opened 2021-02-28 20:50 UTC
**BEE2 version:** 4.39.2

**Description of the bug:** The auto-portals don't appear to function in any era style, even when set to Start Enabled.

**Expected behavior:** The portals to actually work.

**Steps to reproduce:** Place an auto-portal down in any style, connect it to a button or set to Start Enabled. Compile and test it.

**Additional information:** I have the latest packages I could find for this version. I did not edit these packages other than add the patch that went with it. I'm not sure if this bug only applies to me.

**Comment by TimmyBuildar** [comment] 2021-03-04 03:51
thanks!

**Comment by LautaroL20** [comment] 2021-03-04 14:59
If you close the issue before the next Beemod release is out, some people will not going to see that this issue was already reported and fixed, which might cause that someone could fall into making a duplicate of this.

**Comment by deli73** [comment] 2021-03-17 01:25
when are we gonna get a release build wtih this fix?

**Closed** 2021-07-02 06:52 UTC
Labels: Bug, Done
