### ISSUE TITLE
Half-size triggers

### ISSUE THREAD

**Issue by snorepion** [BEEmod/BEE2-items#1791] opened 2017-03-31 23:21 UTC
I'm building a map with various death traps and one of them is an angled panel that crushes the player. However, I can't get it to trigger properly and crush the player, it's one or the other. With a half-sized Trigger Once, I'd be able to do that. Basically, it would just be Trigger Once, but the size of And/Or/Not invisible gates.

This might be impossible, since the triggers are hard-wired into the game, but maybe there's some hack you can do that will make it possible.

**Comment by ZombiePwner1** [comment] 2017-03-31 23:31
No it's possible to change the size of the triggers in hammer so half size triggers are possible.

**Comment by snorepion** [comment] 2017-03-31 23:34
That's good. I can't build levels in Hammer because BEE2 messed it up somehow and I can't fix it, so are you going to make the variant an item or do I just need to suck it up?

**Comment by Luke18033** [comment] 2017-03-31 23:39
How is Hammer broken? The compilation? If that's the case, there's an easy way to fix it. Change the VBSP and VRAD paths to their `original` versions in the settings.

**Comment by snorepion** [comment] 2017-04-01 00:04
Already tried that, still doesn't work. VVIS has issues and the entities get messed up a lot. I've tried
- Changing VBSP and VRAD to original
- Verifying game and Hammer files
- Using `preview.vmf` instead of whatever export name I use
- Running `map [whatever]` instead of launching the game from Hammer

Main problem is that VVIS doesn't work with the full compile setting, making levels look horrendous, especially deadly goo.

**Comment by Luke18033** [comment] 2017-04-01 00:20
Oh, are you trying to edit from exported BEE maps? If you are, make sure you don't use `puzzlemaker_export` - it screws things up. Instead edit `maps/styled/preview.vmf`. Make sure the spawn location is set to Elevator and Restart When Reaching Exit is off, otherwise things won't work correctly when publishing.

TeamSpen210 is probably going to comment this exact same thing, he always does. :-P

**Comment by snorepion** [comment] 2017-04-01 00:22
Like I said, I already do the `preview.vmf` thing, but it still doesn't work. It works better than exported maps, but still doesn't have proper visibility.

**Comment by LautaroL20** [comment] 2017-04-01 01:41
This is a duplicate of: https://github.com/BEEmod/BEE2-items/issues/300

**Closed by LautaroL20** 2017-04-01 01:41 UTC
Labels: Enhancement, New Item Variant

**Comment by snorepion** [comment] 2017-04-01 15:31
Well, apparently I should search before making an issue.

**Comment by TheDarkBomber** [comment] 2017-04-03 08:13
Is it `styled/preview.vmf`? Or just `preview.vmf`?
