### ISSUE TITLE
Old Portal 1 "Half-Life-esque" Beta Style

### ISSUE THREAD

**Issue by Endermage77** [BEEmod/BEE2-items#1675] opened 2017-03-08 01:23 UTC
Not to be confused with the other portal 1 beta style suggestions, which mainly took from the age of development where many things weren't completely textured, and bluish bits were turquoise and that brief period of Star Trek doors.

No, this is the Half-Life 2-esque stage of development.
The style as seen in the "game", per se, can be seen in its entirety in this (sadly) 2-hour long portal-beta montage entitled [The Evolution of Portal](https://www.youtube.com/watch?v=1tfCy8RU5Kk), which thankfully has time stamps for every chamber.
The one to be looking out for are the bits titled "Late 2005," and some prominent ones are chambers 00, 04, 08, 13,18, and Finale.
I must admit, there's quite a bit of work to be done to make this a truly complete style in its own right, but some of its characteristics are as follows:
- Wire connections are literal wires
- Boxes take the form of Metal Crates
- Elevators are Combine-like lifts in some places, and like maintenance lifts in others (I recommend using a stylevar to pick which)
- Goo is yellowish-green and misty on top
- Timers are dials
-  Walls are styled like Half-Life 2 Offices in some bits (I recommend to match this and the lift using a stylevar)
- In other bits it looks like the Combine Citadel (Chamber 18)
- Many props are taken from Half-Life 2
-  Recommended settings take after those of Portal 1 (Except for having None as the voice)
- Orange Portals are Mauve (It's okay if this isn't implemented)
- Emancipation Grids look like Combine forcefields
- Autoportal Frames are Caution Tape frames
- HEP launchers and catchers actually have unique models here (See Test Chamber 08)
- Portal Gun looks vaguely like the Tool Gun (which is from Gmod, but this "Portal Gun" is more fitting with the theme
- Turrets take from Half-Life 2
- Pretty much everything can take after Half-Life 2

-  If you like, we can have a Roller-Mine GlaDOS here for the Monitor (Even though it's from the 2006 beta and not this one (Which is called the Dec 2005 in the vid for some reason), but why not?)

As styles go, this is probably the most currently incomplete of all of them, and as such should definitely be on a long-term to-do list if it is done at all.

This is just one for the back burner if you're running out of ideas. Cool Beans.

**Comment by Byzarru** [comment] 2017-03-08 01:30
Duplicate of #834.

**Closed** 2017-03-08 01:30 UTC

**Comment by Endermage77** [comment] 2017-03-08 01:32
Ah. Right then.
That's a shame.
It'll always be there though, ready to be done when everything else has been done.
