### ISSUE TITLE
Pedestal Button that can be placed in Right-Middle-Left Positions plus rotation toggle

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#1758] opened 2017-03-17 18:38 UTC
![20170317152636_1](https://cloud.githubusercontent.com/assets/12244376/24057468/36132e5a-0b26-11e7-9ea8-8d1ec4e5749c.jpg)

**Comment by Konclan** [comment] 2017-03-17 18:48
This technically already exists

**Comment by Luke18033** [comment] 2017-03-17 18:55
Basically, the Protruding Pedestal Button minus the protruding.

**Comment by Luke18033** [comment] 2017-03-17 18:55
This could just be added to the original item.

**Comment by LautaroL20** [comment] 2017-03-17 19:13
@Konclan - No, you still woudn´t be able to use my protruding ped buttons with a "Track Plataform" close to it because it will gonna say invalid position because floating, this is why this item would be useful:
![20170317160947_1](https://cloud.githubusercontent.com/assets/12244376/24059114/8b9fb4e6-0b2c-11e7-90ae-5e3e9b408a79.jpg)

**Comment by Luke18033** [comment] 2017-03-17 20:04
Make sure the middle button has a 2-tile wide base, the original 3-tile base looks kind of weird since it's not aligned to the tile grid...

**Comment by Luke18033** [comment] 2017-03-17 20:04
Maybe call this the "Pedestal Button Plus"

**Comment by TheDarkBomber** [comment] 2017-03-18 09:19
Duplicate of #447.

**Comment by LautaroL20** [comment] 2017-03-18 09:35
No it isn´t.

**Comment by ZombiePwner1** [comment] 2017-03-18 09:37
@LautaroL20 Lol BTW come online you wheely.

**Comment by TheDarkBomber** [comment] 2017-03-18 11:07
It is.

**Comment by LautaroL20** [comment] 2017-03-18 11:10
@TheDarkBomber - No its not. Can you see the label or do you need a pair of glasses? It says "New Item".

**Comment by TheDarkBomber** [comment] 2017-03-18 11:10
So is #447.

**Comment by LautaroL20** [comment] 2017-03-18 11:11
That one is just about giving a simple rotation toggle for Valve´s pedestal. This one is about a new button variant.

**Comment by TheDarkBomber** [comment] 2017-03-18 11:11
Instead of opening a new issue, why not just edit that one?

**Comment by LautaroL20** [comment] 2017-03-18 11:15
Because merging this in the PeTi´s pedestal would break the `ITEM_BUTTON_PEDESTAL` condition, and that implies breaking old puzzles files as well as the item´s collisions into the Editor.

**Comment by TheDarkBomber** [comment] 2017-03-18 11:32
:man_facepalming: I said edit the issue. Not the item.

**Comment by LautaroL20** [comment] 2017-03-18 11:40
Because this must be a separated issue since it has nothing to do with the konclan´s one anymore.... Issue #447 will also gonna be implemented.

**Comment by hop193** [comment] 2017-03-18 16:28
> Duplicate of #477
It isn't.

**Comment by Luke18033** [comment] 2017-03-18 16:41
That's why you don't give @TheDarkBomber admin access to anything, if he were a collaborator right now he'd probably be locking this or something...

**Comment by LautaroL20** [comment] 2017-03-18 16:56
Indeed, this would have turned into a constant close-re-open annoyiance situation where all of you would had a massive list of notifications into your e-mail inboxes until someone flagged @TheDarkBomber to the Github Support.

**Comment by Luke18033** [comment] 2017-03-18 17:27
> No, its not. Can you see the label or do you need a pair of glasses? It says "New Item".

> So is #447.

I think he does need glasses, #447 does NOT have the New Item label and never did.

**Comment by hop193** [comment] 2017-03-19 01:24
> I think he does need glasses, #447 does NOT have the New Item label and never did.

Lol, he does.

**Comment by hop193** [comment] 2017-05-03 19:45
So, any info about this?

**Comment by LautaroL20** [comment] 2017-05-04 01:18
Glad to see you interesting, once i make the BTS Model Editor for the pedestal button, i will do it.

**Comment by LautaroL20** [comment] 2017-08-11 05:50
This is now implemented. You can test it by using the Dev version, or just wait for the PRL26.

**Closed** 2017-10-10 09:25 UTC
Labels: Implemented, New item
