### ISSUE TITLE
Item Idea: Handrail

### ISSUE THREAD

**Issue by prrg** [BEEmod/BEE2-items#3078] opened 2019-08-02 19:05 UTC
Saw these in Hammer and thought it'd be a really useful inclusion, though idk if it is possible.

Handrails similar to the ones available in Catwalks that could be used to stop the player from reaching certain areas or jumping over to a pit  for example. They could possibly even be used to encircle buttons/cube triggers to keep the dang cubes inside.

**Comment by TeamSpen210** [comment] 2019-08-02 22:20
For this, I think the item would be 4-way rotatable, and place a rail on one side. Placing a bunch would then generate corners and endings as appropriate.

**Comment by King0191** [comment] 2019-08-03 00:20
Could we not connect them? Use something similar to how the Vac tubes work so if one is rotated and connected to one that isn't, it curves appropriately?

**Comment by Luke18033** [comment] 2019-08-04 01:29
Duplicate of #1274.

**Closed by Luke18033** 2019-08-04 01:29 UTC
