### ISSUE TITLE
Surf Ramp

### ISSUE THREAD

**Issue by SW50000** [BEEmod/BEE2-items#1513] opened 2017-01-28 21:07 UTC
Is it possible to add a surf ramp from aperture tag?
![20170128150613_1](https://cloud.githubusercontent.com/assets/20195894/22399835/7cd25c7a-e56b-11e6-9c0e-2c889a4a58ff.jpg)

**Comment by Byzarru** [comment] 2017-01-28 21:25
Duplicate of #1316.

**Closed by Byzarru** 2017-01-28 21:25 UTC
