### ISSUE TITLE
item: extended relaxation vault

### ISSUE THREAD

**Issue by ellingtonvengaboysmuseum** [BEEmod/BEE2-items#198] opened 2015-12-16 16:16 UTC
before i forget, the extended relaxation vault should be added as a item, this is a must if creating a short series of story based test chambers in PTI

**Comment by Luke18033** [comment] 2017-01-26 03:27
An ERV would definitely be useful, but PeTI isn't really for story maps...

**Comment by ZombiePwner1** [comment] 2017-01-26 05:32
How this should work is that whever it's placed down it disables the entry door or it could just delete the entry elevators.

**Comment by Luke18033** [comment] 2017-02-10 19:52
Duplicate of #1245 (which was moved from BEEmod/BEE2.4#32).

**Closed by Luke18033** 2017-02-10 19:52 UTC
Labels: New Item
