### ISSUE TITLE
Make Signage Items use the "HANDLE_8_POSITIONS" 

### ISSUE THREAD

**Issue by iEnderMan06** [BEEmod/BEE2-items#2010] opened 2017-05-27 12:27 UTC
Why do we have them being the way they are right now anyway? It would be a lot better like this so we can have a lot more freedom with where we can place our Signage items, sometimes you might want it next to an antline magnet or a lot of other things.

**Comment by Luke18033** [comment] 2017-05-27 14:22
Duplicate of #1586, it's because of stupid item collisions...

**Closed by Luke18033** 2017-05-27 14:22 UTC
Labels: suggestion
