### ISSUE TITLE
Sphere-type light strips are custom-colored

### ISSUE THREAD

**Issue by Critfish** [BEEmod/BEE2-items#3183] opened 2019-12-28 14:40 UTC
Color would be determined by a timer widget, the colors themselves would be changeable in the Stylevars/Itemvars window, much like how the Cube Coloriser functions.

If used properly, these colored lights could be used to create some pretty cool visuals.

**Comment by Luke18033** [comment] 2020-01-01 06:19
Duplicate of #1414.

**Closed by Luke18033** 2020-01-01 06:19 UTC
Labels: New Item Variant
