### ISSUE TITLE
Use buttontype property to spread Warm, Cold or Neutral lighting on both the Observation Rooms

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#1729] opened 2017-03-14 04:37 UTC
![20170314003324_1](https://cloud.githubusercontent.com/assets/12244376/23885539/9062a380-0852-11e7-9978-28a4c62a906f.jpg)

**Comment by Luke18033** [comment] 2017-03-14 04:38
Duplicate of #1701, you could have just commented there (you did).

**Closed by Luke18033** 2017-03-14 04:38 UTC
Labels: BTS, Clean, Enhancement, Overgrown, Portal 1

**Comment by LautaroL20** [comment] 2017-03-14 04:48
Oh boy........ If i were edited that issue you mention, the author from it would said "DON´T EDIT MY POST, MAKE YOURS A SEPARATE ISSUE." As you said in the past too.
