### ISSUE TITLE
Calm Wheatley Package

### ISSUE THREAD

**Issue by magicdog2013games** [BEEmod/BEE2-items#3160] opened 2019-12-06 23:33 UTC
I was working on a calm wheatley package IE one where he's not abusing and yelling at chell, Its mostly functional but the sounds don't seem to be working, I will submit it here specifically so if the creators of bee2mod want to add it to their packages they can do so and maybe fix whatever's wrong with it, I'm submitting it to issues specifically because I don't know how to fix it
[Wheatleycalm.zip](https://github.com/BEEmod/BEE2-items/files/3934407/Wheatleycalm.zip)

**Comment by TeamSpen210** [comment] 2019-12-06 23:57
The issue is most likely the choreo actor. To use the `choreo` lines, they require an actor NPC to "speak" the lines. For all the Act 4 "evil" Wheatley lines they use GLaDOS's actor which is already present, but the sphere lines look for `@sphere` (the core NPC). You'll need to add `"Bullseye" "@sphere"` to most of your quotes - see the "Maintenence Protocols" one for example:

```python
"Line"
	{
	"Name"   "Maintenence Protocols"
	"ID"     "GENERIC_HACKING"
	"Trans"  "Alright, then. Let's see... 'Vital maintenance protocols.' Wow, there's a lot of them. Should have looked into this earlier. Well, let's try this: [reading while typing] DO THEM. [failure buzzer]. Fair enough. Maybe it's a password."
	"Trans"  "A, A, A, A, A, A. [NNNT!] No, okay. A, A, A, A, A, B. [NNNT!] Hold on, I've done both of these. Skip ahead. A, B, C... D, G, H. [DING!]"
	"Trans" "Oh! Good news! [electric pop] Nevermind."
	
	"Bullseye" "@sphere" 
	
	"Choreo"
		{
		"1" "npc/sphere03/bw_a4_finale04_wakeupa08.vcd"
		"2" "npc/sphere03/bw_a4_finale04_wakeupa09.vcd"
		"3" "npc/sphere03/sp_sabotage_factory_hackdoor08.vcd"
		}
	}
```

**Comment by LautaroL20** [comment] 2019-12-07 00:41
If you will do a contribution to Beemod, feel free to get help from various users at the Discord server and once you finish fixing your package, you can ask to publish it at the #user-created-package in the server. Discord server link: https://discordapp.com/invite/hnGFJrz

**Comment by Luke18033** [comment] 2019-12-07 00:55
Alternatively you can make a pull request, to have it merged into the default pack.

**Comment by LautaroL20** [comment] 2019-12-07 01:04
Well, if the contribution is consistent, then there should not be any problem having it included in the official Beemod content on future releases thru a pull request.

**Comment by magicdog2013games** [comment] 2019-12-07 01:37
I just added "Bullseye" "@sphere" to the lines and it didn't work

**Comment by Luke18033** [comment] 2019-12-07 05:00
Wait, can `npc_bullseye`s be used as actors for voice lines?!

**Comment by TeamSpen210** [comment] 2019-12-07 07:06
You can indeed. That’s what they’re for - an invisible NPC with no collision and the like.

**Comment by magicdog2013games** [comment] 2019-12-18 05:42
[voice_line.zip](https://github.com/BEEmod/BEE2-items/files/3976765/voice_line.zip)
I've modified it but it has the same problem, can someone explain?

**Comment by magicdog2013games** [comment] 2019-12-18 05:44
whoops wrong file
[Wheatleycalm.zip](https://github.com/BEEmod/BEE2-items/files/3976768/Wheatleycalm.zip)

**Comment by ENDERZOMBI102** [comment] 2019-12-18 22:32
fixed and sended to discord in #development

**Closed** 2019-12-18 22:36 UTC
Labels: Contribution

**Comment by Flash4433** [comment] 2019-12-19 11:55
Here's @ENDERZOMBI102 package so we don't have to search in #development
[Wheatleycalm.zip](https://github.com/BEEmod/BEE2-items/files/3983436/Wheatleycalm.zip)
