### ISSUE TITLE
Cutout Tiles should be able to be placed on any surface

### ISSUE THREAD

**Issue by villager103** [BEEmod/BEE2-items#2645] opened 2018-04-15 05:58 UTC
Currently, they can be placed on the floor or ceiling(with no effect)

I see no reason why they shouldn't work on walls and ceilings, given the nature of this item.

**Comment by HugoBDesigner** [comment] 2018-04-15 06:01
Duplicate of #449

**Closed by HugoBDesigner** 2018-04-15 06:01 UTC
Labels: Duplicate, Enhancement
