### ISSUE TITLE
[PRL21.5 Bug] 70´s Old Aperture: A "Mysterious Portal Gun" is again on the Entry´s Floor

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#767] opened 2016-09-04 17:28 UTC
![20160904142644_1](https://cloud.githubusercontent.com/assets/12244376/18232691/b4de2118-72ab-11e6-88d6-5826ed199e38.jpg)

**Comment by TheDarkBomber** [comment] 2016-09-04 19:21
Duplicate of #748.

**Comment by LautaroL20** [comment] 2016-09-04 19:26
Nope. One is from 60´s Old, and this is from 70´s.

**Comment by ZombiePwner1** [comment] 2016-09-05 00:48
These mysterious portal gun issues are making me lmao

**Comment by TeamSpen210** [comment] 2016-09-05 01:01
It's actually an orange-only portalgun, as part of a WIP addition of blue autoportals in the original BEE2. It's now totally useless though, since that's added by the compiler elsewhere.

**Comment by LautaroL20** [comment] 2016-09-05 01:27
@ZombiePwner1 @TeamSpen210  - I think thats part of my humor, not my intention at all to get offend or grief anyone. I just wanna give it a pretty small touch of humor to my bug report titles, specially when somethimes bugs looks so funny, like the case of "Futbol Spawner" wich goes crazy when you place it into a map.

**Comment by GiovanH** [comment] 2020-08-18 23:49
This is no longer the case. 

![2020-08-18 18_48_55-PORTAL 2](https://user-images.githubusercontent.com/6759280/90576330-84035e00-e183-11ea-8c99-1c8b047ab9f9.png)

**Closed** 2020-08-18 23:51 UTC
Labels: Bug, Old Aperture
