### ISSUE TITLE
Using an antline magnet causes an error

### ISSUE THREAD

**Issue by NeoKat75** [BEEmod/BEE2-items#3519] opened 2020-09-11 16:10 UTC
> [I] vbsp.save(): Complete!
[I] <Valve>.run_compiler(): Calling original VBSP...
[I] <Valve>.run_compiler(): Args: '-game', 'C:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/', 'C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\\maps\\styled\\preview.vmf'
[I] <valve>.vbsp(): Valve Software - vbsp.exe (Nov 12 2019)
[I] <valve>.vbsp(): 4 threads
[I] <valve>.vbsp(): materialPath: C:\Program Files (x86)\Steam\steamapps\common\Portal 2\portal2\materials
[I] <valve>.vbsp(): Loading C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf
[I] <valve>.vbsp(): ConVarRef gpu_level doesn't point to an existing ConVar
[I] <valve>.vbsp(): Could not open instance file instances/BEE2/logic/tspen/magnet.vmf
[I] <valve>.vbsp(): 
[I] BEE2_config.save(): Saving changes in config "C:\Users\home-pc\AppData\Roaming\BEEMOD2\config\compile.cfg"!

**Comment by LautaroL20** [comment] 2020-09-11 16:27
This is a duplicate of: #3406

**Closed by LautaroL20** 2020-09-11 16:27 UTC
Labels: Duplicate
