### ISSUE TITLE
Autoportals can be placed and manualy have portals put on, but activating them does nothing.

### ISSUE THREAD

**Issue by PortalPuzzleMan** [BEEmod/BEE2-items#3775] opened 2021-05-04 20:18 UTC
**BEE2 version:**

**Description of the bug:**

**Expected behavior:**

**Steps to reproduce:**

**Additional information:**

**Comment by HeimlichLaboratories** [comment] 2021-05-04 20:52
Already reported various times

**Comment by Luke18033** [comment] 2021-05-04 20:57
Duplicate of #3672

**Closed by Luke18033** 2021-05-04 20:57 UTC
Labels: Bug
