### ISSUE TITLE
BTS Corridors are "Leaked As Hell"

### ISSUE THREAD

**Issue by G3neralGrant** [BEEmod/BEE2-items#1393] opened 2017-01-12 23:38 UTC
I walk in and this
![img1](https://cloud.githubusercontent.com/assets/24685304/21912566/92ecd28e-d8db-11e6-8ac7-b70eb1e24a96.png)
![img2](https://cloud.githubusercontent.com/assets/24685304/21912593/cadccb2c-d8db-11e6-9718-f6808c5749aa.png)
the exit as well
![img3](https://cloud.githubusercontent.com/assets/24685304/21912644/2160a0d6-d8dc-11e6-95f5-158828e5c9b4.png)
this door doesn't open
![img4](https://cloud.githubusercontent.com/assets/24685304/21912690/56c80e4e-d8dc-11e6-89db-a085487420bd.png)
![image](https://cloud.githubusercontent.com/assets/24685304/21912791/07f29d4c-d8dd-11e6-8a82-c4315617db40.png)

**Comment by G3neralGrant** [comment] 2017-01-12 23:43
this corridor isn't even for BTS
![image](https://cloud.githubusercontent.com/assets/24685304/21912885/b8c4893c-d8dd-11e6-8380-e30924f05555.png)

**Comment by LautaroL20** [comment] 2017-01-12 23:43
Well, the BTS Style is pretty much broken right now....

**Comment by ZombiePwner1** [comment] 2017-01-15 13:46
@G3neralGrant Don't use BTS corridors except for 1 and 2.

**Comment by ZombiePwner1** [comment] 2017-01-20 01:20
This is a duplicate of https://github.com/BEEmod/BEE2-items/issues/756

**Closed by ZombiePwner1** 2017-01-20 01:20 UTC
Labels: BTS, Bug, Leak
