### ISSUE TITLE
Conveyor belt from Old Aperture doesn't work

### ISSUE THREAD

**Issue by ZeynAlex** [BEEmod/BEE2-items#4218] opened 2022-08-19 14:33 UTC
### BEE2 Application Version

4.41.0

### BEE2 Package Version

4.41.0 + ucp's

### What operating system are you running on?

Windows 10 (64bit)

### Description of the bug

Conveyor belt doesn't move at all in 50s and 80s styles.

### Expected behavior

I expect it to move.

### Steps to reproduce

Step 1. Place conveyor belt
Step 2. Try to activate it
Step 3. Run map
Step 4. It doesn't move

### Logs and Reports

```shell
-
```

### Additional information

I am creating 80s styled map with conveyor belt.
When I used all the same BEE2.4 settings in the same map, but using Clean style conveyor worked.
Also I have tried it in empty 50s map, but conveyor belt didn't work.

**Comment by Konclan** [comment] 2022-08-19 19:48
Duplicate of #3977

**Closed by Konclan** 2022-08-19 19:48 UTC
Labels: Bug
