### ISSUE TITLE
Sphere passes through angled panel in P1

### ISSUE THREAD

**Issue by Byzarru** [BEEmod/BEE2-items#1515] opened 2017-01-30 04:48 UTC
![20170129224022_1](https://cloud.githubusercontent.com/assets/22107242/22412533/e2cc650c-e674-11e6-9f97-6a718a698895.jpg)
The portal shot was made after the phase-through. The sphere rolled along the glass and phased beneath the angled panel.

**Comment by ZombiePwner1** [comment] 2017-01-30 08:11
This is a duplicate of https://github.com/BEEmod/BEE2-items/issues/1376 doesn't matter when the panel is portable or not cubes are very buggy with the P1 angled panels.

**Closed** 2017-01-30 08:11 UTC
Labels: Bug, Duplicate, Portal 1
