### ISSUE TITLE
[PRL21.5 Bug] 80´s Old Aperture: The SP Entry door is missing its "Frames"

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#770] opened 2016-09-04 17:42 UTC
![20160904143527_1](https://cloud.githubusercontent.com/assets/12244376/18232797/db733906-72ad-11e6-9941-a17af4f3a724.jpg)

**Comment by TheDarkBomber** [comment] 2016-09-04 19:29
Duplicate of #747.

**Comment by LautaroL20** [comment] 2016-09-04 19:33
No.

**Comment by TheDarkBomber** [comment] 2016-09-04 19:40
Yes, it is the same bug.

**Comment by LautaroL20** [comment] 2016-09-04 19:48
Thats is 60´s... This is 80´s, the title clearly says it. Id suggest to get a pair of glasses.

**Comment by TheDarkBomber** [comment] 2016-09-04 20:13
It's still the same bug. Still Old Aperture.

**Comment by LautaroL20** [comment] 2016-09-04 21:14
Not exactly same, they are slightly different. If you got glasses, you can compare the screenshots between each post and you'll see differences. Thays why they´re called 50´s 60´s 70´s and 80´s.

**Comment by TheDarkBomber** [comment] 2016-09-04 21:19
Just because they are different decades, it does not mean they are entirely different bugs.

**Comment by LautaroL20** [comment] 2016-09-04 21:27
Ok, lets ask @TeamSpen210 who is right then. Is my post really a duplicate of https://github.com/TeamSpen210/BEE2-items/issues/747 like DarkBomber says?

**Comment by TeamSpen210** [comment] 2016-09-04 21:51
I'd say kind of, actually they'd be subcategories of the general issue that many retro corridors need to be redone.

**Comment by LautaroL20** [comment] 2016-09-04 21:57
But like you said on the past, its better to split the issues on different post so you can have a more acurate idea and they can be closed separately.

**Comment by ZombiePwner1** [comment] 2016-09-05 00:38
I tested some 80's entries and I did not see any missing frames.

**Comment by TeamSpen210** [comment] 2016-09-05 00:46
You probably won't see through the side like that, the hole might be obscured by the door parts. (When it opens, the sides just move into the wall).

**Comment by ZombiePwner1** [comment] 2016-09-05 05:59
I made sure not to get in contact with the trigger.

**Comment by TeamSpen210** [comment] 2016-09-10 07:54
It's not fixed...

**Closed** 2018-03-29 09:12 UTC
Labels: Bug, Fixed, Old Aperture
