### ISSUE TITLE
Issue when building map with the sendificator (4.37.0)

### ISSUE THREAD

**Issue by BigUpBoris2024** [BEEmod/BEE2-items#3581] opened 2020-12-21 13:30 UTC
Any test chamber with the sendificator in it wont build. It stops at building geometry, then says 'there was an error building the puzzle'

This is from the console on the default puzzle with just the sendificator:

[PORTAL2 PUZZLEMAKER]  CVoxelTestChamber::Export VMF C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf ...
[PORTAL2 PUZZLEMAKER]  CVoxelTestChamber::Export VMF success, chamber size: (8,6,4)
[PORTAL2 PUZZLEMAKER]  Compilation time (after export): 29 (ms)

VBSP failed.

[I] vbsp.main(): BEE2 v VBSP hook initiallised.
[I] cond.core.import_conditions(): Imported all conditions modules!
[I] vbsp.main(): Map path is "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf"
[I] vbsp.main(): New path: "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[I] vbsp.main(): PeTI map detected!
[I] vbsp.main(): Loading settings...
[W] texturing.load_config(): overlays: Unknown texture names faithfling, faithland
[W] texturing.load_config(): special: Unknown texture names edge_special, pedestalside
[W] vbsp_options.load(): Extra config options: {'glass_scale': '0.15', 'staticpan': 'instances/BEE2/clean/static_panel/', 'voice_pack': 'BEE2_GLADOS_CLEAN'}
[I] cond.core.build_itemclass_dict(): Read 30 item IDs, with 48 embeds!
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_ANGLED_BLOCK_60", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_ANGLED_BLOCK_45", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_ANGLED_BLOCK_30", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_ANGLED_BLOCK_CORNER_60", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_ANGLED_BLOCK_CORNER_60", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_ANGLED_BLOCK_CORNER_45", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_ANGLED_BLOCK_CORNER_45", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_ANGLED_BLOCK_CORNER_30", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_ANGLED_BLOCK_CORNER_30", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_FLAT_QUARTER", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_FLAT_HALF", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_FLAT_THREE_QUARTER", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE_PGUN_BASE", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE_PGUN_BASE", which is no longer used.
[I] cubes.parse_conf(): Parsed 7 cube types, 1 dropper types and 4 addons.
[I] fizzler.read_configs(): Loaded 14 fizzlers.
[I] vbsp.load_settings(): Settings Loaded!
[I] vbsp.load_map(): Parsing Map...
[I] vbsp.load_map(): Reading Map...
[I] vbsp.load_map(): Loading complete!
[I] antlines.parse_antlines(): Parsing antlines...
[I] antlines.parse_antlines(): Done! (0 antlines)
[I] vbsp.get_map_info(): Forcing elevator spawn!
[I] vbsp.mod_entryexit(): Setting SP Exit to 1
[I] vbsp.mod_entryexit(): Setting SP Entry to 6
[I] vbsp.get_map_info(): Game Mode: SP
[I] vbsp.get_map_info(): Is Preview: False
[I] brushLoc.read_from_map(): Analysed map, filling air... (12 starting positions..)
[I] brushLoc.read_from_map(): Air filled!
[I] texturing.setup(): Generating texture clumps...
[I] texturing.setup(): NORMAL.FLOOR.BLACK: 17 Clumps for 370 tiles
[I] texturing.setup(): Generating texture clumps...
[I] texturing.setup(): NORMAL.CEILING.WHITE: 11 Clumps for 370 tiles
[I] texturing.setup(): Generating texture clumps...
[I] texturing.setup(): NORMAL.CEILING.BLACK: 11 Clumps for 370 tiles
[I] texturing.setup(): Generating texture clumps...
[I] texturing.setup(): NORMAL.WALL.WHITE: 22 Clumps for 370 tiles
[I] texturing.setup(): Generating texture clumps...
[I] texturing.setup(): NORMAL.WALL.BLACK: 22 Clumps for 370 tiles
[I] texturing.setup(): Generating texture clumps...
[I] texturing.setup(): PANEL.FLOOR.BLACK: 17 Clumps for 370 tiles
[I] texturing.setup(): Generating texture clumps...
[I] texturing.setup(): PANEL.CEILING.BLACK: 11 Clumps for 370 tiles
[I] texturing.setup(): Generating texture clumps...
[I] texturing.setup(): PANEL.WALL.WHITE: 22 Clumps for 370 tiles
[I] texturing.setup(): Generating texture clumps...
[I] texturing.setup(): PANEL.WALL.BLACK: 22 Clumps for 370 tiles
[I] cond.core.check_all(): Checking Conditions...
[I] cubes.link_cubes(): SPLAT File: ['instances/bee2/logic/gel_splat.vmf']
[I] cond.catwalks.res_make_catwalk(): Starting catwalk generator...
[I] cond.scaffold.res_unst_scaffold(): Running Scaffold Generator (BEE2_SCAFFOLD)...
[I] cond.scaffold.res_unst_scaffold(): Finished Scaffold generation!
[I] connections.gen_item_outputs(): Generating item IO...
[I] connections.gen_item_outputs(): Item IO generated.
[I] vbsp.set_elev_videos(): Elevator type: FORCE
[I] voiceLine.add_voice(): Adding Voice Lines!
[W] BEE2_config.load(): Config "bee2\voice.cfg" not found! Using defaults...
[W] BEE2_config.load(): Config "bee2\mid_voice.cfg" not found! Using defaults...
[I] voiceLine.add_voice(): Adding Base instance!
[I] voiceLine.add_voice(): Quote events: []
[I] voiceLine.find_group_quotes(): "ENTRY": 2/15 quotes..
[I] voiceLine.add_quote(): Adding quote: "Line_Human"
 | 	{
 | 	"ID" "SENDIFICATOR_LASERS_LUMP_OF_COAL"
 | 	"Choreo"
 | 		{
 | 		"1" "scenes/npc/glados/coop_test_chamber_both15.vcd"
 | 		"2" "scenes/npc/glados/sp_laser_redirect_intro_entry03.vcd"
 | 		"3" "scenes/npc/glados/sp_paint_jump_trampoline_entry01.vcd"
 | 		}
 | 	}
 | 
 |___

[I] voiceLine.find_group_quotes(): "EXIT": 1/5 quotes..
[I] voiceLine.add_quote(): Adding quote: "Line"
 | 	{
 | 	"ID" "GENERIC_WADDLE"
 | 	"Choreo" "scenes/npc/glados/testchambermisc12.vcd"
 | 	}
 | 
 |___

[I] voiceLine.find_group_quotes(): "MIDCHAMBER": 1/9 quotes..
[I] voiceLine.add_voice(): 1 Mid quotes
[I] voiceLine.add_quote(): Adding quote: "Line"
 | 	{
 | 	"ID" "MULTI_CAVE"
 | 	"File" "clean/cave_reaction.vmf"
 | 	}
 | 
 |___

[I] voiceLine.add_voice(): Done!
[W] packing.pack_list(): Packlist "PACK_HMW_SENDTOR_LOGIC" does not exist!
[I] vbsp.set_player_portalgun(): Setting Portalgun:
[I] vbsp.set_player_portalgun(): Blue: Y, Orange: Y
[I] vbsp.set_player_portalgun(): Done!
[I] cond.core.check_all(): Map has attributes: ['sendificator', 'sendtor', 'needsportalman', 'spawn_dual']
[I] cond.core.check_all(): instanceLocs cache: CacheInfo(hits=3328, misses=338, maxsize=256, currsize=256)
[I] cond.core.check_all(): Style Vars: {'doorcameras': True, 'restartonexit': True, 'multiversecave': True, 'fixfizzlerbump': False, 'nomidvoices': False, 'unlockdefault': False, 'allowgoomist': True, 'funnelallowswitchedlights': True, 'enableshapesignageframe': True}
[I] cond.core.check_all(): Global instances: {'instances/bee2/logic/hmw/sendtor_manager.vmf'}
[I] vbsp.add_extra_ents(): Adding Music...
[I] vbsp.add_extra_ents(): Adding global ents...
[I] vbsp.add_extra_ents(): Adding Global PTI Ents
[I] vbsp.change_ents(): Editing Other Entities...
[I] tiling.generate_brushes(): Generating tiles...
[I] tiling.generate_brushes(): Generating goop...
[I] vbsp.change_overlays(): Editing Overlays...
[I] vbsp.fix_worldspawn(): Editing WorldSpawn
[I] vbsp.save(): Saving New Map...
[I] vbsp.save(): Complete!
[I] <Valve>.run_compiler(): Calling original VBSP...
[I] <Valve>.run_compiler(): Args: '-game', 'C:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/', 'C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\\maps\\styled\\preview.vmf'
[I] <valve>.vbsp(): Valve Software - vbsp.exe (Nov 12 2019)
[I] <valve>.vbsp(): 4 threads
[I] <valve>.vbsp(): materialPath: C:\Program Files (x86)\Steam\steamapps\common\Portal 2\portal2\materials
[I] <valve>.vbsp(): Loading C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf
[I] <valve>.vbsp(): ConVarRef gpu_level doesn't point to an existing ConVar
[I] <valve>.vbsp(): fixing up env_cubemap materials on brush sides...
[I] <valve>.vbsp(): ProcessBlock_Thread: 0...1...2...3...4...5...6...7...8...9...10 (0)
[I] <valve>.vbsp(): ProcessBlock_Thread: 0...1...2...3...4...5...6...7...8...9...10 (0)
[I] <valve>.vbsp(): Processing areas...done (0)
[I] <valve>.vbsp(): Building Faces...done (0)
[I] <valve>.vbsp(): Chop Details...done (0)
[I] <valve>.vbsp(): Find Visible Detail Sides...
[I] <valve>.vbsp(): Merged 410 detail faces...done (1)
[I] <valve>.vbsp(): Merging details...done (0)
[I] <valve>.vbsp(): FixTjuncs...
[I] <valve>.vbsp(): PruneNodes...
[I] <valve>.vbsp(): WriteBSP...
[I] <valve>.vbsp(): done (0)
[I] <valve>.vbsp(): writing C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.prt...Building visibility clusters...
[I] <valve>.vbsp(): done (0)
[I] <valve>.vbsp(): Finding displacement neighbors...
[I] <valve>.vbsp(): Finding lightmap sample positions...
[I] <valve>.vbsp(): Displacement Alpha : 0...1...2...3...4...5...6...7...8...9...10
[I] <valve>.vbsp(): Building Physics collision data...
[I] <valve>.vbsp(): done (1) (403770 bytes)
[I] <valve>.vbsp(): Placing detail props : 0...1...2...3...4...5...6...7...8...9...10
[I] <valve>.vbsp(): Compacting texture/material tables...
[I] <valve>.vbsp(): Reduced 3113 texinfos to 532
[I] <valve>.vbsp(): Reduced 51 texdatas to 46 (1453 bytes to 1324)
[I] <valve>.vbsp(): Writing C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.bsp
[I] <valve>.vbsp(): 
[I] <valve>.vbsp(): nummapplanes:     (  8758 / 65536 )
[I] <valve>.vbsp(): nummapbrushes:    (  1104 /  8192 )
[I] <valve>.vbsp(): nummapbrushsides: (  8957 / 65536 )
[I] <valve>.vbsp(): num_map_overlays: (     2 /   512 )
[I] <valve>.vbsp(): nummodels:        (    35 /  1024 )
[I] <valve>.vbsp(): num_entities:     (   391 / 16384 )
[I] <valve>.vbsp(): 
[I] <valve>.vbsp(): 3 seconds elapsed
[I] <valve>.vbsp(): CDynamicFunction: Loading library 'Kernel32.dll' (775F0000)
[I] <valve>.vbsp(): CDynamicFunction: Lookup of 'TryEnterCriticalSection' in 'Kernel32.dll': 77783060
[I] <valve>.vbsp(): CDynamicFunction: Closing library 'Kernel32.dll' (775F0000)
[I] vbsp.run_vbsp(): VBSP Done!
[I] vbsp.process_vbsp_log(): Retrieved counts: {'brush': ('1104', '8192'), 'overlay': ('2', '512'), 'entity': ('391', '16384')}
[I] BEE2_config.save(): Saving changes in config "C:\Users\(myname)\AppData\Roaming\BEEMOD2\config\compile.cfg"!
[I] vbsp.make_vrad_config(): Generating VRAD config...
[E] (unknown file).(unknown function)(): Uncaught Exception:
Traceback (most recent call last):
  File "F:\Git\BEE2.4\src\compiler_launch.py", line 13, in <module>
  File "F:\Git\BEE2.4\src\vbsp.py", line 2101, in main
  File "F:\Git\BEE2.4\src\vbsp.py", line 1754, in make_vrad_config
  File "F:\Git\BEE2.4\src\cubes.py", line 637, in write_vscripts
FileNotFoundError: [Errno 2] No such file or directory: 'bee2/inject/cube_vscript_01.nut'
[12596] Failed to execute script compiler_launch

**Comment by LautaroL20** [comment] 2020-12-21 16:12
This is a duplicate of: https://github.com/BEEmod/BEE2-items/issues/3307

**Closed by LautaroL20** 2020-12-21 16:12 UTC
Labels: Bug, Compile Error, Duplicate

**Comment by BigUpBoris2024** [comment] 2020-12-21 16:16
My report (3581) and I believe 3408 are different issues. On the report in 3307, ('When I press the button, the blue particle effect appears, but the cube isn't sent') shows that the level has been built. I cant get the test chamber to build.
