### ISSUE TITLE
Neurotoxin Vent can be portallized

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#2084] opened 2017-06-30 14:59 UTC
![Image](https://user-images.githubusercontent.com/12244376/27741427-72879580-5d8b-11e7-8814-ab44512bcb7b.jpg)

**Comment by Luke18033** [comment] 2017-06-30 15:03
Duplicate of #1942.

**Closed by Luke18033** 2017-06-30 15:03 UTC
Labels: Bug
