### ISSUE TITLE
Half-OBS rooms not compatible

### ISSUE THREAD

**Issue by sparrowdragon** [BEEmod/BEE2-items#4414] opened 2024-03-20 21:26 UTC
### BEE2 Application Version

4.44.1 64bit

### BEE2 Package Version

4.44.0 64bit

### What operating system are you running on?

Windows 11

### Description of the bug

I always got a compile failure (shown by the default PETi error warning) each time I added a half-observation room to a Portal 1 or Hybrid-style map

### Expected behavior

When this didn't work I expected a 4.39 version of the items package to work, but I got the same result.

### Steps to reproduce

1. Select Portal 1 or Hybrid style in application
2. Open Portal 2 and create a fresh new chamber
3. Add the half observation room item, you can pick any cube type.
4. Press the compile and run button, and wait for results.

**Comment by TeamSpen210** [comment] 2024-03-20 21:35
What specific error did you get? Open the developer console.

**Comment by TeamSpen210** [comment] 2024-03-21 03:09
I can't reproduce this, the half obs room doesn't even use Cube Type, it uses Button Type. Is this a custom item?

**Comment by vrad-exe** [comment] 2024-03-29 09:54
Closing due to not enough info

**Closed by vrad-exe** 2024-03-29 09:54 UTC
Labels: Bug
