### ISSUE TITLE
Very tall or wide Closed Solid Field has missing graphics

### ISSUE THREAD

**Issue by snorepion** [BEEmod/BEE2-items#1954] opened 2017-05-11 16:49 UTC
![brokencsf](https://cloud.githubusercontent.com/assets/24462989/25961387/5bb9d85c-3637-11e7-9975-c54cf89d4e7e.png)

**Comment by snorepion** [comment] 2017-05-11 16:51
![workingcsf](https://cloud.githubusercontent.com/assets/24462989/25961514/ce527450-3637-11e7-8373-25ab1ec29364.png)
Works fine with one voxel wide fields.

**Comment by Luke18033** [comment] 2017-05-11 16:59
Duplicate of #1918.

**Closed by Luke18033** 2017-05-11 16:59 UTC
Labels: Bug, Unpacked Resource

**Comment by IceTudor** [comment] 2017-10-14 11:58
Doesn't work either way for me, not even one voxel space. It has no texture at all, maybe the "Fizzlers don't show unless reactivated" bug, since the only time i tested it in voxel wide was in the "start enabled mode". Not sure, but the CSF, Rocket Turret and P1 Portals are horribly broken, meanwhile I'm trying to use all 3.
