### ISSUE TITLE
Funnels show as errors in the editor with the 1960s style

### ISSUE THREAD

**Issue by Omegafredo** [BEEmod/BEE2-items#4068] opened 2022-01-22 11:06 UTC
### BEE2 Application Version

4.41.0

### BEE2 Package Version

4.41.0

### What operating system are you running on?

Windows 10 (64bit)

### Description of the bug

The funnels are errors when editing.
![image](https://user-images.githubusercontent.com/71580393/150635901-a647010f-3396-4b8e-8285-7996c4d23bea.png)

### Expected behavior

The funnels would use their actual model.

### Steps to reproduce

1. Set the style to the 1960s style
2. Place a funnel in a level

### Additional information

They work fine when playing.
![image](https://user-images.githubusercontent.com/71580393/150635967-399be603-c4ee-4064-9fe7-2db08e5a83e4.png)

**Comment by Luke18033** [comment] 2022-01-22 18:36
Duplicate of #4006

**Closed by Luke18033** 2022-01-22 18:36 UTC
Labels: Bug
