### ISSUE TITLE
when plans to release the next update.

### ISSUE THREAD

**Issue by love-portal** [BEEmod/BEE2-items#1347] opened 2017-01-07 11:40 UTC

**Comment by TheDarkBomber** [comment] 2017-01-07 11:41
Duplicate of #1331.

**Closed** 2017-01-07 15:21 UTC
Labels: Duplicate

**Comment by Luke18033** [comment] 2017-01-07 17:05
Stop asking when the next release is coming, it'll be soon...

**Comment by TheDarkBomber** [comment] 2017-01-07 17:09
When is the next revision (commit) of the Developer Version coming??
