### ISSUE TITLE
Portal 1 Style 'White Hole Light' stays a strip light and glitches in and out. 

### ISSUE THREAD

**Issue by Entilled** [BEEmod/BEE2-items#3832] opened 2021-06-22 18:16 UTC
I have been using version 4.39.1

White Hole Lights have been turning into regular strip lights and glitch as if they've been overlapping another texture.

All I did was place down them for better lighting in my chamber and I was met with surprise when I started up the chamber. 

As far as I know, the console didn't show me an error but I took a picture of the bug. 
![20210622140152_1](https://user-images.githubusercontent.com/75185125/122978402-7a7af180-d364-11eb-9bf1-6f2820f23f05.jpg)

**Comment by FrozenDragon0** [comment] 2021-06-23 00:08
Duplicate of https://github.com/BEEmod/BEE2-items/issues/3709 

It's best to search for issues on the github you've found already before posting a duplicate.

**Closed by FrozenDragon0** 2021-06-23 00:08 UTC
Labels: Bug, Duplicate
