### ISSUE TITLE
BTS Wheatley

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2-items#1404] opened 2017-01-15 17:22 UTC
This would use a different set of lines where Wheatley is helping you get through BTS areas and reach GLaDOS, rather than trying to get you to test. On Monitors, Wheatley would be attached to his management rail, with BTS textures behind him.

**Comment by ZombiePwner1** [comment] 2017-01-15 22:00
This is a duplicate of https://github.com/BEEmod/BEE2-items/issues/827

**Closed** 2017-01-15 22:00 UTC
Labels: Duplicate, Suggestion

**Comment by TheDarkBomber** [comment] 2017-01-15 22:05
Still needs `BTS` label.
