### ISSUE TITLE
Add Square beams in bts where yellow 2x2 texture spawns

### ISSUE THREAD

**Issue by ellingtonvengaboysmuseum** [BEEmod/BEE2-items#2347] opened 2017-10-31 22:51 UTC
Add Square beams in bts where ever those yellow 2x2 textures spawn, look at the image, if possible by some coding or something, square beams should be added and embedded into the voxel where ever those 2x2 yellow gridded textures show up in BTS... this way it will match how they look in real bts in the original game...

Or remove that specific texture from the BTS style config and make a item like the cutout tile that will make these things on the ceiling, walls, or floor or where ever placed...

![preview0045](https://user-images.githubusercontent.com/11165643/32252584-650ed8c2-be6c-11e7-8072-aec24af6954d.jpg)

**Comment by Luke18033** [comment] 2017-11-01 21:46
Duplicate of #1278 (your own issue). Will you please stop opening duplicate issues, it's not that hard to do a quick search.

**Closed by Luke18033** 2017-11-01 21:46 UTC
Labels: BTS, Enhancement
