### ISSUE TITLE
[New item] Ping panel for coop

### ISSUE THREAD

**Issue by TheEnderek0** [BEEmod/BEE2-items#3341] opened 2020-06-22 09:11 UTC
This item is used in hammer maps. It's a panel that you can set who can ping it, and when that person pings it it sends signal to for ex. cube dropper.

**Comment by Flash4433** [comment] 2020-06-22 11:20
Duplicate of #702 , right?

**Comment by FrozenDragon0** [comment] 2020-06-22 11:41
@Flash4433 Technically yes.

**Closed by FrozenDragon0** 2020-06-22 11:41 UTC
Labels: Duplicate, Suggestion
