### ISSUE TITLE
New item: antline laser

### ISSUE THREAD

**Issue by SCIENTIST2004** [BEEmod/BEE2-items#2758] opened 2018-07-17 15:35 UTC
![20180717175203_1](https://user-images.githubusercontent.com/35931028/42825857-a2d731cc-89eb-11e8-9e41-a46bd618719d.jpg)
![20180717175212_1](https://user-images.githubusercontent.com/35931028/42825935-d8c4b624-89eb-11e8-8fd6-c90053616240.jpg)
and I suggest to make little emitters.
Step 1:
place the first emitter at one side and the second emitter at another side
Step 2:
Link the first emitter to output and the second emitter to input
Step 3:
Link the first emmitter to the second emittet
![exp4](https://user-images.githubusercontent.com/35931028/42827940-3c0437ce-89f0-11e8-9e50-116d68603866.png)
![exp5](https://user-images.githubusercontent.com/35931028/42827948-3eede0fc-89f0-11e8-99d0-390d4746cce1.png)

**Comment by SomePeople27** [comment] 2018-07-17 17:31
Already being done.

**Comment by Konclan** [comment] 2018-07-17 22:37
Duplicate of #496, and yes the design is already finished and ready to be implemented. I don't know if it will be in the next release though.

**Closed** 2018-07-17 22:37 UTC
Labels: Duplicate

**Comment by TeamSpen210** [comment] 2018-07-19 01:13
I haven't made the non-clean variations.
