### ISSUE TITLE
Missing Portal 1 Unstationary Scaffold Slot Instance

### ISSUE THREAD

**Issue by TwoKrazy** [BEEmod/BEE2-items#3801] opened 2021-05-26 19:00 UTC
**BEE2 Version: 4.39.1**

<details>
<summary>Error Log</summary>

[I] <valve>.vbsp(): Could not open instance file instances/BEE2/p1/items/scaffold/slot.vmf

</details>

**Additional information:
When I saw this error, I looked in the files to see if the instance was corrupted or something. When I opened the folder, the instance wasn't there at all. Copying the instance from the clean one fixes the error, but no connections are being made from the slot to the rest of the track, even when it shows the connection in the editor.**

**Edit: Slot connections don't work in the clean styles either.**

**Comment by HeimlichLaboratories** [comment] 2021-05-26 19:40
Does this count as a duplicate of #3777 ?

**Comment by Luke18033** [comment] 2021-09-11 04:03
Duplicate of #3384

**Closed by Luke18033** 2021-09-11 04:03 UTC
Labels: Bug, Portal 1, Compile Error
