### ISSUE TITLE
Gel-sensitive cubes for Aperture Tag

### ISSUE THREAD

**Issue by ncrecc** [BEEmod/BEE2-items#2402] opened 2017-11-11 21:00 UTC
Some kind of item that would indicate "hey, any cubes from this dropper should be fizzled if they get blue/orange/any gel on them"

This would prevent bouncy cubes making the puzzle unwinnable or slippery cubes making reflection-cube-laser-puzzles more annoying

Perhaps there could be a little icon on the cube representing that X gel is not allowed on it, though if there is it should be toggle-able since the original Aperture Tag didn't have or need anything to indicate "this cube fizzles with blue gel".

**Comment by Luke18033** [comment] 2017-11-11 21:08
Sort of a duplicate of #585, which would also solve this problem.

**Comment by ncrecc** [comment] 2017-11-11 21:10
It seems unpaintable cubes would deny both kinds of paint, though. With these cubes you can choose which type of paint they accept and which they deny.

**Comment by TeamSpen210** [comment] 2017-11-11 21:54
We can't detect specific paints, only when it's painted with anything.

**Comment by Endermage77** [comment] 2017-11-11 22:40
I believe there's an item called a Cube Cleaner which is basically a small hole in the wall with water in that you can shove cubes into to clean them.

**Comment by ellingtonvengaboysmuseum** [comment] 2017-11-12 01:15
@TeamSpen210 - they should be for any style in any game...

**Comment by TeamSpen210** [comment] 2017-11-12 01:20
How is that relevant?

**Comment by IceTudor** [comment] 2017-11-13 12:52
A better way to clean cubes in APTAG is to make the gun spray cleansing gel, as you could erase in the original TAG: Power of paint game.

**Comment by Endermage77** [comment] 2017-11-13 23:44
I brought up the paint cleaner because it seemed to me that the poster wanted an easy way of fixing cubes that he accidentally painted and had no way to unpaint. I mention the cube cleaner because that is exactly what it does.

**Comment by ncrecc** [comment] 2017-11-18 03:05
I'm mostly suggesting this because it was in the original Aperture Tag, and the author devoted a commentary node to explaining why it works in-universe.

**Comment by Konclan** [comment] 2021-08-15 03:39
UCP

**Closed by Konclan** 2021-08-15 03:39 UTC
Labels: New Item
