### ISSUE TITLE
1970s buttons not working

### ISSUE THREAD

**Issue by GrayGravity** [BEEmod/BEE2-items#3567] opened 2020-11-29 18:58 UTC
Weighted buttons in the 1970s style do not work at all. Players nor cubes do not activate it.

Images:
https://ibb.co/Zx8THsH

**Comment by LautaroL20** [comment] 2020-11-29 21:23
This is a duplicate of: https://github.com/BEEmod/BEE2-items/issues/3488

**Closed by LautaroL20** 2020-11-29 21:23 UTC
Labels: Bug, Done, Duplicate, Old Aperture
