### ISSUE TITLE
BTS 3D Skybox Textures don't match

### ISSUE THREAD

**Issue by ellingtonvengaboysmuseum** [BEEmod/BEE2-items#2346] opened 2017-10-31 22:49 UTC
The BTS 3D Skybox Textures don't match, take a look at the image and you will know what i mean, this has always drove me a bit nuts... Either change the BTS wall textures to match the pit (easy) or change the pit wall textures to match the current bts (hard)

![preview0055](https://user-images.githubusercontent.com/11165643/32252530-27bac238-be6c-11e7-9732-3e8f5f2b0eee.jpg)

**Comment by Luke18033** [comment] 2017-10-31 22:53
Duplicate of #1451.

**Closed by Luke18033** 2017-10-31 22:53 UTC
