### ISSUE TITLE
Portal 1 Item Dropper Void

### ISSUE THREAD

**Issue by WelderGame3** [BEEmod/BEE2-items#3286] opened 2020-04-26 20:18 UTC
I wasn't sure if anyone made an issue about this, I'm not sure what I would even search to match this description, but...

The Portal 1 Item Droppers delete the brushes around it, and you can see a square of just void around the dropper, this to me seems like a part design error, or otherwise, I don't know.

**Comment by Luke18033** [comment] 2020-04-26 20:43
Duplicate of #3175... Yeah, this is the right issue.

**Closed by Luke18033** 2020-04-26 20:43 UTC

**Comment by LautaroL20** [comment] 2020-04-27 20:27
Do not forget to apply the corresponding label after closing an issue.
