### ISSUE TITLE
Rotating panel 

### ISSUE THREAD

**Issue by BETTEREXTENEDEDITORMOD** [BEEmod/BEE2-items#3128] opened 2019-10-12 00:08 UTC
i've seen these in Ben77 maps and was wondering if you could implement it into Beemod
![Capture rotate_f](https://user-images.githubusercontent.com/31172185/66691232-a0706900-ec49-11e9-92c2-ee31e72ae00e.JPG)
![Capture_rotate_t](https://user-images.githubusercontent.com/31172185/66691236-abc39480-ec49-11e9-8bc2-06816d8fc52f.JPG)

**Comment by LautaroL20** [comment] 2019-10-12 00:11
Interesting suggestion!

**Comment by Luke18033** [comment] 2019-10-12 00:17
Duplicate of #2204.

**Closed by Luke18033** 2019-10-12 00:17 UTC
Labels: New Item

**Comment by BETTEREXTENEDEDITORMOD** [comment] 2019-10-12 00:19
i can't believe i've made a duplicate of my own issue

**Comment by Luke18033** [comment] 2019-10-12 00:21
Oh ha, I didn't even notice.

**Comment by LautaroL20** [comment] 2019-10-12 00:36
LOL
