### ISSUE TITLE
[Enchancement] Add some plants to some overgrown test elements ex. Buttons cube droppers.

### ISSUE THREAD

**Issue by ZombiePwner1** [BEEmod/BEE2-items#726] opened 2016-08-22 00:51 UTC
I've already given the overgrown spawn to u @TeamSpen210 so now I would like to see some plants added to some test elements.

**Comment by Konclan** [comment] 2017-11-25 14:39
This is a duplicate of several different requests, #390 #451 $468 #530

**Closed** 2017-11-25 16:06 UTC
Labels: Enhancement, Overgrown
