### ISSUE TITLE
Some half/center/cross walls are generating random overlapping nodraw brushes

### ISSUE THREAD

**Issue by Miley-Liu** [BEEmod/BEE2-items#3151] opened 2019-11-23 09:54 UTC
### Half walls texture/model seems to be broken as well as it's collisions.
_Here's image showing that:_
![defective_antlinerouter](https://user-images.githubusercontent.com/58081984/69476826-0b7f9480-0ddf-11ea-81e6-51795c7f4bf4.png)

> Note: this is after the **4.36** update.

![image](https://user-images.githubusercontent.com/58081984/69477026-a11c2380-0de1-11ea-9717-19f4684e82c8.png)

> In-editor view of the same place as on first screenshot.

----

Screenshot of the issue in Hammer:
![image](https://user-images.githubusercontent.com/19228201/69483881-abd6b880-0de1-11ea-940a-14aa2a8dfcc3.png)

**Comment by TeamSpen210** [comment] 2019-11-23 09:58
I'm really not sure what this screenshot is even of. What does it look like in the editor view?

**Comment by TeamSpen210** [comment] 2019-11-23 09:58
Are you sure it's that item - does deleting it or moving it prevent this issue?

**Comment by Miley-Liu** [comment] 2019-11-23 09:59
In editor it looks fine

**Comment by Miley-Liu** [comment] 2019-11-23 09:59
I'll check if moving helps

**Comment by Miley-Liu** [comment] 2019-11-23 10:06
![image](https://user-images.githubusercontent.com/58081984/69477001-3834ab80-0de1-11ea-9f80-e90a9b4f676f.png)
Here's the same place in editor @TeamSpen210

**Comment by Miley-Liu** [comment] 2019-11-23 10:14
Okay, I tried deleting and moving, but problem persists.

**Comment by TeamSpen210** [comment] 2019-11-23 10:15
Okay, the problem is with the half walls there, not the router. Delete those, there might be duplicates there or something.

**Comment by Miley-Liu** [comment] 2019-11-23 10:17
Like you mean there's two on eachother?

**Comment by TeamSpen210** [comment] 2019-11-23 10:17
Yes.

**Comment by Miley-Liu** [comment] 2019-11-23 10:18
I'm gonna make a small testing env to see

**Comment by Miley-Liu** [comment] 2019-11-23 10:20
So far I experienced during the debugging is that if I try to place two half walls on each other it throws error

**Comment by Miley-Liu** [comment] 2019-11-23 10:21
The other test that's shown on screenshots was done before **4.36**

**Comment by Miley-Liu** [comment] 2019-11-23 10:31
I deleted all half walls in previous one and placed them back anew and I'll see if that's the case

**Comment by Miley-Liu** [comment] 2019-11-23 10:35
I noticed that even doing that causes the bug

**Comment by Miley-Liu** [comment] 2019-11-23 10:44
@TeamSpen210 Making new map with half walls that are not overlayed on each other still causes the bug

**Comment by Miley-Liu** [comment] 2019-11-23 10:49
![image](https://user-images.githubusercontent.com/58081984/69477494-35d55000-0de7-11ea-809a-df53a83afd32.png)

![image](https://user-images.githubusercontent.com/58081984/69477499-42f23f00-0de7-11ea-8f93-102840e66ffd.png)

**Comment by LautaroL20** [comment] 2019-11-23 13:57
I have done some testing and this does not have anything to do with the mistake of having "duplicates" half-wall on each other, so this leak can perfectly happens in normal situations regardless. Also, the leak can happens with the centered or cross variants too, here are screenshots of the puzzlemaker and in-game results showing how the centered variant gets totally leaked:
![20191123102514_1](https://user-images.githubusercontent.com/12244376/69479619-138b0480-0dde-11ea-8f52-5e2559d8333e.jpg)
![20191123102533_1](https://user-images.githubusercontent.com/12244376/69479620-138b0480-0dde-11ea-9548-97eec293d485.jpg)

**Comment by LautaroL20** [comment] 2019-11-23 14:00
I did not test other styles yet other than original clean, but i do not have any reason to think this would be different in other styles...

**Comment by Luke18033** [comment] 2019-11-23 19:08
Decided to take a look in Hammer to see what was going on here.
![image](https://user-images.githubusercontent.com/19228201/69483814-d8d69b80-0de0-11ea-9b2b-c5d167e19d4b.png)
For whatever reason, some of the half walls are generating these big diagonal nodraw brushes surrounding them. There's also a nodraw brush overlapping the wall itself, which is what causes random parts of it to disappear. So as usual, this isn't a leak, just a visible nodraw. Either way, the question is: why? It only happens with some of them, and I can't figure out exactly what triggers it. TeamSpen would probably be able to figure out, it looks like an issue in the compiler itself.

**Comment by LautaroL20** [comment] 2019-11-23 19:32
It looks like something in the compiler gone nuts...

**Comment by TeamSpen210** [comment] 2019-11-23 20:38
Wow this is broken.

**Comment by HelloIamaPersonThatIsAliveAndHealthily** [comment] 2019-11-23 20:41
Very much...

**Comment by Luke18033** [comment] 2019-11-23 20:51
A while back you told me about something you implemented in the compiler for this item, that allows it to slightly recess into the wall without having an actual colliding embed space. If that still exists now, maybe it broke somehow?

**Comment by TeamSpen210** [comment] 2019-12-04 09:44
Turns out this was because `4 ≠ 4.00000000020000292`. So the second wall was trying to "hollow" the existing thin block again, generating a nodraw brush on the front and angled brushes where the squarebeams faces would be.

**Closed** 2020-07-19 08:15 UTC
Labels: Bug, Fixed
