### ISSUE TITLE
Incredibly huge leak with BTS Skybox (3d) and Cutout tiles

### ISSUE THREAD

**Issue by IceTudor** [BEEmod/BEE2-items#2675] opened 2018-05-01 11:09 UTC
I got a leak, not a small glimpse like other leaks, a full on giant hole in the ground with cutout tiles and bts 3d skybox, here's a pic

![huge leak](https://user-images.githubusercontent.com/28927843/39470923-08423eb0-4d49-11e8-8e5d-7412d10cfca0.png)

Portal style and wheatley voice, if theese have something to do with it, let me know.

**Comment by Fragmentation123** [comment] 2019-12-03 14:25
Why are cutout tiles so leak-inducing? They just cut holes into pieces of geometry...wait...holes...leaks
nevermind

**Comment by Luke18033** [comment] 2020-07-09 03:38
Duplicate of #1700

**Closed by Luke18033** 2020-07-09 03:38 UTC
Labels: Bug, Leak
