### ISSUE TITLE
New Trigger:Audio Trigger

### ISSUE THREAD

**Issue by Konata-Chan** [BEEmod/BEE2-items#1783] opened 2017-03-29 09:19 UTC
Ok.This is hard to explain.I have no idea if this is possible to implement.
Not to be confused with a trigger text
Is a trigger like the current ones.
But:

- When walking on it, it will play a dialog audio

- The dialogs can be modified with the option of "Timer" (Obviously.the audio limit is 30)

- Each number is a different audio.

- The audio of the trigger will adapt depending on which voiceline has chosen the map.Glados/
Announcer/Wheatley and others

This would be useful to make characters like the announcer speak more on the map.
And warn the player of danger from the next room
Example:The dialog "Turret activated" Of the Announcer
It would really sound good In a room with many turrets.

**Comment by TeamSpen210** [comment] 2017-03-29 09:35
The problem is that there aren't really many dialog options that correspond well with each other, so they won't be able to adapt.

**Comment by Byzarru** [comment] 2017-03-29 13:48
See #1169 for the Sound Emitter item. It works with triggers and inputs to emit a sound effect, which uses the ICP to select sound effects (but a default list is provided on the issue page) and the timer to select sounds.

**Comment by LautaroL20** [comment] 2017-03-29 16:30
This is a duplicate of: https://github.com/BEEmod/BEE2-items/issues/760

**Closed by LautaroL20** 2017-03-29 16:30 UTC
Labels: Duplicate
