### ISSUE TITLE
New Style: Manufacturing

### ISSUE THREAD

**Issue by ellingtonvengaboysmuseum** [BEEmod/BEE2-items#1546] opened 2017-02-05 17:48 UTC
new style: Manufacturing

it would be a variant of BTS except the textures used would be the wall textures seen in the background of this video behind ageis. (https://www.youtube.com/watch?v=j4k8vInD0JY&index=33&list=PLFW7HJ_xvmRcIZNiJVLY_dm1KrfFVRPfa) would use current bts bottomless pit textures and it would have a open bottomless pit and it would look similar to art therapy except with a open bottomless pit instead of a reservoir. it would mostly use resources from BTS too.

there would be lots of cubes piled up on shelves too as a aesthetic look

**Comment by Endermage77** [comment] 2017-02-05 18:21
It looks like this is just a mish-mash of already-existing styles.
So, instead of making this a specially-hand-crafted style in its own right, let's work on the Style wizard so we can actually create a warehouse mish-mash.

**Comment by ellingtonvengaboysmuseum** [comment] 2017-02-05 18:23
@Endermage77 - you just gave me a GENIUS idea for a new stylevar.

**Comment by Byzarru** [comment] 2017-02-05 19:50
@TheDarkBomber How soon until WASP comes out?

**Comment by Endermage77** [comment] 2017-02-05 19:53
On the other hand, if on the off-chance that this style takes off the ground, it should probably take more inspiration from the ware-cake-house at the very end of the Portal 1 story.

**Comment by ellingtonvengaboysmuseum** [comment] 2017-02-05 21:23
this style is the next one i am going to work on, it will prob come with pre release 25. it is just a alternative version of bts...

**Comment by TheDarkBomber** [comment] 2017-02-06 19:59
@Endermage77 You mean WASP?

**Comment by Endermage77** [comment] 2017-02-06 20:06
Not especially; I refer in particular to Issue #1196.

**Comment by TheDarkBomber** [comment] 2017-02-06 20:31
That's confirmed. But as WASP instead. Have a nice day. :)

**Comment by Endermage77** [comment] 2017-02-06 23:13
If you'd like a reference for some Warehouse Textures I went into the zone I mentioned above in Garry's Mod and took some screenshots: (I did the best I could with the flashlight)

The Cake as seen as close to the original view as I could do:
![20170206150735_1](https://cloud.githubusercontent.com/assets/25313980/22670525/6de2604c-ec7e-11e6-9d7a-dd1bfd36bcf4.jpg)

Floor Texture:
![20170206150753_1](https://cloud.githubusercontent.com/assets/25313980/22670541/84e0a718-ec7e-11e6-979c-28489a8ca6dd.jpg)

Wall Texture (Not visible in the original cutscene due to fog):
![20170206150802_1](https://cloud.githubusercontent.com/assets/25313980/22670569/a64e75a6-ec7e-11e6-9ed9-6e7ec44a597c.jpg)

Blank sphere racks:
![20170206150820_1](https://cloud.githubusercontent.com/assets/25313980/22670610/d1858386-ec7e-11e6-99f2-22372f7bc70e.jpg)

**Comment by Byzarru** [comment] 2017-02-06 23:16
Why are these anaglyphs?

**Comment by Endermage77** [comment] 2017-02-06 23:17
Er...
I dunno what an anaglyph is.

**Comment by Byzarru** [comment] 2017-02-06 23:18
Why are your pictures 3D?

**Comment by Endermage77** [comment] 2017-02-06 23:21
I just realized.
That effect is some sort of weird after-effect addition thingy from an addon that I've got.
I dunno how to turn it off.

**Comment by ellingtonvengaboysmuseum** [comment] 2017-02-07 03:51
i am changing the name of this style to "Manufacturing" to match the area it's in. is a more open BTS area with different textures from the current bts

**Comment by Endermage77** [comment] 2017-02-07 14:49
So, if I am correct, you basically want a semi-dilapidated [ruined by wear and age] BTS style fashioned after Art Therapy?

**Comment by TheDarkBomber** [comment] 2017-02-08 21:59
If that holds true, then this seems like a bad idea.

**Comment by TeamSpen210** [comment] 2017-02-09 00:04
The current BTS is Manufacturing / Factory. That's much more closed in than the ones in Wheatley theme, which are opened up generally. Art Therapy is a totally different beast, in specific rooms.

**Closed** 2017-02-09 15:43 UTC
Labels: New Style
