### ISSUE TITLE
BTS Co-op player spawns are completely broken

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2-items#1405] opened 2017-01-15 17:27 UTC
This is where you spawn, from the start of the map:
![20170115092458_1](https://cloud.githubusercontent.com/assets/19228201/21964637/c3d8e556-db04-11e6-9d08-3ef96afa90f6.jpg)
You can't do anything, the only way out is noclip.

**Comment by LautaroL20** [comment] 2017-01-15 17:32
This is a duplicate of: https://github.com/BEEmod/BEE2-items/issues/341

**Comment by Luke18033** [comment] 2017-01-15 17:34
No it's not, I can't even get into the game.

**Comment by LautaroL20** [comment] 2017-01-15 19:20
> I can't even get into the map. You could.

Well, i think that players would not be able to complete the map in either scenarios, so i don´t think its a big deal...

**Comment by TheDarkBomber** [comment] 2017-01-15 19:40
>Players does respawn in terrible conditions, "Noclip" is your only way to get out from it

Fixed version:

>The players respawn in terrible conditions, "Noclip" is the only way to get out of it.

**Comment by LautaroL20** [comment] 2017-01-15 19:51
It looks like TheDarkBomber woks better than Google Translator.... Why not develop "TheBomberTranslator", you shown having some potential.....Lol!

**Comment by TheDarkBomber** [comment] 2017-01-15 19:53
I am Native English, so I should be able to fix GT English easily.

**Comment by LautaroL20** [comment] 2017-01-15 20:00
I were using Google Translator for some years ago, but decided to stop using it since its even worst than my actual English knowledge.

**Comment by TheDarkBomber** [comment] 2017-01-15 20:05
>I were using Google Translator for some years ago, but decided to stop using it since its even worst than my actual English knowledge.

Fixed version:

>I was using Google Translate a few years ago, but I decided to stop using it, since it's even worse than my actual English knowledge.

**Comment by Luke18033** [comment] 2017-01-15 20:46
@LautaroL20 - All that doesn't need to be in the title, that's what the description is for.

**Comment by LautaroL20** [comment] 2017-01-15 20:50
Your title gives a duplicate issue feeling, thats why i changed it.

**Comment by TheDarkBomber** [comment] 2017-01-15 21:03
>Your title gives a duplicate issue feeling, thats why i changed it.

Fixed version:

>Your title gives off a duplicate issue feeling, that's why I changed it.

**Comment by TeamSpen210** [comment] 2017-04-20 04:03
Fixed by adding a room.

**Closed by TeamSpen210** 2017-04-20 04:03 UTC
Labels: BTS, Bug, CO-OP
