### ISSUE TITLE
Bee is a bug in 2.4 28

### ISSUE THREAD

**Issue by Mitia514** [BEEmod/BEE2-items#2536] opened 2018-03-03 18:45 UTC
I created the map using the sendifiсator, but it doesn't let the cube through the portals.
Here is the link to the map  
 http://steamcommunity.com/sharedfiles/filedetails/?id=1314409008

![20180303214426_1](https://user-images.githubusercontent.com/37024972/36937980-34e4028c-1f2c-11e8-9377-cfee0ce2363e.jpg)

**Comment by Luke18033** [comment] 2018-03-03 18:53
Duplicate of #2503. Place an Absolute Fizzler somewhere in the map to fix it.

**Closed by Luke18033** 2018-03-03 18:53 UTC
