### ISSUE TITLE
Monitor Screen Not Working

### ISSUE THREAD

**Issue by G3neralGrant** [BEEmod/BEE2-items#1353] opened 2017-01-07 22:18 UTC
The monitor is just black...but the actual screen is behind it? I don't know if im just using it wrong but it doesn't look right.

(https://cloud.githubusercontent.com/assets/24685304/21745577/f5a71caa-d4e3-11e6-890a-263d2d9dd2be.png)

(https://cloud.githubusercontent.com/assets/24685304/21745574/d9c3ef36-d4e3-11e6-8dd7-9710b8c2cad8.png)

[behind screen](https://cloud.githubusercontent.com/assets/24685304/21745520/0189878e-d4e3-11e6-878c-e150dfe22ad4.png)

**Comment by TheDarkBomber** [comment] 2017-01-07 22:21
Do you have a voice enabled? (e.g. GLaDOS)

**Comment by G3neralGrant** [comment] 2017-01-07 22:27
yes.

**Comment by LautaroL20** [comment] 2017-01-07 22:27
This is a duplicate of: https://github.com/BEEmod/BEE2-items/issues/1083

**Closed by LautaroL20** 2017-01-07 22:27 UTC
