### ISSUE TITLE
Co-op exit doesnt work after trying the SP exit

### ISSUE THREAD

**Issue by LionRezz** [BEEmod/BEE2-items#2920] opened 2019-02-26 20:11 UTC
All i did was trying out other exits, alas it just resulted in the door never opening.
My map consists of tasks that slowly lets you work your way towards the exit, so my exit doesnt have any connections and should open when both players are in front of it. Sadly, it doesnt.
What caused this and how can i fix it?

I have beemod and bee2 installed. For all i know, im only using the bee2.

I have tried changing between SP and Co-op, SP always works and Co-op never works.
I tried changing Co-op corridors, which didnt achieve any goals.

**Comment by LautaroL20** [comment] 2019-02-26 20:28
Which Style where you using when you experienced this issue?

**Comment by LautaroL20** [comment] 2019-02-26 20:29
Because if the style you were using was Clean, then this is a duplicate of: https://github.com/BEEmod/BEE2-items/issues/2880

**Comment by LionRezz** [comment] 2019-02-26 20:56
Does changing the style fix the bug?

**Closed** 2019-02-26 21:17 UTC
