### ISSUE TITLE
portal magnets are completely broken

### ISSUE THREAD

**Issue by j12600** [BEEmod/BEE2-items#3934] opened 2021-09-13 17:50 UTC
portal magnets do not work currently. they won't fix a placed portal on to a surface, rendering them useless.

**Comment by Konclan** [comment] 2021-09-13 18:06
Possibly a duplicate of #3894

**Comment by j12600** [comment] 2021-09-13 18:07
actually, I was being dumb and forgot how portal magnets work. Sorry!

**Closed** 2021-09-13 18:08 UTC
Labels: Invalid
