### ISSUE TITLE
Lack of texture on the button.

### ISSUE THREAD

**Issue by MikeAvtone** [BEEmod/BEE2-items#4045] opened 2022-01-02 14:26 UTC
![20220102172235_1](https://user-images.githubusercontent.com/84069529/147878875-cfbfc493-a3d5-43f7-baed-0645a5bcd4e1.jpg)

**Comment by Luke18033** [comment] 2022-01-02 20:37
Duplicate of #3645

**Closed by Luke18033** 2022-01-02 20:37 UTC
