### ISSUE TITLE
Normal Signage causes "Failure To Compile" in Portal 1 Style

### ISSUE THREAD

**Issue by KabanFriends** [BEEmod/BEE2-items#2964] opened 2019-04-07 03:22 UTC
I had no time to get the console error since I was busy but I noticed the chamber with signage fails to compile

**Comment by LautaroL20** [comment] 2019-04-07 03:34
This is a duplicate of: https://github.com/BEEmod/BEE2-items/issues/2512

**Closed by LautaroL20** 2019-04-07 03:34 UTC
Labels: Bug, Duplicate
