### ISSUE TITLE
monitor visuals for Nigel

### ISSUE THREAD

**Issue by Darealxbox** [BEEmod/BEE2-items#4159] opened 2022-07-09 17:08 UTC
### Description of the feature

just a generic one for Nigel would be nice but of course it isn't necessary 

### Why should this be implemented

details in maps

### Additional information

I can't code so I don't have images but look at a monitor in the campaign

**Comment by Darealxbox** [comment] 2022-07-09 17:55
k

**Comment by Luke18033** [comment] 2023-05-06 07:24
Duplicate of #1378

**Closed by Luke18033** 2023-05-06 07:24 UTC
Labels: Enhancement, Aperture Tag
