### ISSUE TITLE
Thinking with Time Machine

### ISSUE THREAD

**Issue by seagemgames** [BEEmod/BEE2-items#2237] opened 2017-09-24 16:53 UTC
I think it would be really cool to either:
A - add TWTM items like the floor cube creator thingy (it constructs the cube infront of you)
or B - add TWTM style, where cube droppers can be placed anywhere and construct the cubes, and the doors are different

I do not mean:
ADD TWTM MECHANICS FRURURURURU!!!1!!!11!
I do mean:
Add TWTM Styled items/Unstyled items

**Comment by CreepiX987** [comment] 2017-09-24 17:19
+ glass/neon test chamber signs, normal signage is glass/neon, and the light strips are a set of four light squares.

**Comment by Luke18033** [comment] 2017-09-24 17:31
Duplicate of #589.

**Closed by Luke18033** 2017-09-24 17:31 UTC
