### ISSUE TITLE
New style: Outside

### ISSUE THREAD

**Issue by Flametusk** [BEEmod/BEE2-items#1329] opened 2017-01-04 01:24 UTC
The sky box would be the sky, and There would be cliffs and stuff maybe?

**Comment by ZombiePwner1** [comment] 2017-01-04 01:27
I don't think it's possible to generate cliffs in the PeTi

**Comment by ZombiePwner1** [comment] 2017-01-04 01:29
And how would an outside style work? there would need to be bumpy ground which will make it more realistic but the problem is the PeTi needs to be flat.

**Comment by Flametusk** [comment] 2017-01-04 01:29
...The sloped blocks?

**Comment by ZombiePwner1** [comment] 2017-01-04 01:30
The sloped blocks wouldn't look very nice for cliffs

**Comment by Flametusk** [comment] 2017-01-04 01:30
Maybe the same way that the textures are done?

**Comment by ZombiePwner1** [comment] 2017-01-04 01:31
Afraid that won't work either.

**Comment by ZombiePwner1** [comment] 2017-01-04 01:33
i will close this for now until spencer takes a look.

**Comment by Flametusk** [comment] 2017-01-04 01:34
Then I have no idea. Maybe just a very overgrown area, also using some old aperture textures,  with the sky showing? As a sky box?

**Comment by ZombiePwner1** [comment] 2017-01-04 01:49
Having a mix of overgrown and old aperture textures wouldn't feel right. And it can break the style between them.

**Comment by TheDarkBomber** [comment] 2017-01-05 13:00
Still needs the `New Style` label.

**Comment by LautaroL20** [comment] 2017-06-12 03:56
> ZombiePwner1 Said: "i will close this for now until Spencer takes a look."

Why did you close the issue? He didn´t replied yet...

**Comment by Luke18033** [comment] 2021-02-10 18:35
This isn't a style that really works in the puzzlemaker.

**Closed by Luke18033** 2021-02-10 18:35 UTC
Labels: New Style
