### ISSUE TITLE
Floating cubes when on a lightbridge

### ISSUE THREAD

**Issue by eeeee48** [BEEmod/BEE2-items#2922] opened 2019-03-02 03:07 UTC
![image](https://user-images.githubusercontent.com/32681975/53676292-7791f980-3ca0-11e9-993a-34092ac3b694.png)

I'm confused on how this works, Isn't the cube supposed to fall?

Here's the map it's on: https://steamcommunity.com/sharedfiles/filedetails/?id=1669831744 (It's the second cube)

**Comment by MeloettaRules28** [comment] 2019-03-06 20:57
Lautaro, where do you think you are right now? This IS the item repository.

**Comment by ZombiePwner1** [comment] 2019-03-06 22:52
@LautaroL20 lol @MeloettaRules28 has a point wheels.

**Comment by TeamSpen210** [comment] 2019-03-06 23:24
I transferred the issue, so it was originally there when he made the comment.

**Comment by LautaroL20** [comment] 2019-03-06 23:41
@ZombiePwner1 - You and @MeloettaRules28 both are really needing a pair of glasses urgently... it was as simple as paying attention to the event history shown in small icons right below my comment:

![issue events](https://user-images.githubusercontent.com/12244376/53921675-0d86a500-4050-11e9-80d9-6c0d30b3ce71.png)

**Comment by Luke18033** [comment] 2021-11-06 01:58
Is this really reproducible?

**Comment by Luke18033** [comment] 2021-11-16 23:58
I can't reproduce this, it seems like a Valve bug, if anything...

**Closed by Luke18033** 2021-11-16 23:58 UTC
Labels: Bug
