### ISSUE TITLE
BTS style causes "Failure To Compile"

### ISSUE THREAD

**Issue by ismellpie3** [BEEmod/BEE2-items#3720] opened 2021-03-27 22:49 UTC
**BEE2 Version: 4.39.1**

<details>
<summary>Error Log</summary>

[I] vbsp.main(): BEE2 v4.39.1 VBSP hook initiallised.
[I] cond.core.import_conditions(): Imported all conditions modules!
[I] vbsp.main(): Map path is "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf"
[I] vbsp.main(): New path: "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[I] vbsp.main(): PeTI map detected!
[I] vbsp.main(): Loading settings...
[W] texturing.load_config(): overlays: Unknown texture names faithfling, faithland
[W] options.load(): Extra config options: {'glass_scale': '0.05', 'voice_pack': 'BEE2_ANNOUNCER_APOC'}
[I] cubes.parse_conf(): Parsed 7 cube types, 1 dropper types and 4 addons.
[I] fizzler.read_configs(): Loaded 14 fizzlers.
[I] vbsp.load_settings(): Settings Loaded!
[I] vbsp.load_map(): Parsing Map...
[I] vbsp.load_map(): Reading Map...
[I] vbsp.load_map(): Loading complete!
[I] antlines.parse_antlines(): Parsing antlines...
[I] antlines.parse_antlines(): Done! (0 antlines)
[I] vbsp.get_map_info(): Forcing elevator spawn!
[I] vbsp.mod_entryexit(): Setting SP Entry to 1
[I] vbsp.mod_entryexit(): Setting SP Exit to 1
[I] vbsp.get_map_info(): Game Mode: SP
[I] vbsp.get_map_info(): Is Preview: False
[I] brushLoc.read_from_map(): Analysed map, filling air... (11 starting positions..)
[I] brushLoc.read_from_map(): Air filled!
[E] (unknown file).(unknown function)(): Uncaught Exception:
Traceback (most recent call last):
  File "compiler_launch.py", line 13, in <module>
  File "vbsp.py", line 1897, in main
  File "precomp\texturing.py", line 706, in setup
  File "srctools\vmt.py", line 120, in parse
  File "srctools\_tokenizer.pyx", line 151, in srctools._tokenizer.Tokenizer.__init__
TypeError: Expected unicode, got Special
[37116] Failed to execute script compiler_launch

</details>

**Additional information: Even if I try to compile an empty map, it will cause failure to compile...**

**Comment by LautaroL20** [comment] 2021-03-27 23:44
The log that you have attached can not be deployed...

**Comment by seagemgames** [comment] 2021-03-27 23:46
They didn't attach a log...

**Comment by LautaroL20** [comment] 2021-03-28 01:18
> seagemgames said: "They didn't attach a log..."

If you pay attention to the issue´s description, you will see that there is something like a triangle tab that it is supposed to display a log but it does not work. The issue´s author clearly wanted to post a log but he did not do it well:
![Question](https://user-images.githubusercontent.com/12244376/112739350-1e155b00-8f4a-11eb-9cbe-19755db30cfb.png)

**Comment by seagemgames** [comment] 2021-03-28 01:19
That's autogenerated by the issue template.

**Comment by ismellpie3** [comment] 2021-04-01 23:48
sorry i forgot the log 
 here it is 

[I] vbsp.main(): BEE2 v4.39.1 VBSP hook initiallised.
[I] cond.core.import_conditions(): Imported all conditions modules!
[I] vbsp.main(): Map path is "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf"
[I] vbsp.main(): New path: "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[I] vbsp.main(): PeTI map detected!
[I] vbsp.main(): Loading settings...
[W] texturing.load_config(): overlays: Unknown texture names faithfling, faithland
[W] options.load(): Extra config options: {'glass_scale': '0.05', 'voice_pack': 'BEE2_ANNOUNCER_APOC'}
[I] cubes.parse_conf(): Parsed 7 cube types, 1 dropper types and 4 addons.
[I] fizzler.read_configs(): Loaded 14 fizzlers.
[I] vbsp.load_settings(): Settings Loaded!
[I] vbsp.load_map(): Parsing Map...
[I] vbsp.load_map(): Reading Map...
[I] vbsp.load_map(): Loading complete!
[I] antlines.parse_antlines(): Parsing antlines...
[I] antlines.parse_antlines(): Done! (0 antlines)
[I] vbsp.get_map_info(): Forcing elevator spawn!
[I] vbsp.mod_entryexit(): Setting SP Entry to 1
[I] vbsp.mod_entryexit(): Setting SP Exit to 1
[I] vbsp.get_map_info(): Game Mode: SP
[I] vbsp.get_map_info(): Is Preview: False
[I] brushLoc.read_from_map(): Analysed map, filling air... (11 starting positions..)
[I] brushLoc.read_from_map(): Air filled!
[E] (unknown file).(unknown function)(): Uncaught Exception:
Traceback (most recent call last):
  File "compiler_launch.py", line 13, in <module>
  File "vbsp.py", line 1897, in main
  File "precomp\texturing.py", line 706, in setup
  File "srctools\vmt.py", line 120, in parse
  File "srctools\_tokenizer.pyx", line 151, in srctools._tokenizer.Tokenizer.__init__
TypeError: Expected unicode, got Special
[37116] Failed to execute script compiler_launch

**Comment by KaziPlays** [comment] 2021-04-04 15:02
I think It's because of the fizzler update error, but I'm not sure.

**Comment by TeamSpen210** [comment] 2021-04-04 23:49
This is a duplicate of BEEmod/BEE2.4#1511.

**Comment by Konclan** [comment] 2021-08-29 08:24
https://github.com/BEEmod/BEE2.4/blob/master/FAQ.md#why-is-bts-being-removed

**Closed by Konclan** 2021-08-29 08:24 UTC
Labels: BTS, Compile Error
