### ISSUE TITLE
Kinetic Gel Absorbtion Detector

### ISSUE THREAD

**Issue by TheLoafLord** [BEEmod/BEE2-items#2117] opened 2017-08-01 06:01 UTC
A fizzler that activates when a selected gel falls through it. Kinda like the Radiative Flux Rectangle, but for gels. Maybe make it so you can choose which gel activates it (Weighted, Cube, Sphere options.). Colour would be a blue octagon pattern (If possible.).

**Comment by ZombiePwner1** [comment] 2017-08-01 07:10
@TheLoafLord This should be a reversed version of the flux field.

**Comment by TheLoafLord** [comment] 2017-08-01 07:14
yeah, that would work great! look, i would model this myself, but i have no knowledge on how to do such stuff. i would love to. so quick question, do you know any tutorials i could watch/read so i could learn to do this? the only knowledge i have with hammer is tf2 maps haha.

**Comment by TeamSpen210** [comment] 2017-08-01 10:11
We can't do this, there's no way to sense gels.

**Comment by Endermage77** [comment] 2017-08-01 18:48
Even for a generic detector that looks for any kind of gel blob?

**Comment by TeamSpen210** [comment] 2017-08-01 20:37
Indeed. Pretty much the only way is to either detect the position of the portals and everything else (IE fake it), or put a cube in the way and detect when that's painted.

**Comment by Endermage77** [comment] 2017-08-01 21:14
A cube-based detector may work, although that would imply that it would be gel falling <b>into</b> the detector rather than <b>through</b>.

...Actually, I think this is a duplicate post!
Yeah, #1507.

**Comment by TeamSpen210** [comment] 2017-08-01 21:57
Duplicate of #1507.

**Comment by TeamSpen210** [comment] 2017-08-01 21:57
Duplicate of #1507.

**Closed by TeamSpen210** 2017-08-01 21:57 UTC
