### ISSUE TITLE
Overgrown separated coop checkpoint has a missing instance.

### ISSUE THREAD

**Issue by ZombiePwner1** [BEEmod/BEE2-items#3054] opened 2019-07-12 03:37 UTC
:\Program Files (x86)\Steam\steamapps\common\Aperture Tag\portal2\materials
[I] <valve>.vbsp(): Loading C:/Program Files (x86)/Steam/steamapps/common/Aperture Tag/sdk_content\maps\styled\preview.vmf
[I] <valve>.vbsp(): ConVarRef gpu_level doesn't point to an existing ConVar
[I] <valve>.vbsp(): Could not open instance file instances/BEE2/over/items/tSpen/coop_checkpoint_sep.vmf
[I] <valve>.vbsp():

**Comment by LautaroL20** [comment] 2019-07-14 20:52
This is a duplicate of: https://github.com/BEEmod/BEE2-items/issues/2263

**Closed by LautaroL20** 2019-07-14 20:52 UTC
Labels: Bug, Missing Instance, Overgrown
