### ISSUE TITLE
Dark Mode Theme

### ISSUE THREAD

**Issue by DatPerkYT** [BEEmod/BEE2-items#3959] opened 2021-10-03 21:20 UTC
### Description of the feature

I think that Dark Mode should be a theme. THIS IS ONLY FOR THE BEEmod APP, NOT PORTAL 2.

### Why should this be implemented

I think adding a dark mode theme is a way that some people would like, and help sensitive eyes. Again... this would might be a bit too "Hard" To add because the Shadows. Just an idea again. Sorry for requesting 2 in a day I'm just trying to get them off my head, and get a reply to see if they could/would be added.

### Additional information

Heres a General idea oh what it could look like. i just lazied it and filed the boxes in but you get the idea:
![pellet](https://user-images.githubusercontent.com/90533282/135771882-37dcfd5f-4e07-4cdf-b020-65d0db4b1a38.png)
.

**Comment by Luke18033** [comment] 2021-10-03 21:22
Duplicate of BEEmod/BEE2.4#1176

**Comment by DatPerkYT** [comment] 2021-10-03 21:22
What?
sorry i did not know that-

**Closed by Luke18033** 2021-10-03 21:22 UTC
Labels: Enhancement

**Comment by DatPerkYT** [comment] 2021-10-03 21:24
now i feel terrible for wasting your time lol
