### ISSUE TITLE
Gyroscope Turrets

### ISSUE THREAD

**Issue by Endermage77** [BEEmod/BEE2-items#2002] opened 2017-05-23 13:40 UTC
These turrets are a bit tougher than the regular ones, in that they attempt to right themselves when tipped off-balance. This would be handy in situations where turrets are intended to stay upright when they would otherwise fall down every time (eg. conveyor belts, track platforms, side pistons pushing on them, standing on PRF's or CSF's or glass, etc.)
They would be distinguished with some sort of yellow paint job.

**Comment by ZFM2004** [comment] 2017-05-24 18:54
this sounds awesome!

**Comment by ZFM2004** [comment] 2017-05-24 18:55
however, how would you beat them? put them into a fizzler?

**Comment by Endermage77** [comment] 2017-05-24 23:41
The gyroscope isn't that powerful; tipping them by grabbing them manually or smacking them with a high-velocity object will work, as well as the other normal methods of fizzling and lasering.

**Comment by TeamSpen210** [comment] 2017-05-25 00:38
Ideally I'd want the turret to detect the surface, and like add a clamp model to that to attach it.

**Comment by IceTudor** [comment] 2017-10-21 08:07
Nice, but this seems to be a duplicate of https://github.com/BEEmod/BEE2-items/issues/1545

**Comment by Endermage77** [comment] 2017-10-21 16:42
Sortof.
That turret is simply a differently-structured turret that is simply hard to tip over because of how it is built.
This turret actively tries to balance itself and thus is also difficult to tip. It would have a power good enough to stop it tipping after a drop, for instance, or being moved by platforms.

**Comment by Konclan** [comment] 2021-08-15 04:21
UCP

**Closed by Konclan** 2021-08-15 04:21 UTC
Labels: New Item
