### ISSUE TITLE
Coop Exit Trigger not working in Clean or Original Clean

### ISSUE THREAD

**Issue by galacticnerds** [BEEmod/BEE2-items#2880] opened 2018-12-23 06:28 UTC
![20181222221823_1](https://user-images.githubusercontent.com/30561577/50381302-52e22b80-0638-11e9-87b0-c980dcd8905d.jpg)

Appears to have been reported in #1392 a year ago and was said to be fixed, but the issue still remains. I tried adding an input to the exit but that didn't work. Using 4.32.0.

**Comment by galacticnerds** [comment] 2018-12-23 23:19
> When using BEE2.4 after installing a new version, old resources from past releases will not be overwritten, resulting in bugs that were fixed still being present and some things not working correctly. In order to solve this annoyance, you will have to do the following:
> 
> 1 - Make sure your antivirus is not blocking the compiler´s files of Beemod that are located in the `bin` folder inside the Portal 2 game´s directory. Just add the whole `bin` folder in your antivirus exception´s list, because otherwise this can cause a ****"building error"**** issue when building your puzzle.
> 
> 2 - Open Beemod and click on: `File ----> Uninstall From Selected Game ----> "Are you sure you want to delete "PORTAL 2"? ----> YES`.
> 
> 3 - Wait 1 minute while Beemod removes their resources from Portal 2.
> 
> 4 - Verify the Game Cache Files.
> 
> 5 - Make sure to have downloaded and unzipped the latest Item's Packages and Application version of BEE2.4, and both must be from the same Pre-Release Version, otherwise bugs may occur. Links:
> 
> https://github.com/BEEmod/BEE2.4/releases (Application)
> https://github.com/BEEmod/BEE2-items/releases (Item's Packages)
> 
> Note that if you are running Beemod on Linux or Mac Os X, or even on 32 Bit versions of Windows, issues can occur. Beemod currently works well only on 64 Bit versions of Windows 7, 8 and 10.
> 
> 6 - Click on: `File ----> Options ----> Development`, then uncheck the option: `Preserve Game Directories`.
> 
> 7 - Now choose your favorite Items & Style and export your palette to the game.
> 
> 8 - Make sure to save these steps in a text file in case you get similar issues in the future.
> 
> 9 - Happy mapmaking!

Yea, I did that.

**Comment by LautaroL20** [comment] 2018-12-23 23:52
Well, this issue you´ve open was already fixed since many releases ago. That is why i thought my steps would help you solving your issue, as many people on similar scenarios confirmed it works.

**Comment by galacticnerds** [comment] 2018-12-24 00:40
Well I literally uninstalled the game and it still happens, so if that isn't proof that it still happens then I don't know what is.

**Comment by Luke18033** [comment] 2018-12-24 01:34
I also have this issue.
![20181223173049_1](https://user-images.githubusercontent.com/19228201/50389007-d05d7880-06d8-11e9-92c2-2fe95ea36322.jpg)

**Comment by galacticnerds** [comment] 2018-12-24 03:36
Just clean and original from what I know.

**Comment by LautaroL20** [comment] 2018-12-24 03:46
Yes, it is still glitched.

**Comment by CreatorLockyn** [comment] 2019-01-19 19:31
Couldn't find this post so I made my own which was closed I have the exact same problem and I have absolutely no Idea on how to fix this

**Comment by LautaroL20** [comment] 2019-01-19 20:16
Well, you will have to wait for a fix until TeamSpen210 sees this issue. Since he has made two releases without a fix for this...

**Comment by TeamSpen210** [comment] 2019-02-27 03:21
The door logic is pretty complex, it has a lot of states it can be in depending on where the two players are. I might as well just convert it to just use VScript.

**Comment by DogeIsCut** [comment] 2019-03-06 02:38
bump

**Comment by galacticnerds** [comment] 2019-03-06 20:00
Pretty sure there's gonna be a megapatch released some time in the next month. He's been fixing plenty of issues but hasn't made a release yet.

**Closed** 2019-03-10 06:29 UTC
Labels: Bug, Clean, Fixed
