### ISSUE TITLE
Delayer having an option to be muted

### ISSUE THREAD

**Issue by HugoBDesigner** [BEEmod/BEE2-items#1736] opened 2017-03-15 04:43 UTC
Maybe add a "Start enabled" option for the time delayer entities to control whether or not they do their ticking sound. Quite useful for hidden/unseen contraptions.

**Comment by Byzarru** [comment] 2017-03-16 03:18
Duplicate of #1524.

**Comment by Byzarru** [comment] 2017-03-16 03:18
Duplicate of #1524.

**Closed by Byzarru** 2017-03-16 03:18 UTC
Labels: Duplicate, New Item Property, Suggestion
