### ISSUE TITLE
Force deflection field is completely bugged when start enabled is off.

### ISSUE THREAD

**Issue by ZombiePwner1** [BEEmod/BEE2-items#1923] opened 2017-05-07 00:19 UTC
![20170507081609_1](https://cloud.githubusercontent.com/assets/18079316/25776871/aa72bc8a-32fd-11e7-955a-0d25e6e8669b.jpg)

The frame will be disabled as it's supposed to.

![20170507081630_1](https://cloud.githubusercontent.com/assets/18079316/25776873/acd872e4-32fd-11e7-9a20-b419e7796671.jpg)

The field itself will still be enabled but lets everything through it.

**Comment by Luke18033** [comment] 2017-05-07 00:27
Duplicate of #1858.

**Closed by Luke18033** 2017-05-07 00:27 UTC
Labels: Bug
