### ISSUE TITLE
Portal 1 door has nodraw texture at its base

### ISSUE THREAD

**Issue by NeoKat75** [BEEmod/BEE2-items#3554] opened 2020-11-05 12:30 UTC
Spooky :o 
![image](https://user-images.githubusercontent.com/48127893/98241268-c1ee7200-1f7b-11eb-8ca1-4d8d3b4edfb7.png)

**Comment by FrozenDragon0** [comment] 2020-11-05 12:33
Sort of a duplicate to this: https://github.com/BEEmod/BEE2-items/issues/3444

**Comment by LautaroL20** [comment] 2020-11-05 12:44
> Sort of a duplicate to this: #3444

That issue is about the door of a Coop Exit corridor. This is of a placeable door. However, their issue cause could still be the same?

**Comment by FrozenDragon0** [comment] 2020-11-05 12:51
It is the same as the floor is still missing just like the coop exit door.

**Comment by maxdevgithub** [comment] 2020-11-05 13:37
Duplicate of https://github.com/BEEmod/BEE2-items/issues/3448

**Comment by maxdevgithub** [comment] 2020-11-05 13:45
I knew there was something familiar

**Closed** 2020-11-05 13:45 UTC
Labels: Bug, Duplicate, Portal 1
