### ISSUE TITLE
GEL IN the Pneumatic Diversity Vent

### ISSUE THREAD

**Issue by ILIA-NENASHEV** [BEEmod/BEE2-items#1177] opened 2016-12-11 21:33 UTC
![default](https://cloud.githubusercontent.com/assets/24510029/21083482/a4a6ac3a-c002-11e6-8b2a-08d55a8f7bc9.PNG)

**Comment by Luke18033** [comment] 2016-12-11 22:05
What?

**Comment by Byzarru** [comment] 2016-12-11 23:22
Gels currently don't work in diversity vents.

**Comment by TeamSpen210** [comment] 2016-12-11 23:33
It's not possible to impement gels in that fashion, where you can suck up gel and deposit it elsewhere. It is possible (and I probably will) to have a tube functioning as effectively an extension of a gel dropper (only spawning that particular gel).

**Comment by ILIA-NENASHEV** [comment] 2016-12-12 04:30
TeamSpen210 вы можете добавить этот элемент

**Comment by ZombiePwner1** [comment] 2016-12-12 04:50
@ILIA-NENASHEV Next time when you make a issue please provide a description other than screenshots please :)

**Comment by Luke18033** [comment] 2016-12-31 20:57
Duplicate of #662.

**Closed by Luke18033** 2016-12-31 20:57 UTC
