### ISSUE TITLE
Stackable FourthReaper's Fizzlers

### ISSUE THREAD

**Issue by KRWCLASSIC** [BEEmod/BEE2-items#4302] opened 2023-03-19 13:51 UTC
### Description of the feature

Stackable in mean you can change their type in-game like cubes or glass/grates

### Why should this be implemented

Doing this will make it more compact allowing you to use all of FourthReaper's fizzlers without using many object slots

### Additional information

This should be looking like cubes in "Portal 2 Collapsed" pallete
![image](https://user-images.githubusercontent.com/80610057/226179885-ff5e632b-d0a4-4a1b-ac81-1b493e1bc036.png)

**Comment by saismee** [comment] 2023-03-19 13:54
Duplicate of #2786

**Closed** 2023-03-19 13:56 UTC
Labels: Duplicate, Enhancement
