### ISSUE TITLE
Protruding button go poof

### ISSUE THREAD

**Issue by NeoKat75** [BEEmod/BEE2-items#3546] opened 2020-10-13 20:38 UTC
Protruding pedestal buttons are invisible, but still interactable and fire their outputs correctly.
![image](https://user-images.githubusercontent.com/48127893/95913526-0d629580-0dad-11eb-988a-043205f84fc5.png)

**Comment by Luke18033** [comment] 2020-10-13 21:26
Duplicate of #3388 (it's positioned 1 block higher, inside the ceiling)

**Closed by Luke18033** 2020-10-13 21:26 UTC
Labels: Bug

**Comment by LautaroL20** [comment] 2020-10-14 02:16
@NeoKat75 - This bug is fixed in the next release.
