### ISSUE TITLE
Add music trigger to swap out music mid chamber.

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#1400] opened 2017-01-14 22:11 UTC
Moved from: https://github.com/BEEmod/BEE2.4/issues/478

Original post by Alfe5:

"I feel like a lot of portal 2 music is situational and doesn't fit for the entire chamber. I believe a lot of map creators would love it of there were a simple music trigger to change the music. However, you should probably flesh out music bugs first before implementing it."

**Comment by Byzarru** [comment] 2017-01-14 23:18
Duplicate of #550.

**Comment by Luke18033** [comment] 2017-01-15 04:55
I wish this would be added though, it would work really well for some maps.

**Closed by Luke18033** 2017-01-15 04:55 UTC
Labels: Enhancement

**Comment by Byzarru** [comment] 2017-01-15 05:08
I've suggested a sound effect item (issue still open!), if it's any consolation,

**Comment by TheDarkBomber** [comment] 2017-01-15 08:49
You should let people move issues themselves.

**Comment by LautaroL20** [comment] 2017-01-15 14:42
@TheDarkBomber - As usual with these issues, no actions are taken by the author itself, so i must move it.
