### ISSUE TITLE
[Suggestion] Rotating panel with attached elements

### ISSUE THREAD

**Issue by King0191** [BEEmod/BEE2-items#2667] opened 2018-04-27 20:01 UTC
In chamber 18 of Portal 1. We see a spinning wall-panel with a HEP launcher on it. So i was thinking. Maybe this could be added, along side the same thing for a laser? This could also be adapted into excursion funnels or Light Bridges (It would just be harder and i don't really see the point) This isn't for recreating Chamber 18 (tho someone is gonna use it for that.) But i think it would greatly benefit tests that use H.E.P.S or lasers (Hell make it so that its Fizzler or Laserfield to change between Laser or HEP if possible,)

**Comment by BETTEREXTENEDEDITORMOD** [comment] 2018-04-27 21:26
Duplicate of #2204

**Closed** 2018-04-28 12:56 UTC
Labels: Duplicate, New Item, Suggestion
