### ISSUE TITLE
Add new items (from old bee mod (2.2.5) please!!!)

### ISSUE THREAD

**Issue by SCIENTIST2004** [BEEmod/BEE2-items#2474] opened 2018-01-31 21:51 UTC
1. sphere cannon
2. clamped cube
3. rotating faith plate
4. cube transmuter
5. TNT turret
6. retractable floor button
7. breacable glass
8. catapult cube
9. shredder
10. caget items (turret,reflction cube)

**Comment by BETTEREXTENEDEDITORMOD** [comment] 2018-01-31 22:38
all i want to know is 
what is a clamped cube 
and what is a cube transmuter?

**Comment by Luke18033** [comment] 2018-01-31 22:54
Duplicate of #95.

**Closed by Luke18033** 2018-01-31 22:54 UTC

**Comment by Endermage77** [comment] 2018-02-01 04:29
Clamped Cube: A cube on a clamp, like how the turret droppers winch in clamps to replace turrets. They were powered on, then they dropped the cube and retracted away. Unfortunately, they could not respawn cubes.

Cube Transmuter: Set what type of cube you want to transmute, and it will turn any cube you stick in there to that type. For some reason, it only worked once and then never transmuted again until level reset.
