### ISSUE TITLE
Closed solid fields don't generate gridded walls in original clean.

### ISSUE THREAD

**Issue by ZombiePwner1** [BEEmod/BEE2-items#2651] opened 2018-04-18 03:51 UTC
![20180418114140_1](https://user-images.githubusercontent.com/18079316/38910972-c6b6b86c-42fe-11e8-93a2-87f50644845d.jpg)

**Comment by LautaroL20** [comment] 2018-04-18 11:55
This is a duplicate of: https://github.com/BEEmod/BEE2-items/issues/518

**Closed by LautaroL20** 2018-04-18 11:55 UTC
Labels: Bug, Clean, Duplicate
