### ISSUE TITLE
[Item Suggestion] Electrical Wall

### ISSUE THREAD

**Issue by KabanFriends** [BEEmod/BEE2-items#2965] opened 2019-04-08 04:57 UTC
The item I want:
![20190408135022_1](https://user-images.githubusercontent.com/45000995/55699372-93a65a80-5a05-11e9-99d2-32723294d759.jpg)
(Portal: Prelude)

How do we place it in the editor:
![image](https://user-images.githubusercontent.com/45000995/55699458-eed84d00-5a05-11e9-92f6-f982fbc45c38.png)
Place it like this and the entire wall tile becomes that black electrical wall.

![image](https://user-images.githubusercontent.com/45000995/55699521-20e9af00-5a06-11e9-8c28-e96814ffd75d.png)
When you place it like this then it will become a large one black wall thingy. (Like in screenshot)

**Comment by Konclan** [comment] 2019-04-08 05:22
Pretty much a duplicate of #2179

**Closed** 2019-04-08 08:43 UTC
Labels: Duplicate
