### ISSUE TITLE
Compile error in BTS style (TypeError: Expected unicode, got special) (4.39.0)

### ISSUE THREAD

**Issue by seagemgames** [BEEmod/BEE2-items#3739] opened 2021-02-27 16:43 UTC
Version: 4.39.0

Used Style: BTS
Used Items: Entry door, Exit door and Large Observation room in the default chamber

Log: https://pastebin.com/sBMGrGCn

I couldn't find any other issues with a similar log.

**Comment by AeroGas** [comment] 2021-04-07 09:03
So someone know how to solve it?

**Comment by LautaroL20** [comment] 2021-04-07 09:18
Nope.

**Comment by AeroGas** [comment] 2021-04-07 09:19
> 
> 
> Nope.

Oh. So we can't use BTS style for now?

**Comment by LautaroL20** [comment] 2021-04-07 09:38
You will need to wait for the next beemod update.

**Comment by FrozenDragon0** [comment] 2021-05-02 10:26
Isn't this issue a duplicate of https://github.com/BEEmod/BEE2-items/issues/3720 ?

**Comment by LautaroL20** [comment] 2021-05-02 12:36
Yep, but that issue is closed and should be re-open.

**Comment by FrozenDragon0** [comment] 2021-05-02 12:49
This would be a duplicate of https://github.com/BEEmod/BEE2-items/issues/3720

**Closed by FrozenDragon0** 2021-05-02 12:49 UTC
Labels: BTS, Compile Error, Duplicate

**Comment by seagemgames** [comment] 2021-05-02 13:00
That's a duplicate of this...

**Comment by FrozenDragon0** [comment] 2021-05-02 13:24
Yes but the issue I mentioned has a lower number.
