### ISSUE TITLE
Sticky Gel (Not Adhesion Gel)

### ISSUE THREAD

**Issue by Endermage77** [BEEmod/BEE2-items#1633] opened 2017-02-27 16:42 UTC
This is NOT the mauve-colored adhesion gel, which has already been said time and again not to work well with the PTI.

Instead, this gel is simply what it sounds like: sticky.
Properties:
- Players cannot jump while standing on it
- Players move slower while standing on it
- Players fall slower when contacting it on the wall
- Objects stick to it regardless of gravity
- Objects resist being moved when pushed while on it
- Objects painted with sticky gel also have the properties listed above

I'm still not quite sure what color it would be, though.

**Comment by TheDarkBomber** [comment] 2017-02-27 16:45
Can't add new gels.

**Comment by Luke18033** [comment] 2017-02-27 16:51
You can, but they would need to replace Reflection Gel so you couldn't have both in the same map. It would be an alternate version of Reflection Gel, if anything.

**Comment by TheDarkBomber** [comment] 2017-02-27 16:56
Or you can add it as a wall surface instead of a gel.

**Comment by Byzarru** [comment] 2017-02-27 17:35
It it were a wall surface, it'd be a duplicate of #1336.

**Comment by Luke18033** [comment] 2017-02-27 17:38
No, the gravity wall is different.

**Comment by Byzarru** [comment] 2017-02-27 19:58
@TheDarkBomber Aren't you working on an item like this already?

**Comment by TheDarkBomber** [comment] 2017-02-27 20:24
No.

**Comment by Endermage77** [comment] 2017-02-27 20:40
I would be alright with not having this and reflection gel together.

**Comment by TheDarkBomber** [comment] 2017-02-27 20:50
Actually, I think a brown would be a better colour.

**Comment by hop193** [comment] 2017-04-01 19:18
The Cut Content color was sorta Purple.

**Comment by Endermage77** [comment] 2017-04-02 02:23
Well, I suggested slimy green because sticky purple is already used by people who have managed to successfully replicate adhesion gel in their own maps.

**Comment by HelloIamapersonthatisalive** [comment] 2017-05-31 00:48
How about like a yellowish white, like real glue

**Comment by Endermage77** [comment] 2017-06-01 00:46
May cause confusion for people who have no sense of color and can't distinguish any shades of white, due to the presence of Conversion Gel.

**Comment by Luke18033** [comment] 2021-02-10 18:52
Adding new gels involves some pretty hacky stuff which wouldn't work very well in the Puzzlemaker.

But you did totally just predict Minecraft honey blocks.

**Closed by Luke18033** 2021-02-10 18:52 UTC
Labels: New Item
