### ISSUE TITLE
The Turret Target

### ISSUE THREAD

**Issue by Cosmiscient** [BEEmod/BEE2-items#3731] opened 2021-04-03 02:46 UTC
**Description of the item:** The Turret Target would sit on a wall, and force turrets ( facing its direction and within its line of sight ) to fire at it constantly. Turrets would prioritize the target over the player. The most significant part is the output signal sent upon being hit by a bullet.

**Item options:** It would be placed a lot like the unstationary scaffold. If the track isn't extended, it would sit, stationary on the wall. If it's extended, it would be able to move back and forth across the track.
It wouldn't have properties except for a pedestal button timer, which would determine how long it would output for after being shot a single time by a turret.

**Additional information:** If a turret has to decide between a turret target and a turret target cube, it'll prioritize the turret target. I believe this would allow for far more possibilities for test solutions.

**Comment by KaziPlays** [comment] 2021-04-04 14:00
This was sort of what I've suggested for an UCP but who knows? Maybe they'll add it?

**Comment by Cosmiscient** [comment] 2021-04-06 20:33
This is actually very similar to #1509 yet a little more involved.

**Comment by Luke18033** [comment] 2021-04-13 00:38
Duplicate of #2620, you can suggest moving it on a track in a comment on that issue.

**Closed by Luke18033** 2021-04-13 00:38 UTC
Labels: New Item
