### ISSUE TITLE
BTS 3D Skybox Leak

### ISSUE THREAD

**Issue by ellingtonvengaboysmuseum** [BEEmod/BEE2-items#2331] opened 2017-10-29 21:05 UTC
The BTS 3D Skybox has a Leak seen at the test chamber entry door frame of all current entry corridors...

![preview0014](https://user-images.githubusercontent.com/11165643/32148314-53db7c7e-bccb-11e7-8a4d-b450f54b72c1.jpg)

**Comment by Luke18033** [comment] 2017-10-29 21:14
Duplicate of #1222.

**Closed by Luke18033** 2017-10-29 21:14 UTC

**Comment by ellingtonvengaboysmuseum** [comment] 2017-10-29 21:57
@Luke18033 - Also do you know about the Bts 3D Skybox Texture Mismatch (Pit is using Modern Metal BTS Textures, area above is using Cement textures)

**Comment by Luke18033** [comment] 2017-10-29 21:59
Yes, #1451.

**Comment by IceTudor** [comment] 2017-11-02 11:45
God, in the version I'm using, the BTS style exit/entry is broken completely
