### ISSUE TITLE
60´s Old Aperture DeadlyGoo renders as a leak (probably due to the Drawbridge)

### ISSUE THREAD

**Issue by epicGamingA** [BEEmod/BEE2-items#4056] opened 2022-01-14 00:24 UTC
there is a bug with the goo it shows that void thing that hurts your eyes

**Comment by LautaroL20** [comment] 2022-01-14 00:50
Why did you open a blank issue? Much information is missing here, you have a leak in your map and thats why the goo turns nodraw, but it would help if you can provide which BEEmod version are you using, which style where you using and if possible, which items did you have in your map when this happened.

**Comment by epicGamingA** [comment] 2022-01-14 16:12
style 1960 apeture ver is 4.41.1 items i had buttons cubes a had portal guns doors and etc

**Comment by LautaroL20** [comment] 2022-01-14 16:32
Please, try building your map again and if the goo is still bugged, go to `Portal 2/sdk_content/maps/styled`, put `preview.vmf` and `preview.lin` in a ZIP, then upload that here.

**Comment by epicGamingA** [comment] 2022-01-14 19:58
i updated bee mod to clean aperture and adding some stuff that wheatley has and the goo works

**Comment by LautaroL20** [comment] 2022-01-14 20:28
Switching to another style will not get the 60´s DeadlyGoo fixed... it would help if when you use the 60´s style and if the goo is still bugged, you go to `Portal 2/sdk_content/maps/styled`, put `preview.vmf` and `preview.lin` in a ZIP, then upload that here so we can get it fixed for the next BEEmod release.

**Comment by epicGamingA** [comment] 2022-01-14 20:58
i updated it back to old aperture but the goo is working now

**Comment by LautaroL20** [comment] 2022-01-14 21:02
Well, if the issue starts to happen again, let me know and I will re-open the issue.

**Comment by epicGamingA** [comment] 2022-01-14 21:02
ok

**Comment by epicGamingA** [comment] 2022-01-14 21:03
btw the old apeture style hurts my mind

**Comment by epicGamingA** [comment] 2022-01-15 01:00
[goobug.zip](https://github.com/BEEmod/BEE2-items/files/7873965/goobug.zip)
its happening

**Comment by LautaroL20** [comment] 2022-01-15 04:06
I will give it a check as soon as I have some free time.

**Comment by epicGamingA** [comment] 2022-01-15 18:15
ok

**Comment by LautaroL20** [comment] 2022-01-16 04:56
You missed the file `preview.lin` in your ZIP file, without it I can´t see where the leak occurs...

**Comment by LautaroL20** [comment] 2022-01-16 05:00
Now you should rebuild your 60´s aperture map again and include both files `preview.lin` and `preview.vmf` in your ZIP because both files are equally relevant, Including only the file `preview.vmf` is useless.

**Comment by epicGamingA** [comment] 2022-01-16 19:16
[goobug.zip](https://github.com/BEEmod/BEE2-items/files/7877730/goobug.zip)
here

**Comment by LautaroL20** [comment] 2022-01-16 20:51
Alright, the leak seems to be caused by the Drawbridge. Can you please remove the Drawbridge from your map and then compile it again to see if the goo is still bugged or not? I just checked your pointfile in Hammer and this is the result:

![Drawbridge Hammer Pointfile](https://user-images.githubusercontent.com/12244376/149677540-e3c08343-e23e-4114-ab38-efa1c6e90a6c.png)

**Comment by epicGamingA** [comment] 2022-01-16 20:54
i will try

**Comment by epicGamingA** [comment] 2022-01-16 20:59
why did the drawbridge render the goo as a leak?

**Comment by LautaroL20** [comment] 2022-01-16 21:39
It is because a part of the model is outside of the map, and when something is on the void it will produce a leak in the map causing the goo to appearing bugged. Let me know if removing the drawbridge from the map makes the goo to work fine.

**Comment by epicGamingA** [comment] 2022-01-16 21:46
its works

**Comment by epicGamingA** [comment] 2022-01-16 21:47
you can find it in my workshop named aperture testing

**Comment by epicGamingA** [comment] 2022-01-16 21:47
this is the link https://steamcommunity.com/sharedfiles/filedetails/?id=2722057784

**Comment by LautaroL20** [comment] 2022-01-16 22:02
Drawbridge causing a leak in the map would be a duplicate of: https://github.com/BEEmod/BEE2-items/issues/3574, but do not worry because this issue is in the list of bugs that must be fixed before a new BEEmod release comes out.

**Closed by LautaroL20** 2022-01-16 22:02 UTC
Labels: Bug, Old Aperture
