### ISSUE TITLE
Rexaura cube deflector drops cube in both clean styled (might also happen in overgrown but not in any of the old aperture, P1, and BTS themes) the beams that hold the cube and fizzle the pellets upon contact don't show up as well

### ISSUE THREAD

**Issue by kdabest2** [BEEmod/BEE2-items#2915] opened 2019-02-22 22:50 UTC

**Comment by TeamSpen210** [comment] 2019-02-22 22:58
Duplicate of #2425

**Closed** 2019-02-22 22:59 UTC
Labels: Bug, Clean, Duplicate, Fixed

**Comment by TeamSpen210** [comment] 2019-02-22 23:02
Coincidentally I fixed this yesterday.
