### ISSUE TITLE
Less noticeable colliding box on the P1 angled panel, maybe?

### ISSUE THREAD

**Issue by ncrecc** [BEEmod/BEE2-items#2697] opened 2018-05-09 12:27 UTC
https://i.imgur.com/f7O4Wwq.gif

I think it should just be on top of the cyllinders to make sure players can't climb on them, and when the panel is coming down, it should push things out of the way.

That or a redesign for the panels so that something visually occupies the invisible hitbox.

**Comment by ZombiePwner1** [comment] 2018-05-09 13:00
@ncrecc Definitely could do for a smaller collision box.

**Comment by Luke18033** [comment] 2018-05-13 02:16
Duplicate of #1648

**Closed by Luke18033** 2018-05-13 02:16 UTC
Labels: Enhancement, Portal 1
