### ISSUE TITLE
Portal 1 piston platform having z-fighting issues on their back

### ISSUE THREAD

**Issue by NeoKat75** [BEEmod/BEE2-items#3551] opened 2020-11-04 13:58 UTC
[Video](https://youtu.be/QX5lDjzRb1k)

**Comment by LautaroL20** [comment] 2020-11-04 16:02
Yeah, that´s z-fighting issues.

**Comment by seagemgames** [comment] 2021-01-27 15:20
Still happening in 4.38.1

**Comment by Konclan** [comment] 2021-08-13 19:52
Duplicate of #3165

**Closed by Konclan** 2021-08-13 19:52 UTC
Labels: Bug, Portal 1
