### ISSUE TITLE
Rocket Turret's Rocket not appearing if fired.

### ISSUE THREAD

**Issue by minecraftgeek196** [BEEmod/BEE2-items#3187] opened 2020-01-04 11:56 UTC
The title explains it all.

**Comment by Flash4433** [comment] 2020-01-04 14:05
Duplicate of #1909

**Comment by ZombiePwner1** [comment] 2020-01-04 14:06
We are already aware of this problem, Multiple issues have already been posted about it.

**Closed by ZombiePwner1** 2020-01-04 14:06 UTC
Labels: Bug, Long Term

**Comment by Luke18033** [comment] 2020-01-04 18:28
I'm not sure how this would be fixed, I don't have the problem?

**Comment by ZombiePwner1** [comment] 2020-01-05 09:37
@Luke18033 It's different for everyone either that or your using a fixed instance.

**Comment by Luke18033** [comment] 2020-01-05 17:32
Why does it happen though? The rocket prop is in the base game, it's not a custom model or anything.

**Comment by TeamSpen210** [comment] 2020-01-05 22:13
It's not actually.

**Comment by Luke18033** [comment] 2020-01-05 23:20
The turret itself isn't, I thought the actual rocket was though (isn't it used by the `prop_rocket_tripwire`?)

**Comment by ZombiePwner1** [comment] 2020-01-06 00:24
@Luke18033 Nope the rocket was taken out during development.

**Comment by Luke18033** [comment] 2020-01-06 00:28
![image](https://user-images.githubusercontent.com/19228201/71788556-64df0400-2fd8-11ea-84a6-7bd309d3710f.png)
This is in the base game's VPK.

**Comment by Luke18033** [comment] 2020-01-06 00:30
Either way, I think that's irrelevant in this case since if it wasn't already in the files then A. the BEE2.4 compiler should automatically pack the model and B. if it wasn't getting packed, it would appear as an error, not invisible.

**Comment by ZombiePwner1** [comment] 2020-01-06 11:01
Well it doesn't help when valve removed most of the rocket turret's source code.

**Comment by TeamSpen210** [comment] 2020-01-06 21:33
They didn't...
