### ISSUE TITLE
Orange Bottomless Pit For Portal 1 Style.

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#2646] opened 2018-04-15 16:18 UTC
![capture 9](https://user-images.githubusercontent.com/31172185/38771427-1cc30d0c-3fd8-11e8-8502-85f34ae8fb8d.PNG)

Just a orange pit like seen in Portal Pro, at the ending secquence you could see a large orange pit. Will orangifiy your screen, and kill you if you jump in. Basically a background of panels on P1 style, orange glowing pit. Emits orange lights.

![capture 10](https://user-images.githubusercontent.com/31172185/38771425-1843fd0e-3fd8-11e8-8538-4be5552a5896.PNG)

**Comment by LautaroL20** [comment] 2018-04-15 23:26
Giving credit is always welcome here.

**Comment by villager103** [comment] 2018-04-16 01:44
Maybe we can have a stylevar/other option to make them blue/white? It would certainly help in chambers where most of the lighting is white/blue, and orange lighting would look out of place.

**Comment by BETTEREXTENEDEDITORMOD** [comment] 2018-04-16 04:10
A tan pit would look really nice
<img width="238" alt="capture 87" src="https://user-images.githubusercontent.com/31172185/38789765-5745317a-40f1-11e8-9a2b-c1faf6f816a7.PNG">

**Comment by LautaroL20** [comment] 2018-04-16 04:37
That does not fit with the P1 Style at all. Orange colour in the other hand is accurate for it.

**Comment by Nikita74RU** [comment] 2018-04-16 15:32
Thanks for moving it.

**Comment by Nikita74RU** [comment] 2018-04-16 15:39
Bottomless Pit's backstory: was a floor filled with goo, but melted through the structure, causing to blend out into a huge bottomless void.

**Comment by BETTEREXTENEDEDITORMOD** [comment] 2018-04-16 19:30
Maybe @LautaroL20 can ask ellingtonvengaboysmuseum for his P1 bottomless pit so we can already have it premade

**Comment by LautaroL20** [comment] 2018-04-16 21:04
@BETTEREXTENEDEDITORMOD - He was active during the 2015 year, but now hes pretty much inactive. The only way would be contacting him thru his Steam account.

**Comment by LautaroL20** [comment] 2018-04-16 21:29
This is his steam profile, he even has its comment section open to everyone so you can adress him a message: https://steamcommunity.com/id/ellingtonisle

**Comment by ellingtonvengaboysmuseum** [comment] 2018-04-16 22:24
Here you go! last version of it is a blue skybox and You might have to do some work to get it working on modern Bee2

[P1 Pit.zip](https://github.com/BEEmod/BEE2-items/files/1917520/P1.Pit.zip)

**Comment by LautaroL20** [comment] 2018-04-16 22:27
Awesome to see you here, i will revise your content and probably will do a branch/pull request for it, ill ask Spencer to give it a revision.

**Comment by Nikita74RU** [comment] 2018-04-21 14:33
How do i install it?

**Comment by Nikita74RU** [comment] 2018-04-21 14:34
Can't put it into zip.

**Comment by Nikita74RU** [comment] 2018-04-21 14:36
Pack it into zip and give me the .zip please.

**Comment by ZombiePwner1** [comment] 2018-04-29 00:01
@Nikita74Russian You were most likely banned to stop posting useless issues.

**Comment by Nikita74Russian** [comment] 2018-05-06 14:34
I think TeamSpen or anyone from collaborators.

**Comment by Nikita74Russian** [comment] 2018-05-08 18:56
I just made a issue, that improves the idea. #2694

**Comment by philhzss** [comment] 2018-08-19 00:52
Sorry for bringing up an old topic, but can someone explain how to get this P1 Pit.zip file (from ellingtonvengaboysmuseum) into Bee2, if it's relatively simple? I downloaded it and tried various things but it doesn't seem to work.

If it's too complicated or no one knows, no worries, it's not important. Thank you!

**Comment by maxdevgithub** [comment] 2020-09-21 15:14
In latest version this would be useless since currently they are being reimplemented

**Comment by Konclan** [comment] 2021-02-10 19:01
Duplicate of #87

**Closed by Konclan** 2021-02-10 19:02 UTC
Labels: Enhancement, Portal 1
